package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Checklist generated by hbm2java
 */
public class Checklist implements java.io.Serializable
{

	// Fields    

	private Long checklistId;

	private Request request;

	private Long numStations;

	private Date dateCreated;

	private long createdBy;

	private Date dateModified;

	private Long modifiedBy;

	private Set checklistDatas = new HashSet(0);

	// Constructors

	/** default constructor */
	public Checklist()
	{
	}

	/** minimal constructor */
	public Checklist(Request request, Date dateCreated, long createdBy)
	{
		this.request = request;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
	}

	/** full constructor */
	public Checklist(Request request, Long numStations, Date dateCreated, long createdBy, Date dateModified, Long modifiedBy, Set checklistDatas)
	{
		this.request = request;
		this.numStations = numStations;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.checklistDatas = checklistDatas;
	}

	// Property accessors
	public Long getChecklistId()
	{
		return this.checklistId;
	}

	public void setChecklistId(Long checklistId)
	{
		this.checklistId = checklistId;
	}

	public Request getRequest()
	{
		return this.request;
	}

	public void setRequest(Request request)
	{
		this.request = request;
	}

	public Long getNumStations()
	{
		return this.numStations;
	}

	public void setNumStations(Long numStations)
	{
		this.numStations = numStations;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Set getChecklistDatas()
	{
		return this.checklistDatas;
	}

	public void setChecklistDatas(Set checklistDatas)
	{
		this.checklistDatas = checklistDatas;
	}

}
