package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Condition generated by hbm2java
 */
public class Condition implements java.io.Serializable
{

	// Fields    

	private Long conditionId;

	private String name;

	private String activeFlag;

	private Long sequenceNo;

	private Date dateCreated;

	private long createdBy;

	private Date dateModified;

	private Long modifiedBy;

	private Set quoteConditions = new HashSet(0);

	// Constructors

	/** default constructor */
	public Condition()
	{
	}

	/** minimal constructor */
	public Condition(String name, Date dateCreated, long createdBy)
	{
		this.name = name;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
	}

	/** full constructor */
	public Condition(String name, String activeFlag, Long sequenceNo, Date dateCreated, long createdBy, Date dateModified, Long modifiedBy, Set quoteConditions)
	{
		this.name = name;
		this.activeFlag = activeFlag;
		this.sequenceNo = sequenceNo;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.quoteConditions = quoteConditions;
	}

	// Property accessors
	public Long getConditionId()
	{
		return this.conditionId;
	}

	public void setConditionId(Long conditionId)
	{
		this.conditionId = conditionId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getActiveFlag()
	{
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag)
	{
		this.activeFlag = activeFlag;
	}

	public Long getSequenceNo()
	{
		return this.sequenceNo;
	}

	public void setSequenceNo(Long sequenceNo)
	{
		this.sequenceNo = sequenceNo;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Set getQuoteConditions()
	{
		return this.quoteConditions;
	}

	public void setQuoteConditions(Set quoteConditions)
	{
		this.quoteConditions = quoteConditions;
	}

}
