package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable
{

	// Fields    

	private Long contactId;

	private Lookup lookupByContStatusTypeId;

	private Lookup lookupByContactTypeId;

	private Customer customer;

	private Organization organization;

	private String contactName;

	private String extDealerId;

	private String phoneWork;

	private String phoneCell;

	private String phoneHome;

	private String email;

	private String emailPhone;

	private String street1;

	private String street2;

	private String street3;

	private String city;

	private String state;

	private String zip;

	private String notes;

	private Date dateCreated;

	private long createdBy;

	private Date dateModified;

	private Long modifiedBy;

	private Set trackings = new HashSet(0);

	private Set requestsForFurniture2ContactId = new HashSet(0);

	private Set requestsForDDesignerContactId = new HashSet(0);

	private Set invoiceTrackings = new HashSet(0);

	private Set requestsForAMSalesContactId = new HashSet(0);

	private Set servicesForProjectMgrContactId = new HashSet(0);

	private Set jobLocationsForBldgMgmtContactId = new HashSet(0);

	private Set usersForContactId = new HashSet(0);

	private Set servicesForIdmContactId = new HashSet(0);

	private Set requestsForSecurityContactId = new HashSet(0);

	private Set requestsForDSalesRepContactId = new HashSet(0);

	private Set requestsForMoverContactId = new HashSet(0);

	private Set usersForVendorContactId = new HashSet(0);

	private Set requestsForDSalesSupContactId = new HashSet(0);

	private Set requestsForCarpetLayerContactId = new HashSet(0);

	private Set requestsForFurniture1ContactId = new HashSet(0);

	private Set requestsForApproverContactId = new HashSet(0);

	private Set requestsForADDesignerContactId = new HashSet(0);

	private Set requestsForDProjMgrContactId = new HashSet(0);

	private Set servicesForSalesContactId = new HashSet(0);

	private Set requestsForOtherContactId = new HashSet(0);

	private Set requestsForCustomerContactId = new HashSet(0);

	private Set requestsForAMContactId = new HashSet(0);

	private Set requestsForGenContractorContactId = new HashSet(0);

	private Set servicesForSupportContactId = new HashSet(0);

	private Set servicesForDesignerContactId = new HashSet(0);

	private Set requestsForAltCustomerContactId = new HashSet(0);

	private Set contactGroups = new HashSet(0);

	private Set requestsForElectricianContactId = new HashSet(0);

	private Set requestsForAMInstallSupContactId = new HashSet(0);

	private Set servicesForCustomerContactId = new HashSet(0);

	private Set requestsForDataPhoneContactId = new HashSet(0);

	private Set jobLocationsForJobLocContactId = new HashSet(0);

	private Set requestsForBldgMgrContactId = new HashSet(0);

	// Constructors

	/** default constructor */
	public Contact()
	{
	}

	/** minimal constructor */
	public Contact(Lookup lookupByContStatusTypeId, Organization organization, String contactName, String extDealerId, Date dateCreated, long createdBy)
	{
		this.lookupByContStatusTypeId = lookupByContStatusTypeId;
		this.organization = organization;
		this.contactName = contactName;
		this.extDealerId = extDealerId;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
	}

	/** full constructor */
	public Contact(Lookup lookupByContStatusTypeId, Lookup lookupByContactTypeId, Customer customer, Organization organization, String contactName, String extDealerId, String phoneWork,
			String phoneCell, String phoneHome, String email, String emailPhone, String street1, String street2, String street3, String city, String state, String zip, String notes, Date dateCreated,
			long createdBy, Date dateModified, Long modifiedBy, Set trackings, Set requestsForFurniture2ContactId, Set requestsForDDesignerContactId, Set invoiceTrackings,
			Set requestsForAMSalesContactId, Set servicesForProjectMgrContactId, Set jobLocationsForBldgMgmtContactId, Set usersForContactId, Set servicesForIdmContactId,
			Set requestsForSecurityContactId, Set requestsForDSalesRepContactId, Set requestsForMoverContactId, Set usersForVendorContactId, Set requestsForDSalesSupContactId,
			Set requestsForCarpetLayerContactId, Set requestsForFurniture1ContactId, Set requestsForApproverContactId, Set requestsForADDesignerContactId, Set requestsForDProjMgrContactId,
			Set servicesForSalesContactId, Set requestsForOtherContactId, Set requestsForCustomerContactId, Set requestsForAMContactId, Set requestsForGenContractorContactId,
			Set servicesForSupportContactId, Set servicesForDesignerContactId, Set requestsForAltCustomerContactId, Set contactGroups, Set requestsForElectricianContactId,
			Set requestsForAMInstallSupContactId, Set servicesForCustomerContactId, Set requestsForDataPhoneContactId, Set jobLocationsForJobLocContactId, Set requestsForBldgMgrContactId)
	{
		this.lookupByContStatusTypeId = lookupByContStatusTypeId;
		this.lookupByContactTypeId = lookupByContactTypeId;
		this.customer = customer;
		this.organization = organization;
		this.contactName = contactName;
		this.extDealerId = extDealerId;
		this.phoneWork = phoneWork;
		this.phoneCell = phoneCell;
		this.phoneHome = phoneHome;
		this.email = email;
		this.emailPhone = emailPhone;
		this.street1 = street1;
		this.street2 = street2;
		this.street3 = street3;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.notes = notes;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.trackings = trackings;
		this.requestsForFurniture2ContactId = requestsForFurniture2ContactId;
		this.requestsForDDesignerContactId = requestsForDDesignerContactId;
		this.invoiceTrackings = invoiceTrackings;
		this.requestsForAMSalesContactId = requestsForAMSalesContactId;
		this.servicesForProjectMgrContactId = servicesForProjectMgrContactId;
		this.jobLocationsForBldgMgmtContactId = jobLocationsForBldgMgmtContactId;
		this.usersForContactId = usersForContactId;
		this.servicesForIdmContactId = servicesForIdmContactId;
		this.requestsForSecurityContactId = requestsForSecurityContactId;
		this.requestsForDSalesRepContactId = requestsForDSalesRepContactId;
		this.requestsForMoverContactId = requestsForMoverContactId;
		this.usersForVendorContactId = usersForVendorContactId;
		this.requestsForDSalesSupContactId = requestsForDSalesSupContactId;
		this.requestsForCarpetLayerContactId = requestsForCarpetLayerContactId;
		this.requestsForFurniture1ContactId = requestsForFurniture1ContactId;
		this.requestsForApproverContactId = requestsForApproverContactId;
		this.requestsForADDesignerContactId = requestsForADDesignerContactId;
		this.requestsForDProjMgrContactId = requestsForDProjMgrContactId;
		this.servicesForSalesContactId = servicesForSalesContactId;
		this.requestsForOtherContactId = requestsForOtherContactId;
		this.requestsForCustomerContactId = requestsForCustomerContactId;
		this.requestsForAMContactId = requestsForAMContactId;
		this.requestsForGenContractorContactId = requestsForGenContractorContactId;
		this.servicesForSupportContactId = servicesForSupportContactId;
		this.servicesForDesignerContactId = servicesForDesignerContactId;
		this.requestsForAltCustomerContactId = requestsForAltCustomerContactId;
		this.contactGroups = contactGroups;
		this.requestsForElectricianContactId = requestsForElectricianContactId;
		this.requestsForAMInstallSupContactId = requestsForAMInstallSupContactId;
		this.servicesForCustomerContactId = servicesForCustomerContactId;
		this.requestsForDataPhoneContactId = requestsForDataPhoneContactId;
		this.jobLocationsForJobLocContactId = jobLocationsForJobLocContactId;
		this.requestsForBldgMgrContactId = requestsForBldgMgrContactId;
	}

	// Property accessors
	public Long getContactId()
	{
		return this.contactId;
	}

	public void setContactId(Long contactId)
	{
		this.contactId = contactId;
	}

	public Lookup getLookupByContStatusTypeId()
	{
		return this.lookupByContStatusTypeId;
	}

	public void setLookupByContStatusTypeId(Lookup lookupByContStatusTypeId)
	{
		this.lookupByContStatusTypeId = lookupByContStatusTypeId;
	}

	public Lookup getLookupByContactTypeId()
	{
		return this.lookupByContactTypeId;
	}

	public void setLookupByContactTypeId(Lookup lookupByContactTypeId)
	{
		this.lookupByContactTypeId = lookupByContactTypeId;
	}

	public Customer getCustomer()
	{
		return this.customer;
	}

	public void setCustomer(Customer customer)
	{
		this.customer = customer;
	}

	public Organization getOrganization()
	{
		return this.organization;
	}

	public void setOrganization(Organization organization)
	{
		this.organization = organization;
	}

	public String getContactName()
	{
		return this.contactName;
	}

	public void setContactName(String contactName)
	{
		this.contactName = contactName;
	}

	public String getExtDealerId()
	{
		return this.extDealerId;
	}

	public void setExtDealerId(String extDealerId)
	{
		this.extDealerId = extDealerId;
	}

	public String getPhoneWork()
	{
		return this.phoneWork;
	}

	public void setPhoneWork(String phoneWork)
	{
		this.phoneWork = phoneWork;
	}

	public String getPhoneCell()
	{
		return this.phoneCell;
	}

	public void setPhoneCell(String phoneCell)
	{
		this.phoneCell = phoneCell;
	}

	public String getPhoneHome()
	{
		return this.phoneHome;
	}

	public void setPhoneHome(String phoneHome)
	{
		this.phoneHome = phoneHome;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getEmailPhone()
	{
		return this.emailPhone;
	}

	public void setEmailPhone(String emailPhone)
	{
		this.emailPhone = emailPhone;
	}

	public String getStreet1()
	{
		return this.street1;
	}

	public void setStreet1(String street1)
	{
		this.street1 = street1;
	}

	public String getStreet2()
	{
		return this.street2;
	}

	public void setStreet2(String street2)
	{
		this.street2 = street2;
	}

	public String getStreet3()
	{
		return this.street3;
	}

	public void setStreet3(String street3)
	{
		this.street3 = street3;
	}

	public String getCity()
	{
		return this.city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	public String getState()
	{
		return this.state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	public String getZip()
	{
		return this.zip;
	}

	public void setZip(String zip)
	{
		this.zip = zip;
	}

	public String getNotes()
	{
		return this.notes;
	}

	public void setNotes(String notes)
	{
		this.notes = notes;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Set getTrackings()
	{
		return this.trackings;
	}

	public void setTrackings(Set trackings)
	{
		this.trackings = trackings;
	}

	public Set getRequestsForFurniture2ContactId()
	{
		return this.requestsForFurniture2ContactId;
	}

	public void setRequestsForFurniture2ContactId(Set requestsForFurniture2ContactId)
	{
		this.requestsForFurniture2ContactId = requestsForFurniture2ContactId;
	}

	public Set getRequestsForDDesignerContactId()
	{
		return this.requestsForDDesignerContactId;
	}

	public void setRequestsForDDesignerContactId(Set requestsForDDesignerContactId)
	{
		this.requestsForDDesignerContactId = requestsForDDesignerContactId;
	}

	public Set getInvoiceTrackings()
	{
		return this.invoiceTrackings;
	}

	public void setInvoiceTrackings(Set invoiceTrackings)
	{
		this.invoiceTrackings = invoiceTrackings;
	}

	public Set getRequestsForAMSalesContactId()
	{
		return this.requestsForAMSalesContactId;
	}

	public void setRequestsForAMSalesContactId(Set requestsForAMSalesContactId)
	{
		this.requestsForAMSalesContactId = requestsForAMSalesContactId;
	}

	public Set getServicesForProjectMgrContactId()
	{
		return this.servicesForProjectMgrContactId;
	}

	public void setServicesForProjectMgrContactId(Set servicesForProjectMgrContactId)
	{
		this.servicesForProjectMgrContactId = servicesForProjectMgrContactId;
	}

	public Set getJobLocationsForBldgMgmtContactId()
	{
		return this.jobLocationsForBldgMgmtContactId;
	}

	public void setJobLocationsForBldgMgmtContactId(Set jobLocationsForBldgMgmtContactId)
	{
		this.jobLocationsForBldgMgmtContactId = jobLocationsForBldgMgmtContactId;
	}

	public Set getUsersForContactId()
	{
		return this.usersForContactId;
	}

	public void setUsersForContactId(Set usersForContactId)
	{
		this.usersForContactId = usersForContactId;
	}

	public Set getServicesForIdmContactId()
	{
		return this.servicesForIdmContactId;
	}

	public void setServicesForIdmContactId(Set servicesForIdmContactId)
	{
		this.servicesForIdmContactId = servicesForIdmContactId;
	}

	public Set getRequestsForSecurityContactId()
	{
		return this.requestsForSecurityContactId;
	}

	public void setRequestsForSecurityContactId(Set requestsForSecurityContactId)
	{
		this.requestsForSecurityContactId = requestsForSecurityContactId;
	}

	public Set getRequestsForDSalesRepContactId()
	{
		return this.requestsForDSalesRepContactId;
	}

	public void setRequestsForDSalesRepContactId(Set requestsForDSalesRepContactId)
	{
		this.requestsForDSalesRepContactId = requestsForDSalesRepContactId;
	}

	public Set getRequestsForMoverContactId()
	{
		return this.requestsForMoverContactId;
	}

	public void setRequestsForMoverContactId(Set requestsForMoverContactId)
	{
		this.requestsForMoverContactId = requestsForMoverContactId;
	}

	public Set getUsersForVendorContactId()
	{
		return this.usersForVendorContactId;
	}

	public void setUsersForVendorContactId(Set usersForVendorContactId)
	{
		this.usersForVendorContactId = usersForVendorContactId;
	}

	public Set getRequestsForDSalesSupContactId()
	{
		return this.requestsForDSalesSupContactId;
	}

	public void setRequestsForDSalesSupContactId(Set requestsForDSalesSupContactId)
	{
		this.requestsForDSalesSupContactId = requestsForDSalesSupContactId;
	}

	public Set getRequestsForCarpetLayerContactId()
	{
		return this.requestsForCarpetLayerContactId;
	}

	public void setRequestsForCarpetLayerContactId(Set requestsForCarpetLayerContactId)
	{
		this.requestsForCarpetLayerContactId = requestsForCarpetLayerContactId;
	}

	public Set getRequestsForFurniture1ContactId()
	{
		return this.requestsForFurniture1ContactId;
	}

	public void setRequestsForFurniture1ContactId(Set requestsForFurniture1ContactId)
	{
		this.requestsForFurniture1ContactId = requestsForFurniture1ContactId;
	}

	public Set getRequestsForApproverContactId()
	{
		return this.requestsForApproverContactId;
	}

	public void setRequestsForApproverContactId(Set requestsForApproverContactId)
	{
		this.requestsForApproverContactId = requestsForApproverContactId;
	}

	public Set getRequestsForADDesignerContactId()
	{
		return this.requestsForADDesignerContactId;
	}

	public void setRequestsForADDesignerContactId(Set requestsForADDesignerContactId)
	{
		this.requestsForADDesignerContactId = requestsForADDesignerContactId;
	}

	public Set getRequestsForDProjMgrContactId()
	{
		return this.requestsForDProjMgrContactId;
	}

	public void setRequestsForDProjMgrContactId(Set requestsForDProjMgrContactId)
	{
		this.requestsForDProjMgrContactId = requestsForDProjMgrContactId;
	}

	public Set getServicesForSalesContactId()
	{
		return this.servicesForSalesContactId;
	}

	public void setServicesForSalesContactId(Set servicesForSalesContactId)
	{
		this.servicesForSalesContactId = servicesForSalesContactId;
	}

	public Set getRequestsForOtherContactId()
	{
		return this.requestsForOtherContactId;
	}

	public void setRequestsForOtherContactId(Set requestsForOtherContactId)
	{
		this.requestsForOtherContactId = requestsForOtherContactId;
	}

	public Set getRequestsForCustomerContactId()
	{
		return this.requestsForCustomerContactId;
	}

	public void setRequestsForCustomerContactId(Set requestsForCustomerContactId)
	{
		this.requestsForCustomerContactId = requestsForCustomerContactId;
	}

	public Set getRequestsForAMContactId()
	{
		return this.requestsForAMContactId;
	}

	public void setRequestsForAMContactId(Set requestsForAMContactId)
	{
		this.requestsForAMContactId = requestsForAMContactId;
	}

	public Set getRequestsForGenContractorContactId()
	{
		return this.requestsForGenContractorContactId;
	}

	public void setRequestsForGenContractorContactId(Set requestsForGenContractorContactId)
	{
		this.requestsForGenContractorContactId = requestsForGenContractorContactId;
	}

	public Set getServicesForSupportContactId()
	{
		return this.servicesForSupportContactId;
	}

	public void setServicesForSupportContactId(Set servicesForSupportContactId)
	{
		this.servicesForSupportContactId = servicesForSupportContactId;
	}

	public Set getServicesForDesignerContactId()
	{
		return this.servicesForDesignerContactId;
	}

	public void setServicesForDesignerContactId(Set servicesForDesignerContactId)
	{
		this.servicesForDesignerContactId = servicesForDesignerContactId;
	}

	public Set getRequestsForAltCustomerContactId()
	{
		return this.requestsForAltCustomerContactId;
	}

	public void setRequestsForAltCustomerContactId(Set requestsForAltCustomerContactId)
	{
		this.requestsForAltCustomerContactId = requestsForAltCustomerContactId;
	}

	public Set getContactGroups()
	{
		return this.contactGroups;
	}

	public void setContactGroups(Set contactGroups)
	{
		this.contactGroups = contactGroups;
	}

	public Set getRequestsForElectricianContactId()
	{
		return this.requestsForElectricianContactId;
	}

	public void setRequestsForElectricianContactId(Set requestsForElectricianContactId)
	{
		this.requestsForElectricianContactId = requestsForElectricianContactId;
	}

	public Set getRequestsForAMInstallSupContactId()
	{
		return this.requestsForAMInstallSupContactId;
	}

	public void setRequestsForAMInstallSupContactId(Set requestsForAMInstallSupContactId)
	{
		this.requestsForAMInstallSupContactId = requestsForAMInstallSupContactId;
	}

	public Set getServicesForCustomerContactId()
	{
		return this.servicesForCustomerContactId;
	}

	public void setServicesForCustomerContactId(Set servicesForCustomerContactId)
	{
		this.servicesForCustomerContactId = servicesForCustomerContactId;
	}

	public Set getRequestsForDataPhoneContactId()
	{
		return this.requestsForDataPhoneContactId;
	}

	public void setRequestsForDataPhoneContactId(Set requestsForDataPhoneContactId)
	{
		this.requestsForDataPhoneContactId = requestsForDataPhoneContactId;
	}

	public Set getJobLocationsForJobLocContactId()
	{
		return this.jobLocationsForJobLocContactId;
	}

	public void setJobLocationsForJobLocContactId(Set jobLocationsForJobLocContactId)
	{
		this.jobLocationsForJobLocContactId = jobLocationsForJobLocContactId;
	}

	public Set getRequestsForBldgMgrContactId()
	{
		return this.requestsForBldgMgrContactId;
	}

	public void setRequestsForBldgMgrContactId(Set requestsForBldgMgrContactId)
	{
		this.requestsForBldgMgrContactId = requestsForBldgMgrContactId;
	}

}
