package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;

/**
 * Customersbudget generated by hbm2java
 */
public class Customersbudget implements java.io.Serializable
{

	// Fields    

	private Long customerId;

	private Integer year;

	private BigDecimal budget;

	// Constructors

	/** default constructor */
	public Customersbudget()
	{
	}

	/** full constructor */
	public Customersbudget(Integer year, BigDecimal budget)
	{
		this.year = year;
		this.budget = budget;
	}

	// Property accessors
	public Long getCustomerId()
	{
		return this.customerId;
	}

	public void setCustomerId(Long customerId)
	{
		this.customerId = customerId;
	}

	public Integer getYear()
	{
		return this.year;
	}

	public void setYear(Integer year)
	{
		this.year = year;
	}

	public BigDecimal getBudget()
	{
		return this.budget;
	}

	public void setBudget(BigDecimal budget)
	{
		this.budget = budget;
	}

}
