package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * CustomCol generated by hbm2java
 */
public class CustomCol implements java.io.Serializable
{

	// Fields    

	private Long customColId;

	private Request request;

	private long customCustColId;

	private Long serviceId;

	private String colValue;

	private String colTitle;

	private long colSequence;

	private String activeFlag;

	private String isMandatory;

	private String isDroplist;

	private long createdBy;

	private Date dateCreated;

	private Long modifiedBy;

	private Date dateModified;

	// Constructors

	/** default constructor */
	public CustomCol()
	{
	}

	/** minimal constructor */
	public CustomCol(long customCustColId, String colTitle, long colSequence, String activeFlag, String isMandatory, String isDroplist, long createdBy, Date dateCreated)
	{
		this.customCustColId = customCustColId;
		this.colTitle = colTitle;
		this.colSequence = colSequence;
		this.activeFlag = activeFlag;
		this.isMandatory = isMandatory;
		this.isDroplist = isDroplist;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public CustomCol(Request request, long customCustColId, Long serviceId, String colValue, String colTitle, long colSequence, String activeFlag, String isMandatory, String isDroplist,
			long createdBy, Date dateCreated, Long modifiedBy, Date dateModified)
	{
		this.request = request;
		this.customCustColId = customCustColId;
		this.serviceId = serviceId;
		this.colValue = colValue;
		this.colTitle = colTitle;
		this.colSequence = colSequence;
		this.activeFlag = activeFlag;
		this.isMandatory = isMandatory;
		this.isDroplist = isDroplist;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
	}

	// Property accessors
	public Long getCustomColId()
	{
		return this.customColId;
	}

	public void setCustomColId(Long customColId)
	{
		this.customColId = customColId;
	}

	public Request getRequest()
	{
		return this.request;
	}

	public void setRequest(Request request)
	{
		this.request = request;
	}

	public long getCustomCustColId()
	{
		return this.customCustColId;
	}

	public void setCustomCustColId(long customCustColId)
	{
		this.customCustColId = customCustColId;
	}

	public Long getServiceId()
	{
		return this.serviceId;
	}

	public void setServiceId(Long serviceId)
	{
		this.serviceId = serviceId;
	}

	public String getColValue()
	{
		return this.colValue;
	}

	public void setColValue(String colValue)
	{
		this.colValue = colValue;
	}

	public String getColTitle()
	{
		return this.colTitle;
	}

	public void setColTitle(String colTitle)
	{
		this.colTitle = colTitle;
	}

	public long getColSequence()
	{
		return this.colSequence;
	}

	public void setColSequence(long colSequence)
	{
		this.colSequence = colSequence;
	}

	public String getActiveFlag()
	{
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag)
	{
		this.activeFlag = activeFlag;
	}

	public String getIsMandatory()
	{
		return this.isMandatory;
	}

	public void setIsMandatory(String isMandatory)
	{
		this.isMandatory = isMandatory;
	}

	public String getIsDroplist()
	{
		return this.isDroplist;
	}

	public void setIsDroplist(String isDroplist)
	{
		this.isDroplist = isDroplist;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

}
