package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Document generated by hbm2java
 */
public class Document implements java.io.Serializable
{

	// Fields    

	private Long documentId;

	private Project project;

	private Format format;

	private String name;

	private String code;

	private Long lockedBy;

	private Date dateLocked;

	private long createdBy;

	private Date dateCreated;

	private Long modifiedBy;

	private Date dateModified;

	private Set versions = new HashSet(0);

	// Constructors

	/** default constructor */
	public Document()
	{
	}

	/** minimal constructor */
	public Document(Project project, Format format, String name, long createdBy, Date dateCreated)
	{
		this.project = project;
		this.format = format;
		this.name = name;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public Document(Project project, Format format, String name, String code, Long lockedBy, Date dateLocked, long createdBy, Date dateCreated, Long modifiedBy, Date dateModified, Set versions)
	{
		this.project = project;
		this.format = format;
		this.name = name;
		this.code = code;
		this.lockedBy = lockedBy;
		this.dateLocked = dateLocked;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.versions = versions;
	}

	// Property accessors
	public Long getDocumentId()
	{
		return this.documentId;
	}

	public void setDocumentId(Long documentId)
	{
		this.documentId = documentId;
	}

	public Project getProject()
	{
		return this.project;
	}

	public void setProject(Project project)
	{
		this.project = project;
	}

	public Format getFormat()
	{
		return this.format;
	}

	public void setFormat(Format format)
	{
		this.format = format;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public Long getLockedBy()
	{
		return this.lockedBy;
	}

	public void setLockedBy(Long lockedBy)
	{
		this.lockedBy = lockedBy;
	}

	public Date getDateLocked()
	{
		return this.dateLocked;
	}

	public void setDateLocked(Date dateLocked)
	{
		this.dateLocked = dateLocked;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Set getVersions()
	{
		return this.versions;
	}

	public void setVersions(Set versions)
	{
		this.versions = versions;
	}

}
