package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * Email generated by hbm2java
 */
public class Email implements java.io.Serializable
{

	// Fields    

	private Long emailId;

	private Long projectId;

	private Long requestId;

	private Long quoteId;

	private String emailSentFlag;

	private String fromEmail;

	private Long toContactId;

	private String toEmail;

	private String subject;

	private String body;

	private Date dateCreated;

	private long createdBy;

	private Date dateModified;

	private Long modifiedBy;

	// Constructors

	/** default constructor */
	public Email()
	{
	}

	/** minimal constructor */
	public Email(String emailSentFlag, Date dateCreated, long createdBy)
	{
		this.emailSentFlag = emailSentFlag;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
	}

	/** full constructor */
	public Email(Long projectId, Long requestId, Long quoteId, String emailSentFlag, String fromEmail, Long toContactId, String toEmail, String subject, String body, Date dateCreated, long createdBy,
			Date dateModified, Long modifiedBy)
	{
		this.projectId = projectId;
		this.requestId = requestId;
		this.quoteId = quoteId;
		this.emailSentFlag = emailSentFlag;
		this.fromEmail = fromEmail;
		this.toContactId = toContactId;
		this.toEmail = toEmail;
		this.subject = subject;
		this.body = body;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
	}

	// Property accessors
	public Long getEmailId()
	{
		return this.emailId;
	}

	public void setEmailId(Long emailId)
	{
		this.emailId = emailId;
	}

	public Long getProjectId()
	{
		return this.projectId;
	}

	public void setProjectId(Long projectId)
	{
		this.projectId = projectId;
	}

	public Long getRequestId()
	{
		return this.requestId;
	}

	public void setRequestId(Long requestId)
	{
		this.requestId = requestId;
	}

	public Long getQuoteId()
	{
		return this.quoteId;
	}

	public void setQuoteId(Long quoteId)
	{
		this.quoteId = quoteId;
	}

	public String getEmailSentFlag()
	{
		return this.emailSentFlag;
	}

	public void setEmailSentFlag(String emailSentFlag)
	{
		this.emailSentFlag = emailSentFlag;
	}

	public String getFromEmail()
	{
		return this.fromEmail;
	}

	public void setFromEmail(String fromEmail)
	{
		this.fromEmail = fromEmail;
	}

	public Long getToContactId()
	{
		return this.toContactId;
	}

	public void setToContactId(Long toContactId)
	{
		this.toContactId = toContactId;
	}

	public String getToEmail()
	{
		return this.toEmail;
	}

	public void setToEmail(String toEmail)
	{
		this.toEmail = toEmail;
	}

	public String getSubject()
	{
		return this.subject;
	}

	public void setSubject(String subject)
	{
		this.subject = subject;
	}

	public String getBody()
	{
		return this.body;
	}

	public void setBody(String body)
	{
		this.body = body;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

}
