package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;

/**
 * ExpensesBatchLine generated by hbm2java
 */
public class ExpensesBatchLine implements java.io.Serializable
{

	// Fields    

	private Long serviceLineId;

	private long intBatchId;

	private BigDecimal expenseQty;

	private BigDecimal expenseRate;

	private BigDecimal expenseTotal;

	private String extItemId;

	private String expenseExportCode;

	private String extEmployeeId;

	// Constructors

	/** default constructor */
	public ExpensesBatchLine()
	{
	}

	/** minimal constructor */
	public ExpensesBatchLine(long intBatchId)
	{
		this.intBatchId = intBatchId;
	}

	/** full constructor */
	public ExpensesBatchLine(long intBatchId, BigDecimal expenseQty, BigDecimal expenseRate, BigDecimal expenseTotal, String extItemId, String expenseExportCode, String extEmployeeId)
	{
		this.intBatchId = intBatchId;
		this.expenseQty = expenseQty;
		this.expenseRate = expenseRate;
		this.expenseTotal = expenseTotal;
		this.extItemId = extItemId;
		this.expenseExportCode = expenseExportCode;
		this.extEmployeeId = extEmployeeId;
	}

	// Property accessors
	public Long getServiceLineId()
	{
		return this.serviceLineId;
	}

	public void setServiceLineId(Long serviceLineId)
	{
		this.serviceLineId = serviceLineId;
	}

	public long getIntBatchId()
	{
		return this.intBatchId;
	}

	public void setIntBatchId(long intBatchId)
	{
		this.intBatchId = intBatchId;
	}

	public BigDecimal getExpenseQty()
	{
		return this.expenseQty;
	}

	public void setExpenseQty(BigDecimal expenseQty)
	{
		this.expenseQty = expenseQty;
	}

	public BigDecimal getExpenseRate()
	{
		return this.expenseRate;
	}

	public void setExpenseRate(BigDecimal expenseRate)
	{
		this.expenseRate = expenseRate;
	}

	public BigDecimal getExpenseTotal()
	{
		return this.expenseTotal;
	}

	public void setExpenseTotal(BigDecimal expenseTotal)
	{
		this.expenseTotal = expenseTotal;
	}

	public String getExtItemId()
	{
		return this.extItemId;
	}

	public void setExtItemId(String extItemId)
	{
		this.extItemId = extItemId;
	}

	public String getExpenseExportCode()
	{
		return this.expenseExportCode;
	}

	public void setExpenseExportCode(String expenseExportCode)
	{
		this.expenseExportCode = expenseExportCode;
	}

	public String getExtEmployeeId()
	{
		return this.extEmployeeId;
	}

	public void setExtEmployeeId(String extEmployeeId)
	{
		this.extEmployeeId = extEmployeeId;
	}

}
