package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Format generated by hbm2java
 */
public class Format implements java.io.Serializable
{

	// Fields    

	private Long formatId;

	private String name;

	private String extension;

	private String description;

	private Date dateCreated;

	private long createdBy;

	private Date dateModified;

	private Long modifiedBy;

	private Set documents = new HashSet(0);

	// Constructors

	/** default constructor */
	public Format()
	{
	}

	/** minimal constructor */
	public Format(String name, String extension, String description, Date dateCreated, long createdBy)
	{
		this.name = name;
		this.extension = extension;
		this.description = description;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
	}

	/** full constructor */
	public Format(String name, String extension, String description, Date dateCreated, long createdBy, Date dateModified, Long modifiedBy, Set documents)
	{
		this.name = name;
		this.extension = extension;
		this.description = description;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.documents = documents;
	}

	// Property accessors
	public Long getFormatId()
	{
		return this.formatId;
	}

	public void setFormatId(Long formatId)
	{
		this.formatId = formatId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getExtension()
	{
		return this.extension;
	}

	public void setExtension(String extension)
	{
		this.extension = extension;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Set getDocuments()
	{
		return this.documents;
	}

	public void setDocuments(Set documents)
	{
		this.documents = documents;
	}

}
