package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Function generated by hbm2java
 */
public class Function implements java.io.Serializable
{

	// Fields    

	private Long functionId;

	private FunctionGroup functionGroup;

	private Long templateId;

	private String target;

	private String name;

	private String code;

	private String description;

	private Long templateLocationId;

	private Long sequenceNo;

	private String isNavFunction;

	private String isMenuFunction;

	private Date dateCreated;

	private long createdBy;

	private Date dateModified;

	private Long modifiedBy;

	private Set roleFunctionRights = new HashSet(0);

	// Constructors

	/** default constructor */
	public Function()
	{
	}

	/** minimal constructor */
	public Function(FunctionGroup functionGroup, String name, Date dateCreated, long createdBy)
	{
		this.functionGroup = functionGroup;
		this.name = name;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
	}

	/** full constructor */
	public Function(FunctionGroup functionGroup, Long templateId, String target, String name, String code, String description, Long templateLocationId, Long sequenceNo, String isNavFunction,
			String isMenuFunction, Date dateCreated, long createdBy, Date dateModified, Long modifiedBy, Set roleFunctionRights)
	{
		this.functionGroup = functionGroup;
		this.templateId = templateId;
		this.target = target;
		this.name = name;
		this.code = code;
		this.description = description;
		this.templateLocationId = templateLocationId;
		this.sequenceNo = sequenceNo;
		this.isNavFunction = isNavFunction;
		this.isMenuFunction = isMenuFunction;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.roleFunctionRights = roleFunctionRights;
	}

	// Property accessors
	public Long getFunctionId()
	{
		return this.functionId;
	}

	public void setFunctionId(Long functionId)
	{
		this.functionId = functionId;
	}

	public FunctionGroup getFunctionGroup()
	{
		return this.functionGroup;
	}

	public void setFunctionGroup(FunctionGroup functionGroup)
	{
		this.functionGroup = functionGroup;
	}

	public Long getTemplateId()
	{
		return this.templateId;
	}

	public void setTemplateId(Long templateId)
	{
		this.templateId = templateId;
	}

	public String getTarget()
	{
		return this.target;
	}

	public void setTarget(String target)
	{
		this.target = target;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public Long getTemplateLocationId()
	{
		return this.templateLocationId;
	}

	public void setTemplateLocationId(Long templateLocationId)
	{
		this.templateLocationId = templateLocationId;
	}

	public Long getSequenceNo()
	{
		return this.sequenceNo;
	}

	public void setSequenceNo(Long sequenceNo)
	{
		this.sequenceNo = sequenceNo;
	}

	public String getIsNavFunction()
	{
		return this.isNavFunction;
	}

	public void setIsNavFunction(String isNavFunction)
	{
		this.isNavFunction = isNavFunction;
	}

	public String getIsMenuFunction()
	{
		return this.isMenuFunction;
	}

	public void setIsMenuFunction(String isMenuFunction)
	{
		this.isMenuFunction = isMenuFunction;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Set getRoleFunctionRights()
	{
		return this.roleFunctionRights;
	}

	public void setRoleFunctionRights(Set roleFunctionRights)
	{
		this.roleFunctionRights = roleFunctionRights;
	}

}
