package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.HashSet;
import java.util.Set;

/**
 * FunctionGroup generated by hbm2java
 */
public class FunctionGroup implements java.io.Serializable
{

	// Fields    

	private Long functionGroupId;

	private String name;

	private String code;

	private Set functions = new HashSet(0);

	// Constructors

	/** default constructor */
	public FunctionGroup()
	{
	}

	/** minimal constructor */
	public FunctionGroup(String name)
	{
		this.name = name;
	}

	/** full constructor */
	public FunctionGroup(String name, String code, Set functions)
	{
		this.name = name;
		this.code = code;
		this.functions = functions;
	}

	// Property accessors
	public Long getFunctionGroupId()
	{
		return this.functionGroupId;
	}

	public void setFunctionGroupId(Long functionGroupId)
	{
		this.functionGroupId = functionGroupId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public Set getFunctions()
	{
		return this.functions;
	}

	public void setFunctions(Set functions)
	{
		this.functions = functions;
	}

}
