package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice implements java.io.Serializable
{

	// Fields    

	private Long invoiceId;

	private Lookup lookupByInvoiceTypeId;

	private Lookup lookupByBillingTypeId;

	private Lookup lookupByInvoiceFormatTypeId;

	private InvoiceStatus invoiceStatus;

	private Organization organization;

	private Job job;

	private InvoiceBatchStatuse invoiceBatchStatuse;

	private Customer customer;

	private String poNo;

	private String extBatchId;

	private Long assignedToUserId;

	private String extInvoiceId;

	private String description;

	private String gpDescription;

	private String costCodes;

	private Date startDate;

	private Date endDate;

	private String extBillCustId;

	private String salesReps;

	private Date dateSent;

	private Date dateCreated;

	private long createdBy;

	private Date dateModified;

	private Long modifiedBy;

	private Set serviceLines = new HashSet(0);

	private Set invoiceLines = new HashSet(0);

	private Set invoiceTrackings = new HashSet(0);

	// Constructors

	/** default constructor */
	public Invoice()
	{
	}

	/** minimal constructor */
	public Invoice(Lookup lookupByInvoiceTypeId, InvoiceStatus invoiceStatuse, Job job, Date dateCreated, long createdBy)
	{
		this.lookupByInvoiceTypeId = lookupByInvoiceTypeId;
		this.invoiceStatus = invoiceStatuse;
		this.job = job;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
	}

	/** full constructor */
	public Invoice(Lookup lookupByInvoiceTypeId, Lookup lookupByBillingTypeId, Lookup lookupByInvoiceFormatTypeId, InvoiceStatus invoiceStatuse, Organization organization, Job job,
			InvoiceBatchStatuse invoiceBatchStatuse, Customer customer, String poNo, String extBatchId, Long assignedToUserId, String extInvoiceId, String description, String gpDescription,
			String costCodes, Date startDate, Date endDate, String extBillCustId, String salesReps, Date dateSent, Date dateCreated, long createdBy, Date dateModified, Long modifiedBy,
			Set serviceLines, Set invoiceLines, Set invoiceTrackings)
	{
		this.lookupByInvoiceTypeId = lookupByInvoiceTypeId;
		this.lookupByBillingTypeId = lookupByBillingTypeId;
		this.lookupByInvoiceFormatTypeId = lookupByInvoiceFormatTypeId;
		this.invoiceStatus = invoiceStatuse;
		this.organization = organization;
		this.job = job;
		this.invoiceBatchStatuse = invoiceBatchStatuse;
		this.customer = customer;
		this.poNo = poNo;
		this.extBatchId = extBatchId;
		this.assignedToUserId = assignedToUserId;
		this.extInvoiceId = extInvoiceId;
		this.description = description;
		this.gpDescription = gpDescription;
		this.costCodes = costCodes;
		this.startDate = startDate;
		this.endDate = endDate;
		this.extBillCustId = extBillCustId;
		this.salesReps = salesReps;
		this.dateSent = dateSent;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.serviceLines = serviceLines;
		this.invoiceLines = invoiceLines;
		this.invoiceTrackings = invoiceTrackings;
	}

	// Property accessors
	public Long getInvoiceId()
	{
		return this.invoiceId;
	}

	public void setInvoiceId(Long invoiceId)
	{
		this.invoiceId = invoiceId;
	}

	public Lookup getLookupByInvoiceTypeId()
	{
		return this.lookupByInvoiceTypeId;
	}

	public void setLookupByInvoiceTypeId(Lookup lookupByInvoiceTypeId)
	{
		this.lookupByInvoiceTypeId = lookupByInvoiceTypeId;
	}

	public Lookup getLookupByBillingTypeId()
	{
		return this.lookupByBillingTypeId;
	}

	public void setLookupByBillingTypeId(Lookup lookupByBillingTypeId)
	{
		this.lookupByBillingTypeId = lookupByBillingTypeId;
	}

	public Lookup getLookupByInvoiceFormatTypeId()
	{
		return this.lookupByInvoiceFormatTypeId;
	}

	public void setLookupByInvoiceFormatTypeId(Lookup lookupByInvoiceFormatTypeId)
	{
		this.lookupByInvoiceFormatTypeId = lookupByInvoiceFormatTypeId;
	}

	public InvoiceStatus getInvoiceStatus()
	{
		return this.invoiceStatus;
	}

	public void setInvoiceStatus(InvoiceStatus invoiceStatuse)
	{
		this.invoiceStatus = invoiceStatuse;
	}

	public Organization getOrganization()
	{
		return this.organization;
	}

	public void setOrganization(Organization organization)
	{
		this.organization = organization;
	}

	public Job getJob()
	{
		return this.job;
	}

	public void setJob(Job job)
	{
		this.job = job;
	}

	public InvoiceBatchStatuse getInvoiceBatchStatuse()
	{
		return this.invoiceBatchStatuse;
	}

	public void setInvoiceBatchStatuse(InvoiceBatchStatuse invoiceBatchStatuse)
	{
		this.invoiceBatchStatuse = invoiceBatchStatuse;
	}

	public Customer getCustomer()
	{
		return this.customer;
	}

	public void setCustomer(Customer customer)
	{
		this.customer = customer;
	}

	public String getPoNo()
	{
		return this.poNo;
	}

	public void setPoNo(String poNo)
	{
		this.poNo = poNo;
	}

	public String getExtBatchId()
	{
		return this.extBatchId;
	}

	public void setExtBatchId(String extBatchId)
	{
		this.extBatchId = extBatchId;
	}

	public Long getAssignedToUserId()
	{
		return this.assignedToUserId;
	}

	public void setAssignedToUserId(Long assignedToUserId)
	{
		this.assignedToUserId = assignedToUserId;
	}

	public String getExtInvoiceId()
	{
		return this.extInvoiceId;
	}

	public void setExtInvoiceId(String extInvoiceId)
	{
		this.extInvoiceId = extInvoiceId;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public String getGpDescription()
	{
		return this.gpDescription;
	}

	public void setGpDescription(String gpDescription)
	{
		this.gpDescription = gpDescription;
	}

	public String getCostCodes()
	{
		return this.costCodes;
	}

	public void setCostCodes(String costCodes)
	{
		this.costCodes = costCodes;
	}

	public Date getStartDate()
	{
		return this.startDate;
	}

	public void setStartDate(Date startDate)
	{
		this.startDate = startDate;
	}

	public Date getEndDate()
	{
		return this.endDate;
	}

	public void setEndDate(Date endDate)
	{
		this.endDate = endDate;
	}

	public String getExtBillCustId()
	{
		return this.extBillCustId;
	}

	public void setExtBillCustId(String extBillCustId)
	{
		this.extBillCustId = extBillCustId;
	}

	public String getSalesReps()
	{
		return this.salesReps;
	}

	public void setSalesReps(String salesReps)
	{
		this.salesReps = salesReps;
	}

	public Date getDateSent()
	{
		return this.dateSent;
	}

	public void setDateSent(Date dateSent)
	{
		this.dateSent = dateSent;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Set getServiceLines()
	{
		return this.serviceLines;
	}

	public void setServiceLines(Set serviceLines)
	{
		this.serviceLines = serviceLines;
	}

	public Set getInvoiceLines()
	{
		return this.invoiceLines;
	}

	public void setInvoiceLines(Set invoiceLines)
	{
		this.invoiceLines = invoiceLines;
	}

	public Set getInvoiceTrackings()
	{
		return this.invoiceTrackings;
	}

	public void setInvoiceTrackings(Set invoiceTrackings)
	{
		this.invoiceTrackings = invoiceTrackings;
	}

}
