package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceBatchStatuse generated by hbm2java
 */
public class InvoiceBatchStatuse implements java.io.Serializable
{

	// Fields    

	private Long statusId;

	private String code;

	private String name;

	private Set invoices = new HashSet(0);

	// Constructors

	/** default constructor */
	public InvoiceBatchStatuse()
	{
	}

	/** minimal constructor */
	public InvoiceBatchStatuse(String code, String name)
	{
		this.code = code;
		this.name = name;
	}

	/** full constructor */
	public InvoiceBatchStatuse(String code, String name, Set invoices)
	{
		this.code = code;
		this.name = name;
		this.invoices = invoices;
	}

	// Property accessors
	public Long getStatusId()
	{
		return this.statusId;
	}

	public void setStatusId(Long statusId)
	{
		this.statusId = statusId;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Set getInvoices()
	{
		return this.invoices;
	}

	public void setInvoices(Set invoices)
	{
		this.invoices = invoices;
	}

}
