package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;
import java.util.Date;

/**
 * ItemCostingHistory generated by hbm2java
 */
public class ItemCostingHistory implements java.io.Serializable
{

	// Fields    

	private Long itemCostingHistoryId;

	private Item item;

	private BigDecimal costPerUom;

	private Short percentMargin;

	private String createdBy;

	private Date dateCreated;

	// Constructors

	/** default constructor */
	public ItemCostingHistory()
	{
	}

	/** minimal constructor */
	public ItemCostingHistory(Item item, String createdBy, Date dateCreated)
	{
		this.item = item;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public ItemCostingHistory(Item item, BigDecimal costPerUom, Short percentMargin, String createdBy, Date dateCreated)
	{
		this.item = item;
		this.costPerUom = costPerUom;
		this.percentMargin = percentMargin;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	// Property accessors
	public Long getItemCostingHistoryId()
	{
		return this.itemCostingHistoryId;
	}

	public void setItemCostingHistoryId(Long itemCostingHistoryId)
	{
		this.itemCostingHistoryId = itemCostingHistoryId;
	}

	public Item getItem()
	{
		return this.item;
	}

	public void setItem(Item item)
	{
		this.item = item;
	}

	public BigDecimal getCostPerUom()
	{
		return this.costPerUom;
	}

	public void setCostPerUom(BigDecimal costPerUom)
	{
		this.costPerUom = costPerUom;
	}

	public Short getPercentMargin()
	{
		return this.percentMargin;
	}

	public void setPercentMargin(Short percentMargin)
	{
		this.percentMargin = percentMargin;
	}

	public String getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

}
