package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item implements java.io.Serializable
{

	// Fields    

	private Long itemId;

	private Lookup lookupByItemStatusTypeId;

	private Lookup lookupByItemTypeId;

	private Organization organization;

	private Lookup lookupByJobTypeId;

	private String name;

	private String code;

	private String description;

	private String extItemId;

	private String billableFlag;

	private Long sequenceNo;

	private String expenseExportCode;

	private Date dateCreated;

	private long createdBy;

	private Date dateModified;

	private Long modifiedBy;

	private BigDecimal costPerUom;

	private Short percentMargin;

	private String columnPosition;

	private Set resourceTypeItems = new HashSet(0);

	private Set itemCostingHistories = new HashSet(0);

	private Set invoiceLines = new HashSet(0);

	private Set serviceLines = new HashSet(0);

	private Set jobItemRates = new HashSet(0);

	private Set resourceItems = new HashSet(0);

	// Constructors

	/** default constructor */
	public Item()
	{
	}

	/** minimal constructor */
	public Item(String name, String extItemId, String billableFlag, Date dateCreated, long createdBy)
	{
		this.name = name;
		this.extItemId = extItemId;
		this.billableFlag = billableFlag;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
	}

	/** full constructor */
	public Item(Lookup lookupByItemStatusTypeId, Lookup lookupByItemTypeId, Organization organization, Lookup lookupByJobTypeId, String name, String code, String description, String extItemId,
			String billableFlag, Long sequenceNo, String expenseExportCode, Date dateCreated, long createdBy, Date dateModified, Long modifiedBy, BigDecimal costPerUom, Short percentMargin,
			String columnPosition, Set resourceTypeItems, Set itemCostingHistories, Set invoiceLines, Set serviceLines, Set jobItemRates, Set resourceItems)
	{
		this.lookupByItemStatusTypeId = lookupByItemStatusTypeId;
		this.lookupByItemTypeId = lookupByItemTypeId;
		this.organization = organization;
		this.lookupByJobTypeId = lookupByJobTypeId;
		this.name = name;
		this.code = code;
		this.description = description;
		this.extItemId = extItemId;
		this.billableFlag = billableFlag;
		this.sequenceNo = sequenceNo;
		this.expenseExportCode = expenseExportCode;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.costPerUom = costPerUom;
		this.percentMargin = percentMargin;
		this.columnPosition = columnPosition;
		this.resourceTypeItems = resourceTypeItems;
		this.itemCostingHistories = itemCostingHistories;
		this.invoiceLines = invoiceLines;
		this.serviceLines = serviceLines;
		this.jobItemRates = jobItemRates;
		this.resourceItems = resourceItems;
	}

	// Property accessors
	public Long getItemId()
	{
		return this.itemId;
	}

	public void setItemId(Long itemId)
	{
		this.itemId = itemId;
	}

	public Lookup getLookupByItemStatusTypeId()
	{
		return this.lookupByItemStatusTypeId;
	}

	public void setLookupByItemStatusTypeId(Lookup lookupByItemStatusTypeId)
	{
		this.lookupByItemStatusTypeId = lookupByItemStatusTypeId;
	}

	public Lookup getLookupByItemTypeId()
	{
		return this.lookupByItemTypeId;
	}

	public void setLookupByItemTypeId(Lookup lookupByItemTypeId)
	{
		this.lookupByItemTypeId = lookupByItemTypeId;
	}

	public Organization getOrganization()
	{
		return this.organization;
	}

	public void setOrganization(Organization organization)
	{
		this.organization = organization;
	}

	public Lookup getLookupByJobTypeId()
	{
		return this.lookupByJobTypeId;
	}

	public void setLookupByJobTypeId(Lookup lookupByJobTypeId)
	{
		this.lookupByJobTypeId = lookupByJobTypeId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public String getExtItemId()
	{
		return this.extItemId;
	}

	public void setExtItemId(String extItemId)
	{
		this.extItemId = extItemId;
	}

	public String getBillableFlag()
	{
		return this.billableFlag;
	}

	public void setBillableFlag(String billableFlag)
	{
		this.billableFlag = billableFlag;
	}

	public Long getSequenceNo()
	{
		return this.sequenceNo;
	}

	public void setSequenceNo(Long sequenceNo)
	{
		this.sequenceNo = sequenceNo;
	}

	public String getExpenseExportCode()
	{
		return this.expenseExportCode;
	}

	public void setExpenseExportCode(String expenseExportCode)
	{
		this.expenseExportCode = expenseExportCode;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public BigDecimal getCostPerUom()
	{
		return this.costPerUom;
	}

	public void setCostPerUom(BigDecimal costPerUom)
	{
		this.costPerUom = costPerUom;
	}

	public Short getPercentMargin()
	{
		return this.percentMargin;
	}

	public void setPercentMargin(Short percentMargin)
	{
		this.percentMargin = percentMargin;
	}

	public String getColumnPosition()
	{
		return this.columnPosition;
	}

	public void setColumnPosition(String columnPosition)
	{
		this.columnPosition = columnPosition;
	}

	public Set getResourceTypeItems()
	{
		return this.resourceTypeItems;
	}

	public void setResourceTypeItems(Set resourceTypeItems)
	{
		this.resourceTypeItems = resourceTypeItems;
	}

	public Set getItemCostingHistories()
	{
		return this.itemCostingHistories;
	}

	public void setItemCostingHistories(Set itemCostingHistories)
	{
		this.itemCostingHistories = itemCostingHistories;
	}

	public Set getInvoiceLines()
	{
		return this.invoiceLines;
	}

	public void setInvoiceLines(Set invoiceLines)
	{
		this.invoiceLines = invoiceLines;
	}

	public Set getServiceLines()
	{
		return this.serviceLines;
	}

	public void setServiceLines(Set serviceLines)
	{
		this.serviceLines = serviceLines;
	}

	public Set getJobItemRates()
	{
		return this.jobItemRates;
	}

	public void setJobItemRates(Set jobItemRates)
	{
		this.jobItemRates = jobItemRates;
	}

	public Set getResourceItems()
	{
		return this.resourceItems;
	}

	public void setResourceItems(Set resourceItems)
	{
		this.resourceItems = resourceItems;
	}

}
