package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * JobDistribution generated by hbm2java
 */
public class JobDistribution implements java.io.Serializable
{

	// Fields    

	private Long jobDistributionId;

	private Job job;

	private long userId;

	private Long schResourceId;

	private Date removeDate;

	private long createdBy;

	private Date dateCreated;

	private Long modifiedBy;

	private Date dateModified;

	// Constructors

	/** default constructor */
	public JobDistribution()
	{
	}

	/** minimal constructor */
	public JobDistribution(Job job, long userId, long createdBy, Date dateCreated)
	{
		this.job = job;
		this.userId = userId;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public JobDistribution(Job job, long userId, Long schResourceId, Date removeDate, long createdBy, Date dateCreated, Long modifiedBy, Date dateModified)
	{
		this.job = job;
		this.userId = userId;
		this.schResourceId = schResourceId;
		this.removeDate = removeDate;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
	}

	// Property accessors
	public Long getJobDistributionId()
	{
		return this.jobDistributionId;
	}

	public void setJobDistributionId(Long jobDistributionId)
	{
		this.jobDistributionId = jobDistributionId;
	}

	public Job getJob()
	{
		return this.job;
	}

	public void setJob(Job job)
	{
		this.job = job;
	}

	public long getUserId()
	{
		return this.userId;
	}

	public void setUserId(long userId)
	{
		this.userId = userId;
	}

	public Long getSchResourceId()
	{
		return this.schResourceId;
	}

	public void setSchResourceId(Long schResourceId)
	{
		this.schResourceId = schResourceId;
	}

	public Date getRemoveDate()
	{
		return this.removeDate;
	}

	public void setRemoveDate(Date removeDate)
	{
		this.removeDate = removeDate;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

}
