package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JobItemRate generated by hbm2java
 */
public class JobItemRate implements java.io.Serializable
{

	// Fields    

	private Long jobItemRateId;

	private Item item;

	private Lookup lookup;

	private Job job;

	private BigDecimal rate;

	private String extRateId;

	private String extUomName;

	private Date dateCreated;

	private long createdBy;

	private Date dateModified;

	private Long modifiedBy;

	private Set resourceEstimates = new HashSet(0);

	// Constructors

	/** default constructor */
	public JobItemRate()
	{
	}

	/** minimal constructor */
	public JobItemRate(Item item, Job job, String extRateId, Date dateCreated, long createdBy)
	{
		this.item = item;
		this.job = job;
		this.extRateId = extRateId;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
	}

	/** full constructor */
	public JobItemRate(Item item, Lookup lookup, Job job, BigDecimal rate, String extRateId, String extUomName, Date dateCreated, long createdBy, Date dateModified, Long modifiedBy,
			Set resourceEstimates)
	{
		this.item = item;
		this.lookup = lookup;
		this.job = job;
		this.rate = rate;
		this.extRateId = extRateId;
		this.extUomName = extUomName;
		this.dateCreated = dateCreated;
		this.createdBy = createdBy;
		this.dateModified = dateModified;
		this.modifiedBy = modifiedBy;
		this.resourceEstimates = resourceEstimates;
	}

	// Property accessors
	public Long getJobItemRateId()
	{
		return this.jobItemRateId;
	}

	public void setJobItemRateId(Long jobItemRateId)
	{
		this.jobItemRateId = jobItemRateId;
	}

	public Item getItem()
	{
		return this.item;
	}

	public void setItem(Item item)
	{
		this.item = item;
	}

	public Lookup getLookup()
	{
		return this.lookup;
	}

	public void setLookup(Lookup lookup)
	{
		this.lookup = lookup;
	}

	public Job getJob()
	{
		return this.job;
	}

	public void setJob(Job job)
	{
		this.job = job;
	}

	public BigDecimal getRate()
	{
		return this.rate;
	}

	public void setRate(BigDecimal rate)
	{
		this.rate = rate;
	}

	public String getExtRateId()
	{
		return this.extRateId;
	}

	public void setExtRateId(String extRateId)
	{
		this.extRateId = extRateId;
	}

	public String getExtUomName()
	{
		return this.extUomName;
	}

	public void setExtUomName(String extUomName)
	{
		this.extUomName = extUomName;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Set getResourceEstimates()
	{
		return this.resourceEstimates;
	}

	public void setResourceEstimates(Set resourceEstimates)
	{
		this.resourceEstimates = resourceEstimates;
	}

}
