package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LookupType generated by hbm2java
 */
public class LookupType implements java.io.Serializable
{

	// Fields    

	private Long lookupTypeId;

	private LookupType lookupType;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private String code;

	private String name;

	private String activeFlag;

	private String updatableFlag;

	private Date dateCreated;

	private Date dateModified;

	private Set lookupTypes = new HashSet(0);

	private Set lookups = new HashSet(0);

	// Constructors

	/** default constructor */
	public LookupType()
	{
	}

	/** minimal constructor */
	public LookupType(User userByCreatedBy, String activeFlag, String updatableFlag, Date dateCreated)
	{
		this.userByCreatedBy = userByCreatedBy;
		this.activeFlag = activeFlag;
		this.updatableFlag = updatableFlag;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public LookupType(LookupType lookupType, User userByModifiedBy, User userByCreatedBy, String code, String name, String activeFlag, String updatableFlag, Date dateCreated, Date dateModified,
			Set lookupTypes, Set lookups)
	{
		this.lookupType = lookupType;
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.code = code;
		this.name = name;
		this.activeFlag = activeFlag;
		this.updatableFlag = updatableFlag;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.lookupTypes = lookupTypes;
		this.lookups = lookups;
	}

	// Property accessors
	public Long getLookupTypeId()
	{
		return this.lookupTypeId;
	}

	public void setLookupTypeId(Long lookupTypeId)
	{
		this.lookupTypeId = lookupTypeId;
	}

	public LookupType getLookupType()
	{
		return this.lookupType;
	}

	public void setLookupType(LookupType lookupType)
	{
		this.lookupType = lookupType;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getActiveFlag()
	{
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag)
	{
		this.activeFlag = activeFlag;
	}

	public String getUpdatableFlag()
	{
		return this.updatableFlag;
	}

	public void setUpdatableFlag(String updatableFlag)
	{
		this.updatableFlag = updatableFlag;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Set getLookupTypes()
	{
		return this.lookupTypes;
	}

	public void setLookupTypes(Set lookupTypes)
	{
		this.lookupTypes = lookupTypes;
	}

	public Set getLookups()
	{
		return this.lookups;
	}

	public void setLookups(Set lookups)
	{
		this.lookups = lookups;
	}

}
