package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization implements java.io.Serializable
{

	// Fields    

	private Long organizationId;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private String name;

	private String code;

	private String resourceName;

	private String dbPrefix;

	private String prIntegrationName;

	private String invIntegrationName;

	private String extDirectDealerId;

	private String payCodeTable;

	private String pdaItemPaycodesTable;

	private long sequenceNo;

	private Date dateCreated;

	private Date dateModified;

	private Long schedulerContactId;

	private String extDciDealerId;

	private String invoiceSuffix;

	private String commentId;

	private String defaultSite;

	private Set items = new HashSet(0);

	private Set invoices = new HashSet(0);

	private Set customers = new HashSet(0);

	private Set payrollBatches = new HashSet(0);

	private Set resources = new HashSet(0);

	private Set contacts = new HashSet(0);

	private Set userOrganizations = new HashSet(0);

	// Constructors

	/** default constructor */
	public Organization()
	{
	}

	/** minimal constructor */
	public Organization(User userByCreatedBy, String name, String resourceName, String dbPrefix, String payCodeTable, String pdaItemPaycodesTable, long sequenceNo, Date dateCreated)
	{
		this.userByCreatedBy = userByCreatedBy;
		this.name = name;
		this.resourceName = resourceName;
		this.dbPrefix = dbPrefix;
		this.payCodeTable = payCodeTable;
		this.pdaItemPaycodesTable = pdaItemPaycodesTable;
		this.sequenceNo = sequenceNo;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public Organization(User userByModifiedBy, User userByCreatedBy, String name, String code, String resourceName, String dbPrefix, String prIntegrationName, String invIntegrationName,
			String extDirectDealerId, String payCodeTable, String pdaItemPaycodesTable, long sequenceNo, Date dateCreated, Date dateModified, Long schedulerContactId, String extDciDealerId,
			String invoiceSuffix, String commentId, String defaultSite, Set items, Set invoices, Set customers, Set payrollBatches, Set resources, Set contacts, Set userOrganizations)
	{
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.name = name;
		this.code = code;
		this.resourceName = resourceName;
		this.dbPrefix = dbPrefix;
		this.prIntegrationName = prIntegrationName;
		this.invIntegrationName = invIntegrationName;
		this.extDirectDealerId = extDirectDealerId;
		this.payCodeTable = payCodeTable;
		this.pdaItemPaycodesTable = pdaItemPaycodesTable;
		this.sequenceNo = sequenceNo;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.schedulerContactId = schedulerContactId;
		this.extDciDealerId = extDciDealerId;
		this.invoiceSuffix = invoiceSuffix;
		this.commentId = commentId;
		this.defaultSite = defaultSite;
		this.items = items;
		this.invoices = invoices;
		this.customers = customers;
		this.payrollBatches = payrollBatches;
		this.resources = resources;
		this.contacts = contacts;
		this.userOrganizations = userOrganizations;
	}

	// Property accessors
	public Long getOrganizationId()
	{
		return this.organizationId;
	}

	public void setOrganizationId(Long organizationId)
	{
		this.organizationId = organizationId;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getResourceName()
	{
		return this.resourceName;
	}

	public void setResourceName(String resourceName)
	{
		this.resourceName = resourceName;
	}

	public String getDbPrefix()
	{
		return this.dbPrefix;
	}

	public void setDbPrefix(String dbPrefix)
	{
		this.dbPrefix = dbPrefix;
	}

	public String getPrIntegrationName()
	{
		return this.prIntegrationName;
	}

	public void setPrIntegrationName(String prIntegrationName)
	{
		this.prIntegrationName = prIntegrationName;
	}

	public String getInvIntegrationName()
	{
		return this.invIntegrationName;
	}

	public void setInvIntegrationName(String invIntegrationName)
	{
		this.invIntegrationName = invIntegrationName;
	}

	public String getExtDirectDealerId()
	{
		return this.extDirectDealerId;
	}

	public void setExtDirectDealerId(String extDirectDealerId)
	{
		this.extDirectDealerId = extDirectDealerId;
	}

	public String getPayCodeTable()
	{
		return this.payCodeTable;
	}

	public void setPayCodeTable(String payCodeTable)
	{
		this.payCodeTable = payCodeTable;
	}

	public String getPdaItemPaycodesTable()
	{
		return this.pdaItemPaycodesTable;
	}

	public void setPdaItemPaycodesTable(String pdaItemPaycodesTable)
	{
		this.pdaItemPaycodesTable = pdaItemPaycodesTable;
	}

	public long getSequenceNo()
	{
		return this.sequenceNo;
	}

	public void setSequenceNo(long sequenceNo)
	{
		this.sequenceNo = sequenceNo;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Long getSchedulerContactId()
	{
		return this.schedulerContactId;
	}

	public void setSchedulerContactId(Long schedulerContactId)
	{
		this.schedulerContactId = schedulerContactId;
	}

	public String getExtDciDealerId()
	{
		return this.extDciDealerId;
	}

	public void setExtDciDealerId(String extDciDealerId)
	{
		this.extDciDealerId = extDciDealerId;
	}

	public String getInvoiceSuffix()
	{
		return this.invoiceSuffix;
	}

	public void setInvoiceSuffix(String invoiceSuffix)
	{
		this.invoiceSuffix = invoiceSuffix;
	}

	public String getCommentId()
	{
		return this.commentId;
	}

	public void setCommentId(String commentId)
	{
		this.commentId = commentId;
	}

	public String getDefaultSite()
	{
		return this.defaultSite;
	}

	public void setDefaultSite(String defaultSite)
	{
		this.defaultSite = defaultSite;
	}

	public Set getItems()
	{
		return this.items;
	}

	public void setItems(Set items)
	{
		this.items = items;
	}

	public Set getInvoices()
	{
		return this.invoices;
	}

	public void setInvoices(Set invoices)
	{
		this.invoices = invoices;
	}

	public Set getCustomers()
	{
		return this.customers;
	}

	public void setCustomers(Set customers)
	{
		this.customers = customers;
	}

	public Set getPayrollBatches()
	{
		return this.payrollBatches;
	}

	public void setPayrollBatches(Set payrollBatches)
	{
		this.payrollBatches = payrollBatches;
	}

	public Set getResources()
	{
		return this.resources;
	}

	public void setResources(Set resources)
	{
		this.resources = resources;
	}

	public Set getContacts()
	{
		return this.contacts;
	}

	public void setContacts(Set contacts)
	{
		this.contacts = contacts;
	}

	public Set getUserOrganizations()
	{
		return this.userOrganizations;
	}

	public void setUserOrganizations(Set userOrganizations)
	{
		this.userOrganizations = userOrganizations;
	}

}
