package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

/**
 * OrgGpTable generated by hbm2java
 */
public class OrgGpTable implements java.io.Serializable
{

	// Fields    

	private Long orgTableId;

	private long tableId;

	private long orgId;

	private String viewName;

	// Constructors

	/** default constructor */
	public OrgGpTable()
	{
	}

	/** full constructor */
	public OrgGpTable(long tableId, long orgId, String viewName)
	{
		this.tableId = tableId;
		this.orgId = orgId;
		this.viewName = viewName;
	}

	// Property accessors
	public Long getOrgTableId()
	{
		return this.orgTableId;
	}

	public void setOrgTableId(Long orgTableId)
	{
		this.orgTableId = orgTableId;
	}

	public long getTableId()
	{
		return this.tableId;
	}

	public void setTableId(long tableId)
	{
		this.tableId = tableId;
	}

	public long getOrgId()
	{
		return this.orgId;
	}

	public void setOrgId(long orgId)
	{
		this.orgId = orgId;
	}

	public String getViewName()
	{
		return this.viewName;
	}

	public void setViewName(String viewName)
	{
		this.viewName = viewName;
	}

}
