package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * PayrollBatch generated by hbm2java
 */
public class PayrollBatch implements java.io.Serializable
{

	// Fields    

	private Long intBatchId;

	private Lookup lookup;

	private Organization organization;

	private User user;

	private String extBatchId;

	private Date beginDate;

	private Date endDate;

	private Date dateCreated;

	// Constructors

	/** default constructor */
	public PayrollBatch()
	{
	}

	/** minimal constructor */
	public PayrollBatch(Organization organization, String extBatchId, Date beginDate, Date endDate)
	{
		this.organization = organization;
		this.extBatchId = extBatchId;
		this.beginDate = beginDate;
		this.endDate = endDate;
	}

	/** full constructor */
	public PayrollBatch(Lookup lookup, Organization organization, User user, String extBatchId, Date beginDate, Date endDate, Date dateCreated)
	{
		this.lookup = lookup;
		this.organization = organization;
		this.user = user;
		this.extBatchId = extBatchId;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.dateCreated = dateCreated;
	}

	// Property accessors
	public Long getIntBatchId()
	{
		return this.intBatchId;
	}

	public void setIntBatchId(Long intBatchId)
	{
		this.intBatchId = intBatchId;
	}

	public Lookup getLookup()
	{
		return this.lookup;
	}

	public void setLookup(Lookup lookup)
	{
		this.lookup = lookup;
	}

	public Organization getOrganization()
	{
		return this.organization;
	}

	public void setOrganization(Organization organization)
	{
		this.organization = organization;
	}

	public User getUser()
	{
		return this.user;
	}

	public void setUser(User user)
	{
		this.user = user;
	}

	public String getExtBatchId()
	{
		return this.extBatchId;
	}

	public void setExtBatchId(String extBatchId)
	{
		this.extBatchId = extBatchId;
	}

	public Date getBeginDate()
	{
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate)
	{
		this.beginDate = beginDate;
	}

	public Date getEndDate()
	{
		return this.endDate;
	}

	public void setEndDate(Date endDate)
	{
		this.endDate = endDate;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

}
