package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;

/**
 * PayrollBatchLine generated by hbm2java
 */
public class PayrollBatchLine implements java.io.Serializable
{

	// Fields    

	private Long serviceLineId;

	private ServiceLine serviceLine;

	private long intBatchId;

	private BigDecimal payrollQty;

	private BigDecimal payrollRate;

	private BigDecimal payrollTotal;

	private String extItemId;

	private String extEmployeeId;

	private String extPayCode;

	// Constructors

	/** default constructor */
	public PayrollBatchLine()
	{
	}

	/** minimal constructor */
	public PayrollBatchLine(ServiceLine serviceLine, long intBatchId)
	{
		this.serviceLine = serviceLine;
		this.intBatchId = intBatchId;
	}

	/** full constructor */
	public PayrollBatchLine(ServiceLine serviceLine, long intBatchId, BigDecimal payrollQty, BigDecimal payrollRate, BigDecimal payrollTotal, String extItemId, String extEmployeeId, String extPayCode)
	{
		this.serviceLine = serviceLine;
		this.intBatchId = intBatchId;
		this.payrollQty = payrollQty;
		this.payrollRate = payrollRate;
		this.payrollTotal = payrollTotal;
		this.extItemId = extItemId;
		this.extEmployeeId = extEmployeeId;
		this.extPayCode = extPayCode;
	}

	// Property accessors
	public Long getServiceLineId()
	{
		return this.serviceLineId;
	}

	public void setServiceLineId(Long serviceLineId)
	{
		this.serviceLineId = serviceLineId;
	}

	public ServiceLine getServiceLine()
	{
		return this.serviceLine;
	}

	public void setServiceLine(ServiceLine serviceLine)
	{
		this.serviceLine = serviceLine;
	}

	public long getIntBatchId()
	{
		return this.intBatchId;
	}

	public void setIntBatchId(long intBatchId)
	{
		this.intBatchId = intBatchId;
	}

	public BigDecimal getPayrollQty()
	{
		return this.payrollQty;
	}

	public void setPayrollQty(BigDecimal payrollQty)
	{
		this.payrollQty = payrollQty;
	}

	public BigDecimal getPayrollRate()
	{
		return this.payrollRate;
	}

	public void setPayrollRate(BigDecimal payrollRate)
	{
		this.payrollRate = payrollRate;
	}

	public BigDecimal getPayrollTotal()
	{
		return this.payrollTotal;
	}

	public void setPayrollTotal(BigDecimal payrollTotal)
	{
		this.payrollTotal = payrollTotal;
	}

	public String getExtItemId()
	{
		return this.extItemId;
	}

	public void setExtItemId(String extItemId)
	{
		this.extItemId = extItemId;
	}

	public String getExtEmployeeId()
	{
		return this.extEmployeeId;
	}

	public void setExtEmployeeId(String extEmployeeId)
	{
		this.extEmployeeId = extEmployeeId;
	}

	public String getExtPayCode()
	{
		return this.extPayCode;
	}

	public void setExtPayCode(String extPayCode)
	{
		this.extPayCode = extPayCode;
	}

}
