package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * ProjectNote generated by hbm2java
 */
public class ProjectNote implements java.io.Serializable
{

	// Fields    

	private Long projectNoteId;

	private Project project;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private String note;

	private Date dateCreated;

	private Date dateModified;

	// Constructors

	/** default constructor */
	public ProjectNote()
	{
	}

	/** minimal constructor */
	public ProjectNote(Project project, User userByCreatedBy, String note, Date dateCreated)
	{
		this.project = project;
		this.userByCreatedBy = userByCreatedBy;
		this.note = note;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public ProjectNote(Project project, User userByModifiedBy, User userByCreatedBy, String note, Date dateCreated, Date dateModified)
	{
		this.project = project;
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.note = note;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	// Property accessors
	public Long getProjectNoteId()
	{
		return this.projectNoteId;
	}

	public void setProjectNoteId(Long projectNoteId)
	{
		this.projectNoteId = projectNoteId;
	}

	public Project getProject()
	{
		return this.project;
	}

	public void setProject(Project project)
	{
		this.project = project;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public String getNote()
	{
		return this.note;
	}

	public void setNote(String note)
	{
		this.note = note;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

}
