package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable
{

	// Fields    

	private Long projectId;

	private Customer customer;
	
	private Customer endUser;

	private User userByModifiedBy;

	private Lookup lookupByProjectTypeId;

	private User userByCreatedBy;

	private Lookup lookupByProjectStatusTypeId;

	private long projectNo;

	private String jobName;

	private BigDecimal percentComplete;
	
	private String isNew;

	private Date dateCreated;

	private Date dateModified;

	private Set requests = new HashSet(0);

	private Set documents = new HashSet(0);

	private Set projectNotes = new HashSet(0);

	private Set punchlists = new HashSet(0);

	private Set jobs = new HashSet(0);

	// Constructors

	/** default constructor */
	public Project()
	{
	}

	/** minimal constructor */
	public Project(Customer customer, Lookup lookupByProjectTypeId, User userByCreatedBy, Lookup lookupByProjectStatusTypeId, long projectNo, Date dateCreated)
	{
		this.customer = customer;
		this.lookupByProjectTypeId = lookupByProjectTypeId;
		this.userByCreatedBy = userByCreatedBy;
		this.lookupByProjectStatusTypeId = lookupByProjectStatusTypeId;
		this.projectNo = projectNo;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public Project(Customer customer, Customer endUser, User userByModifiedBy, Lookup lookupByProjectTypeId, User userByCreatedBy, Lookup lookupByProjectStatusTypeId, long projectNo, String jobName,
			BigDecimal percentComplete, String isNew, Date dateCreated, Date dateModified, Set requests, Set documents, Set projectNotes, Set punchlists, Set jobs)
	{
		this.customer = customer;
		this.endUser = endUser;
		this.userByModifiedBy = userByModifiedBy;
		this.lookupByProjectTypeId = lookupByProjectTypeId;
		this.userByCreatedBy = userByCreatedBy;
		this.lookupByProjectStatusTypeId = lookupByProjectStatusTypeId;
		this.projectNo = projectNo;
		this.jobName = jobName;
		this.percentComplete = percentComplete;
		this.isNew = isNew;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.requests = requests;
		this.documents = documents;
		this.projectNotes = projectNotes;
		this.punchlists = punchlists;
		this.jobs = jobs;
	}

	// Property accessors
	public Long getProjectId()
	{
		return this.projectId;
	}

	public void setProjectId(Long projectId)
	{
		this.projectId = projectId;
	}

	public Customer getCustomer()
	{
		return this.customer;
	}

	public void setCustomer(Customer customer)
	{
		this.customer = customer;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public Lookup getLookupByProjectTypeId()
	{
		return this.lookupByProjectTypeId;
	}

	public void setLookupByProjectTypeId(Lookup lookupByProjectTypeId)
	{
		this.lookupByProjectTypeId = lookupByProjectTypeId;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public Lookup getLookupByProjectStatusTypeId()
	{
		return this.lookupByProjectStatusTypeId;
	}

	public void setLookupByProjectStatusTypeId(Lookup lookupByProjectStatusTypeId)
	{
		this.lookupByProjectStatusTypeId = lookupByProjectStatusTypeId;
	}

	public long getProjectNo()
	{
		return this.projectNo;
	}

	public void setProjectNo(long projectNo)
	{
		this.projectNo = projectNo;
	}

	public String getJobName()
	{
		return this.jobName;
	}

	public void setJobName(String jobName)
	{
		this.jobName = jobName;
	}

	public BigDecimal getPercentComplete()
	{
		return this.percentComplete;
	}

	public void setPercentComplete(BigDecimal percentComplete)
	{
		this.percentComplete = percentComplete;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public String getIsNew()
	{
		return isNew;
	}

	public void setIsNew(String isNew)
	{
		this.isNew = isNew;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Set getRequests()
	{
		return this.requests;
	}

	public void setRequests(Set requests)
	{
		this.requests = requests;
	}

	public Set getDocuments()
	{
		return this.documents;
	}

	public void setDocuments(Set documents)
	{
		this.documents = documents;
	}

	public Set getProjectNotes()
	{
		return this.projectNotes;
	}

	public void setProjectNotes(Set projectNotes)
	{
		this.projectNotes = projectNotes;
	}

	public Set getPunchlists()
	{
		return this.punchlists;
	}

	public void setPunchlists(Set punchlists)
	{
		this.punchlists = punchlists;
	}

	public Set getJobs()
	{
		return this.jobs;
	}

	public void setJobs(Set jobs)
	{
		this.jobs = jobs;
	}

	public Customer getEndUser() {
		return endUser;
	}

	public void setEndUser(Customer endUser) {
		this.endUser = endUser;
	}

}
