package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * QuoteCondition generated by hbm2java
 */
public class QuoteCondition implements java.io.Serializable
{

	// Fields    

	private Long quoteConditionId;

	private Quote quote;

	private Condition condition;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private char useFlag;

	private Date dateCreated;

	private Date dateModified;

	// Constructors

	/** default constructor */
	public QuoteCondition()
	{
	}

	/** minimal constructor */
	public QuoteCondition(Quote quote, Condition condition, char useFlag)
	{
		this.quote = quote;
		this.condition = condition;
		this.useFlag = useFlag;
	}

	/** full constructor */
	public QuoteCondition(Quote quote, Condition condition, User userByModifiedBy, User userByCreatedBy, char useFlag, Date dateCreated, Date dateModified)
	{
		this.quote = quote;
		this.condition = condition;
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.useFlag = useFlag;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	// Property accessors
	public Long getQuoteConditionId()
	{
		return this.quoteConditionId;
	}

	public void setQuoteConditionId(Long quoteConditionId)
	{
		this.quoteConditionId = quoteConditionId;
	}

	public Quote getQuote()
	{
		return this.quote;
	}

	public void setQuote(Quote quote)
	{
		this.quote = quote;
	}

	public Condition getCondition()
	{
		return this.condition;
	}

	public void setCondition(Condition condition)
	{
		this.condition = condition;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public char getUseFlag()
	{
		return this.useFlag;
	}

	public void setUseFlag(char useFlag)
	{
		this.useFlag = useFlag;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

}
