package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * RequestDocument generated by hbm2java
 */
public class RequestDocument implements java.io.Serializable
{

	// Fields    

	private Long requestDocumentId;

	private Request request;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private String name;

	private String description;

	private Date dateCreated;

	private Date dateModified;

	// Constructors

	/** default constructor */
	public RequestDocument()
	{
	}

	/** minimal constructor */
	public RequestDocument(Request request, User userByCreatedBy, Date dateCreated)
	{
		this.request = request;
		this.userByCreatedBy = userByCreatedBy;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public RequestDocument(Request request, User userByModifiedBy, User userByCreatedBy, String name, String description, Date dateCreated, Date dateModified)
	{
		this.request = request;
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.name = name;
		this.description = description;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	// Property accessors
	public Long getRequestDocumentId()
	{
		return this.requestDocumentId;
	}

	public void setRequestDocumentId(Long requestDocumentId)
	{
		this.requestDocumentId = requestDocumentId;
	}

	public Request getRequest()
	{
		return this.request;
	}

	public void setRequest(Request request)
	{
		this.request = request;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

}
