package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * ResourceTypeItem generated by hbm2java
 */
public class ResourceTypeItem implements java.io.Serializable
{

	// Fields    

	private Long resTypeItemId;

	private Item item;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private ResourceType resourceType;

	private String defaultItemFlag;

	private Date dateCreated;

	private Date dateModified;

	// Constructors

	/** default constructor */
	public ResourceTypeItem()
	{
	}

	/** minimal constructor */
	public ResourceTypeItem(Item item, User userByCreatedBy, ResourceType resourceType, String defaultItemFlag, Date dateCreated)
	{
		this.item = item;
		this.userByCreatedBy = userByCreatedBy;
		this.resourceType = resourceType;
		this.defaultItemFlag = defaultItemFlag;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public ResourceTypeItem(Item item, User userByModifiedBy, User userByCreatedBy, ResourceType resourceType, String defaultItemFlag, Date dateCreated, Date dateModified)
	{
		this.item = item;
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.resourceType = resourceType;
		this.defaultItemFlag = defaultItemFlag;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	// Property accessors
	public Long getResTypeItemId()
	{
		return this.resTypeItemId;
	}

	public void setResTypeItemId(Long resTypeItemId)
	{
		this.resTypeItemId = resTypeItemId;
	}

	public Item getItem()
	{
		return this.item;
	}

	public void setItem(Item item)
	{
		this.item = item;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public ResourceType getResourceType()
	{
		return this.resourceType;
	}

	public void setResourceType(ResourceType resourceType)
	{
		this.resourceType = resourceType;
	}

	public String getDefaultItemFlag()
	{
		return this.defaultItemFlag;
	}

	public void setDefaultItemFlag(String defaultItemFlag)
	{
		this.defaultItemFlag = defaultItemFlag;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

}
