package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ResourceType generated by hbm2java
 */
public class ResourceType implements java.io.Serializable
{

	// Fields    

	private Long resourceTypeId;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private String code;

	private String name;

	private Long defTimeUomTypeId;

	private Long defResCatTypeId;

	private String estimateHoursFlag;

	private String uniqueFlag;

	private Long sequenceNo;

	private Date dateCreated;

	private Date dateModified;

	private Set resources = new HashSet(0);

	private Set resourceTypeItems = new HashSet(0);

	private Set resourceEstimates = new HashSet(0);

	// Constructors

	/** default constructor */
	public ResourceType()
	{
	}

	/** minimal constructor */
	public ResourceType(User userByCreatedBy, String code, String name, String estimateHoursFlag, String uniqueFlag, Date dateCreated)
	{
		this.userByCreatedBy = userByCreatedBy;
		this.code = code;
		this.name = name;
		this.estimateHoursFlag = estimateHoursFlag;
		this.uniqueFlag = uniqueFlag;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public ResourceType(User userByModifiedBy, User userByCreatedBy, String code, String name, Long defTimeUomTypeId, Long defResCatTypeId, String estimateHoursFlag, String uniqueFlag,
			Long sequenceNo, Date dateCreated, Date dateModified, Set resources, Set resourceTypeItems, Set resourceEstimates)
	{
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.code = code;
		this.name = name;
		this.defTimeUomTypeId = defTimeUomTypeId;
		this.defResCatTypeId = defResCatTypeId;
		this.estimateHoursFlag = estimateHoursFlag;
		this.uniqueFlag = uniqueFlag;
		this.sequenceNo = sequenceNo;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.resources = resources;
		this.resourceTypeItems = resourceTypeItems;
		this.resourceEstimates = resourceEstimates;
	}

	// Property accessors
	public Long getResourceTypeId()
	{
		return this.resourceTypeId;
	}

	public void setResourceTypeId(Long resourceTypeId)
	{
		this.resourceTypeId = resourceTypeId;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Long getDefTimeUomTypeId()
	{
		return this.defTimeUomTypeId;
	}

	public void setDefTimeUomTypeId(Long defTimeUomTypeId)
	{
		this.defTimeUomTypeId = defTimeUomTypeId;
	}

	public Long getDefResCatTypeId()
	{
		return this.defResCatTypeId;
	}

	public void setDefResCatTypeId(Long defResCatTypeId)
	{
		this.defResCatTypeId = defResCatTypeId;
	}

	public String getEstimateHoursFlag()
	{
		return this.estimateHoursFlag;
	}

	public void setEstimateHoursFlag(String estimateHoursFlag)
	{
		this.estimateHoursFlag = estimateHoursFlag;
	}

	public String getUniqueFlag()
	{
		return this.uniqueFlag;
	}

	public void setUniqueFlag(String uniqueFlag)
	{
		this.uniqueFlag = uniqueFlag;
	}

	public Long getSequenceNo()
	{
		return this.sequenceNo;
	}

	public void setSequenceNo(Long sequenceNo)
	{
		this.sequenceNo = sequenceNo;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Set getResources()
	{
		return this.resources;
	}

	public void setResources(Set resources)
	{
		this.resources = resources;
	}

	public Set getResourceTypeItems()
	{
		return this.resourceTypeItems;
	}

	public void setResourceTypeItems(Set resourceTypeItems)
	{
		this.resourceTypeItems = resourceTypeItems;
	}

	public Set getResourceEstimates()
	{
		return this.resourceEstimates;
	}

	public void setResourceEstimates(Set resourceEstimates)
	{
		this.resourceEstimates = resourceEstimates;
	}

}
