package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * ResourceEstimate generated by hbm2java
 */
public class ResourceEstimate implements java.io.Serializable
{

	// Fields    

	private Long resourceEstId;

	private JobItemRate jobItemRate;

	private User userByModifiedBy;

	private Service service;

	private Job job;

	private User userByCreatedBy;

	private ResourceType resourceType;

	private Long unitQty;

	private long timeUomTypeId;

	private Long timeQty;

	private Date startDate;

	private Long totalHours;

	private Date dateCreated;

	private Date dateModified;

	// Constructors

	/** default constructor */
	public ResourceEstimate()
	{
	}

	/** minimal constructor */
	public ResourceEstimate(Job job, User userByCreatedBy, ResourceType resourceType, long timeUomTypeId, Date dateCreated)
	{
		this.job = job;
		this.userByCreatedBy = userByCreatedBy;
		this.resourceType = resourceType;
		this.timeUomTypeId = timeUomTypeId;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public ResourceEstimate(JobItemRate jobItemRate, User userByModifiedBy, Service service, Job job, User userByCreatedBy, ResourceType resourceType, Long unitQty, long timeUomTypeId, Long timeQty,
			Date startDate, Long totalHours, Date dateCreated, Date dateModified)
	{
		this.jobItemRate = jobItemRate;
		this.userByModifiedBy = userByModifiedBy;
		this.service = service;
		this.job = job;
		this.userByCreatedBy = userByCreatedBy;
		this.resourceType = resourceType;
		this.unitQty = unitQty;
		this.timeUomTypeId = timeUomTypeId;
		this.timeQty = timeQty;
		this.startDate = startDate;
		this.totalHours = totalHours;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	// Property accessors
	public Long getResourceEstId()
	{
		return this.resourceEstId;
	}

	public void setResourceEstId(Long resourceEstId)
	{
		this.resourceEstId = resourceEstId;
	}

	public JobItemRate getJobItemRate()
	{
		return this.jobItemRate;
	}

	public void setJobItemRate(JobItemRate jobItemRate)
	{
		this.jobItemRate = jobItemRate;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public Service getService()
	{
		return this.service;
	}

	public void setService(Service service)
	{
		this.service = service;
	}

	public Job getJob()
	{
		return this.job;
	}

	public void setJob(Job job)
	{
		this.job = job;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public ResourceType getResourceType()
	{
		return this.resourceType;
	}

	public void setResourceType(ResourceType resourceType)
	{
		this.resourceType = resourceType;
	}

	public Long getUnitQty()
	{
		return this.unitQty;
	}

	public void setUnitQty(Long unitQty)
	{
		this.unitQty = unitQty;
	}

	public long getTimeUomTypeId()
	{
		return this.timeUomTypeId;
	}

	public void setTimeUomTypeId(long timeUomTypeId)
	{
		this.timeUomTypeId = timeUomTypeId;
	}

	public Long getTimeQty()
	{
		return this.timeQty;
	}

	public void setTimeQty(Long timeQty)
	{
		this.timeQty = timeQty;
	}

	public Date getStartDate()
	{
		return this.startDate;
	}

	public void setStartDate(Date startDate)
	{
		this.startDate = startDate;
	}

	public Long getTotalHours()
	{
		return this.totalHours;
	}

	public void setTotalHours(Long totalHours)
	{
		this.totalHours = totalHours;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

}
