package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Resource generated by hbm2java
 */
public class Resource implements java.io.Serializable
{

	// Fields    

	private Long resourceId;

	private User userByUserId;

	private Organization organization;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private ResourceType resourceType;

	private String name;

	private long resCategoryTypeId;

	private String attachedFlag;

	private String vendorName;

	private String extVendorId;

	private String activeFlag;

	private String foremanFlag;

	private String notes;

	private Long sortOrder;

	private Date dateCreated;

	private Date dateModified;

	private String qp3Team;

	private Set schResources = new HashSet(0);

	private Set resourceItems = new HashSet(0);

	private Set jobs = new HashSet(0);

	private Set serviceLines = new HashSet(0);

	private Set schResources_1 = new HashSet(0);

	// Constructors

	/** default constructor */
	public Resource()
	{
	}

	/** minimal constructor */
	public Resource(Organization organization, User userByCreatedBy, ResourceType resourceType, String name, long resCategoryTypeId, String activeFlag, String foremanFlag, Date dateCreated)
	{
		this.organization = organization;
		this.userByCreatedBy = userByCreatedBy;
		this.resourceType = resourceType;
		this.name = name;
		this.resCategoryTypeId = resCategoryTypeId;
		this.activeFlag = activeFlag;
		this.foremanFlag = foremanFlag;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public Resource(User userByUserId, Organization organization, User userByModifiedBy, User userByCreatedBy, ResourceType resourceType, String name, long resCategoryTypeId, String attachedFlag,
			String vendorName, String extVendorId, String activeFlag, String foremanFlag, String notes, Long sortOrder, Date dateCreated, Date dateModified, String qp3Team, Set schResources,
			Set resourceItems, Set jobs, Set serviceLines, Set schResources_1)
	{
		this.userByUserId = userByUserId;
		this.organization = organization;
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.resourceType = resourceType;
		this.name = name;
		this.resCategoryTypeId = resCategoryTypeId;
		this.attachedFlag = attachedFlag;
		this.vendorName = vendorName;
		this.extVendorId = extVendorId;
		this.activeFlag = activeFlag;
		this.foremanFlag = foremanFlag;
		this.notes = notes;
		this.sortOrder = sortOrder;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.qp3Team = qp3Team;
		this.schResources = schResources;
		this.resourceItems = resourceItems;
		this.jobs = jobs;
		this.serviceLines = serviceLines;
		this.schResources_1 = schResources_1;
	}

	// Property accessors
	public Long getResourceId()
	{
		return this.resourceId;
	}

	public void setResourceId(Long resourceId)
	{
		this.resourceId = resourceId;
	}

	public User getUserByUserId()
	{
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId)
	{
		this.userByUserId = userByUserId;
	}

	public Organization getOrganization()
	{
		return this.organization;
	}

	public void setOrganization(Organization organization)
	{
		this.organization = organization;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public ResourceType getResourceType()
	{
		return this.resourceType;
	}

	public void setResourceType(ResourceType resourceType)
	{
		this.resourceType = resourceType;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public long getResCategoryTypeId()
	{
		return this.resCategoryTypeId;
	}

	public void setResCategoryTypeId(long resCategoryTypeId)
	{
		this.resCategoryTypeId = resCategoryTypeId;
	}

	public String getAttachedFlag()
	{
		return this.attachedFlag;
	}

	public void setAttachedFlag(String attachedFlag)
	{
		this.attachedFlag = attachedFlag;
	}

	public String getVendorName()
	{
		return this.vendorName;
	}

	public void setVendorName(String vendorName)
	{
		this.vendorName = vendorName;
	}

	public String getExtVendorId()
	{
		return this.extVendorId;
	}

	public void setExtVendorId(String extVendorId)
	{
		this.extVendorId = extVendorId;
	}

	public String getActiveFlag()
	{
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag)
	{
		this.activeFlag = activeFlag;
	}

	public String getForemanFlag()
	{
		return this.foremanFlag;
	}

	public void setForemanFlag(String foremanFlag)
	{
		this.foremanFlag = foremanFlag;
	}

	public String getNotes()
	{
		return this.notes;
	}

	public void setNotes(String notes)
	{
		this.notes = notes;
	}

	public Long getSortOrder()
	{
		return this.sortOrder;
	}

	public void setSortOrder(Long sortOrder)
	{
		this.sortOrder = sortOrder;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public String getQp3Team()
	{
		return this.qp3Team;
	}

	public void setQp3Team(String qp3Team)
	{
		this.qp3Team = qp3Team;
	}

	public Set getSchResources()
	{
		return this.schResources;
	}

	public void setSchResources(Set schResources)
	{
		this.schResources = schResources;
	}

	public Set getResourceItems()
	{
		return this.resourceItems;
	}

	public void setResourceItems(Set resourceItems)
	{
		this.resourceItems = resourceItems;
	}

	public Set getJobs()
	{
		return this.jobs;
	}

	public void setJobs(Set jobs)
	{
		this.jobs = jobs;
	}

	public Set getServiceLines()
	{
		return this.serviceLines;
	}

	public void setServiceLines(Set serviceLines)
	{
		this.serviceLines = serviceLines;
	}

	public Set getSchResources_1()
	{
		return this.schResources_1;
	}

	public void setSchResources_1(Set schResources_1)
	{
		this.schResources_1 = schResources_1;
	}

}
