package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable
{

	// Fields    

	private Long roleId;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private String name;

	private String code;

	private Date dateCreated;

	private Date dateModified;

	private Set userRoles = new HashSet(0);

	private Set roleFunctionRights = new HashSet(0);

	// Constructors

	/** default constructor */
	public Role()
	{
	}

	/** minimal constructor */
	public Role(User userByCreatedBy, String name, String code, Date dateCreated)
	{
		this.userByCreatedBy = userByCreatedBy;
		this.name = name;
		this.code = code;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public Role(User userByModifiedBy, User userByCreatedBy, String name, String code, Date dateCreated, Date dateModified, Set userRoles, Set roleFunctionRights)
	{
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.name = name;
		this.code = code;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.userRoles = userRoles;
		this.roleFunctionRights = roleFunctionRights;
	}

	// Property accessors
	public Long getRoleId()
	{
		return this.roleId;
	}

	public void setRoleId(Long roleId)
	{
		this.roleId = roleId;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Set getUserRoles()
	{
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles)
	{
		this.userRoles = userRoles;
	}

	public Set getRoleFunctionRights()
	{
		return this.roleFunctionRights;
	}

	public void setRoleFunctionRights(Set roleFunctionRights)
	{
		this.roleFunctionRights = roleFunctionRights;
	}

}
