package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

/**
 * ServiceStatuse generated by hbm2java
 */
public class ServiceStatuse implements java.io.Serializable
{

	// Fields    

	private Long statusId;

	private String code;

	private String name;

	// Constructors

	/** default constructor */
	public ServiceStatuse()
	{
	}

	/** full constructor */
	public ServiceStatuse(String code, String name)
	{
		this.code = code;
		this.name = name;
	}

	// Property accessors
	public Long getStatusId()
	{
		return this.statusId;
	}

	public void setStatusId(Long statusId)
	{
		this.statusId = statusId;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

}
