package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable
{

	// Fields    

	private Long serviceId;

	private Lookup lookupByPunchlistTypeId;

	private Contact contactBySupportContactId;

	private JobLocation jobLocationByJobLocationId;

	private Contact contactByDesignerContactId;

	private Lookup lookupByScheduleTypeId;

	private Lookup lookupByWoodProductTypeId;

	private Lookup lookupByPriFurnLineTypeId;

	private Lookup lookupBySecFurnLineTypeId;

	private Lookup lookupByPriFurnTypeId;

	private Request request;

	private Contact contactByIdmContactId;

	private Contact contactByCustomerContactId;

	private User userByModifiedBy;

	private Lookup lookupByServiceTypeId;

	private Lookup lookupByBillingTypeId;

	private Lookup lookupByServStatusTypeId;

	private JobLocation jobLocationByReportToLocId;

	private Lookup lookupByDeliveryTypeId;

	private Lookup lookupBySecFurnTypeId;

	private Contact contactByProjectMgrContactId;

	private Job job;

	private User userByCreatedBy;

	private Contact contactBySalesContactId;

	private Long quoteId;

	private Long serviceNo;

	private String description;

	private String internalReqFlag;

	private String customerRefNo;

	private String poNo;

	private Long orderedBy;

	private Date orderedDate;

	private Date estStartDate;

	private Date estStartTime;

	private Date estEndDate;

	private Date truckShipDate;

	private Date truckArrivalDate;

	private String productSetupDesc;

	private String warehouseLoc;

	private String numStations;

	private String productQty;

	private String blueprintLocation;

	private Long quoteTotal;

	private Character headValFlag;

	private Character locValFlag;

	private Character prodValFlag;

	private Character schValFlag;

	private Character taskValFlag;

	private Character resValFlag;

	private Character custValFlag;

	private Character billValFlag;

	private String custCol1;

	private String custCol2;

	private String custCol3;

	private String custCol4;

	private String custCol5;

	private String custCol6;

	private String custCol7;

	private String custCol8;

	private String custCol9;

	private String custCol10;

	private String taxableFlag;

	private String watchFlag;

	private String weekendFlag;

	private String misc;

	private Date dateCreated;

	private Date dateModified;

	private Date schStartDate;

	private Date schStartTime;

	private Date schEndDate;

	private Date actStartDate;

	private Date actStartTime;

	private Date actEndDate;

	private Long priorityTypeId;

	private Long versionNo;

	private Set serviceLinesForTcServiceId = new HashSet(0);

	private Set trackings = new HashSet(0);

	private Set serviceTasks = new HashSet(0);

	private Set serviceLinesForPhServiceId = new HashSet(0);

	private Set schResourcesForServiceId = new HashSet(0);

	private Set serviceLinesForBillServiceId = new HashSet(0);

	private Set schResourcesForHiddenServiceId = new HashSet(0);

	private Set resourceEstimates = new HashSet(0);

	// Constructors

	/** default constructor */
	public Service()
	{
	}

	/** minimal constructor */
	public Service(Lookup lookupByScheduleTypeId, Lookup lookupByServiceTypeId, Lookup lookupByServStatusTypeId, Lookup lookupByDeliveryTypeId, Job job, User userByCreatedBy, String internalReqFlag,
			Date dateCreated)
	{
		this.lookupByScheduleTypeId = lookupByScheduleTypeId;
		this.lookupByServiceTypeId = lookupByServiceTypeId;
		this.lookupByServStatusTypeId = lookupByServStatusTypeId;
		this.lookupByDeliveryTypeId = lookupByDeliveryTypeId;
		this.job = job;
		this.userByCreatedBy = userByCreatedBy;
		this.internalReqFlag = internalReqFlag;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public Service(Lookup lookupByPunchlistTypeId, Contact contactBySupportContactId, JobLocation jobLocationByJobLocationId, Contact contactByDesignerContactId, Lookup lookupByScheduleTypeId,
			Lookup lookupByWoodProductTypeId, Lookup lookupByPriFurnLineTypeId, Lookup lookupBySecFurnLineTypeId, Lookup lookupByPriFurnTypeId, Request request, Contact contactByIdmContactId,
			Contact contactByCustomerContactId, User userByModifiedBy, Lookup lookupByServiceTypeId, Lookup lookupByBillingTypeId, Lookup lookupByServStatusTypeId,
			JobLocation jobLocationByReportToLocId, Lookup lookupByDeliveryTypeId, Lookup lookupBySecFurnTypeId, Contact contactByProjectMgrContactId, Job job, User userByCreatedBy,
			Contact contactBySalesContactId, Long quoteId, Long serviceNo, String description, String internalReqFlag, String customerRefNo, String poNo, Long orderedBy, Date orderedDate,
			Date estStartDate, Date estStartTime, Date estEndDate, Date truckShipDate, Date truckArrivalDate, String productSetupDesc, String warehouseLoc, String numStations, String productQty,
			String blueprintLocation, Long quoteTotal, Character headValFlag, Character locValFlag, Character prodValFlag, Character schValFlag, Character taskValFlag, Character resValFlag,
			Character custValFlag, Character billValFlag, String custCol1, String custCol2, String custCol3, String custCol4, String custCol5, String custCol6, String custCol7, String custCol8,
			String custCol9, String custCol10, String taxableFlag, String watchFlag, String weekendFlag, String misc, Date dateCreated, Date dateModified, Date schStartDate, Date schStartTime,
			Date schEndDate, Date actStartDate, Date actStartTime, Date actEndDate, Long priorityTypeId, Long versionNo, Set serviceLinesForTcServiceId, Set trackings, Set serviceTasks,
			Set serviceLinesForPhServiceId, Set schResourcesForServiceId, Set serviceLinesForBillServiceId, Set schResourcesForHiddenServiceId, Set resourceEstimates)
	{
		this.lookupByPunchlistTypeId = lookupByPunchlistTypeId;
		this.contactBySupportContactId = contactBySupportContactId;
		this.jobLocationByJobLocationId = jobLocationByJobLocationId;
		this.contactByDesignerContactId = contactByDesignerContactId;
		this.lookupByScheduleTypeId = lookupByScheduleTypeId;
		this.lookupByWoodProductTypeId = lookupByWoodProductTypeId;
		this.lookupByPriFurnLineTypeId = lookupByPriFurnLineTypeId;
		this.lookupBySecFurnLineTypeId = lookupBySecFurnLineTypeId;
		this.lookupByPriFurnTypeId = lookupByPriFurnTypeId;
		this.request = request;
		this.contactByIdmContactId = contactByIdmContactId;
		this.contactByCustomerContactId = contactByCustomerContactId;
		this.userByModifiedBy = userByModifiedBy;
		this.lookupByServiceTypeId = lookupByServiceTypeId;
		this.lookupByBillingTypeId = lookupByBillingTypeId;
		this.lookupByServStatusTypeId = lookupByServStatusTypeId;
		this.jobLocationByReportToLocId = jobLocationByReportToLocId;
		this.lookupByDeliveryTypeId = lookupByDeliveryTypeId;
		this.lookupBySecFurnTypeId = lookupBySecFurnTypeId;
		this.contactByProjectMgrContactId = contactByProjectMgrContactId;
		this.job = job;
		this.userByCreatedBy = userByCreatedBy;
		this.contactBySalesContactId = contactBySalesContactId;
		this.quoteId = quoteId;
		this.serviceNo = serviceNo;
		this.description = description;
		this.internalReqFlag = internalReqFlag;
		this.customerRefNo = customerRefNo;
		this.poNo = poNo;
		this.orderedBy = orderedBy;
		this.orderedDate = orderedDate;
		this.estStartDate = estStartDate;
		this.estStartTime = estStartTime;
		this.estEndDate = estEndDate;
		this.truckShipDate = truckShipDate;
		this.truckArrivalDate = truckArrivalDate;
		this.productSetupDesc = productSetupDesc;
		this.warehouseLoc = warehouseLoc;
		this.numStations = numStations;
		this.productQty = productQty;
		this.blueprintLocation = blueprintLocation;
		this.quoteTotal = quoteTotal;
		this.headValFlag = headValFlag;
		this.locValFlag = locValFlag;
		this.prodValFlag = prodValFlag;
		this.schValFlag = schValFlag;
		this.taskValFlag = taskValFlag;
		this.resValFlag = resValFlag;
		this.custValFlag = custValFlag;
		this.billValFlag = billValFlag;
		this.custCol1 = custCol1;
		this.custCol2 = custCol2;
		this.custCol3 = custCol3;
		this.custCol4 = custCol4;
		this.custCol5 = custCol5;
		this.custCol6 = custCol6;
		this.custCol7 = custCol7;
		this.custCol8 = custCol8;
		this.custCol9 = custCol9;
		this.custCol10 = custCol10;
		this.taxableFlag = taxableFlag;
		this.watchFlag = watchFlag;
		this.weekendFlag = weekendFlag;
		this.misc = misc;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.schStartDate = schStartDate;
		this.schStartTime = schStartTime;
		this.schEndDate = schEndDate;
		this.actStartDate = actStartDate;
		this.actStartTime = actStartTime;
		this.actEndDate = actEndDate;
		this.priorityTypeId = priorityTypeId;
		this.versionNo = versionNo;
		this.serviceLinesForTcServiceId = serviceLinesForTcServiceId;
		this.trackings = trackings;
		this.serviceTasks = serviceTasks;
		this.serviceLinesForPhServiceId = serviceLinesForPhServiceId;
		this.schResourcesForServiceId = schResourcesForServiceId;
		this.serviceLinesForBillServiceId = serviceLinesForBillServiceId;
		this.schResourcesForHiddenServiceId = schResourcesForHiddenServiceId;
		this.resourceEstimates = resourceEstimates;
	}

	// Property accessors
	public Long getServiceId()
	{
		return this.serviceId;
	}

	public void setServiceId(Long serviceId)
	{
		this.serviceId = serviceId;
	}

	public Lookup getLookupByPunchlistTypeId()
	{
		return this.lookupByPunchlistTypeId;
	}

	public void setLookupByPunchlistTypeId(Lookup lookupByPunchlistTypeId)
	{
		this.lookupByPunchlistTypeId = lookupByPunchlistTypeId;
	}

	public Contact getContactBySupportContactId()
	{
		return this.contactBySupportContactId;
	}

	public void setContactBySupportContactId(Contact contactBySupportContactId)
	{
		this.contactBySupportContactId = contactBySupportContactId;
	}

	public JobLocation getJobLocationByJobLocationId()
	{
		return this.jobLocationByJobLocationId;
	}

	public void setJobLocationByJobLocationId(JobLocation jobLocationByJobLocationId)
	{
		this.jobLocationByJobLocationId = jobLocationByJobLocationId;
	}

	public Contact getContactByDesignerContactId()
	{
		return this.contactByDesignerContactId;
	}

	public void setContactByDesignerContactId(Contact contactByDesignerContactId)
	{
		this.contactByDesignerContactId = contactByDesignerContactId;
	}

	public Lookup getLookupByScheduleTypeId()
	{
		return this.lookupByScheduleTypeId;
	}

	public void setLookupByScheduleTypeId(Lookup lookupByScheduleTypeId)
	{
		this.lookupByScheduleTypeId = lookupByScheduleTypeId;
	}

	public Lookup getLookupByWoodProductTypeId()
	{
		return this.lookupByWoodProductTypeId;
	}

	public void setLookupByWoodProductTypeId(Lookup lookupByWoodProductTypeId)
	{
		this.lookupByWoodProductTypeId = lookupByWoodProductTypeId;
	}

	public Lookup getLookupByPriFurnLineTypeId()
	{
		return this.lookupByPriFurnLineTypeId;
	}

	public void setLookupByPriFurnLineTypeId(Lookup lookupByPriFurnLineTypeId)
	{
		this.lookupByPriFurnLineTypeId = lookupByPriFurnLineTypeId;
	}

	public Lookup getLookupBySecFurnLineTypeId()
	{
		return this.lookupBySecFurnLineTypeId;
	}

	public void setLookupBySecFurnLineTypeId(Lookup lookupBySecFurnLineTypeId)
	{
		this.lookupBySecFurnLineTypeId = lookupBySecFurnLineTypeId;
	}

	public Lookup getLookupByPriFurnTypeId()
	{
		return this.lookupByPriFurnTypeId;
	}

	public void setLookupByPriFurnTypeId(Lookup lookupByPriFurnTypeId)
	{
		this.lookupByPriFurnTypeId = lookupByPriFurnTypeId;
	}

	public Request getRequest()
	{
		return this.request;
	}

	public void setRequest(Request request)
	{
		this.request = request;
	}

	public Contact getContactByIdmContactId()
	{
		return this.contactByIdmContactId;
	}

	public void setContactByIdmContactId(Contact contactByIdmContactId)
	{
		this.contactByIdmContactId = contactByIdmContactId;
	}

	public Contact getContactByCustomerContactId()
	{
		return this.contactByCustomerContactId;
	}

	public void setContactByCustomerContactId(Contact contactByCustomerContactId)
	{
		this.contactByCustomerContactId = contactByCustomerContactId;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public Lookup getLookupByServiceTypeId()
	{
		return this.lookupByServiceTypeId;
	}

	public void setLookupByServiceTypeId(Lookup lookupByServiceTypeId)
	{
		this.lookupByServiceTypeId = lookupByServiceTypeId;
	}

	public Lookup getLookupByBillingTypeId()
	{
		return this.lookupByBillingTypeId;
	}

	public void setLookupByBillingTypeId(Lookup lookupByBillingTypeId)
	{
		this.lookupByBillingTypeId = lookupByBillingTypeId;
	}

	public Lookup getLookupByServStatusTypeId()
	{
		return this.lookupByServStatusTypeId;
	}

	public void setLookupByServStatusTypeId(Lookup lookupByServStatusTypeId)
	{
		this.lookupByServStatusTypeId = lookupByServStatusTypeId;
	}

	public JobLocation getJobLocationByReportToLocId()
	{
		return this.jobLocationByReportToLocId;
	}

	public void setJobLocationByReportToLocId(JobLocation jobLocationByReportToLocId)
	{
		this.jobLocationByReportToLocId = jobLocationByReportToLocId;
	}

	public Lookup getLookupByDeliveryTypeId()
	{
		return this.lookupByDeliveryTypeId;
	}

	public void setLookupByDeliveryTypeId(Lookup lookupByDeliveryTypeId)
	{
		this.lookupByDeliveryTypeId = lookupByDeliveryTypeId;
	}

	public Lookup getLookupBySecFurnTypeId()
	{
		return this.lookupBySecFurnTypeId;
	}

	public void setLookupBySecFurnTypeId(Lookup lookupBySecFurnTypeId)
	{
		this.lookupBySecFurnTypeId = lookupBySecFurnTypeId;
	}

	public Contact getContactByProjectMgrContactId()
	{
		return this.contactByProjectMgrContactId;
	}

	public void setContactByProjectMgrContactId(Contact contactByProjectMgrContactId)
	{
		this.contactByProjectMgrContactId = contactByProjectMgrContactId;
	}

	public Job getJob()
	{
		return this.job;
	}

	public void setJob(Job job)
	{
		this.job = job;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public Contact getContactBySalesContactId()
	{
		return this.contactBySalesContactId;
	}

	public void setContactBySalesContactId(Contact contactBySalesContactId)
	{
		this.contactBySalesContactId = contactBySalesContactId;
	}

	public Long getQuoteId()
	{
		return this.quoteId;
	}

	public void setQuoteId(Long quoteId)
	{
		this.quoteId = quoteId;
	}

	public Long getServiceNo()
	{
		return this.serviceNo;
	}

	public void setServiceNo(Long serviceNo)
	{
		this.serviceNo = serviceNo;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public String getInternalReqFlag()
	{
		return this.internalReqFlag;
	}

	public void setInternalReqFlag(String internalReqFlag)
	{
		this.internalReqFlag = internalReqFlag;
	}

	public String getCustomerRefNo()
	{
		return this.customerRefNo;
	}

	public void setCustomerRefNo(String customerRefNo)
	{
		this.customerRefNo = customerRefNo;
	}

	public String getPoNo()
	{
		return this.poNo;
	}

	public void setPoNo(String poNo)
	{
		this.poNo = poNo;
	}

	public Long getOrderedBy()
	{
		return this.orderedBy;
	}

	public void setOrderedBy(Long orderedBy)
	{
		this.orderedBy = orderedBy;
	}

	public Date getOrderedDate()
	{
		return this.orderedDate;
	}

	public void setOrderedDate(Date orderedDate)
	{
		this.orderedDate = orderedDate;
	}

	public Date getEstStartDate()
	{
		return this.estStartDate;
	}

	public void setEstStartDate(Date estStartDate)
	{
		this.estStartDate = estStartDate;
	}

	public Date getEstStartTime()
	{
		return this.estStartTime;
	}

	public void setEstStartTime(Date estStartTime)
	{
		this.estStartTime = estStartTime;
	}

	public Date getEstEndDate()
	{
		return this.estEndDate;
	}

	public void setEstEndDate(Date estEndDate)
	{
		this.estEndDate = estEndDate;
	}

	public Date getTruckShipDate()
	{
		return this.truckShipDate;
	}

	public void setTruckShipDate(Date truckShipDate)
	{
		this.truckShipDate = truckShipDate;
	}

	public Date getTruckArrivalDate()
	{
		return this.truckArrivalDate;
	}

	public void setTruckArrivalDate(Date truckArrivalDate)
	{
		this.truckArrivalDate = truckArrivalDate;
	}

	public String getProductSetupDesc()
	{
		return this.productSetupDesc;
	}

	public void setProductSetupDesc(String productSetupDesc)
	{
		this.productSetupDesc = productSetupDesc;
	}

	public String getWarehouseLoc()
	{
		return this.warehouseLoc;
	}

	public void setWarehouseLoc(String warehouseLoc)
	{
		this.warehouseLoc = warehouseLoc;
	}

	public String getNumStations()
	{
		return this.numStations;
	}

	public void setNumStations(String numStations)
	{
		this.numStations = numStations;
	}

	public String getProductQty()
	{
		return this.productQty;
	}

	public void setProductQty(String productQty)
	{
		this.productQty = productQty;
	}

	public String getBlueprintLocation()
	{
		return this.blueprintLocation;
	}

	public void setBlueprintLocation(String blueprintLocation)
	{
		this.blueprintLocation = blueprintLocation;
	}

	public Long getQuoteTotal()
	{
		return this.quoteTotal;
	}

	public void setQuoteTotal(Long quoteTotal)
	{
		this.quoteTotal = quoteTotal;
	}

	public Character getHeadValFlag()
	{
		return this.headValFlag;
	}

	public void setHeadValFlag(Character headValFlag)
	{
		this.headValFlag = headValFlag;
	}

	public Character getLocValFlag()
	{
		return this.locValFlag;
	}

	public void setLocValFlag(Character locValFlag)
	{
		this.locValFlag = locValFlag;
	}

	public Character getProdValFlag()
	{
		return this.prodValFlag;
	}

	public void setProdValFlag(Character prodValFlag)
	{
		this.prodValFlag = prodValFlag;
	}

	public Character getSchValFlag()
	{
		return this.schValFlag;
	}

	public void setSchValFlag(Character schValFlag)
	{
		this.schValFlag = schValFlag;
	}

	public Character getTaskValFlag()
	{
		return this.taskValFlag;
	}

	public void setTaskValFlag(Character taskValFlag)
	{
		this.taskValFlag = taskValFlag;
	}

	public Character getResValFlag()
	{
		return this.resValFlag;
	}

	public void setResValFlag(Character resValFlag)
	{
		this.resValFlag = resValFlag;
	}

	public Character getCustValFlag()
	{
		return this.custValFlag;
	}

	public void setCustValFlag(Character custValFlag)
	{
		this.custValFlag = custValFlag;
	}

	public Character getBillValFlag()
	{
		return this.billValFlag;
	}

	public void setBillValFlag(Character billValFlag)
	{
		this.billValFlag = billValFlag;
	}

	public String getCustCol1()
	{
		return this.custCol1;
	}

	public void setCustCol1(String custCol1)
	{
		this.custCol1 = custCol1;
	}

	public String getCustCol2()
	{
		return this.custCol2;
	}

	public void setCustCol2(String custCol2)
	{
		this.custCol2 = custCol2;
	}

	public String getCustCol3()
	{
		return this.custCol3;
	}

	public void setCustCol3(String custCol3)
	{
		this.custCol3 = custCol3;
	}

	public String getCustCol4()
	{
		return this.custCol4;
	}

	public void setCustCol4(String custCol4)
	{
		this.custCol4 = custCol4;
	}

	public String getCustCol5()
	{
		return this.custCol5;
	}

	public void setCustCol5(String custCol5)
	{
		this.custCol5 = custCol5;
	}

	public String getCustCol6()
	{
		return this.custCol6;
	}

	public void setCustCol6(String custCol6)
	{
		this.custCol6 = custCol6;
	}

	public String getCustCol7()
	{
		return this.custCol7;
	}

	public void setCustCol7(String custCol7)
	{
		this.custCol7 = custCol7;
	}

	public String getCustCol8()
	{
		return this.custCol8;
	}

	public void setCustCol8(String custCol8)
	{
		this.custCol8 = custCol8;
	}

	public String getCustCol9()
	{
		return this.custCol9;
	}

	public void setCustCol9(String custCol9)
	{
		this.custCol9 = custCol9;
	}

	public String getCustCol10()
	{
		return this.custCol10;
	}

	public void setCustCol10(String custCol10)
	{
		this.custCol10 = custCol10;
	}

	public String getTaxableFlag()
	{
		return this.taxableFlag;
	}

	public void setTaxableFlag(String taxableFlag)
	{
		this.taxableFlag = taxableFlag;
	}

	public String getWatchFlag()
	{
		return this.watchFlag;
	}

	public void setWatchFlag(String watchFlag)
	{
		this.watchFlag = watchFlag;
	}

	public String getWeekendFlag()
	{
		return this.weekendFlag;
	}

	public void setWeekendFlag(String weekendFlag)
	{
		this.weekendFlag = weekendFlag;
	}

	public String getMisc()
	{
		return this.misc;
	}

	public void setMisc(String misc)
	{
		this.misc = misc;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Date getSchStartDate()
	{
		return this.schStartDate;
	}

	public void setSchStartDate(Date schStartDate)
	{
		this.schStartDate = schStartDate;
	}

	public Date getSchStartTime()
	{
		return this.schStartTime;
	}

	public void setSchStartTime(Date schStartTime)
	{
		this.schStartTime = schStartTime;
	}

	public Date getSchEndDate()
	{
		return this.schEndDate;
	}

	public void setSchEndDate(Date schEndDate)
	{
		this.schEndDate = schEndDate;
	}

	public Date getActStartDate()
	{
		return this.actStartDate;
	}

	public void setActStartDate(Date actStartDate)
	{
		this.actStartDate = actStartDate;
	}

	public Date getActStartTime()
	{
		return this.actStartTime;
	}

	public void setActStartTime(Date actStartTime)
	{
		this.actStartTime = actStartTime;
	}

	public Date getActEndDate()
	{
		return this.actEndDate;
	}

	public void setActEndDate(Date actEndDate)
	{
		this.actEndDate = actEndDate;
	}

	public Long getPriorityTypeId()
	{
		return this.priorityTypeId;
	}

	public void setPriorityTypeId(Long priorityTypeId)
	{
		this.priorityTypeId = priorityTypeId;
	}

	public Long getVersionNo()
	{
		return this.versionNo;
	}

	public void setVersionNo(Long versionNo)
	{
		this.versionNo = versionNo;
	}

	public Set getServiceLinesForTcServiceId()
	{
		return this.serviceLinesForTcServiceId;
	}

	public void setServiceLinesForTcServiceId(Set serviceLinesForTcServiceId)
	{
		this.serviceLinesForTcServiceId = serviceLinesForTcServiceId;
	}

	public Set getTrackings()
	{
		return this.trackings;
	}

	public void setTrackings(Set trackings)
	{
		this.trackings = trackings;
	}

	public Set getServiceTasks()
	{
		return this.serviceTasks;
	}

	public void setServiceTasks(Set serviceTasks)
	{
		this.serviceTasks = serviceTasks;
	}

	public Set getServiceLinesForPhServiceId()
	{
		return this.serviceLinesForPhServiceId;
	}

	public void setServiceLinesForPhServiceId(Set serviceLinesForPhServiceId)
	{
		this.serviceLinesForPhServiceId = serviceLinesForPhServiceId;
	}

	public Set getSchResourcesForServiceId()
	{
		return this.schResourcesForServiceId;
	}

	public void setSchResourcesForServiceId(Set schResourcesForServiceId)
	{
		this.schResourcesForServiceId = schResourcesForServiceId;
	}

	public Set getServiceLinesForBillServiceId()
	{
		return this.serviceLinesForBillServiceId;
	}

	public void setServiceLinesForBillServiceId(Set serviceLinesForBillServiceId)
	{
		this.serviceLinesForBillServiceId = serviceLinesForBillServiceId;
	}

	public Set getSchResourcesForHiddenServiceId()
	{
		return this.schResourcesForHiddenServiceId;
	}

	public void setSchResourcesForHiddenServiceId(Set schResourcesForHiddenServiceId)
	{
		this.schResourcesForHiddenServiceId = schResourcesForHiddenServiceId;
	}

	public Set getResourceEstimates()
	{
		return this.resourceEstimates;
	}

	public void setResourceEstimates(Set resourceEstimates)
	{
		this.resourceEstimates = resourceEstimates;
	}

}
