package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ServiceLine generated by hbm2java
 */
public class ServiceLine implements java.io.Serializable
{

	// Fields    

	private Long serviceLineId;

	private Service serviceByTcServiceId;

	private User userByVerifiedBy;

	private Lookup lookup;

	private Invoice invoice;

	private Resource resource;

	private Service serviceByPhServiceId;

	private User userByModifiedBy;

	private Service serviceByBillServiceId;

	private User userByOverrideBy;

	private Item item;

	private ServiceLineStatuse serviceLineStatuse;

	private User userByEnteredBy;

	private User userByCreatedBy;

	private Long organizationId;

	private Long tcJobNo;

	private Long tcServiceNo;

	private Long tcServiceLineNo;

	private Long billJobNo;

	private Long billServiceNo;

	private Long billServiceLineNo;

	private Date serviceLineDate;

	private String serviceLineDateVarchar;

	private String exportedFlag;

	private String billedFlag;

	private String postedFlag;

	private String pooledFlag;

	private Long tcJobId;

	private Long billJobId;

	private String resourceName;

	private String itemName;

	private String itemTypeCode;

	private Long postedFromInvoiceId;

	private String taxableFlag;

	private String billableFlag;

	private BigDecimal tcQty;

	private BigDecimal tcRate;

	private BigDecimal payrollQty;

	private BigDecimal payrollRate;

	private String extPayCode;

	private String payrollExportedFlag;

	private BigDecimal expenseQty;

	private BigDecimal expenseRate;

	private String expensesExportedFlag;

	private BigDecimal billQty;

	private BigDecimal billRate;

	private BigDecimal billHourlyQty;

	private BigDecimal billHourlyRate;

	private BigDecimal billExpQty;

	private BigDecimal billExpRate;

	private BigDecimal allocatedQty;

	private String internalReqFlag;

	private String partiallyAllocatedFlag;

	private String fullyAllocatedFlag;

	private Long palmRepId;

	private Date enteredDate;

	private String entryMethod;

	private Date overrideDate;

	private Date verifiedDate;

	private Date dateCreated;

	private Date dateModified;

	private Date serviceLineWeek;

	private String serviceLineWeekVarchar;

	private String extId;

	private BigDecimal tcTotal;

	private BigDecimal payrollTotal;

	private BigDecimal expenseTotal;

	private BigDecimal billTotal;

	private BigDecimal billHourlyTotal;

	private BigDecimal billExpTotal;

	private Set payrollBatchLines = new HashSet(0);

	private Set servInvLines = new HashSet(0);

	// Constructors

	/** default constructor */
	public ServiceLine()
	{
	}

	/** minimal constructor */
	public ServiceLine(User userByCreatedBy, String exportedFlag, String billedFlag, String postedFlag, String partiallyAllocatedFlag, String fullyAllocatedFlag, Date dateCreated, BigDecimal tcTotal,
			BigDecimal payrollTotal, BigDecimal expenseTotal, BigDecimal billTotal, BigDecimal billHourlyTotal, BigDecimal billExpTotal)
	{
		this.userByCreatedBy = userByCreatedBy;
		this.exportedFlag = exportedFlag;
		this.billedFlag = billedFlag;
		this.postedFlag = postedFlag;
		this.partiallyAllocatedFlag = partiallyAllocatedFlag;
		this.fullyAllocatedFlag = fullyAllocatedFlag;
		this.dateCreated = dateCreated;
		this.tcTotal = tcTotal;
		this.payrollTotal = payrollTotal;
		this.expenseTotal = expenseTotal;
		this.billTotal = billTotal;
		this.billHourlyTotal = billHourlyTotal;
		this.billExpTotal = billExpTotal;
	}

	/** full constructor */
	public ServiceLine(Service serviceByTcServiceId, User userByVerifiedBy, Lookup lookup, Invoice invoice, Resource resource, Service serviceByPhServiceId, User userByModifiedBy,
			Service serviceByBillServiceId, User userByOverrideBy, Item item, ServiceLineStatuse serviceLineStatuse, User userByEnteredBy, User userByCreatedBy, Long organizationId, Long tcJobNo,
			Long tcServiceNo, Long tcServiceLineNo, Long billJobNo, Long billServiceNo, Long billServiceLineNo, Date serviceLineDate, String serviceLineDateVarchar, String exportedFlag,
			String billedFlag, String postedFlag, String pooledFlag, Long tcJobId, Long billJobId, String resourceName, String itemName, String itemTypeCode, Long postedFromInvoiceId,
			String taxableFlag, String billableFlag, BigDecimal tcQty, BigDecimal tcRate, BigDecimal payrollQty, BigDecimal payrollRate, String extPayCode, String payrollExportedFlag,
			BigDecimal expenseQty, BigDecimal expenseRate, String expensesExportedFlag, BigDecimal billQty, BigDecimal billRate, BigDecimal billHourlyQty, BigDecimal billHourlyRate,
			BigDecimal billExpQty, BigDecimal billExpRate, BigDecimal allocatedQty, String internalReqFlag, String partiallyAllocatedFlag, String fullyAllocatedFlag, Long palmRepId, Date enteredDate,
			String entryMethod, Date overrideDate, Date verifiedDate, Date dateCreated, Date dateModified, Date serviceLineWeek, String serviceLineWeekVarchar, String extId, BigDecimal tcTotal,
			BigDecimal payrollTotal, BigDecimal expenseTotal, BigDecimal billTotal, BigDecimal billHourlyTotal, BigDecimal billExpTotal, Set payrollBatchLines, Set servInvLines)
	{
		this.serviceByTcServiceId = serviceByTcServiceId;
		this.userByVerifiedBy = userByVerifiedBy;
		this.lookup = lookup;
		this.invoice = invoice;
		this.resource = resource;
		this.serviceByPhServiceId = serviceByPhServiceId;
		this.userByModifiedBy = userByModifiedBy;
		this.serviceByBillServiceId = serviceByBillServiceId;
		this.userByOverrideBy = userByOverrideBy;
		this.item = item;
		this.serviceLineStatuse = serviceLineStatuse;
		this.userByEnteredBy = userByEnteredBy;
		this.userByCreatedBy = userByCreatedBy;
		this.organizationId = organizationId;
		this.tcJobNo = tcJobNo;
		this.tcServiceNo = tcServiceNo;
		this.tcServiceLineNo = tcServiceLineNo;
		this.billJobNo = billJobNo;
		this.billServiceNo = billServiceNo;
		this.billServiceLineNo = billServiceLineNo;
		this.serviceLineDate = serviceLineDate;
		this.serviceLineDateVarchar = serviceLineDateVarchar;
		this.exportedFlag = exportedFlag;
		this.billedFlag = billedFlag;
		this.postedFlag = postedFlag;
		this.pooledFlag = pooledFlag;
		this.tcJobId = tcJobId;
		this.billJobId = billJobId;
		this.resourceName = resourceName;
		this.itemName = itemName;
		this.itemTypeCode = itemTypeCode;
		this.postedFromInvoiceId = postedFromInvoiceId;
		this.taxableFlag = taxableFlag;
		this.billableFlag = billableFlag;
		this.tcQty = tcQty;
		this.tcRate = tcRate;
		this.payrollQty = payrollQty;
		this.payrollRate = payrollRate;
		this.extPayCode = extPayCode;
		this.payrollExportedFlag = payrollExportedFlag;
		this.expenseQty = expenseQty;
		this.expenseRate = expenseRate;
		this.expensesExportedFlag = expensesExportedFlag;
		this.billQty = billQty;
		this.billRate = billRate;
		this.billHourlyQty = billHourlyQty;
		this.billHourlyRate = billHourlyRate;
		this.billExpQty = billExpQty;
		this.billExpRate = billExpRate;
		this.allocatedQty = allocatedQty;
		this.internalReqFlag = internalReqFlag;
		this.partiallyAllocatedFlag = partiallyAllocatedFlag;
		this.fullyAllocatedFlag = fullyAllocatedFlag;
		this.palmRepId = palmRepId;
		this.enteredDate = enteredDate;
		this.entryMethod = entryMethod;
		this.overrideDate = overrideDate;
		this.verifiedDate = verifiedDate;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.serviceLineWeek = serviceLineWeek;
		this.serviceLineWeekVarchar = serviceLineWeekVarchar;
		this.extId = extId;
		this.tcTotal = tcTotal;
		this.payrollTotal = payrollTotal;
		this.expenseTotal = expenseTotal;
		this.billTotal = billTotal;
		this.billHourlyTotal = billHourlyTotal;
		this.billExpTotal = billExpTotal;
		this.payrollBatchLines = payrollBatchLines;
		this.servInvLines = servInvLines;
	}

	// Property accessors
	public Long getServiceLineId()
	{
		return this.serviceLineId;
	}

	public void setServiceLineId(Long serviceLineId)
	{
		this.serviceLineId = serviceLineId;
	}

	public Service getServiceByTcServiceId()
	{
		return this.serviceByTcServiceId;
	}

	public void setServiceByTcServiceId(Service serviceByTcServiceId)
	{
		this.serviceByTcServiceId = serviceByTcServiceId;
	}

	public User getUserByVerifiedBy()
	{
		return this.userByVerifiedBy;
	}

	public void setUserByVerifiedBy(User userByVerifiedBy)
	{
		this.userByVerifiedBy = userByVerifiedBy;
	}

	public Lookup getLookup()
	{
		return this.lookup;
	}

	public void setLookup(Lookup lookup)
	{
		this.lookup = lookup;
	}

	public Invoice getInvoice()
	{
		return this.invoice;
	}

	public void setInvoice(Invoice invoice)
	{
		this.invoice = invoice;
	}

	public Resource getResource()
	{
		return this.resource;
	}

	public void setResource(Resource resource)
	{
		this.resource = resource;
	}

	public Service getServiceByPhServiceId()
	{
		return this.serviceByPhServiceId;
	}

	public void setServiceByPhServiceId(Service serviceByPhServiceId)
	{
		this.serviceByPhServiceId = serviceByPhServiceId;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public Service getServiceByBillServiceId()
	{
		return this.serviceByBillServiceId;
	}

	public void setServiceByBillServiceId(Service serviceByBillServiceId)
	{
		this.serviceByBillServiceId = serviceByBillServiceId;
	}

	public User getUserByOverrideBy()
	{
		return this.userByOverrideBy;
	}

	public void setUserByOverrideBy(User userByOverrideBy)
	{
		this.userByOverrideBy = userByOverrideBy;
	}

	public Item getItem()
	{
		return this.item;
	}

	public void setItem(Item item)
	{
		this.item = item;
	}

	public ServiceLineStatuse getServiceLineStatuse()
	{
		return this.serviceLineStatuse;
	}

	public void setServiceLineStatuse(ServiceLineStatuse serviceLineStatuse)
	{
		this.serviceLineStatuse = serviceLineStatuse;
	}

	public User getUserByEnteredBy()
	{
		return this.userByEnteredBy;
	}

	public void setUserByEnteredBy(User userByEnteredBy)
	{
		this.userByEnteredBy = userByEnteredBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public Long getOrganizationId()
	{
		return this.organizationId;
	}

	public void setOrganizationId(Long organizationId)
	{
		this.organizationId = organizationId;
	}

	public Long getTcJobNo()
	{
		return this.tcJobNo;
	}

	public void setTcJobNo(Long tcJobNo)
	{
		this.tcJobNo = tcJobNo;
	}

	public Long getTcServiceNo()
	{
		return this.tcServiceNo;
	}

	public void setTcServiceNo(Long tcServiceNo)
	{
		this.tcServiceNo = tcServiceNo;
	}

	public Long getTcServiceLineNo()
	{
		return this.tcServiceLineNo;
	}

	public void setTcServiceLineNo(Long tcServiceLineNo)
	{
		this.tcServiceLineNo = tcServiceLineNo;
	}

	public Long getBillJobNo()
	{
		return this.billJobNo;
	}

	public void setBillJobNo(Long billJobNo)
	{
		this.billJobNo = billJobNo;
	}

	public Long getBillServiceNo()
	{
		return this.billServiceNo;
	}

	public void setBillServiceNo(Long billServiceNo)
	{
		this.billServiceNo = billServiceNo;
	}

	public Long getBillServiceLineNo()
	{
		return this.billServiceLineNo;
	}

	public void setBillServiceLineNo(Long billServiceLineNo)
	{
		this.billServiceLineNo = billServiceLineNo;
	}

	public Date getServiceLineDate()
	{
		return this.serviceLineDate;
	}

	public void setServiceLineDate(Date serviceLineDate)
	{
		this.serviceLineDate = serviceLineDate;
	}

	public String getServiceLineDateVarchar()
	{
		return this.serviceLineDateVarchar;
	}

	public void setServiceLineDateVarchar(String serviceLineDateVarchar)
	{
		this.serviceLineDateVarchar = serviceLineDateVarchar;
	}

	public String getExportedFlag()
	{
		return this.exportedFlag;
	}

	public void setExportedFlag(String exportedFlag)
	{
		this.exportedFlag = exportedFlag;
	}

	public String getBilledFlag()
	{
		return this.billedFlag;
	}

	public void setBilledFlag(String billedFlag)
	{
		this.billedFlag = billedFlag;
	}

	public String getPostedFlag()
	{
		return this.postedFlag;
	}

	public void setPostedFlag(String postedFlag)
	{
		this.postedFlag = postedFlag;
	}

	public String getPooledFlag()
	{
		return this.pooledFlag;
	}

	public void setPooledFlag(String pooledFlag)
	{
		this.pooledFlag = pooledFlag;
	}

	public Long getTcJobId()
	{
		return this.tcJobId;
	}

	public void setTcJobId(Long tcJobId)
	{
		this.tcJobId = tcJobId;
	}

	public Long getBillJobId()
	{
		return this.billJobId;
	}

	public void setBillJobId(Long billJobId)
	{
		this.billJobId = billJobId;
	}

	public String getResourceName()
	{
		return this.resourceName;
	}

	public void setResourceName(String resourceName)
	{
		this.resourceName = resourceName;
	}

	public String getItemName()
	{
		return this.itemName;
	}

	public void setItemName(String itemName)
	{
		this.itemName = itemName;
	}

	public String getItemTypeCode()
	{
		return this.itemTypeCode;
	}

	public void setItemTypeCode(String itemTypeCode)
	{
		this.itemTypeCode = itemTypeCode;
	}

	public Long getPostedFromInvoiceId()
	{
		return this.postedFromInvoiceId;
	}

	public void setPostedFromInvoiceId(Long postedFromInvoiceId)
	{
		this.postedFromInvoiceId = postedFromInvoiceId;
	}

	public String getTaxableFlag()
	{
		return this.taxableFlag;
	}

	public void setTaxableFlag(String taxableFlag)
	{
		this.taxableFlag = taxableFlag;
	}

	public String getBillableFlag()
	{
		return this.billableFlag;
	}

	public void setBillableFlag(String billableFlag)
	{
		this.billableFlag = billableFlag;
	}

	public BigDecimal getTcQty()
	{
		return this.tcQty;
	}

	public void setTcQty(BigDecimal tcQty)
	{
		this.tcQty = tcQty;
	}

	public BigDecimal getTcRate()
	{
		return this.tcRate;
	}

	public void setTcRate(BigDecimal tcRate)
	{
		this.tcRate = tcRate;
	}

	public BigDecimal getPayrollQty()
	{
		return this.payrollQty;
	}

	public void setPayrollQty(BigDecimal payrollQty)
	{
		this.payrollQty = payrollQty;
	}

	public BigDecimal getPayrollRate()
	{
		return this.payrollRate;
	}

	public void setPayrollRate(BigDecimal payrollRate)
	{
		this.payrollRate = payrollRate;
	}

	public String getExtPayCode()
	{
		return this.extPayCode;
	}

	public void setExtPayCode(String extPayCode)
	{
		this.extPayCode = extPayCode;
	}

	public String getPayrollExportedFlag()
	{
		return this.payrollExportedFlag;
	}

	public void setPayrollExportedFlag(String payrollExportedFlag)
	{
		this.payrollExportedFlag = payrollExportedFlag;
	}

	public BigDecimal getExpenseQty()
	{
		return this.expenseQty;
	}

	public void setExpenseQty(BigDecimal expenseQty)
	{
		this.expenseQty = expenseQty;
	}

	public BigDecimal getExpenseRate()
	{
		return this.expenseRate;
	}

	public void setExpenseRate(BigDecimal expenseRate)
	{
		this.expenseRate = expenseRate;
	}

	public String getExpensesExportedFlag()
	{
		return this.expensesExportedFlag;
	}

	public void setExpensesExportedFlag(String expensesExportedFlag)
	{
		this.expensesExportedFlag = expensesExportedFlag;
	}

	public BigDecimal getBillQty()
	{
		return this.billQty;
	}

	public void setBillQty(BigDecimal billQty)
	{
		this.billQty = billQty;
	}

	public BigDecimal getBillRate()
	{
		return this.billRate;
	}

	public void setBillRate(BigDecimal billRate)
	{
		this.billRate = billRate;
	}

	public BigDecimal getBillHourlyQty()
	{
		return this.billHourlyQty;
	}

	public void setBillHourlyQty(BigDecimal billHourlyQty)
	{
		this.billHourlyQty = billHourlyQty;
	}

	public BigDecimal getBillHourlyRate()
	{
		return this.billHourlyRate;
	}

	public void setBillHourlyRate(BigDecimal billHourlyRate)
	{
		this.billHourlyRate = billHourlyRate;
	}

	public BigDecimal getBillExpQty()
	{
		return this.billExpQty;
	}

	public void setBillExpQty(BigDecimal billExpQty)
	{
		this.billExpQty = billExpQty;
	}

	public BigDecimal getBillExpRate()
	{
		return this.billExpRate;
	}

	public void setBillExpRate(BigDecimal billExpRate)
	{
		this.billExpRate = billExpRate;
	}

	public BigDecimal getAllocatedQty()
	{
		return this.allocatedQty;
	}

	public void setAllocatedQty(BigDecimal allocatedQty)
	{
		this.allocatedQty = allocatedQty;
	}

	public String getInternalReqFlag()
	{
		return this.internalReqFlag;
	}

	public void setInternalReqFlag(String internalReqFlag)
	{
		this.internalReqFlag = internalReqFlag;
	}

	public String getPartiallyAllocatedFlag()
	{
		return this.partiallyAllocatedFlag;
	}

	public void setPartiallyAllocatedFlag(String partiallyAllocatedFlag)
	{
		this.partiallyAllocatedFlag = partiallyAllocatedFlag;
	}

	public String getFullyAllocatedFlag()
	{
		return this.fullyAllocatedFlag;
	}

	public void setFullyAllocatedFlag(String fullyAllocatedFlag)
	{
		this.fullyAllocatedFlag = fullyAllocatedFlag;
	}

	public Long getPalmRepId()
	{
		return this.palmRepId;
	}

	public void setPalmRepId(Long palmRepId)
	{
		this.palmRepId = palmRepId;
	}

	public Date getEnteredDate()
	{
		return this.enteredDate;
	}

	public void setEnteredDate(Date enteredDate)
	{
		this.enteredDate = enteredDate;
	}

	public String getEntryMethod()
	{
		return this.entryMethod;
	}

	public void setEntryMethod(String entryMethod)
	{
		this.entryMethod = entryMethod;
	}

	public Date getOverrideDate()
	{
		return this.overrideDate;
	}

	public void setOverrideDate(Date overrideDate)
	{
		this.overrideDate = overrideDate;
	}

	public Date getVerifiedDate()
	{
		return this.verifiedDate;
	}

	public void setVerifiedDate(Date verifiedDate)
	{
		this.verifiedDate = verifiedDate;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public Date getServiceLineWeek()
	{
		return this.serviceLineWeek;
	}

	public void setServiceLineWeek(Date serviceLineWeek)
	{
		this.serviceLineWeek = serviceLineWeek;
	}

	public String getServiceLineWeekVarchar()
	{
		return this.serviceLineWeekVarchar;
	}

	public void setServiceLineWeekVarchar(String serviceLineWeekVarchar)
	{
		this.serviceLineWeekVarchar = serviceLineWeekVarchar;
	}

	public String getExtId()
	{
		return this.extId;
	}

	public void setExtId(String extId)
	{
		this.extId = extId;
	}

	public BigDecimal getTcTotal()
	{
		return this.tcTotal;
	}

	public void setTcTotal(BigDecimal tcTotal)
	{
		this.tcTotal = tcTotal;
	}

	public BigDecimal getPayrollTotal()
	{
		return this.payrollTotal;
	}

	public void setPayrollTotal(BigDecimal payrollTotal)
	{
		this.payrollTotal = payrollTotal;
	}

	public BigDecimal getExpenseTotal()
	{
		return this.expenseTotal;
	}

	public void setExpenseTotal(BigDecimal expenseTotal)
	{
		this.expenseTotal = expenseTotal;
	}

	public BigDecimal getBillTotal()
	{
		return this.billTotal;
	}

	public void setBillTotal(BigDecimal billTotal)
	{
		this.billTotal = billTotal;
	}

	public BigDecimal getBillHourlyTotal()
	{
		return this.billHourlyTotal;
	}

	public void setBillHourlyTotal(BigDecimal billHourlyTotal)
	{
		this.billHourlyTotal = billHourlyTotal;
	}

	public BigDecimal getBillExpTotal()
	{
		return this.billExpTotal;
	}

	public void setBillExpTotal(BigDecimal billExpTotal)
	{
		this.billExpTotal = billExpTotal;
	}

	public Set getPayrollBatchLines()
	{
		return this.payrollBatchLines;
	}

	public void setPayrollBatchLines(Set payrollBatchLines)
	{
		this.payrollBatchLines = payrollBatchLines;
	}

	public Set getServInvLines()
	{
		return this.servInvLines;
	}

	public void setServInvLines(Set servInvLines)
	{
		this.servInvLines = servInvLines;
	}

}
