package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.HashSet;
import java.util.Set;

/**
 * ServiceLineStatuse generated by hbm2java
 */
public class ServiceLineStatuse implements java.io.Serializable
{

	// Fields    

	private Long statusId;

	private String code;

	private String name;

	private Set serviceLines = new HashSet(0);

	// Constructors

	/** default constructor */
	public ServiceLineStatuse()
	{
	}

	/** minimal constructor */
	public ServiceLineStatuse(String code, String name)
	{
		this.code = code;
		this.name = name;
	}

	/** full constructor */
	public ServiceLineStatuse(String code, String name, Set serviceLines)
	{
		this.code = code;
		this.name = name;
		this.serviceLines = serviceLines;
	}

	// Property accessors
	public Long getStatusId()
	{
		return this.statusId;
	}

	public void setStatusId(Long statusId)
	{
		this.statusId = statusId;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Set getServiceLines()
	{
		return this.serviceLines;
	}

	public void setServiceLines(Set serviceLines)
	{
		this.serviceLines = serviceLines;
	}

}
