package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

/**
 * Tab generated by hbm2java
 */
public class Tab implements java.io.Serializable
{

	// Fields    

	private Long tabId;

	private long templateId;

	private String name;

	private long sequence;

	private String typeCode;

	private String defaultTab;

	private String tableId;

	private Long parentTabId;

	private Long tabLevel;

	// Constructors

	/** default constructor */
	public Tab()
	{
	}

	/** minimal constructor */
	public Tab(long templateId, String name, long sequence, String typeCode, String defaultTab, String tableId)
	{
		this.templateId = templateId;
		this.name = name;
		this.sequence = sequence;
		this.typeCode = typeCode;
		this.defaultTab = defaultTab;
		this.tableId = tableId;
	}

	/** full constructor */
	public Tab(long templateId, String name, long sequence, String typeCode, String defaultTab, String tableId, Long parentTabId, Long tabLevel)
	{
		this.templateId = templateId;
		this.name = name;
		this.sequence = sequence;
		this.typeCode = typeCode;
		this.defaultTab = defaultTab;
		this.tableId = tableId;
		this.parentTabId = parentTabId;
		this.tabLevel = tabLevel;
	}

	// Property accessors
	public Long getTabId()
	{
		return this.tabId;
	}

	public void setTabId(Long tabId)
	{
		this.tabId = tabId;
	}

	public long getTemplateId()
	{
		return this.templateId;
	}

	public void setTemplateId(long templateId)
	{
		this.templateId = templateId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public long getSequence()
	{
		return this.sequence;
	}

	public void setSequence(long sequence)
	{
		this.sequence = sequence;
	}

	public String getTypeCode()
	{
		return this.typeCode;
	}

	public void setTypeCode(String typeCode)
	{
		this.typeCode = typeCode;
	}

	public String getDefaultTab()
	{
		return this.defaultTab;
	}

	public void setDefaultTab(String defaultTab)
	{
		this.defaultTab = defaultTab;
	}

	public String getTableId()
	{
		return this.tableId;
	}

	public void setTableId(String tableId)
	{
		this.tableId = tableId;
	}

	public Long getParentTabId()
	{
		return this.parentTabId;
	}

	public void setParentTabId(Long parentTabId)
	{
		this.parentTabId = parentTabId;
	}

	public Long getTabLevel()
	{
		return this.tabLevel;
	}

	public void setTabLevel(Long tabLevel)
	{
		this.tabLevel = tabLevel;
	}

}
