package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

/**
 * Template generated by hbm2java
 */
public class Template implements java.io.Serializable
{

	// Fields    

	private Long templateId;

	private String templateName;

	// Constructors

	/** default constructor */
	public Template()
	{
	}

	/** full constructor */
	public Template(String templateName)
	{
		this.templateName = templateName;
	}

	// Property accessors
	public Long getTemplateId()
	{
		return this.templateId;
	}

	public void setTemplateId(Long templateId)
	{
		this.templateId = templateId;
	}

	public String getTemplateName()
	{
		return this.templateName;
	}

	public void setTemplateName(String templateName)
	{
		this.templateName = templateName;
	}

}
