package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * UserOrganization generated by hbm2java
 */
public class UserOrganization implements java.io.Serializable
{

	// Fields    

	private UserOrganizationId id;

	private User userByUserId;

	private Organization organization;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private Date dateCreated;

	private Date dateModified;

	// Constructors

	/** default constructor */
	public UserOrganization()
	{
	}

	/** minimal constructor */
	public UserOrganization(User userByUserId, Organization organization, User userByCreatedBy, Date dateCreated)
	{
		this.userByUserId = userByUserId;
		this.organization = organization;
		this.userByCreatedBy = userByCreatedBy;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public UserOrganization(User userByUserId, Organization organization, User userByModifiedBy, User userByCreatedBy, Date dateCreated, Date dateModified)
	{
		this.userByUserId = userByUserId;
		this.organization = organization;
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	// Property accessors
	public UserOrganizationId getId()
	{
		return this.id;
	}

	public void setId(UserOrganizationId id)
	{
		this.id = id;
	}

	public User getUserByUserId()
	{
		return this.userByUserId;
	}

	public void setUserByUserId(User userByUserId)
	{
		this.userByUserId = userByUserId;
	}

	public Organization getOrganization()
	{
		return this.organization;
	}

	public void setOrganization(Organization organization)
	{
		this.organization = organization;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

}
