package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

/**
 * UsersCrystal generated by hbm2java
 */
public class UsersCrystal implements java.io.Serializable
{

	// Fields    

	private String login;

	private String password;

	private String company;

	// Constructors

	/** default constructor */
	public UsersCrystal()
	{
	}

	/** minimal constructor */
	public UsersCrystal(String password)
	{
		this.password = password;
	}

	/** full constructor */
	public UsersCrystal(String password, String company)
	{
		this.password = password;
		this.company = company;
	}

	// Property accessors
	public String getLogin()
	{
		return this.login;
	}

	public void setLogin(String login)
	{
		this.login = login;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public String getCompany()
	{
		return this.company;
	}

	public void setCompany(String company)
	{
		this.company = company;
	}

}
