package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable
{

	// Fields    

	private Long userId;

	private Lookup lookupByEmploymentTypeId;

	private Contact contactByContactId;

	private Contact contactByVendorContactId;

	private Lookup lookupByUserTypeId;

	private Customer customer;

	private User userByModifiedBy;

	private User userByCreatedBy;

	private String extEmployeeId;

	private String extDealerId;

	private String dealerName;

	private String firstName;

	private String lastName;

	private String login;

	private String password;

	private Date lastLogin;

	private String pin;

	private String activeFlag;

	private String imobileLogin;

	private Date lastSynchDate;

	private Date dateCreated;

	private Date dateModified;

	private String fullName;

	private String qp3;

	

	private Set roles = new HashSet(0);
	private Set organizations = new HashSet(0);
     private Set userCustomers = new HashSet(0);

	// Constructors

	/** default constructor */
	public User()
	{
	}

	/** minimal constructor */
	public User(Lookup lookupByEmploymentTypeId, User userByCreatedBy, String extDealerId, String firstName, String lastName, String login, String password, String activeFlag, Date dateCreated)
	{
		this.lookupByEmploymentTypeId = lookupByEmploymentTypeId;
		this.userByCreatedBy = userByCreatedBy;
		this.extDealerId = extDealerId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.login = login;
		this.password = password;
		this.activeFlag = activeFlag;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public User(Lookup lookupByEmploymentTypeId, Contact contactByContactId, Contact contactByVendorContactId, Lookup lookupByUserTypeId, Customer customer, User userByModifiedBy,
			User userByCreatedBy, String extEmployeeId, String extDealerId, String dealerName, String firstName, String lastName, String login, String password, Date lastLogin, String pin,
			String activeFlag, String imobileLogin, Date lastSynchDate, Date dateCreated, Date dateModified, String fullName, String qp3, Set resourceTypeItemsForCreatedBy,
			Set quoteConditionsForCreatedBy, Set payrollBatches, Set serviceLinesForModifiedBy, Set rolesForModifiedBy, Set serviceLinesForEnteredBy, Set roleFunctionRightsForModifiedBy,
			Set resourcesForCreatedBy, Set servicesForCreatedBy, Set userApprovers, Set resourceItemsForCreatedBy, Set serviceLinesForCreatedBy, Set lookupTypesForCreatedBy,
			Set resourceEstimatesForCreatedBy, Set trackingsForFromUserId, Set servicesForModifiedBy, Set serviceTasks, Set resourceTypesForCreatedBy, Set resourcesForUserId,
			Set userOrganizationsForCreatedBy, Set projectsForModifiedBy, Set rolesForCreatedBy, Set quotesForQuotedByUserId, Set resourceItemsForModifiedBy, Set schResourcesForCreatedBy,
			Set trackingsForModifiedBy, Set resourceTypeItemsForModifiedBy, Set jobsForBillingUserId, Set requestDocumentsForCreatedBy, Set userJobTypes, Set userRolesForCreatedBy,
			Set rightTypesForModifiedBy, Set rightTypesForCreatedBy, Set punchlistIssuesForCreatedBy, Set organizationsForModifiedBy, Set schResourcesForModifiedBy, Set punchlistIssuesForModifiedBy,
			Set serviceLinesForVerifiedBy, Set organizationsForCreatedBy, Set jobsForModifiedBy, Set projectNotesForModifiedBy, Set projectNotesForCreatedBy, Set requestsForModifiedBy,
			Set requestDocumentsForModifiedBy, Set requestsForCreatedBy, Set resourcesForModifiedBy, Set quotesForModifiedBy, Set resourceEstimatesForModifiedBy, Set userRolesForModifiedBy,
			Set roleFunctionRightsForCreatedBy, Set serviceLinesForOverrideBy, Set punchlistsForModifiedBy, Set jobLocationsForModifiedBy, Set resourceTypesForModifiedBy, Set usersForCreatedBy,
			Set punchlistsForCreatedBy, Set projectsForCreatedBy, Set quoteConditionsForModifiedBy, Set trackingsForCreatedBy, Set lookupTypesForModifiedBy, Set usersForModifiedBy,
			Set userOrganizationsForUserId, Set jobLocationsForCreatedBy, Set userOrganizationsForModifiedBy, Set jobsForCreatedBy, Set quotesForCreatedBy, Set userRolesForUserId)
	{
		this.lookupByEmploymentTypeId = lookupByEmploymentTypeId;
		this.contactByContactId = contactByContactId;
		this.contactByVendorContactId = contactByVendorContactId;
		this.lookupByUserTypeId = lookupByUserTypeId;
		this.customer = customer;
		this.userByModifiedBy = userByModifiedBy;
		this.userByCreatedBy = userByCreatedBy;
		this.extEmployeeId = extEmployeeId;
		this.extDealerId = extDealerId;
		this.dealerName = dealerName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.login = login;
		this.password = password;
		this.lastLogin = lastLogin;
		this.pin = pin;
		this.activeFlag = activeFlag;
		this.imobileLogin = imobileLogin;
		this.lastSynchDate = lastSynchDate;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.fullName = fullName;
		this.qp3 = qp3;
		this.roles = userRolesForUserId;
	}

	// Property accessors
	public Long getUserId()
	{
		return this.userId;
	}

	public void setUserId(Long userId)
	{
		this.userId = userId;
	}

	public Lookup getLookupByEmploymentTypeId()
	{
		return this.lookupByEmploymentTypeId;
	}

	public void setLookupByEmploymentTypeId(Lookup lookupByEmploymentTypeId)
	{
		this.lookupByEmploymentTypeId = lookupByEmploymentTypeId;
	}

	public Contact getContactByContactId()
	{
		return this.contactByContactId;
	}

	public void setContactByContactId(Contact contactByContactId)
	{
		this.contactByContactId = contactByContactId;
	}

	public Contact getContactByVendorContactId()
	{
		return this.contactByVendorContactId;
	}

	public void setContactByVendorContactId(Contact contactByVendorContactId)
	{
		this.contactByVendorContactId = contactByVendorContactId;
	}

	public Lookup getLookupByUserTypeId()
	{
		return this.lookupByUserTypeId;
	}

	public void setLookupByUserTypeId(Lookup lookupByUserTypeId)
	{
		this.lookupByUserTypeId = lookupByUserTypeId;
	}

	public Customer getCustomer()
	{
		return this.customer;
	}

	public void setCustomer(Customer customer)
	{
		this.customer = customer;
	}

	public User getUserByModifiedBy()
	{
		return this.userByModifiedBy;
	}

	public void setUserByModifiedBy(User userByModifiedBy)
	{
		this.userByModifiedBy = userByModifiedBy;
	}

	public User getUserByCreatedBy()
	{
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy)
	{
		this.userByCreatedBy = userByCreatedBy;
	}

	public String getExtEmployeeId()
	{
		return this.extEmployeeId;
	}

	public void setExtEmployeeId(String extEmployeeId)
	{
		this.extEmployeeId = extEmployeeId;
	}

	public String getExtDealerId()
	{
		return this.extDealerId;
	}

	public void setExtDealerId(String extDealerId)
	{
		this.extDealerId = extDealerId;
	}

	public String getDealerName()
	{
		return this.dealerName;
	}

	public void setDealerName(String dealerName)
	{
		this.dealerName = dealerName;
	}

	public String getFirstName()
	{
		return this.firstName;
	}

	public void setFirstName(String firstName)
	{
		this.firstName = firstName;
	}

	public String getLastName()
	{
		return this.lastName;
	}

	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	public String getLogin()
	{
		return this.login;
	}

	public void setLogin(String login)
	{
		this.login = login;
	}

	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public Date getLastLogin()
	{
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin)
	{
		this.lastLogin = lastLogin;
	}

	public String getPin()
	{
		return this.pin;
	}

	public void setPin(String pin)
	{
		this.pin = pin;
	}

	public String getActiveFlag()
	{
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag)
	{
		this.activeFlag = activeFlag;
	}

	public String getImobileLogin()
	{
		return this.imobileLogin;
	}

	public void setImobileLogin(String imobileLogin)
	{
		this.imobileLogin = imobileLogin;
	}

	public Date getLastSynchDate()
	{
		return this.lastSynchDate;
	}

	public void setLastSynchDate(Date lastSynchDate)
	{
		this.lastSynchDate = lastSynchDate;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

	public String getFullName()
	{
		return this.fullName;
	}

	public void setFullName(String fullName)
	{
		this.fullName = fullName;
	}

	public String getQp3()
	{
		return this.qp3;
	}

	public void setQp3(String qp3)
	{
		this.qp3 = qp3;
	}


	public Set getRoles()
	{
		return this.roles;
	}

	public void setRoles(Set userRolesForUserId)
	{
		this.roles = userRolesForUserId;
	}

	public Set getOrganizations()
	{
		return organizations;
	}

    public Set getUserCustomers() {
        return this.userCustomers;
    }
    
    public void setUserCustomers(Set userCustomers) {
        this.userCustomers = userCustomers;
    }
	public void setOrganizations(Set organizations)
	{
		this.organizations = organizations;
	}


}
