package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

/**
 * UserRoleId generated by hbm2java
 */
public class UserRoleId implements java.io.Serializable
{

	// Fields    

	private long userId;

	private long roleId;

	// Constructors

	/** default constructor */
	public UserRoleId()
	{
	}

	/** full constructor */
	public UserRoleId(long userId, long roleId)
	{
		this.userId = userId;
		this.roleId = roleId;
	}

	// Property accessors
	public long getUserId()
	{
		return this.userId;
	}

	public void setUserId(long userId)
	{
		this.userId = userId;
	}

	public long getRoleId()
	{
		return this.roleId;
	}

	public void setRoleId(long roleId)
	{
		this.roleId = roleId;
	}

	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRoleId))
			return false;
		UserRoleId castOther = (UserRoleId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getRoleId();
		return result;
	}

}
