package com.dynamic.servicetrax.orm;
// Generated Nov 1, 2006 10:52:25 AM by Hibernate Tools 3.2.0.beta6a



/**
 * UserCustomer generated by hbm2java
 */
public class UserCustomer  implements java.io.Serializable {

    // Fields    

     private long userCustomerId;
     private User user;
     private Customer customer;

     // Constructors

    /** default constructor */
    public UserCustomer() {
    }

    /** full constructor */
    public UserCustomer(long userCustomerId, User user, Customer customer) {
       this.userCustomerId = userCustomerId;
       this.user = user;
       this.customer = customer;
    }
    
   
    // Property accessors
    public long getUserCustomerId() {
        return this.userCustomerId;
    }
    
    public void setUserCustomerId(long userCustomerId) {
        this.userCustomerId = userCustomerId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }




}


