package com.dynamic.servicetrax.orm;

// Generated Apr 27, 2006 9:55:28 AM by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * Version generated by hbm2java
 */
public class Version implements java.io.Serializable
{

	// Fields    

	private Long versionId;

	private Document document;

	private String code;

	private String comments;

	private long numDownloads;

	private long createdBy;

	private Date dateCreated;

	private Long modifiedBy;

	private Date dateModified;

	// Constructors

	/** default constructor */
	public Version()
	{
	}

	/** minimal constructor */
	public Version(Document document, String code, long numDownloads, long createdBy, Date dateCreated)
	{
		this.document = document;
		this.code = code;
		this.numDownloads = numDownloads;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	/** full constructor */
	public Version(Document document, String code, String comments, long numDownloads, long createdBy, Date dateCreated, Long modifiedBy, Date dateModified)
	{
		this.document = document;
		this.code = code;
		this.comments = comments;
		this.numDownloads = numDownloads;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
	}

	// Property accessors
	public Long getVersionId()
	{
		return this.versionId;
	}

	public void setVersionId(Long versionId)
	{
		this.versionId = versionId;
	}

	public Document getDocument()
	{
		return this.document;
	}

	public void setDocument(Document document)
	{
		this.document = document;
	}

	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getComments()
	{
		return this.comments;
	}

	public void setComments(String comments)
	{
		this.comments = comments;
	}

	public long getNumDownloads()
	{
		return this.numDownloads;
	}

	public void setNumDownloads(long numDownloads)
	{
		this.numDownloads = numDownloads;
	}

	public long getCreatedBy()
	{
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public Long getModifiedBy()
	{
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified()
	{
		return this.dateModified;
	}

	public void setDateModified(Date dateModified)
	{
		this.dateModified = dateModified;
	}

}
