/* Generated By:JavaCC: Do not edit this line. SqlConstants.java */
package dynamic.dbtk.parser;

public interface SqlConstants {

  int EOF = 0;
  int K_ALL = 5;
  int K_AND = 6;
  int K_ANY = 7;
  int K_AS = 8;
  int K_ASC = 9;
  int K_BEGIN = 10;
  int K_BETWEEN = 11;
  int K_BINARY_INTEGER = 12;
  int K_BOOLEAN = 13;
  int K_BY = 14;
  int K_CHAR = 15;
  int K_CLOSE = 16;
  int K_COMMENT = 17;
  int K_COMMIT = 18;
  int K_CONNECT = 19;
  int K_CONSTANT = 20;
  int K_CURRENT = 21;
  int K_CURSOR = 22;
  int K_DATE = 23;
  int K_DECIMAL = 24;
  int K_DECLARE = 25;
  int K_DEFAULT = 26;
  int K_DELETE = 27;
  int K_DESC = 28;
  int K_DISTINCT = 29;
  int K_DO = 30;
  int K_ELSE = 31;
  int K_ELSIF = 32;
  int K_END = 33;
  int K_EXCEPTION = 34;
  int K_EXCEPTION_INIT = 35;
  int K_EXCLUSIVE = 36;
  int K_EXISTS = 37;
  int K_EXIT = 38;
  int K_FETCH = 39;
  int K_FLOAT = 40;
  int K_FOR = 41;
  int K_FROM = 42;
  int K_FULL = 43;
  int K_FUNCTION = 44;
  int K_GOTO = 45;
  int K_GROUP = 46;
  int K_HAVING = 47;
  int K_IF = 48;
  int K_IN = 49;
  int K_INNER = 50;
  int K_INDEX = 51;
  int K_INSERT = 52;
  int K_INTEGER = 53;
  int K_INTERSECT = 54;
  int K_INTO = 55;
  int K_IS = 56;
  int K_JOIN = 57;
  int K_LEFT = 58;
  int K_LIKE = 59;
  int K_LOCK = 60;
  int K_LOOP = 61;
  int K_MINUS = 62;
  int K_MODE = 63;
  int K_NATURAL = 64;
  int K_NOT = 65;
  int K_NOWAIT = 66;
  int K_NULL = 67;
  int K_NUMBER = 68;
  int K_OF = 69;
  int K_ON = 70;
  int K_ONLY = 71;
  int K_OPEN = 72;
  int K_OR = 73;
  int K_ORDER = 74;
  int K_OTHERS = 75;
  int K_OUT = 76;
  int K_OUTER = 77;
  int K_PACKAGE = 78;
  int K_POSITIVE = 79;
  int K_PRAGMA = 80;
  int K_PRIOR = 81;
  int K_PROCEDURE = 82;
  int K_RAISE = 83;
  int K_READ = 84;
  int K_REAL = 85;
  int K_RECORD = 86;
  int K_REF = 87;
  int K_RETURN = 88;
  int K_REVERSE = 89;
  int K_RIGHT = 90;
  int K_ROLLBACK = 91;
  int K_ROW = 92;
  int K_SAVEPOINT = 93;
  int K_SEGMENT = 94;
  int K_SELECT = 95;
  int K_SET = 96;
  int K_SHARE = 97;
  int K_SMALLINT = 98;
  int K_SQL = 99;
  int K_START = 100;
  int K_TABLE = 101;
  int K_THEN = 102;
  int K_TO = 103;
  int K_TRANSACTION = 104;
  int K_UNION = 105;
  int K_UPDATE = 106;
  int K_USE = 107;
  int K_VALUES = 108;
  int K_VARCHAR2 = 109;
  int K_WHEN = 110;
  int K_WHERE = 111;
  int K_WHILE = 112;
  int K_WITH = 113;
  int K_WORK = 114;
  int K_WRITE = 115;
  int K_CASE = 116;
  int S_NUMBER = 117;
  int FLOAT = 118;
  int INTEGER = 119;
  int DIGIT = 120;
  int LINE_COMMENT = 121;
  int MULTI_LINE_COMMENT = 122;
  int S_IDENTIFIER = 123;
  int LETTER = 124;
  int SPECIAL_CHARS = 125;
  int S_BIND = 126;
  int S_CHAR_LITERAL = 127;
  int S_QUOTED_IDENTIFIER = 128;
  int S_OUTER = 129;
  int S_LEFT_PAREN = 130;
  int S_RIGHT_PAREN = 131;
  int K_ORDER_BY = 132;
  int K_GROUP_BY = 133;
  int K_START_WITH = 134;
  int K_CONNECT_BY = 135;
  int K_FOR_UPDATE_OF = 136;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"BEGIN\"",
    "\"BETWEEN\"",
    "\"BINARY_INTEGER\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"CHAR\"",
    "\"CLOSE\"",
    "\"COMMENT\"",
    "\"COMMIT\"",
    "\"CONNECT\"",
    "\"CONSTANT\"",
    "\"CURRENT\"",
    "\"CURSOR\"",
    "\"DATE\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DISTINCT\"",
    "\"DO\"",
    "\"ELSE\"",
    "\"ELSIF\"",
    "\"END\"",
    "\"EXCEPTION\"",
    "\"EXCEPTION_INIT\"",
    "\"EXCLUSIVE\"",
    "\"EXISTS\"",
    "\"EXIT\"",
    "\"FETCH\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"GOTO\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"IF\"",
    "\"IN\"",
    "\"INNER\"",
    "\"INDEX\"",
    "\"INSERT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LOCK\"",
    "\"LOOP\"",
    "\"MINUS\"",
    "\"MODE\"",
    "\"NATURAL\"",
    "\"NOT\"",
    "\"NOWAIT\"",
    "\"NULL\"",
    "\"NUMBER\"",
    "\"OF\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"PACKAGE\"",
    "\"POSITIVE\"",
    "\"PRAGMA\"",
    "\"PRIOR\"",
    "\"PROCEDURE\"",
    "\"RAISE\"",
    "\"READ\"",
    "\"REAL\"",
    "\"RECORD\"",
    "\"REF\"",
    "\"RETURN\"",
    "\"REVERSE\"",
    "\"RIGHT\"",
    "\"ROLLBACK\"",
    "\"ROW\"",
    "\"SAVEPOINT\"",
    "\"SEGMENT\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"SHARE\"",
    "\"SMALLINT\"",
    "\"SQL\"",
    "\"START\"",
    "\"TABLE\"",
    "\"THEN\"",
    "\"TO\"",
    "\"TRANSACTION\"",
    "\"UNION\"",
    "\"UPDATE\"",
    "\"USE\"",
    "\"VALUES\"",
    "\"VARCHAR2\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WHILE\"",
    "\"WITH\"",
    "\"WORK\"",
    "\"WRITE\"",
    "\"CASE\"",
    "<S_NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_BIND>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<S_OUTER>",
    "\"(\"",
    "\")\"",
    "<K_ORDER_BY>",
    "<K_GROUP_BY>",
    "<K_START_WITH>",
    "<K_CONNECT_BY>",
    "<K_FOR_UPDATE_OF>",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\"#\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"*=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\",\"",
    "\".*\"",
    "\"||\"",
    "\"/\"",
    "\"**\"",
  };

}
