CREATE VIEW dbo.AIA_OFFICE_INTERIORS_CUSTOMER_V
AS
SELECT     dbo.CONTACTS.CONTACT_ID, dbo.CONTACTS.CONTACT_NAME, dbo.CONTACTS.ORGANIZATION_ID, dbo.CONTACTS.EXT_DEALER_ID, 
                      dbo.CONTACTS.CUSTOMER_ID, dbo.CUSTOMERS.DEALER_NAME, dbo.CUSTOMERS.EXT_CUSTOMER_ID, dbo.CUSTOMERS.CUSTOMER_NAME
FROM         dbo.CONTACTS FULL OUTER JOIN
                      dbo.CUSTOMERS ON dbo.CONTACTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID
WHERE     (dbo.CONTACTS.ORGANIZATION_ID = 8) AND (dbo.CUSTOMERS.CUSTOMER_NAME = 'Office Interior') OR
                      (dbo.CUSTOMERS.CUSTOMER_NAME = 'Office Interiors - Atlanta') OR
                      (dbo.CUSTOMERS.CUSTOMER_NAME = 'Facilitec')

