CREATE VIEW dbo.AIA_JOB_LOCATIONS_V
AS
SELECT     dbo.JOB_LOCATIONS.JOB_LOCATION_ID, dbo.CUSTOMERS.EXT_DEALER_ID, dbo.JOB_LOCATIONS.CUSTOMER_ID, 
                      dbo.JOB_LOCATIONS.JOB_LOCATION_NAME, dbo.JOB_LOCATIONS.LOCATION_TYPE_ID, dbo.JOB_LOCATIONS.EXT_ADDRESS_ID, 
                      dbo.JOB_LOCATIONS.STREET1, dbo.JOB_LOCATIONS.STREET2, dbo.JOB_LOCATIONS.STREET3, dbo.JOB_LOCATIONS.CITY, 
                      dbo.JOB_LOCATIONS.STATE, dbo.JOB_LOCATIONS.ZIP, dbo.JOB_LOCATIONS.COUNTRY, dbo.JOB_LOCATIONS.active_flag, 
                      dbo.JOB_LOCATIONS.county, dbo.CUSTOMERS.CUSTOMER_NAME
FROM         dbo.CUSTOMERS INNER JOIN
                      dbo.JOB_LOCATIONS ON dbo.CUSTOMERS.CUSTOMER_ID = dbo.JOB_LOCATIONS.CUSTOMER_ID
WHERE     (dbo.CUSTOMERS.EXT_DEALER_ID = '10309') AND (dbo.JOB_LOCATIONS.active_flag = 'y') OR
                      (dbo.CUSTOMERS.EXT_DEALER_ID = '10046') OR
                      (dbo.CUSTOMERS.EXT_DEALER_ID = '11133') OR
                      (dbo.CUSTOMERS.EXT_DEALER_ID = '10300') OR
                      (dbo.CUSTOMERS.EXT_DEALER_ID = '10971') OR
                      (dbo.CUSTOMERS.EXT_DEALER_ID = '10000')

