CREATE VIEW dbo.bad_reqs
AS
SELECT     TOP 100 PERCENT dbo.CUSTOMERS.DEALER_NAME, dbo.CUSTOMERS.CUSTOMER_NAME, dbo.JOBS.JOB_NO, dbo.JOBS.JOB_NAME, 
                      dbo.SERVICES.SERVICE_NO, dbo.CUSTOM_COLS.CUSTOM_COL_ID, dbo.SERVICES.DATE_CREATED, dbo.LOOKUPS.CODE, 
                      LOOKUPS_1.CODE AS Expr1
FROM         dbo.JOBS INNER JOIN
                      dbo.SERVICES ON dbo.JOBS.JOB_ID = dbo.SERVICES.JOB_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.JOBS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.LOOKUPS ON dbo.SERVICES.SERVICE_TYPE_ID = dbo.LOOKUPS.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_1 ON dbo.JOBS.JOB_TYPE_ID = LOOKUPS_1.LOOKUP_ID LEFT OUTER JOIN
                      dbo.CUSTOM_COLS ON dbo.SERVICES.SERVICE_ID = dbo.CUSTOM_COLS.SERVICE_ID
WHERE     (dbo.CUSTOM_COLS.CUSTOM_COL_ID IS NULL) AND (dbo.LOOKUPS.CODE = 'short_view') AND (dbo.SERVICES.DATE_CREATED BETWEEN 
                      CONVERT(DATETIME, '2003-10-01 00:00:00', 102) AND GETDATE()) AND (LOOKUPS_1.CODE = 'service_account')
ORDER BY dbo.SERVICES.DATE_CREATED, dbo.CUSTOMERS.DEALER_NAME, dbo.CUSTOMERS.CUSTOMER_NAME, dbo.JOBS.JOB_NO, dbo.JOBS.JOB_NAME, 
                      dbo.SERVICES.SERVICE_NO

