CREATE VIEW dbo.CHANGED_HRS_V
AS
SELECT     dbo.BILLING_V.ORGANIZATION_ID, dbo.BILLING_V.BILL_JOB_ID, dbo.BILLING_V.BILL_JOB_NO, dbo.JOBS_V.JOB_NAME, 
                      dbo.JOBS_V.FOREMAN_RESOURCE_ID, dbo.JOBS_V.foreman_resource_name, dbo.BILLING_V.BILL_SERVICE_ID, dbo.BILLING_V.BILL_SERVICE_NO, 
                      dbo.BILLING_V.SERVICE_LINE_ID, dbo.BILLING_V.BILL_SERVICE_LINE_NO, dbo.BILLING_V.SERVICE_LINE_DATE, 
                      dbo.BILLING_V.SERVICE_LINE_DATE_VARCHAR, dbo.BILLING_V.STATUS_ID, dbo.BILLING_V.status_name, dbo.BILLING_V.RESOURCE_ID, 
                      dbo.RESOURCES_V.USER_ID, dbo.RESOURCES_V.EXT_EMPLOYEE_ID, dbo.RESOURCES_V.user_full_name AS employee_name, dbo.BILLING_V.POOLED_FLAG,
                      dbo.BILLING_V.ITEM_NAME, dbo.BILLING_V.PAYROLL_QTY, dbo.BILLING_V.BILL_HOURLY_QTY, dbo.BILLING_V.BILL_HOURLY_RATE, 
                      ISNULL(dbo.BILLING_V.PAYROLL_QTY, 0) - ISNULL(dbo.BILLING_V.BILL_HOURLY_QTY, 0) AS hours_difference
FROM         dbo.BILLING_V LEFT OUTER JOIN
                      dbo.RESOURCES_V ON dbo.BILLING_V.RESOURCE_ID = dbo.RESOURCES_V.RESOURCE_ID LEFT OUTER JOIN
                      dbo.JOBS_V ON dbo.BILLING_V.BILL_JOB_ID = dbo.JOBS_V.JOB_ID
WHERE     (ISNULL(dbo.BILLING_V.PAYROLL_QTY, 0) - ISNULL(dbo.BILLING_V.BILL_HOURLY_QTY, 0) <> 0)



