
CREATE VIEW dbo.CONDITIONS_V
AS
SELECT     dbo.CONDITIONS.CONDITION_ID, dbo.QUOTE_CONDITIONS.USE_FLAG, dbo.CONDITIONS.NAME, dbo.CONDITIONS.DATE_CREATED, 
                      dbo.CONDITIONS.CREATED_BY, USERS_1.FIRST_NAME + ' ' + USERS_1.LAST_NAME AS created_by_name, dbo.CONDITIONS.DATE_MODIFIED, 
                      dbo.CONDITIONS.MODIFIED_BY, USERS_2.FIRST_NAME + ' ' + USERS_2.LAST_NAME AS modified_by_name
FROM         dbo.QUOTE_CONDITIONS RIGHT OUTER JOIN
                      dbo.CONDITIONS ON dbo.QUOTE_CONDITIONS.CONDITION_ID = dbo.CONDITIONS.CONDITION_ID LEFT OUTER JOIN
                      dbo.USERS USERS_2 ON dbo.CONDITIONS.MODIFIED_BY = USERS_2.USER_ID LEFT OUTER JOIN
                      dbo.USERS USERS_1 ON dbo.CONDITIONS.CREATED_BY = USERS_1.USER_ID


