CREATE VIEW dbo.CONTACTS_V
AS
SELECT     dbo.CONTACTS.ORGANIZATION_ID, dbo.CONTACTS.CONTACT_ID, dbo.CONTACTS.CONTACT_NAME, dbo.CONTACTS.EXT_DEALER_ID, 
                      dbo.CONTACTS.CUSTOMER_ID, dbo.CUSTOMERS.PARENT_CUSTOMER_ID, dbo.CUSTOMERS.CUSTOMER_NAME, 
                      dbo.CONTACT_GROUPS.CONTACT_TYPE_ID, LOOKUPS_2.CODE AS contact_type_code, LOOKUPS_2.NAME AS contact_type_name, 
                      dbo.CONTACTS.CONT_STATUS_TYPE_ID, CONT_STATUS_TYPE.CODE AS cont_status_type_code, 
                      CONT_STATUS_TYPE.NAME AS cont_status_type_name, dbo.CONTACTS.PHONE_WORK, dbo.CONTACTS.PHONE_CELL, 
                      dbo.CONTACTS.PHONE_HOME, dbo.CONTACTS.EMAIL, dbo.CONTACTS.STREET1, dbo.CONTACTS.STREET2, dbo.CONTACTS.STREET3, 
                      dbo.CONTACTS.CITY, dbo.CONTACTS.STATE, dbo.CONTACTS.ZIP, dbo.CONTACTS.NOTES, dbo.CONTACTS.DATE_CREATED, 
                      dbo.CONTACTS.CREATED_BY, USERS_V_1.full_name AS created_by_name, dbo.CONTACTS.DATE_MODIFIED, dbo.CONTACTS.MODIFIED_BY, 
                      USERS_V_2.full_name AS modified_by_name
FROM         dbo.CUSTOMERS RIGHT OUTER JOIN
                      dbo.CONTACTS LEFT OUTER JOIN
                      dbo.CONTACT_GROUPS ON dbo.CONTACTS.CONTACT_ID = dbo.CONTACT_GROUPS.CONTACT_ID LEFT OUTER JOIN
                      dbo.LOOKUPS CONT_STATUS_TYPE ON dbo.CONTACTS.CONT_STATUS_TYPE_ID = CONT_STATUS_TYPE.LOOKUP_ID LEFT OUTER JOIN
                      dbo.LOOKUPS LOOKUPS_2 ON dbo.CONTACT_GROUPS.CONTACT_TYPE_ID = LOOKUPS_2.LOOKUP_ID ON 
                      dbo.CUSTOMERS.CUSTOMER_ID = dbo.CONTACTS.CUSTOMER_ID LEFT OUTER JOIN
                      dbo.USERS_V USERS_V_2 ON dbo.CONTACTS.MODIFIED_BY = USERS_V_2.USER_ID LEFT OUTER JOIN
                      dbo.USERS_V USERS_V_1 ON dbo.CONTACTS.CREATED_BY = USERS_V_1.USER_ID



