CREATE VIEW dbo.Contacts_qry_lookupbyorg
AS
SELECT     TOP 100 PERCENT dbo.CUSTOMERS.DEALER_NAME, dbo.CUSTOMERS.CUSTOMER_NAME, dbo.CONTACTS.CONTACT_ID, 
                      dbo.CONTACTS.CONTACT_NAME, dbo.CONTACTS.EMAIL, dbo.LOOKUPS.NAME AS STATUS, dbo.CONTACTS.ORGANIZATION_ID, 
                      dbo.CONTACTS.EXT_DEALER_ID
FROM         dbo.CONTACTS INNER JOIN
                      dbo.LOOKUPS ON dbo.CONTACTS.CONT_STATUS_TYPE_ID = dbo.LOOKUPS.LOOKUP_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.CONTACTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID
WHERE     (dbo.CONTACTS.ORGANIZATION_ID = 4) AND (dbo.CONTACTS.EXT_DEALER_ID = '10002') OR
                      (dbo.CONTACTS.EXT_DEALER_ID = '10004') OR
                      (dbo.CONTACTS.EXT_DEALER_ID = '10006') OR
                      (dbo.CONTACTS.EXT_DEALER_ID = '10008')
ORDER BY dbo.CONTACTS.CONTACT_NAME

