CREATE VIEW dbo.crystal_USERS_AND_RESOURCE_TYPES
AS
SELECT     dbo.USERS.USER_ID, dbo.USERS.FULL_NAME, dbo.RESOURCE_TYPES.NAME, dbo.RESOURCES.ORGANIZATION_ID, dbo.RESOURCES.ACTIVE_FLAG,
                       dbo.ORGANIZATIONS.NAME AS Org_Id_Name
FROM         dbo.USERS INNER JOIN
                      dbo.RESOURCES ON dbo.USERS.USER_ID = dbo.RESOURCES.USER_ID INNER JOIN
                      dbo.RESOURCE_TYPES ON dbo.RESOURCES.RESOURCE_TYPE_ID = dbo.RESOURCE_TYPES.RESOURCE_TYPE_ID INNER JOIN
                      dbo.ORGANIZATIONS ON dbo.RESOURCES.ORGANIZATION_ID = dbo.ORGANIZATIONS.ORGANIZATION_ID
WHERE     (dbo.RESOURCES.ACTIVE_FLAG = 'y')

