CREATE VIEW dbo.crystal_REQUESTS_COUNT_USAGE_V
AS
SELECT     dbo.REQUESTS.REQUEST_ID, dbo.REQUESTS.REQUEST_TYPE_ID, REQUEST_TYPE.CODE AS request_type_code, 
                      REQUEST_TYPE.NAME AS request_type_name, dbo.REQUESTS.REQUEST_STATUS_TYPE_ID, dbo.REQUESTS.DATE_CREATED, 
                      dbo.REQUESTS.CREATED_BY, USERS_1.FIRST_NAME + ' ' + USERS_1.LAST_NAME AS created_by_name, CONVERT(varchar(12), 
                      dbo.REQUESTS.DATE_CREATED, 101) AS date_created_varchar, USERS_1.EXT_DEALER_ID, dbo.REQUESTS.VERSION_NO, 
                      dbo.REQUESTS.IS_SURVEYED, dbo.REQUESTS.IS_QUOTED, dbo.REQUESTS.QUOTE_REQUEST_ID
FROM         dbo.LOOKUPS REQUEST_TYPE INNER JOIN
                      dbo.REQUESTS ON REQUEST_TYPE.LOOKUP_ID = dbo.REQUESTS.REQUEST_TYPE_ID INNER JOIN
                      dbo.USERS USERS_1 ON dbo.REQUESTS.CREATED_BY = USERS_1.USER_ID

