CREATE VIEW dbo.crystal_JOBS_INVOICED_BUT_DOLLARS_REMAIN_IN_JOB_V
AS
SELECT     TOP 100 PERCENT dbo.SERVICE_LINES.ORGANIZATION_ID, dbo.SERVICE_LINES.SERVICE_LINE_ID, dbo.SERVICE_LINES.TC_JOB_NO, 
                      dbo.SERVICE_LINES.TC_SERVICE_NO, dbo.SERVICE_LINES.TC_SERVICE_LINE_NO, dbo.SERVICE_LINES.STATUS_ID, 
                      dbo.SERVICE_LINES.BILLED_FLAG, dbo.SERVICE_LINES.POSTED_FLAG, dbo.SERVICE_LINES.RESOURCE_ID, 
                      dbo.SERVICE_LINES.RESOURCE_NAME, dbo.SERVICE_LINES.ITEM_ID, dbo.SERVICE_LINES.ITEM_NAME, dbo.SERVICE_LINES.ITEM_TYPE_CODE, 
                      dbo.SERVICE_LINES.INVOICE_ID, dbo.SERVICE_LINES.POSTED_FROM_INVOICE_ID, dbo.SERVICE_LINES.BILLABLE_FLAG, 
                      dbo.SERVICE_LINES.bill_exp_total, dbo.SERVICE_LINES.bill_hourly_total, dbo.SERVICE_LINES.bill_total, dbo.SERVICE_LINES.expense_total, 
                      dbo.JOBS.JOB_NAME, dbo.JOBS.BILLING_USER_ID, dbo.USERS.FULL_NAME
FROM         dbo.SERVICE_LINES INNER JOIN
                      dbo.JOBS ON dbo.SERVICE_LINES.TC_JOB_NO = dbo.JOBS.JOB_NO INNER JOIN
                      dbo.USERS ON dbo.JOBS.BILLING_USER_ID = dbo.USERS.USER_ID
WHERE     (dbo.SERVICE_LINES.BILLABLE_FLAG = 'y') AND (dbo.SERVICE_LINES.POSTED_FLAG = 'n') AND (dbo.SERVICE_LINES.INVOICE_ID IS NOT NULL)
ORDER BY dbo.SERVICE_LINES.TC_JOB_NO

