CREATE VIEW dbo.crystal_JOB_LOCATIONS_V
AS
SELECT     TOP 100 PERCENT dbo.JOB_LOCATIONS_V.ORGANIZATION_ID, dbo.CUSTOMERS.CUSTOMER_ID, dbo.CUSTOMERS.EXT_CUSTOMER_ID, 
                      dbo.CUSTOMERS.CUSTOMER_NAME, dbo.CUSTOMERS.ACTIVE_FLAG, dbo.JOB_LOCATIONS_V.JOB_LOCATION_ID, 
                      dbo.JOB_LOCATIONS_V.JOB_LOCATION_NAME, dbo.JOB_LOCATIONS_V.LOCATION_TYPE_ID, dbo.JOB_LOCATIONS_V.location_type_code, 
                      dbo.JOB_LOCATIONS_V.location_type_name, dbo.JOB_LOCATIONS_V.STREET1, dbo.JOB_LOCATIONS_V.STREET2, dbo.JOB_LOCATIONS_V.CITY, 
                      dbo.JOB_LOCATIONS_V.STATE, dbo.JOB_LOCATIONS_V.ZIP, dbo.ORGANIZATIONS.NAME, dbo.CUSTOMERS.EXT_DEALER_ID, 
                      dbo.CUSTOMERS.DEALER_NAME, dbo.JOB_LOCATIONS_V.DATE_CREATED
FROM         dbo.JOB_LOCATIONS_V INNER JOIN
                      dbo.CUSTOMERS ON dbo.JOB_LOCATIONS_V.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.ORGANIZATIONS ON dbo.CUSTOMERS.ORGANIZATION_ID = dbo.ORGANIZATIONS.ORGANIZATION_ID
WHERE     (dbo.CUSTOMERS.EXT_DEALER_ID = '10001') AND (dbo.CUSTOMERS.ACTIVE_FLAG = 'y') OR
                      (dbo.CUSTOMERS.EXT_DEALER_ID = '10875') OR
                      (dbo.CUSTOMERS.EXT_DEALER_ID = '10002') OR
                      (dbo.CUSTOMERS.EXT_DEALER_ID = '10003') OR
                      (dbo.CUSTOMERS.EXT_DEALER_ID = '10000')

