CREATE VIEW dbo.crystal_USERS_V
AS
SELECT     TOP 100 PERCENT dbo.USER_ROLES.ROLE_ID, dbo.USERS.USER_ID, dbo.USERS.FULL_NAME, dbo.ROLES.NAME AS Role_Name, 
                      dbo.USER_ORGANIZATIONS.ORGANIZATION_ID, dbo.USERS.ACTIVE_FLAG
FROM         dbo.USER_ORGANIZATIONS INNER JOIN
                      dbo.USERS ON dbo.USER_ORGANIZATIONS.USER_ID = dbo.USERS.USER_ID LEFT OUTER JOIN
                      dbo.USER_ROLES INNER JOIN
                      dbo.ROLES ON dbo.USER_ROLES.ROLE_ID = dbo.ROLES.ROLE_ID ON dbo.USERS.USER_ID = dbo.USER_ROLES.USER_ID
WHERE     (dbo.USERS.ACTIVE_FLAG = 'y')
ORDER BY dbo.USER_ROLES.ROLE_ID

