CREATE VIEW dbo.crystal_SCH_ACT_1_V
AS
SELECT     dbo.SCH_RESOURCE_DATES_V.SCH_RESOURCE_ID, dbo.SCH_RESOURCE_DATES_V.RESOURCE_ID, dbo.RESOURCES_V.resource_name, 
                      dbo.SCH_RESOURCE_DATES_V.JOB_ID, dbo.JOBS.JOB_NO, dbo.SCH_RESOURCE_DATES_V.SERVICE_ID, 
                      dbo.SCH_RESOURCE_DATES_V.RES_START_DATE, dbo.SCH_RESOURCE_DATES_V.RES_END_DATE, 
                      dbo.SCH_RESOURCE_DATES_V.exploded_date
FROM         dbo.SCH_RESOURCE_DATES_V INNER JOIN
                      dbo.RESOURCES_V ON dbo.SCH_RESOURCE_DATES_V.RESOURCE_ID = dbo.RESOURCES_V.RESOURCE_ID INNER JOIN
                      dbo.JOBS ON dbo.SCH_RESOURCE_DATES_V.JOB_ID = dbo.JOBS.JOB_ID
WHERE     (dbo.RESOURCES_V.resource_name IS NOT NULL)

