CREATE VIEW dbo.crystal_UNBILL_ACCT_V
AS
SELECT     dbo.INVOICES_V.ORGANIZATION_ID, dbo.INVOICES_V.PO_NO, dbo.INVOICES_V.DESCRIPTION, dbo.INVOICES_V.INVOICE_ID, 
                      dbo.INVOICE_PRE_TOTAL_V.JOB_NO, dbo.INVOICE_PRE_TOTAL_V.custom_line_total, dbo.INVOICE_PRE_TOTAL_V.bill_hourly_total, 
                      dbo.INVOICE_PRE_TOTAL_V.bill_exp_total, dbo.INVOICE_PRE_TOTAL_V.bill_total, dbo.INVOICES_V.STATUS_ID, dbo.INVOICE_STATUSES.NAME, 
                      dbo.INVOICES_V.DATE_CREATED, dbo.INVOICE_PRE_TOTAL_V.DEALER_NAME
FROM         dbo.INVOICES_V INNER JOIN
                      dbo.INVOICE_STATUSES ON dbo.INVOICES_V.STATUS_ID = dbo.INVOICE_STATUSES.STATUS_ID LEFT OUTER JOIN
                      dbo.INVOICE_LINES_V ON dbo.INVOICES_V.INVOICE_ID = dbo.INVOICE_LINES_V.INVOICE_ID LEFT OUTER JOIN
                      dbo.INVOICE_PRE_TOTAL_V ON dbo.INVOICES_V.INVOICE_ID = dbo.INVOICE_PRE_TOTAL_V.INVOICE_ID

