CREATE VIEW dbo.RETURN_TO_JOB_MAD_V
AS
SELECT     TOP 100 PERCENT dbo.CHECKLIST_DATA.CHECKLIST_ID, dbo.CHECKLIST_DATA.DATA_NAME AS JOB_COMPLETED_ON_FIRST_TRIP, 
                      dbo.CHECKLIST_DATA.DATA_VALUE, dbo.REQUESTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, dbo.PROJECTS.JOB_NAME, 
                      dbo.CHECKLISTS.DATE_CREATED AS CHECKLIST_CREATED, dbo.PROJECTS.DATE_CREATED AS JOB_CREATED, 
                      dbo.CHECKLISTS.CREATED_BY AS CHECKLIST_CREATED_BY, dbo.CUSTOMERS.ORGANIZATION_ID
FROM         dbo.CHECKLIST_DATA INNER JOIN
                      dbo.CHECKLISTS ON dbo.CHECKLIST_DATA.CHECKLIST_ID = dbo.CHECKLISTS.CHECKLIST_ID INNER JOIN
                      dbo.REQUESTS ON dbo.CHECKLISTS.REQUEST_ID = dbo.REQUESTS.REQUEST_ID INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.PROJECTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID
WHERE     (dbo.CHECKLIST_DATA.DATA_NAME = '2') AND (dbo.CUSTOMERS.ORGANIZATION_ID = 2)
ORDER BY dbo.PROJECTS.PROJECT_NO

