CREATE VIEW dbo.crystal_dashboard_JOB_COSTING_V2
AS
SELECT     distinct CAST(dbo.JOBS_V.JOB_NO AS VARCHAR) AS job_no_varchar, dbo.RESOURCES_V.EXT_EMPLOYEE_ID, dbo.RESOURCES_V.USER_ID, 
                      dbo.JOBS_V.CUSTOMER_ID, dbo.JOBS_V.CUSTOMER_NAME, dbo.JOBS_V.JOB_NAME, dbo.RESOURCES_V.resource_name, 
                      dbo.RESOURCES_V.resource_type_name, dbo.RESOURCES_V.RESOURCE_TYPE_ID, dbo.ORGANIZATIONS.NAME AS Org_Name, 
                      dbo.ORGANIZATIONS.CODE AS Org_Code, dbo.ITEMS.COST_PER_UOM, dbo.SERVICE_LINES.ORGANIZATION_ID, dbo.SERVICE_LINES.TC_JOB_NO, 
                      dbo.SERVICE_LINES.TC_SERVICE_NO, dbo.SERVICE_LINES.TC_SERVICE_LINE_NO, dbo.SERVICE_LINES.ITEM_NAME, 
                      dbo.SERVICE_LINES.TC_JOB_ID, dbo.SERVICE_LINES.TC_SERVICE_ID, dbo.SERVICE_LINES.PH_SERVICE_ID, 
                      dbo.SERVICE_LINES.SERVICE_LINE_ID, dbo.SERVICE_LINES.SERVICE_LINE_DATE, dbo.SERVICE_LINES.STATUS_ID, 
                      dbo.SERVICE_LINES.RESOURCE_ID, dbo.SERVICE_LINES.ITEM_ID, dbo.SERVICE_LINES.TC_QTY, dbo.SERVICE_LINES.TC_RATE, 
                      dbo.SERVICE_LINES.tc_total, dbo.SERVICE_LINES.PAYROLL_QTY, dbo.SERVICE_LINES.EXT_PAY_CODE, dbo.ITEMS.COLUMN_POSITION, 
                      dbo.ITEMS.ITEM_TYPE_ID, dbo.JOBS_V.PROJECT_ID, dbo.SERVICE_LINES.bill_total, dbo.INVOICE_TOTALS_V.extended_price, 
                      dbo.INVOICE_TOTALS_V.custom_total, dbo.SERVICE_LINES.BILL_QTY, dbo.SERVICE_LINES.BILL_EXP_QTY, dbo.SERVICE_LINES.BILL_RATE, 
                      dbo.SERVICE_LINES.BILL_EXP_RATE, dbo.SERVICE_LINES.bill_exp_total, dbo.SERVICE_LINES.bill_hourly_total, dbo.SERVICE_LINES.expense_total, 
                      dbo.SERVICE_LINES.payroll_total, dbo.JOBS_V.job_type_name
FROM         dbo.SERVICE_LINES INNER JOIN
                      dbo.ORGANIZATIONS ON dbo.SERVICE_LINES.ORGANIZATION_ID = dbo.ORGANIZATIONS.ORGANIZATION_ID INNER JOIN
                      dbo.REQUESTS_V ON dbo.ORGANIZATIONS.ORGANIZATION_ID = dbo.REQUESTS_V.ORGANIZATION_ID LEFT OUTER JOIN
                      dbo.ITEMS ON dbo.SERVICE_LINES.ITEM_ID = dbo.ITEMS.ITEM_ID LEFT OUTER JOIN
                      dbo.INVOICE_TOTALS_V ON dbo.SERVICE_LINES.TC_JOB_ID = dbo.INVOICE_TOTALS_V.JOB_ID AND 
                      dbo.SERVICE_LINES.INVOICE_ID = dbo.INVOICE_TOTALS_V.INVOICE_ID LEFT OUTER JOIN
                      dbo.RESOURCES_V ON dbo.SERVICE_LINES.RESOURCE_ID = dbo.RESOURCES_V.RESOURCE_ID FULL OUTER JOIN
                      dbo.JOBS_V ON dbo.SERVICE_LINES.TC_JOB_ID = dbo.JOBS_V.JOB_ID



