CREATE VIEW dbo.crystal_JOB_STATUS_RPT_V
AS
SELECT     TOP 100 PERCENT dbo.SERVICE_LINES.ORGANIZATION_ID, dbo.SERVICE_LINES.TC_JOB_ID, dbo.SERVICE_LINES.TC_SERVICE_ID, 
                      dbo.SERVICE_LINES.SERVICE_LINE_ID, dbo.SERVICE_LINES.TC_JOB_NO, dbo.SERVICE_LINES.TC_SERVICE_NO, 
                      dbo.SERVICE_LINES.TC_SERVICE_LINE_NO, dbo.JOBS_V.DEALER_NAME, dbo.JOBS_V.EXT_DEALER_ID, dbo.JOBS_V.CUSTOMER_NAME, 
                      cast(dbo.JOBS_V.billing_user_name as varchar(20)) AS job_owner, dbo.JOBS_V.job_status_type_name, dbo.SERVICE_LINES.SERVICE_LINE_DATE, 
                      dbo.SERVICE_LINES.SERVICE_LINE_DATE_VARCHAR, dbo.SERVICE_LINES.STATUS_ID AS serv_line_status_id, dbo.SERVICE_LINES.BILLABLE_FLAG, 
                      SUM(dbo.SERVICE_LINES.TC_QTY) AS sum_tc_qty, SUM(dbo.SERVICE_LINES.ALLOCATED_QTY) AS sum_allocated_qty, 
                      dbo.SERVICE_LINES.TC_RATE, SUM(dbo.SERVICE_LINES.TC_TOTAL) AS sum_tc_total, SUM(dbo.SERVICE_LINES.BILL_QTY) AS sum_bill_qty, 
                      dbo.SERVICE_LINES.BILL_RATE, SUM(dbo.SERVICE_LINES.BILL_TOTAL) AS sum_bill_total, 
                      ISNULL(CAST(dbo.SERVICE_LINES.INVOICE_ID AS VARCHAR), 'None') AS invoice_no, GETDATE() AS report_date, MAX(dbo.SERVICES.EST_END_DATE) 
                      AS job_end_date, dbo.SERVICE_LINES.EXPORTED_FLAG, dbo.SERVICE_LINES.BILLED_FLAG, dbo.SERVICE_LINES.POSTED_FLAG, 
                      dbo.SERVICE_LINES.FULLY_ALLOCATED_FLAG, dbo.SERVICE_LINES.INTERNAL_REQ_FLAG, dbo.SERVICE_LINES.PH_SERVICE_ID, 
                      dbo.SERVICE_LINE_STATUSES.CODE
FROM         dbo.SERVICE_LINES INNER JOIN
                      dbo.SERVICE_LINE_STATUSES ON dbo.SERVICE_LINES.STATUS_ID = dbo.SERVICE_LINE_STATUSES.STATUS_ID LEFT OUTER JOIN
                      dbo.JOBS_V ON dbo.SERVICE_LINES.TC_JOB_ID = dbo.JOBS_V.JOB_ID LEFT OUTER JOIN
                      dbo.SERVICES ON dbo.SERVICE_LINES.PH_SERVICE_ID = dbo.SERVICES.SERVICE_ID AND 
                      dbo.SERVICE_LINES.TC_SERVICE_ID = dbo.SERVICES.SERVICE_ID AND dbo.SERVICE_LINES.BILL_SERVICE_ID = dbo.SERVICES.SERVICE_ID
GROUP BY dbo.SERVICE_LINES.ORGANIZATION_ID, dbo.SERVICE_LINES.SERVICE_LINE_ID, dbo.SERVICE_LINES.TC_JOB_ID, 
                      dbo.SERVICE_LINES.TC_SERVICE_ID, dbo.SERVICE_LINES.TC_JOB_NO, dbo.SERVICE_LINES.TC_SERVICE_NO, 
                      dbo.SERVICE_LINES.TC_SERVICE_LINE_NO, dbo.JOBS_V.DEALER_NAME, dbo.JOBS_V.EXT_DEALER_ID, dbo.JOBS_V.CUSTOMER_NAME, 
                      dbo.JOBS_V.billing_user_name, dbo.JOBS_V.job_status_type_name, dbo.SERVICE_LINES.SERVICE_LINE_DATE, 
                      dbo.SERVICE_LINES.SERVICE_LINE_DATE_VARCHAR, dbo.SERVICE_LINES.STATUS_ID, dbo.SERVICE_LINES.BILLABLE_FLAG, 
                      dbo.SERVICE_LINES.TC_RATE, ISNULL(CAST(dbo.SERVICE_LINES.INVOICE_ID AS VARCHAR), 'None'), dbo.SERVICE_LINES.INVOICE_ID, 
                      dbo.SERVICE_LINES.FULLY_ALLOCATED_FLAG, dbo.SERVICE_LINES.BILL_RATE, dbo.SERVICE_LINES.EXPORTED_FLAG, 
                      dbo.SERVICE_LINES.POSTED_FLAG, dbo.SERVICE_LINES.BILLED_FLAG, dbo.SERVICE_LINES.INTERNAL_REQ_FLAG, 
                      dbo.SERVICE_LINES.PH_SERVICE_ID, dbo.SERVICE_LINE_STATUSES.CODE
HAVING      (dbo.JOBS_V.CUSTOMER_NAME IS NOT NULL)


