CREATE VIEW dbo.crystal_MADISON_RPT1_V
AS
SELECT     dbo.REQUESTS.REQUEST_ID, dbo.REQUESTS.REQUEST_NO, dbo.REQUESTS.PROJECT_ID, dbo.SERVICES.SERVICE_ID, 
                      dbo.REQUESTS.DEALER_CUST_ID, dbo.REQUESTS.CUSTOMER_PO_NO, dbo.REQUESTS.DEALER_PO_NO, dbo.REQUESTS.DEALER_PO_LINE_NO, 
                      dbo.REQUESTS.DEALER_PROJECT_NO, dbo.REQUESTS.PUNCHLIST_ITEM_TYPE_ID, PUNCHLIST_ITEM_TYPE.CODE AS punchlist_item_type_code, 
                      PUNCHLIST_ITEM_TYPE.NAME AS punchlist_item_type_name, dbo.REQUESTS.PUNCHLIST_LINE, dbo.REQUESTS.PUNCHLIST_COMPLETE_DATE, 
                      dbo.PROJECTS_V.PROJECT_NO, CONVERT(varchar, dbo.PROJECTS_V.PROJECT_NO) + '-' + CONVERT(varchar, dbo.REQUESTS.REQUEST_NO) 
                      AS project_request_no, dbo.PROJECTS_V.CUSTOMER_ID, CUSTOMERS_1.ORGANIZATION_ID, CUSTOMERS_1.EXT_DEALER_ID, 
                      CUSTOMERS_1.DEALER_NAME, CUSTOMERS_1.EXT_CUSTOMER_ID, CUSTOMERS_1.CUSTOMER_NAME, dbo.PROJECTS_V.JOB_NAME, 
                      dbo.REQUESTS.EST_START_DATE
FROM         dbo.LOOKUPS DELIVERY_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS SITE_VISIT_REQ_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS WALL_MOUNT_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS SEC_FURN_LINE_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS PRI_FURN_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS REQUEST_STATUS_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS FURN_PLAN_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS ACCOUNT_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS WORKSTATION_TYPICAL_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS PUNCHLIST_ITEM_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS CASE_FURN_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS FURN_SPEC_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS CASE_FURN_LINE_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS WOOD_PRODUCT_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS SCHEDULE_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS APPROVAL_REQ_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS SERV_STATUS_TYPE RIGHT OUTER JOIN
                      dbo.SERVICES RIGHT OUTER JOIN
                      dbo.USERS USERS_1 RIGHT OUTER JOIN
                      dbo.USERS USERS_2 RIGHT OUTER JOIN
                      dbo.REQUESTS ON USERS_2.USER_ID = dbo.REQUESTS.MODIFIED_BY ON USERS_1.USER_ID = dbo.REQUESTS.CREATED_BY ON 
                      dbo.SERVICES.REQUEST_ID = dbo.REQUESTS.REQUEST_ID ON SERV_STATUS_TYPE.LOOKUP_ID = dbo.SERVICES.SERV_STATUS_TYPE_ID ON 
                      APPROVAL_REQ_TYPE.LOOKUP_ID = dbo.REQUESTS.APPROVAL_REQ_TYPE_ID ON 
                      SCHEDULE_TYPE.LOOKUP_ID = dbo.REQUESTS.SCHEDULE_TYPE_ID ON 
                      WOOD_PRODUCT_TYPE.LOOKUP_ID = dbo.REQUESTS.WOOD_PRODUCT_TYPE_ID ON 
                      CASE_FURN_LINE_TYPE.LOOKUP_ID = dbo.REQUESTS.CASE_FURN_LINE_TYPE_ID ON 
                      FURN_SPEC_TYPE.LOOKUP_ID = dbo.REQUESTS.FURN_SPEC_TYPE_ID ON 
                      CASE_FURN_TYPE.LOOKUP_ID = dbo.REQUESTS.CASE_FURN_TYPE_ID ON 
                      PUNCHLIST_ITEM_TYPE.LOOKUP_ID = dbo.REQUESTS.PUNCHLIST_ITEM_TYPE_ID ON 
                      WORKSTATION_TYPICAL_TYPE.LOOKUP_ID = dbo.REQUESTS.WORKSTATION_TYPICAL_TYPE_ID ON 
                      ACCOUNT_TYPE.LOOKUP_ID = dbo.REQUESTS.ACCOUNT_TYPE_ID ON FURN_PLAN_TYPE.LOOKUP_ID = dbo.REQUESTS.FURN_PLAN_TYPE_ID ON 
                      REQUEST_STATUS_TYPE.LOOKUP_ID = dbo.REQUESTS.REQUEST_STATUS_TYPE_ID ON 
                      PRI_FURN_TYPE.LOOKUP_ID = dbo.REQUESTS.PRI_FURN_TYPE_ID ON 
                      SEC_FURN_LINE_TYPE.LOOKUP_ID = dbo.REQUESTS.SEC_FURN_LINE_TYPE_ID LEFT OUTER JOIN
                      dbo.LOOKUPS REQUEST_TYPE ON dbo.REQUESTS.REQUEST_TYPE_ID = REQUEST_TYPE.LOOKUP_ID LEFT OUTER JOIN
                      dbo.LOOKUPS PRI_FURN_LINE_TYPE ON dbo.REQUEST
