CREATE VIEW dbo.RETURN_TO_JOB_RPT
AS
SELECT     dbo.CHECKLIST_DATA.CHECKLIST_ID, dbo.CHECKLIST_DATA.DATA_NAME AS JOB_COMPLETED_ON_FIRST_TRIP, 
                      dbo.CHECKLIST_DATA.DATA_VALUE, dbo.REQUESTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, dbo.PROJECTS.JOB_NAME, 
                      dbo.CHECKLISTS.DATE_CREATED AS CHECKLIST_CREATED, dbo.PROJECTS.DATE_CREATED AS JOB_CREATED, 
                      dbo.CHECKLISTS.CREATED_BY AS CHECKLIST_CREATED_BY
FROM         dbo.CHECKLIST_DATA INNER JOIN
                      dbo.CHECKLISTS ON dbo.CHECKLIST_DATA.CHECKLIST_ID = dbo.CHECKLISTS.CHECKLIST_ID INNER JOIN
                      dbo.REQUESTS ON dbo.CHECKLISTS.REQUEST_ID = dbo.REQUESTS.REQUEST_ID INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID
WHERE     (dbo.CHECKLIST_DATA.DATA_NAME = '2')

