CREATE VIEW dbo.crystal_pkf_quote_V
AS
SELECT     dbo.QUOTES.QUOTE_ID, dbo.QUOTES.QUOTE_NO, dbo.REQUESTS.PROJECT_ID, dbo.QUOTES.REQUEST_ID, dbo.QUOTES.IS_SENT, 
                      dbo.QUOTES.QUOTED_BY_USER_ID, dbo.QUOTES.DESCRIPTION, dbo.QUOTES.QUOTE_TOTAL, dbo.REQUESTS.DURATION_QTY, 
                      dbo.QUOTES.TAXABLE_FLAG, dbo.REQUESTS.CUST_COL_1, dbo.REQUESTS.CUST_COL_2, dbo.REQUESTS.CUST_COL_3, 
                      dbo.REQUESTS.CUST_COL_4, dbo.REQUESTS.CUST_COL_5, dbo.REQUESTS.CUST_COL_6, dbo.REQUESTS.CUST_COL_7, 
                      dbo.REQUESTS.CUST_COL_8, dbo.REQUESTS.CUST_COL_9, dbo.REQUESTS.CUST_COL_10, dbo.REQUESTS.CUSTOMER_PO_NO, 
                      dbo.REQUESTS.REQUEST_NO
FROM         dbo.QUOTES LEFT OUTER JOIN
                      dbo.REQUESTS ON dbo.QUOTES.REQUEST_ID = dbo.REQUESTS.REQUEST_ID
WHERE     (dbo.REQUESTS.PROJECT_ID = 22045)

