CREATE VIEW dbo.crystal_Job_Cost_V
AS
SELECT     dbo.JOB_TIME_BY_EMP_V.ORGANIZATION_ID, dbo.JOB_TIME_BY_EMP_V.TC_JOB_NO, dbo.JOB_TIME_BY_EMP_V.JOB_NAME, 
                      dbo.JOB_TIME_BY_EMP_V.SERVICE_LINE_DATE, dbo.JOB_TIME_BY_EMP_V.resource_name, dbo.JOB_TIME_BY_EMP_V.EXT_EMPLOYEE_ID, 
                      dbo.JOB_TIME_BY_EMP_V.ITEM_NAME, dbo.JOB_TIME_BY_EMP_V.PAYROLL_QTY, dbo.JOB_TIME_BY_EMP_V.PAYROLL_RATE, 
                      dbo.JOB_TIME_BY_EMP_V.PAYROLL_TOTAL, AMBIM.dbo.UPR00400.PAYRTAMT, dbo.JOB_TIME_BY_EMP_V.SERVICE_LINE_ID, 
                      AMBIM.dbo.UPR00400.PAYRCORD
FROM         dbo.JOB_TIME_BY_EMP_V FULL OUTER JOIN
                      AMBIM.dbo.UPR00400 ON dbo.JOB_TIME_BY_EMP_V.EXT_EMPLOYEE_ID <= AMBIM.dbo.UPR00400.EMPLOYID

