CREATE VIEW dbo.crystal_csc_routing_ticket_v
AS
SELECT     dbo.REQUESTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, dbo.REQUESTS.REQUEST_NO, dbo.REQUESTS.PRIORITY_TYPE_ID, 
                      LOOKUPS_1.NAME AS PRIORITY, dbo.REQUESTS.CUSTOMER_PO_NO, dbo.REQUESTS.LEVEL_TYPE_ID, 
                      dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID, dbo.CONTACTS.CONTACT_NAME AS VENDOR_NAME, dbo.REQUEST_VENDORS.EMAILED_DATE, 
                      dbo.REQUEST_VENDORS.SCH_START_DATE, dbo.REQUEST_VENDORS.SCH_START_TIME, dbo.REQUEST_VENDORS.SCH_END_DATE, 
                      dbo.REQUEST_VENDORS.ACT_START_DATE, dbo.REQUEST_VENDORS.ACT_START_TIME, dbo.REQUEST_VENDORS.ACT_END_DATE, 
                      dbo.REQUESTS.EST_START_DATE, dbo.REQUEST_VENDORS.ESTIMATED_COST, dbo.REQUEST_VENDORS.TOTAL_COST, 
                      dbo.REQUEST_VENDORS.INVOICE_DATE, dbo.REQUEST_VENDORS.INVOICE_NUMBERS, dbo.REQUEST_VENDORS.VISIT_COUNT, 
                      dbo.REQUEST_VENDORS.COMPLETE_FLAG, dbo.REQUEST_VENDORS.INVOICED_FLAG, dbo.PROJECTS.JOB_NAME, LOOKUPS_1.NAME AS ACTIVITY, 
                      dbo.REQUESTS.QTY1, LOOKUPS_2.NAME AS CATEGORY, dbo.REQUESTS.CUST_COL_1, dbo.REQUESTS.CUST_COL_2, dbo.REQUESTS.CUST_COL_3, 
                      dbo.REQUESTS.CUST_COL_4, dbo.REQUESTS.CUST_COL_5, dbo.REQUESTS.CUST_COL_6, dbo.REQUESTS.CUST_COL_7, 
                      dbo.REQUESTS.CUST_COL_8, dbo.REQUESTS.CUST_COL_9, dbo.REQUESTS.CUST_COL_10
FROM         dbo.REQUEST_VENDORS INNER JOIN
                      dbo.REQUESTS ON dbo.REQUEST_VENDORS.REQUEST_ID = dbo.REQUESTS.REQUEST_ID INNER JOIN
                      dbo.CONTACTS ON dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID = dbo.CONTACTS.CONTACT_ID INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_1 ON dbo.REQUESTS.ACTIVITY_TYPE_ID1 = LOOKUPS_1.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_2 ON dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID1 = LOOKUPS_2.LOOKUP_ID INNER JOIN
                      dbo.SCH_RESOURCES_ALL_V ON dbo.REQUESTS.PROJECT_ID = dbo.SCH_RESOURCES_ALL_V.JOB_ID LEFT OUTER JOIN
                      dbo.LOOKUPS LOOKUPS_3 ON dbo.REQUESTS.PRIORITY_TYPE_ID = LOOKUPS_3.LOOKUP_ID

