CREATE VIEW dbo.crystal_SYNCH_REPORT_V
AS
SELECT     TOP 100 PERCENT FULL_NAME, IMOBILE_LOGIN, LAST_SYNCH_DATE, LAST_LOGIN AS LAST_SERVICETRAX_LOGIN
FROM         dbo.USERS
WHERE     (LAST_SYNCH_DATE IS NOT NULL) AND (ACTIVE_FLAG = 'Y') AND (IMOBILE_LOGIN IS NOT NULL)
ORDER BY FULL_NAME

