CREATE VIEW dbo.crystal_JOBS_CLOSED_V
AS
SELECT     TOP 100 PERCENT dbo.JOBS.JOB_ID, dbo.JOBS.PROJECT_ID, dbo.JOBS.JOB_NO, dbo.JOBS.JOB_NAME, dbo.JOBS.JOB_TYPE_ID, 
                      dbo.JOBS.JOB_STATUS_TYPE_ID, dbo.JOBS.CUSTOMER_ID, dbo.CUSTOMERS.ORGANIZATION_ID, dbo.CUSTOMERS.DEALER_NAME, 
                      dbo.CUSTOMERS.CUSTOMER_NAME, dbo.LOOKUPS.NAME
FROM         dbo.JOBS INNER JOIN
                      dbo.CUSTOMERS ON dbo.JOBS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.LOOKUPS ON dbo.JOBS.JOB_STATUS_TYPE_ID = dbo.LOOKUPS.LOOKUP_ID
WHERE     (dbo.CUSTOMERS.ORGANIZATION_ID = 11) AND (dbo.JOBS.JOB_STATUS_TYPE_ID = 115)
ORDER BY dbo.JOBS.JOB_NO

