CREATE VIEW dbo.crystal_SCH_ACT_2_V
AS
SELECT     TC_JOB_NO, TC_SERVICE_NO, SERVICE_LINE_DATE, RESOURCE_ID, RESOURCE_NAME, ITEM_NAME, TC_QTY, OVERRIDE_DATE, VERIFIED_DATE, 
                      VERIFIED_BY, SERVICE_LINE_ID, TC_SERVICE_ID
FROM         dbo.SERVICE_LINES

