CREATE VIEW dbo.crystal_WPS_Timesheet_V
AS
SELECT     dbo.SERVICE_LINES.ORGANIZATION_ID, dbo.SERVICE_LINES.SERVICE_LINE_ID, dbo.SERVICE_LINES.TC_JOB_NO, 
                      dbo.SERVICE_LINES.TC_SERVICE_NO, dbo.SERVICE_LINES.TC_SERVICE_LINE_NO, dbo.SERVICE_LINES.SERVICE_LINE_DATE, 
                      dbo.SERVICE_LINES.STATUS_ID, dbo.SERVICE_LINES.TC_JOB_ID, dbo.SERVICE_LINES.TC_SERVICE_ID, dbo.SERVICE_LINES.RESOURCE_ID, 
                      dbo.SERVICE_LINES.RESOURCE_NAME, dbo.SERVICE_LINES.ITEM_ID, dbo.SERVICE_LINES.ITEM_NAME, dbo.SERVICE_LINES.TC_QTY, 
                      dbo.SERVICE_LINES.TC_RATE, dbo.SERVICE_LINES.TC_TOTAL, dbo.SERVICE_LINES.PALM_REP_ID, dbo.SERVICE_LINES.ENTERED_DATE, 
                      dbo.SERVICE_LINES.ENTERED_BY, dbo.SERVICE_LINES.ENTRY_METHOD, dbo.SERVICE_LINES.VERIFIED_DATE, 
                      dbo.SERVICE_LINES.VERIFIED_BY, dbo.SERVICE_LINES.DATE_CREATED, dbo.SERVICE_LINES.CREATED_BY, dbo.SERVICE_LINES.DATE_MODIFIED, 
                      dbo.SERVICE_LINES.MODIFIED_BY, dbo.SERVICES.DESCRIPTION
FROM         dbo.SERVICE_LINES INNER JOIN
                      dbo.SERVICES ON dbo.SERVICE_LINES.TC_SERVICE_ID = dbo.SERVICES.SERVICE_ID AND 
                      dbo.SERVICE_LINES.TC_JOB_ID = dbo.SERVICES.JOB_ID
WHERE     (dbo.SERVICE_LINES.VERIFIED_BY IS NULL) AND (dbo.SERVICE_LINES.DATE_CREATED > CONVERT(DATETIME, '2004-01-01 00:00:00', 102))

