CREATE VIEW dbo.crystal_GRACO_REPORT_V
AS
SELECT     TOP 100 PERCENT dbo.SERVICE_LINES.BILL_JOB_NO AS JOB_NO, dbo.SERVICES.PO_NO AS PO, dbo.SERVICE_LINES.BILL_SERVICE_NO AS Req, 
                      dbo.SERVICE_LINES.SERVICE_LINE_DATE, dbo.SERVICE_LINES.RESOURCE_NAME, dbo.SERVICE_LINES.ITEM_NAME, 
                      dbo.SERVICE_LINES.BILL_QTY
FROM         dbo.SERVICE_LINES INNER JOIN
                      dbo.SERVICES ON dbo.SERVICE_LINES.TC_SERVICE_ID = dbo.SERVICES.SERVICE_ID
WHERE     (dbo.SERVICE_LINES.RESOURCE_NAME IS NOT NULL) AND (dbo.SERVICE_LINES.BILL_JOB_NO = 392055)
ORDER BY dbo.SERVICE_LINES.RESOURCE_NAME



