CREATE VIEW dbo.VAR_TIME_EXP_CRYSTAL_V
AS
SELECT     TOP 100 PERCENT TC_JOB_ID AS job_id, SUM(ISNULL(TC_QTY * BILL_RATE, 0)) AS sum_time_exp, SUM(ISNULL(PAYROLL_QTY * BILL_RATE, 0)) 
                      AS sum_time, SUM(ISNULL(EXPENSE_QTY * BILL_RATE, 0)) AS sum_exp
FROM         dbo.TIME_CAPTURE_V
GROUP BY TC_JOB_ID, PH_SERVICE_ID
HAVING      (PH_SERVICE_ID IS NULL)
ORDER BY TC_JOB_ID

