CREATE VIEW dbo.crystal_dashboard_REQUEST_SENT_V
AS
SELECT     dbo.REQUESTS.REQUEST_ID, dbo.REQUESTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, dbo.PROJECTS.JOB_NAME, 
                      dbo.REQUESTS.REQUEST_NO, dbo.REQUESTS.VERSION_NO, dbo.REQUESTS.REQUEST_TYPE_ID, dbo.REQUESTS.REQUEST_STATUS_TYPE_ID, 
                      dbo.REQUESTS.IS_SENT, dbo.REQUESTS.EST_START_DATE, dbo.REQUESTS.EST_END_DATE, dbo.REQUESTS.DESCRIPTION, 
                      dbo.REQUESTS.DATE_CREATED, dbo.CUSTOMERS.ORGANIZATION_ID, dbo.CUSTOMERS.EXT_DEALER_ID, 
                      dbo.ORGANIZATIONS.NAME AS Org_Name, dbo.REQUESTS.IS_SENT_DATE AS Req_Sent_Date
FROM         dbo.REQUESTS INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.PROJECTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.ORGANIZATIONS ON dbo.CUSTOMERS.ORGANIZATION_ID = dbo.ORGANIZATIONS.ORGANIZATION_ID

