CREATE VIEW dbo.crystal_TARGET_REPORT1_V
AS
SELECT     TOP 100 PERCENT dbo.SERVICE_LINES.BILL_JOB_NO AS JOB_NO, dbo.SERVICE_LINES.BILL_SERVICE_NO AS Req, 
                      dbo.SERVICE_LINES.SERVICE_LINE_DATE, dbo.SERVICE_LINES.RESOURCE_NAME, dbo.SERVICE_LINES.ITEM_NAME, 
                      dbo.SERVICE_LINES.BILL_QTY, dbo.SERVICES.DESCRIPTION, dbo.SERVICE_LINES.BILL_RATE, dbo.SERVICE_LINES.bill_total, 
                      dbo.SERVICE_LINES.ORGANIZATION_ID, dbo.SERVICES.CUST_COL_6
FROM         dbo.SERVICE_LINES INNER JOIN
                      dbo.SERVICES ON dbo.SERVICE_LINES.TC_SERVICE_ID = dbo.SERVICES.SERVICE_ID
WHERE     (dbo.SERVICE_LINES.RESOURCE_NAME IS NOT NULL) AND (dbo.SERVICE_LINES.BILL_JOB_NO = 791700) OR
                      (dbo.SERVICE_LINES.BILL_JOB_NO = 891700) OR
                      (dbo.SERVICE_LINES.BILL_JOB_NO = 991700)
ORDER BY dbo.SERVICE_LINES.RESOURCE_NAME

