/* original view
 ALTER  VIEW dbo.crystal_csc_WORK_ORDER_MASTER_V
 AS
 SELECT     dbo.REQUESTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, dbo.REQUESTS.REQUEST_NO, dbo.REQUESTS.PRIORITY_TYPE_ID, 
                       LOOKUPS_1.NAME AS PRIORITY, dbo.REQUESTS.LEVEL_TYPE_ID, dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID, 
                       dbo.CONTACTS.CONTACT_NAME AS VENDOR_NAME, dbo.REQUEST_VENDORS.EMAILED_DATE, dbo.REQUEST_VENDORS.SCH_START_DATE, 
                       dbo.REQUEST_VENDORS.SCH_START_TIME, dbo.REQUEST_VENDORS.SCH_END_DATE, dbo.REQUEST_VENDORS.ACT_START_DATE, 
                       dbo.REQUEST_VENDORS.ACT_START_TIME, dbo.REQUEST_VENDORS.ACT_END_DATE, dbo.REQUEST_VENDORS.ESTIMATED_COST, 
                       dbo.REQUEST_VENDORS.TOTAL_COST, dbo.REQUEST_VENDORS.INVOICE_DATE, dbo.REQUEST_VENDORS.INVOICE_NUMBERS, 
                       dbo.REQUEST_VENDORS.VISIT_COUNT, dbo.REQUEST_VENDORS.COMPLETE_FLAG, dbo.REQUEST_VENDORS.INVOICED_FLAG, 
                       dbo.PROJECTS.JOB_NAME, LOOKUPS_1.NAME AS ACTIVITY, dbo.REQUESTS.QTY1, LOOKUPS_2.NAME AS CATEGORY
 FROM         dbo.REQUEST_VENDORS INNER JOIN
                       dbo.REQUESTS ON dbo.REQUEST_VENDORS.REQUEST_ID = dbo.REQUESTS.REQUEST_ID INNER JOIN
                       dbo.CONTACTS ON dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID = dbo.CONTACTS.CONTACT_ID INNER JOIN
                       dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                       dbo.LOOKUPS LOOKUPS_1 ON dbo.REQUESTS.ACTIVITY_TYPE_ID1 = LOOKUPS_1.LOOKUP_ID INNER JOIN
                       dbo.LOOKUPS LOOKUPS_2 ON dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID1 = LOOKUPS_2.LOOKUP_ID LEFT OUTER JOIN
                       dbo.LOOKUPS LOOKUPS_3 ON dbo.REQUESTS.PRIORITY_TYPE_ID = LOOKUPS_3.LOOKUP_ID
 
 GO*/
CREATE VIEW dbo.crystal_csc_WORK_ORDER_MASTER_V
AS
SELECT     dbo.REQUESTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, dbo.REQUESTS.REQUEST_NO, dbo.REQUESTS.PRIORITY_TYPE_ID, 
                      LOOKUPS_1.NAME AS PRIORITY, dbo.REQUESTS.LEVEL_TYPE_ID, dbo.REQUESTS.WORK_ORDER_RECEIVED_DATE, 
                      dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID, dbo.CONTACTS.CONTACT_NAME AS VENDOR_NAME, dbo.REQUEST_VENDORS.EMAILED_DATE, 
                      dbo.REQUEST_VENDORS.SCH_START_DATE, dbo.REQUEST_VENDORS.SCH_START_TIME, dbo.REQUEST_VENDORS.SCH_END_DATE, 
                      dbo.REQUEST_VENDORS.ACT_START_DATE, dbo.REQUEST_VENDORS.ACT_START_TIME, dbo.REQUEST_VENDORS.ACT_END_DATE, 
                      dbo.REQUEST_VENDORS.ESTIMATED_COST, dbo.REQUEST_VENDORS.TOTAL_COST, dbo.REQUEST_VENDORS.INVOICE_DATE, 
                      dbo.REQUEST_VENDORS.INVOICE_NUMBERS, dbo.REQUEST_VENDORS.VISIT_COUNT, dbo.REQUEST_VENDORS.COMPLETE_FLAG, 
                      dbo.REQUEST_VENDORS.INVOICED_FLAG, dbo.PROJECTS.JOB_NAME, LOOKUPS_1.NAME AS ACTIVITY, dbo.REQUESTS.QTY1, 
                      LOOKUPS_2.NAME AS CATEGORY, dbo.REQUESTS.REQUEST_STATUS_TYPE_ID, dbo.REQUESTS.CUSTOMER_PO_NO, 
                      dbo.REQUESTS.DESCRIPTION, dbo.CUSTOMERS.CUSTOMER_NAME, dbo.REQUESTS.IS_SENT_DATE
FROM         dbo.REQUEST_VENDORS INNER JOIN
                      dbo.REQUESTS ON dbo.REQUEST_VENDORS.REQUEST_ID = dbo.REQUESTS.REQUEST_ID INNER JOIN
                      dbo.CONTACTS ON dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID = dbo.CONTACTS.CONTACT_ID INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_1 ON dbo.REQUESTS.ACTIVITY_TYPE_ID1 = LOOKUPS_1.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_2 ON dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID1 = LOOKUPS_2.LOOKUP_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.CONTACTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID AND 
                      dbo.PROJECTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID LEFT OUTER JOIN
                      dbo.LOOKUPS LOOKUPS_3 ON dbo.REQUESTS.PRIORITY_TYPE_ID = LOOKUPS_3.LOOKUP_ID

