CREATE VIEW dbo.EMPLOYEES_V
AS
SELECT     dbo.RESOURCES.ORGANIZATION_ID, dbo.RESOURCES.RESOURCE_ID, dbo.RESOURCES.NAME, dbo.RESOURCES.RES_CATEGORY_TYPE_ID, 
                      RES_CATEGORY_TYPE.CODE AS res_cat_type_code, RES_CATEGORY_TYPE.NAME AS res_cat_type_name, dbo.RESOURCES.RESOURCE_TYPE_ID, 
                      RESOURCE_TYPE.CODE AS resource_type_code, RESOURCE_TYPE.NAME AS resource_type_name, dbo.RESOURCES.USER_ID, 
                      dbo.USERS.FIRST_NAME, dbo.USERS.LAST_NAME, dbo.USERS.EXT_EMPLOYEE_ID, dbo.USERS.EMPLOYMENT_TYPE_ID, 
                      EMPLOYEMENT_TYPE.CODE AS employement_type_code, EMPLOYEMENT_TYPE.NAME AS employement_type_name, dbo.USERS.PIN, 
                      dbo.USERS.ACTIVE_FLAG
FROM         dbo.RESOURCES INNER JOIN
                      dbo.USERS ON dbo.RESOURCES.USER_ID = dbo.USERS.USER_ID LEFT OUTER JOIN
                      dbo.LOOKUPS EMPLOYEMENT_TYPE ON dbo.USERS.EMPLOYMENT_TYPE_ID = EMPLOYEMENT_TYPE.LOOKUP_ID LEFT OUTER JOIN
                      dbo.LOOKUPS RESOURCE_TYPE ON dbo.RESOURCES.RESOURCE_TYPE_ID = RESOURCE_TYPE.LOOKUP_ID LEFT OUTER JOIN
                      dbo.LOOKUPS RES_CATEGORY_TYPE ON dbo.RESOURCES.RES_CATEGORY_TYPE_ID = RES_CATEGORY_TYPE.LOOKUP_ID


