CREATE VIEW dbo.EXPENSES_V
AS
SELECT     dbo.SERVICE_LINES.ORGANIZATION_ID, dbo.SERVICE_LINES.SERVICE_LINE_ID, dbo.SERVICE_LINES.TC_JOB_ID, dbo.SERVICE_LINES.TC_JOB_NO, 
                      dbo.SERVICE_LINES.TC_SERVICE_LINE_NO, dbo.SERVICE_LINES.SERVICE_LINE_DATE, dbo.SERVICE_LINES.SERVICE_LINE_DATE_VARCHAR, 
                      dbo.SERVICE_LINES.SERVICE_LINE_WEEK, dbo.SERVICE_LINES.SERVICE_LINE_WEEK_VARCHAR, dbo.SERVICE_LINES.EXPENSE_QTY, 
                      dbo.SERVICE_LINES.EXPENSE_RATE, dbo.SERVICE_LINES.EXPENSE_TOTAL, dbo.SERVICE_LINES.ITEM_ID, dbo.SERVICE_LINES.ITEM_NAME, 
                      dbo.SERVICE_LINES.ITEM_TYPE_CODE, dbo.ITEMS.EXT_ITEM_ID, dbo.USERS.EXT_EMPLOYEE_ID, dbo.USERS.FULL_NAME AS employee_name, 
                      dbo.SERVICE_LINES.EXPENSES_EXPORTED_FLAG, dbo.ITEMS.EXPENSE_EXPORT_CODE, dbo.RESOURCES.USER_ID, 
                      dbo.RESOURCES.NAME AS resource_name, dbo.SERVICE_LINES.STATUS_ID
FROM         dbo.SERVICE_LINES LEFT OUTER JOIN
                      dbo.USERS RIGHT OUTER JOIN
                      dbo.RESOURCES ON dbo.USERS.USER_ID = dbo.RESOURCES.USER_ID ON 
                      dbo.SERVICE_LINES.RESOURCE_ID = dbo.RESOURCES.RESOURCE_ID LEFT OUTER JOIN
                      dbo.ITEMS ON dbo.SERVICE_LINES.ITEM_ID = dbo.ITEMS.ITEM_ID
WHERE     (dbo.SERVICE_LINES.STATUS_ID > 1) AND (dbo.SERVICE_LINES.EXPENSE_QTY > 0) AND (dbo.SERVICE_LINES.ITEM_TYPE_CODE = 'expense') AND 
                      (dbo.ITEMS.EXPENSE_EXPORT_CODE IS NOT NULL AND dbo.ITEMS.EXPENSE_EXPORT_CODE <> '')

