CREATE VIEW dbo.EXPENSES_EXPORT_V
AS
SELECT     ORGANIZATION_ID, SERVICE_LINE_ID, TC_JOB_ID, TC_JOB_NO, TC_SERVICE_LINE_NO, SERVICE_LINE_DATE, SERVICE_LINE_DATE_VARCHAR, 
                      SERVICE_LINE_WEEK, SERVICE_LINE_WEEK_VARCHAR, EXPENSE_QTY, EXPENSE_RATE, EXPENSE_TOTAL, ITEM_ID, ITEM_NAME, 
                      ITEM_TYPE_CODE, EXT_ITEM_ID, EXT_EMPLOYEE_ID, employee_name, EXPENSES_EXPORTED_FLAG, EXPENSE_EXPORT_CODE, USER_ID, 
                      resource_name, STATUS_ID
FROM         dbo.EXPENSES_V
WHERE     (USER_ID IS NOT NULL) AND (EXPENSE_EXPORT_CODE IS NOT NULL) OR
                      (USER_ID IS NOT NULL) AND (EXPENSE_EXPORT_CODE <> '')

