CREATE VIEW dbo.Expense_Report_for_Sandy
AS
SELECT     ORGANIZATION_ID, SERVICE_LINE_ID, TC_JOB_NO, TC_SERVICE_NO, TC_SERVICE_LINE_NO, SERVICE_LINE_DATE, STATUS_ID, RESOURCE_NAME,
                       ITEM_NAME, ITEM_TYPE_CODE, TAXABLE_FLAG, BILLABLE_FLAG, EXPENSE_QTY, EXPENSE_RATE, EXPENSE_TOTAL
FROM         dbo.SERVICE_LINES
WHERE     (ITEM_TYPE_CODE = 'expense') AND (ORGANIZATION_ID = 2) AND (SERVICE_LINE_DATE >= CONVERT(DATETIME, '2005-09-18 00:00:00', 102))

