CREATE VIEW dbo.EXPENSE_REPORT_V
AS
SELECT     dbo.EXPENSES_V.ORGANIZATION_ID, dbo.EXPENSES_V.TC_JOB_NO, dbo.JOBS_V.JOB_NAME, dbo.EXPENSES_V.item_name, 
                      dbo.EXPENSES_V.SERVICE_LINE_DATE, dbo.EXPENSES_V.EXPENSE_QTY, dbo.EXPENSES_V.EXPENSE_RATE, dbo.EXPENSES_V.EXPENSE_TOTAL, 
                      dbo.EXPENSES_V.EXPENSES_EXPORTED_FLAG, dbo.EXPENSES_V.TC_JOB_ID, dbo.EXPENSES_V.ITEM_ID, dbo.EXPENSES_V.item_type_code, 
                      dbo.EXPENSES_V.USER_ID, dbo.EXPENSES_V.EXT_EMPLOYEE_ID, dbo.EXPENSES_V.employee_name
FROM         dbo.JOBS_V RIGHT OUTER JOIN
                      dbo.EXPENSES_V ON dbo.JOBS_V.JOB_ID = dbo.EXPENSES_V.TC_JOB_ID




