CREATE VIEW dbo.EXPENSES_BATCHES_V
AS
SELECT     dbo.EXPENSES_BATCHES.ORGANIZATION_ID, dbo.SERVICE_LINES.TC_JOB_ID, dbo.SERVICE_LINES.TC_JOB_NO, 
                      dbo.SERVICE_LINES.TC_SERVICE_NO, dbo.SERVICE_LINES.TC_SERVICE_LINE_NO, dbo.EXPENSES_BATCHES.INT_BATCH_ID, 
                      dbo.EXPENSES_BATCHES.EXT_BATCH_ID, dbo.EXPENSES_BATCHES.BEGIN_DATE, dbo.EXPENSES_BATCHES.END_DATE, CONVERT(varchar(12), 
                      dbo.EXPENSES_BATCHES.BEGIN_DATE, 101) AS begin_date_varchar, CONVERT(varchar(12), dbo.EXPENSES_BATCHES.END_DATE, 101) 
                      AS end_date_varchar, CONVERT(varchar(12), dbo.EXPENSES_BATCHES.DATE_CREATED, 101) AS date_created_varchar, 
                      dbo.EXPENSES_BATCH_LINES.SERVICE_LINE_ID, dbo.SERVICE_LINES.EXPENSE_QTY, dbo.SERVICE_LINES.EXPENSE_RATE, 
                      dbo.SERVICE_LINES.EXPENSE_TOTAL, dbo.SERVICE_LINES.ITEM_NAME, dbo.ITEMS.EXT_ITEM_ID, dbo.RESOURCES.USER_ID, 
                      dbo.USERS.EXT_EMPLOYEE_ID, dbo.USERS.FULL_NAME AS employee_name, dbo.EXPENSES_BATCHES.EXPENSES_BATCH_STATUS_TYPE_ID, 
                      dbo.LOOKUPS.CODE AS expenses_batch_status_type_code, dbo.LOOKUPS.NAME AS expenses_batch_status_type_name, 
                      dbo.SERVICE_LINES.SERVICE_LINE_DATE, dbo.SERVICE_LINES.SERVICE_LINE_DATE_VARCHAR, dbo.SERVICE_LINES.SERVICE_LINE_WEEK, 
                      dbo.SERVICE_LINES.SERVICE_LINE_WEEK_VARCHAR, dbo.ITEMS.EXPENSE_EXPORT_CODE
FROM         dbo.USERS RIGHT OUTER JOIN
                      dbo.RESOURCES RIGHT OUTER JOIN
                      dbo.LOOKUPS RIGHT OUTER JOIN
                      dbo.EXPENSES_BATCHES LEFT OUTER JOIN
                      dbo.ITEMS RIGHT OUTER JOIN
                      dbo.EXPENSES_BATCH_LINES LEFT OUTER JOIN
                      dbo.SERVICE_LINES ON dbo.EXPENSES_BATCH_LINES.SERVICE_LINE_ID = dbo.SERVICE_LINES.SERVICE_LINE_ID ON 
                      dbo.ITEMS.ITEM_ID = dbo.SERVICE_LINES.ITEM_ID ON dbo.EXPENSES_BATCHES.INT_BATCH_ID = dbo.EXPENSES_BATCH_LINES.INT_BATCH_ID ON
                       dbo.LOOKUPS.LOOKUP_ID = dbo.EXPENSES_BATCHES.EXPENSES_BATCH_STATUS_TYPE_ID ON 
                      dbo.RESOURCES.RESOURCE_ID = dbo.SERVICE_LINES.RESOURCE_ID ON dbo.USERS.USER_ID = dbo.RESOURCES.USER_ID

