CREATE VIEW FAILED_INTEGRATIONS AS
/* All company database results of batches that have not went over to great plains.  Checked on SOP10200 and SOP30200 table
based on SOPNUMBE field, where the beginning X # of digits definied by datalength() is the invoice ID from servicetrax
that is transfered to Great Plains */
SELECT     INVOICES.INVOICE_ID, INVOICES.ORGANIZATION_ID, INVOICES.PO_NO, INVOICES.INVOICE_TYPE_ID, INVOICES.BILLING_TYPE_ID, 
                      INVOICES.EXT_BATCH_ID, INVOICES.BATCH_STATUS_ID, INVOICES.ASSIGNED_TO_USER_ID, INVOICES.INVOICE_FORMAT_TYPE_ID, 
                      INVOICES.EXT_INVOICE_ID, INVOICES.STATUS_ID, INVOICES.JOB_ID, INVOICES.DESCRIPTION, INVOICES.GP_DESCRIPTION, INVOICES.COST_CODES,
                       INVOICES.START_DATE, INVOICES.END_DATE, INVOICES.BILL_CUSTOMER_ID, INVOICES.EXT_BILL_CUST_ID, INVOICES.SALES_REPS, 
                      INVOICES.DATE_SENT, INVOICES.DATE_CREATED, INVOICES.CREATED_BY, INVOICES.DATE_MODIFIED, INVOICES.MODIFIED_BY,NAME
FROM         INVOICES 
inner join organizations on invoices.organization_id=organizations.organization_id
WHERE     (INVOICES.BATCH_STATUS_ID = '-1') AND cast(INVOICES.INVOICE_ID as varchar(10)) NOT IN (SELECT LEFT(SOPNUMBE,datalength(INVOICES.INVOICE_ID)) FROM AMBIM..SOP10200)
and cast(INVOICES.INVOICE_ID as varchar(10)) NOT IN (SELECT LEFT(SOPNUMBE,datalength(INVOICES.INVOICE_ID)) FROM AMBIM..SOP30200)
and INVOICES.ORGANIZATION_ID=2
OR
                      (dbo.INVOICES.BATCH_STATUS_ID = 1) AND (dbo.INVOICES.STATUS_ID = 4)
union all
SELECT     INVOICES.INVOICE_ID, INVOICES.ORGANIZATION_ID, INVOICES.PO_NO, INVOICES.INVOICE_TYPE_ID, INVOICES.BILLING_TYPE_ID, 
                      INVOICES.EXT_BATCH_ID, INVOICES.BATCH_STATUS_ID, INVOICES.ASSIGNED_TO_USER_ID, INVOICES.INVOICE_FORMAT_TYPE_ID, 
                      INVOICES.EXT_INVOICE_ID, INVOICES.STATUS_ID, INVOICES.JOB_ID, INVOICES.DESCRIPTION, INVOICES.GP_DESCRIPTION, INVOICES.COST_CODES,
                       INVOICES.START_DATE, INVOICES.END_DATE, INVOICES.BILL_CUSTOMER_ID, INVOICES.EXT_BILL_CUST_ID, INVOICES.SALES_REPS, 
                      INVOICES.DATE_SENT, INVOICES.DATE_CREATED, INVOICES.CREATED_BY, INVOICES.DATE_MODIFIED, INVOICES.MODIFIED_BY,NAME
FROM         INVOICES 
inner join organizations on invoices.organization_id=organizations.organization_id
WHERE     (INVOICES.BATCH_STATUS_ID = '-1') AND cast(INVOICES.INVOICE_ID as varchar(10)) NOT IN (SELECT LEFT(SOPNUMBE,datalength(INVOICES.INVOICE_ID)) FROM AMMAD..SOP10200)
and cast(INVOICES.INVOICE_ID as varchar(10)) NOT IN (SELECT LEFT(SOPNUMBE,datalength(INVOICES.INVOICE_ID)) FROM AMMAD..SOP30200)
and INVOICES.ORGANIZATION_ID=4
OR
                      (dbo.INVOICES.BATCH_STATUS_ID = 1)  AND (dbo.INVOICES.STATUS_ID = 4)
union all
SELECT     INVOICES.INVOICE_ID, INVOICES.ORGANIZATION_ID, INVOICES.PO_NO, INVOICES.INVOICE_TYPE_ID, INVOICES.BILLING_TYPE_ID, 
                      INVOICES.EXT_BATCH_ID, INVOICES.BATCH_STATUS_ID, INVOICES.ASSIGNED_TO_USER_ID, INVOICES.INVOICE_FORMAT_TYPE_ID, 
                      INVOICES.EXT_INVOICE_ID, INVOICES.STATUS_ID, INVOICES.JOB_ID, INVOICES.DESCRIPTION, INVOICES.GP_DESCRIPTION, INVOICES.COST_CODES,
                       INVOICES.START_DATE, INVOICES.END_DATE, INVOICES.BILL_CUSTOMER_ID, INVOICES.EXT_BILL_CUST_ID, INVOICES.SALES_REPS, 
                      INVOICES.DATE_SENT, INVOICES.DATE_CREATED, INVOICES.CREATED_BY, INVOICES.DATE_MODIFIED, INVOICES.MODIFIED_BY,NAME
FROM         INVOICES 
inner join organizations on invoices.organization_id=organizations.organization_id
WHERE     (INVOICES.BATCH_STATUS_ID = '-1') AND cast(INVOICES.INVOICE_ID as varchar(10)) NOT IN (SELECT LEFT(SOPNUMBE,datalength(INVOICES.INVOICE_ID)) FROM AIA..SOP10200)
and cast(INVOICES.INVOICE_ID as varchar(10)) NOT IN (SELECT LEFT(SOPNUMBE,datalength(INVOICES.INVOICE_ID)) FROM AIA..SOP30200)
and INVOICES.ORGANIZATION_ID=8
OR
                      (dbo.INVOICES.BATCH_STATUS_ID =
