CREATE VIEW dbo.FINANCE_REPORT1_V
AS
SELECT     dbo.INVOICES.INVOICE_ID, dbo.INVOICES.ORGANIZATION_ID, dbo.INVOICES.PO_NO, dbo.INVOICES.STATUS_ID, dbo.INVOICES.JOB_ID, 
                      dbo.JOBS.JOB_NO, dbo.JOBS.JOB_NAME, dbo.INVOICES.BILL_CUSTOMER_ID, dbo.CUSTOMERS.CUSTOMER_NAME, 
                      dbo.SERVICE_LINES.TC_SERVICE_NO AS Rec, dbo.INVOICE_LINES.INVOICE_LINE_TYPE_ID, dbo.INVOICE_LINES.DESCRIPTION, 
                      dbo.INVOICE_LINES.UNIT_PRICE, dbo.INVOICE_LINES.QTY, dbo.INVOICE_LINES.EXTENDED_PRICE
FROM         dbo.INVOICES INNER JOIN
                      dbo.JOBS ON dbo.INVOICES.JOB_ID = dbo.JOBS.JOB_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.INVOICES.BILL_CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.INVOICE_LINES ON dbo.INVOICES.INVOICE_ID = dbo.INVOICE_LINES.INVOICE_ID FULL OUTER JOIN
                      dbo.SERVICE_LINES ON dbo.INVOICES.INVOICE_ID = dbo.SERVICE_LINES.INVOICE_ID
WHERE     (dbo.INVOICES.ORGANIZATION_ID = 11)

