CREATE VIEW dbo.FUNCTION_RIGHT_TYPES_V
AS
SELECT     TOP 100 PERCENT dbo.FUNCTION_RIGHT_TYPES.FUNCTION_RIGHT_TYPE_ID, dbo.FUNCTION_RIGHT_TYPES.FUNCTION_ID, 
                      dbo.FUNCTIONS.CODE AS function_code, dbo.FUNCTION_RIGHT_TYPES.RIGHT_TYPE_ID, dbo.RIGHT_TYPES.CODE AS right_type_code, 
                      dbo.FUNCTION_RIGHT_TYPES.UPDATABLE_FLAG, dbo.FUNCTION_RIGHT_TYPES.DATE_CREATED, dbo.FUNCTION_RIGHT_TYPES.CREATED_BY, 
                      USERS_1.FIRST_NAME + ' ' + USERS_1.LAST_NAME AS created_by_name, dbo.FUNCTION_RIGHT_TYPES.DATE_MODIFIED, 
                      dbo.FUNCTION_RIGHT_TYPES.MODIFIED_BY, USERS_2.FIRST_NAME + ' ' + USERS_2.LAST_NAME AS modified_by_name, 
                      dbo.FUNCTIONS.FUNCTION_GROUP_ID, dbo.FUNCTIONS.TEMPLATE_ID, dbo.FUNCTIONS.NAME AS function_name, 
                      dbo.FUNCTIONS.DESCRIPTION AS function_desc, dbo.FUNCTIONS.IS_NAV_FUNCTION, dbo.FUNCTIONS.TARGET, 
                      dbo.RIGHT_TYPES.NAME AS right_type_name, dbo.RIGHT_TYPES.DESCRIPTION AS right_type_desc
FROM         dbo.USERS USERS_2 RIGHT OUTER JOIN
                      dbo.FUNCTION_RIGHT_TYPES INNER JOIN
                      dbo.FUNCTIONS ON dbo.FUNCTION_RIGHT_TYPES.FUNCTION_ID = dbo.FUNCTIONS.FUNCTION_ID INNER JOIN
                      dbo.RIGHT_TYPES ON dbo.FUNCTION_RIGHT_TYPES.RIGHT_TYPE_ID = dbo.RIGHT_TYPES.RIGHT_TYPE_ID ON 
                      USERS_2.USER_ID = dbo.FUNCTION_RIGHT_TYPES.MODIFIED_BY LEFT OUTER JOIN
                      dbo.USERS USERS_1 ON dbo.FUNCTION_RIGHT_TYPES.CREATED_BY = USERS_1.USER_ID

