CREATE VIEW dbo.HOURS_BY_PAYCODE_V
AS
SELECT     ORGANIZATION_ID, TC_JOB_ID, TC_JOB_NO, TC_SERVICE_ID, TC_SERVICE_NO, SERVICE_LINE_DATE, EXT_EMPLOYEE_ID, employee_name, 
                      PAYROLL_QTY, EXT_PAY_CODE, USER_ID
FROM         dbo.PAYROLL_V
WHERE     (ORGANIZATION_ID IS NOT NULL)


