CREATE VIEW dbo.INVOICE_COST_CODES_JOB_V
AS
SELECT     TOP 100 PERCENT dbo.INVOICES.INVOICE_ID, dbo.LOOKUPS.CODE AS cost_to_cust, LOOKUPS_1.CODE AS cost_to_vend, 
                      LOOKUPS_2.CODE AS cost_to_job, LOOKUPS_3.CODE AS warehouse_fee, dbo.REQUESTS.D_SALES_REP_CONTACT_ID, 
                      dbo.CONTACTS.CONTACT_NAME AS sales_rep_name, dbo.REQUESTS.DATE_CREATED
FROM         dbo.JOBS INNER JOIN
                      dbo.INVOICES ON dbo.JOBS.JOB_ID = dbo.INVOICES.JOB_ID INNER JOIN
                      dbo.PROJECTS ON dbo.JOBS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.LOOKUPS INNER JOIN
                      dbo.REQUESTS ON dbo.LOOKUPS.LOOKUP_ID = dbo.REQUESTS.COST_TO_CUST_TYPE_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_1 ON dbo.REQUESTS.COST_TO_VEND_TYPE_ID = LOOKUPS_1.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_2 ON dbo.REQUESTS.COST_TO_JOB_TYPE_ID = LOOKUPS_2.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_3 ON dbo.REQUESTS.WAREHOUSE_FEE_TYPE_ID = LOOKUPS_3.LOOKUP_ID ON 
                      dbo.PROJECTS.PROJECT_ID = dbo.REQUESTS.PROJECT_ID LEFT OUTER JOIN
                      dbo.CONTACTS ON dbo.REQUESTS.D_SALES_REP_CONTACT_ID = dbo.CONTACTS.CONTACT_ID
ORDER BY dbo.INVOICES.INVOICE_ID

