CREATE VIEW dbo.INVOICE_TOTALS_V
AS
SELECT     TOP 100 PERCENT dbo.INVOICES.JOB_ID, dbo.INVOICES.INVOICE_ID, SUM(ISNULL(dbo.INVOICE_LINES.UNIT_PRICE, 0) 
                      * ISNULL(dbo.INVOICE_LINES.QTY, 0)) AS extended_price, 
                      (CASE WHEN dbo.LOOKUPS.CODE = 'custom' THEN (SUM(ISNULL(dbo.INVOICE_LINES.UNIT_PRICE, 0) * ISNULL(dbo.INVOICE_LINES.QTY, 0))) 
                      ELSE 0 END) custom_total
FROM         dbo.LOOKUPS RIGHT OUTER JOIN
                      dbo.INVOICE_LINES ON dbo.LOOKUPS.LOOKUP_ID = dbo.INVOICE_LINES.INVOICE_LINE_TYPE_ID RIGHT OUTER JOIN
                      dbo.INVOICES ON dbo.INVOICE_LINES.INVOICE_ID = dbo.INVOICES.INVOICE_ID
GROUP BY dbo.INVOICES.JOB_ID, dbo.INVOICES.INVOICE_ID, dbo.LOOKUPS.CODE
ORDER BY dbo.INVOICES.JOB_ID, dbo.INVOICES.INVOICE_ID



