CREATE VIEW dbo.INVOICES_V
AS
SELECT     TOP 100 PERCENT dbo.INVOICES.ORGANIZATION_ID, dbo.INVOICES.INVOICE_ID, dbo.INVOICES.JOB_ID, CAST(dbo.INVOICES.INVOICE_ID AS varchar) 
                      + dbo.CONTAINS_INVOICE_TRACKING_V.contains_tracking AS invoice_id_trk, dbo.CONTAINS_INVOICE_TRACKING_V.contains_tracking, 
                      dbo.USERS.FIRST_NAME + ' ' + dbo.USERS.LAST_NAME AS created_by_name, 
                      USERS_1.FIRST_NAME + ' ' + USERS_1.LAST_NAME AS modified_by_name, dbo.INVOICES.INVOICE_TYPE_ID, 
                      INVOICE_TYPE.CODE AS invoice_type_code, INVOICE_TYPE.NAME AS invoice_type_name, dbo.INVOICES.BILLING_TYPE_ID, 
                      BILLING_TYPE.CODE AS billing_type_code, BILLING_TYPE.NAME AS billing_type_name, dbo.INVOICES.INVOICE_FORMAT_TYPE_ID, 
                      INVOICE_FORMAT_TYPE.CODE AS invoice_format_type_code, INVOICE_FORMAT_TYPE.NAME AS invoice_format_type_name, 
                      USERS_2.FIRST_NAME + ' ' + USERS_2.LAST_NAME AS assigned_to_name, dbo.INVOICES.MODIFIED_BY, dbo.INVOICES.DATE_MODIFIED, 
                      dbo.INVOICES.CREATED_BY, dbo.INVOICES.PO_NO, dbo.INVOICES.BATCH_STATUS_ID, dbo.INVOICE_BATCH_STATUSES.CODE, 
                      dbo.INVOICES.EXT_BATCH_ID, dbo.INVOICES.ASSIGNED_TO_USER_ID, dbo.INVOICES.EXT_INVOICE_ID, dbo.INVOICES.STATUS_ID, 
                      dbo.INVOICES.DESCRIPTION, dbo.INVOICES.EXT_BILL_CUST_ID, dbo.INVOICES.DATE_SENT, dbo.INVOICES.DATE_CREATED, 
                      dbo.INVOICES.GP_DESCRIPTION, dbo.INVOICES.COST_CODES, dbo.INVOICES.START_DATE, dbo.INVOICES.END_DATE
FROM         dbo.CONTAINS_INVOICE_TRACKING_V RIGHT OUTER JOIN
                      dbo.INVOICES LEFT OUTER JOIN
                      dbo.INVOICE_BATCH_STATUSES ON dbo.INVOICES.BATCH_STATUS_ID = dbo.INVOICE_BATCH_STATUSES.STATUS_ID LEFT OUTER JOIN
                      dbo.USERS ON dbo.INVOICES.CREATED_BY = dbo.USERS.USER_ID LEFT OUTER JOIN
                      dbo.USERS USERS_2 ON dbo.INVOICES.ASSIGNED_TO_USER_ID = USERS_2.USER_ID ON 
                      dbo.CONTAINS_INVOICE_TRACKING_V.INVOICE_ID = dbo.INVOICES.INVOICE_ID LEFT OUTER JOIN
                      dbo.LOOKUPS INVOICE_FORMAT_TYPE ON dbo.INVOICES.INVOICE_FORMAT_TYPE_ID = INVOICE_FORMAT_TYPE.LOOKUP_ID LEFT OUTER JOIN
                      dbo.LOOKUPS BILLING_TYPE ON dbo.INVOICES.BILLING_TYPE_ID = BILLING_TYPE.LOOKUP_ID LEFT OUTER JOIN
                      dbo.LOOKUPS INVOICE_TYPE ON dbo.INVOICES.INVOICE_TYPE_ID = INVOICE_TYPE.LOOKUP_ID LEFT OUTER JOIN
                      dbo.USERS USERS_1 ON dbo.INVOICES.MODIFIED_BY = USERS_1.USER_ID
ORDER BY dbo.INVOICES.INVOICE_ID



