CREATE VIEW dbo.INVOICE_TRACKING_V
AS
SELECT     INVOICE_STATUSES_1.CODE AS invoice_status_code, INVOICE_STATUSES_1.NAME AS invoice_status_name, dbo.INVOICES.STATUS_ID, 
                      dbo.INVOICES.DESCRIPTION, dbo.INVOICE_TRACKING.DATE_CREATED, INVOICE_STATUSES_2.NAME AS new_status_name, 
                      INVOICE_STATUSES_1.NAME AS old_status_name, dbo.CONTACTS.CONTACT_NAME AS to_contact_name, 
                      dbo.USERS.FIRST_NAME + ' ' + dbo.USERS.LAST_NAME AS created_by_name, 
                      USERS_1.FIRST_NAME + ' ' + USERS_1.LAST_NAME AS modified_by_name, dbo.CONTACTS.EMAIL, 
                      USERS_2.FIRST_NAME + ' ' + USERS_2.LAST_NAME AS from_user_name, dbo.INVOICE_TRACKING.DATE_MODIFIED, dbo.INVOICE_TRACKING.NOTES, 
                      dbo.INVOICE_TRACKING.FROM_USER_ID, dbo.INVOICE_TRACKING.TO_CONTACT_ID, dbo.INVOICE_TRACKING.INVOICE_TRACKING_ID, 
                      dbo.INVOICE_TRACKING.INVOICE_ID, dbo.INVOICES.PO_NO, TRACKING_TYPES.CODE AS invoice_tracking_type_code, 
                      TRACKING_TYPES.NAME AS invoice_tracking_type_name, dbo.INVOICE_TRACKING.EMAIL_SENT_FLAG
FROM         dbo.CONTACTS RIGHT OUTER JOIN
                      dbo.INVOICE_STATUSES INVOICE_STATUSES_1 INNER JOIN
                      dbo.INVOICES INNER JOIN
                      dbo.INVOICE_TRACKING ON dbo.INVOICES.INVOICE_ID = dbo.INVOICE_TRACKING.INVOICE_ID ON 
                      INVOICE_STATUSES_1.STATUS_ID = dbo.INVOICES.STATUS_ID INNER JOIN
                      dbo.LOOKUPS TRACKING_TYPES ON dbo.INVOICE_TRACKING.INVOICE_TRACKING_TYPE_ID = TRACKING_TYPES.LOOKUP_ID INNER JOIN
                      dbo.USERS ON dbo.INVOICE_TRACKING.CREATED_BY = dbo.USERS.USER_ID ON 
                      dbo.CONTACTS.CONTACT_ID = dbo.INVOICE_TRACKING.TO_CONTACT_ID LEFT OUTER JOIN
                      dbo.USERS USERS_2 ON dbo.INVOICE_TRACKING.FROM_USER_ID = USERS_2.USER_ID LEFT OUTER JOIN
                      dbo.USERS USERS_1 ON dbo.INVOICE_TRACKING.MODIFIED_BY = USERS_1.USER_ID LEFT OUTER JOIN
                      dbo.INVOICE_STATUSES INVOICE_STATUSES_2 ON dbo.INVOICE_TRACKING.NEW_STATUS_ID = INVOICE_STATUSES_2.STATUS_ID LEFT OUTER JOIN
                      dbo.INVOICE_STATUSES INVOICE_STATUSES_3 ON dbo.INVOICE_TRACKING.OLD_STATUS_ID = INVOICE_STATUSES_3.STATUS_ID


