CREATE VIEW dbo.INVOICE_COST_CODES_LINE_V
AS
SELECT     TOP 100 PERCENT dbo.INVOICES.INVOICE_ID, dbo.LOOKUPS.CODE AS cost_to_cust, LOOKUPS_1.CODE AS cost_to_vend, 
                      LOOKUPS_2.CODE AS cost_to_job, LOOKUPS_3.CODE AS warehouse_fee, dbo.SERVICES.SERVICE_ID, dbo.REQUESTS.D_SALES_REP_CONTACT_ID, 
                      dbo.CONTACTS.CONTACT_NAME AS sales_rep_name
FROM         dbo.INVOICES INNER JOIN
                      dbo.INVOICE_LINES ON dbo.INVOICES.INVOICE_ID = dbo.INVOICE_LINES.INVOICE_ID INNER JOIN
                      dbo.SERV_INV_LINES ON dbo.INVOICE_LINES.INVOICE_LINE_ID = dbo.SERV_INV_LINES.INVOICE_LINE_ID INNER JOIN
                      dbo.SERVICE_LINES ON dbo.SERV_INV_LINES.SERVICE_LINE_ID = dbo.SERVICE_LINES.SERVICE_LINE_ID INNER JOIN
                      dbo.SERVICES ON dbo.SERVICE_LINES.BILL_SERVICE_ID = dbo.SERVICES.SERVICE_ID INNER JOIN
                      dbo.REQUESTS ON dbo.SERVICES.REQUEST_ID = dbo.REQUESTS.REQUEST_ID INNER JOIN
                      dbo.LOOKUPS ON dbo.REQUESTS.COST_TO_CUST_TYPE_ID = dbo.LOOKUPS.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_1 ON dbo.REQUESTS.COST_TO_VEND_TYPE_ID = LOOKUPS_1.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_2 ON dbo.REQUESTS.COST_TO_JOB_TYPE_ID = LOOKUPS_2.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS LOOKUPS_3 ON dbo.REQUESTS.WAREHOUSE_FEE_TYPE_ID = LOOKUPS_3.LOOKUP_ID LEFT OUTER JOIN
                      dbo.CONTACTS ON dbo.REQUESTS.D_SALES_REP_CONTACT_ID = dbo.CONTACTS.CONTACT_ID
GROUP BY dbo.INVOICES.INVOICE_ID, dbo.LOOKUPS.CODE, LOOKUPS_1.CODE, LOOKUPS_2.CODE, LOOKUPS_3.CODE, dbo.SERVICES.SERVICE_ID, 
                      dbo.REQUESTS.D_SALES_REP_CONTACT_ID, dbo.CONTACTS.CONTACT_NAME
HAVING      (dbo.LOOKUPS.CODE = 'Y') OR
                      (LOOKUPS_1.CODE = 'Y') OR
                      (LOOKUPS_2.CODE = 'Y') OR
                      (LOOKUPS_3.CODE = 'Y')
ORDER BY dbo.INVOICES.INVOICE_ID

