CREATE VIEW dbo.ITEMS_USAGE_V
AS
SELECT     TOP 100 PERCENT ORGANIZATION_ID, TC_JOB_NO, TC_SERVICE_NO, TC_SERVICE_LINE_NO, SERVICE_LINE_DATE, STATUS_ID, RESOURCE_NAME,
                       ITEM_ID, ITEM_NAME, ITEM_TYPE_CODE, TC_QTY, EXPENSE_QTY, BILL_QTY, BILL_HOURLY_QTY, BILL_EXP_QTY, bill_hourly_total, 
                      bill_exp_total
FROM         dbo.SERVICE_LINES
ORDER BY ITEM_NAME

