CREATE VIEW dbo.JC_JOB_COSTS_V
AS
SELECT     TOP 100 PERCENT dbo.ORGANIZATIONS.NAME AS [Organization Name], dbo.JOBS.JOB_NO AS [Job No], dbo.SERVICE_LINES.BILL_SERVICE_NO, 
                      dbo.SERVICE_LINES.BILL_SERVICE_LINE_NO, dbo.JOBS.JOB_NAME AS [Job Name], dbo.CUSTOMERS.DEALER_NAME AS [Dealer Name], 
                      dbo.USERS.FIRST_NAME + ' ' + dbo.USERS.LAST_NAME AS [Job Owner], dbo.SERVICE_LINES.SERVICE_LINE_DATE AS [Service Line Date ], 
                      dbo.RESOURCES.NAME AS [Job Supervisor], dbo.ITEMS.NAME AS [Item Name], item_types.CODE AS [Item Type Code], 
                      SUM(dbo.SERVICE_LINES.BILL_QTY) AS Qty, dbo.SERVICE_LINES.BILL_RATE AS Rate, 
                      SUM(dbo.SERVICE_LINES.BILL_QTY * dbo.SERVICE_LINES.BILL_RATE) AS Total, dbo.ITEMS.COST_PER_UOM AS [Cost Per Unit], 
                      SUM(dbo.ITEMS.COST_PER_UOM * dbo.SERVICE_LINES.BILL_QTY) AS [Total Cost], dbo.SERVICE_LINES.SERVICE_LINE_DATE AS [Report Date], 
                      dbo.SERVICE_LINE_STATUSES.CODE, dbo.SERVICE_LINES.BILLED_FLAG, dbo.SERVICE_LINES.POSTED_FLAG, dbo.SERVICE_LINES.POOLED_FLAG, 
                      dbo.SERVICE_LINES.BILLABLE_FLAG, dbo.SERVICES.INTERNAL_REQ_FLAG
FROM         dbo.JOBS INNER JOIN
                      dbo.SERVICES ON dbo.JOBS.JOB_ID = dbo.SERVICES.JOB_ID INNER JOIN
                      dbo.SERVICE_LINES ON dbo.SERVICE_LINES.BILL_SERVICE_ID = dbo.SERVICES.SERVICE_ID INNER JOIN
                      dbo.ITEMS ON dbo.SERVICE_LINES.ITEM_ID = dbo.ITEMS.ITEM_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.JOBS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.ORGANIZATIONS ON dbo.CUSTOMERS.ORGANIZATION_ID = dbo.ORGANIZATIONS.ORGANIZATION_ID INNER JOIN
                      dbo.SERVICE_LINE_STATUSES ON dbo.SERVICE_LINES.STATUS_ID = dbo.SERVICE_LINE_STATUSES.STATUS_ID LEFT OUTER JOIN
                      dbo.RESOURCES ON dbo.JOBS.FOREMAN_RESOURCE_ID = dbo.RESOURCES.RESOURCE_ID LEFT OUTER JOIN
                      dbo.USERS ON dbo.JOBS.BILLING_USER_ID = dbo.USERS.USER_ID INNER JOIN
                      dbo.LOOKUPS item_types ON dbo.ITEMS.ITEM_TYPE_ID = item_types.LOOKUP_ID
GROUP BY dbo.ORGANIZATIONS.NAME, dbo.JOBS.JOB_NO, dbo.JOBS.JOB_NAME, dbo.CUSTOMERS.DEALER_NAME, 
                      dbo.USERS.FIRST_NAME + ' ' + dbo.USERS.LAST_NAME, dbo.RESOURCES.NAME, dbo.ITEMS.NAME, dbo.ITEMS.COST_PER_UOM, 
                      dbo.SERVICE_LINES.SERVICE_LINE_DATE, dbo.SERVICE_LINES.BILL_RATE, dbo.SERVICE_LINE_STATUSES.CODE, item_types.CODE, 
                      dbo.SERVICE_LINES.BILLED_FLAG, dbo.SERVICE_LINES.POSTED_FLAG, dbo.SERVICE_LINES.POOLED_FLAG, dbo.SERVICE_LINES.BILLABLE_FLAG, 
                      dbo.SERVICE_LINES.BILL_SERVICE_NO, dbo.SERVICE_LINES.BILL_SERVICE_LINE_NO, dbo.SERVICES.INTERNAL_REQ_FLAG
HAVING      (dbo.SERVICE_LINE_STATUSES.CODE = 'Submitted') AND (dbo.SERVICE_LINES.SERVICE_LINE_DATE > CONVERT(DATETIME, '2006-01-01 00:00:00', 
                      102)) AND (dbo.SERVICE_LINES.POSTED_FLAG = 'N') AND (dbo.SERVICE_LINES.BILLABLE_FLAG = 'y') AND 
                      (dbo.SERVICES.INTERNAL_REQ_FLAG = 'n')
ORDER BY dbo.ORGANIZATIONS.NAME, dbo.JOBS.JOB_NO, dbo.SERVICE_LINES.SERVICE_LINE_DATE

