CREATE VIEW dbo.JOB_COSTING_V
AS
SELECT     dbo.SERVICE_LINES.TC_JOB_ID, dbo.SERVICE_LINES.TC_SERVICE_ID, dbo.SERVICE_LINES.BILL_JOB_ID, dbo.SERVICE_LINES.BILL_SERVICE_ID, 
                      dbo.SERVICE_LINES.ITEM_ID, dbo.SERVICE_LINES.ITEM_NAME, dbo.SERVICE_LINES.ITEM_TYPE_CODE, dbo.SERVICE_LINES.TC_QTY, 
                      dbo.SERVICE_LINES.TC_RATE, dbo.SERVICE_LINES.tc_total, dbo.ITEMS.COST_PER_UOM, dbo.ITEMS.COLUMN_POSITION, 
                      dbo.SERVICE_LINES.ENTRY_METHOD
FROM         dbo.SERVICE_LINES INNER JOIN
                      dbo.ITEMS ON dbo.SERVICE_LINES.ITEM_ID = dbo.ITEMS.ITEM_ID
WHERE     (dbo.SERVICE_LINES.STATUS_ID >= 3) AND (dbo.SERVICE_LINES.INTERNAL_REQ_FLAG = 'N')

