CREATE VIEW dbo.JOBS_NO_OWNER_V
AS
SELECT     TOP 100 PERCENT dbo.JOBS.JOB_ID, dbo.JOBS.PROJECT_ID, dbo.JOBS.JOB_NO, dbo.JOBS.JOB_NAME, dbo.JOBS.JOB_TYPE_ID, 
                      dbo.JOBS.JOB_STATUS_TYPE_ID, dbo.JOBS.CUSTOMER_ID, dbo.CUSTOMERS.CUSTOMER_NAME, dbo.JOBS.BILLING_USER_ID, 
                      dbo.LOOKUPS.NAME, dbo.CUSTOMERS.DEALER_NAME
FROM         dbo.JOBS INNER JOIN
                      dbo.CUSTOMERS ON dbo.JOBS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.LOOKUPS ON dbo.JOBS.JOB_STATUS_TYPE_ID = dbo.LOOKUPS.LOOKUP_ID
WHERE     (dbo.JOBS.BILLING_USER_ID IS NULL)
ORDER BY dbo.JOBS.JOB_NO

