CREATE VIEW dbo.PAYROLL_BATCHES_V
AS
SELECT     dbo.PAYROLL_BATCHES.ORGANIZATION_ID, dbo.SERVICE_LINES.TC_JOB_ID, dbo.SERVICE_LINES.TC_SERVICE_ID, 
                      dbo.SERVICE_LINES.TC_JOB_NO, dbo.SERVICE_LINES.TC_SERVICE_NO, dbo.SERVICE_LINES.TC_SERVICE_LINE_NO, 
                      dbo.PAYROLL_BATCHES.INT_BATCH_ID, dbo.PAYROLL_BATCHES.EXT_BATCH_ID, dbo.PAYROLL_BATCHES.BEGIN_DATE, 
                      dbo.PAYROLL_BATCHES.END_DATE, CONVERT(varchar(12), dbo.PAYROLL_BATCHES.BEGIN_DATE, 101) AS begin_date_varchar, 
                      CONVERT(varchar(12), dbo.PAYROLL_BATCHES.END_DATE, 101) AS end_date_varchar, CONVERT(varchar(12), 
                      dbo.PAYROLL_BATCHES.DATE_CREATED, 101) AS date_created_varchar, dbo.PAYROLL_BATCH_LINES.SERVICE_LINE_ID, 
                      dbo.SERVICE_LINES.PAYROLL_QTY, dbo.SERVICE_LINES.PAYROLL_RATE, dbo.SERVICE_LINES.EXT_PAY_CODE, dbo.SERVICE_LINES.ITEM_NAME, 
                      dbo.ITEMS.EXT_ITEM_ID, dbo.RESOURCES.USER_ID, dbo.USERS.EXT_EMPLOYEE_ID, dbo.USERS.FULL_NAME AS employee_name, 
                      dbo.PAYROLL_BATCHES.PAYROLL_BATCH_STATUS_TYPE_ID, dbo.LOOKUPS.CODE AS payroll_batch_status_type_code, 
                      dbo.LOOKUPS.NAME AS payroll_batch_status_type_name, dbo.SERVICE_LINES.SERVICE_LINE_DATE, 
                      dbo.SERVICE_LINES.SERVICE_LINE_DATE_VARCHAR, dbo.SERVICE_LINES.SERVICE_LINE_WEEK, 
                      dbo.SERVICE_LINES.SERVICE_LINE_WEEK_VARCHAR
FROM         dbo.USERS RIGHT OUTER JOIN
                      dbo.RESOURCES RIGHT OUTER JOIN
                      dbo.LOOKUPS RIGHT OUTER JOIN
                      dbo.PAYROLL_BATCHES LEFT OUTER JOIN
                      dbo.ITEMS RIGHT OUTER JOIN
                      dbo.PAYROLL_BATCH_LINES LEFT OUTER JOIN
                      dbo.SERVICE_LINES ON dbo.PAYROLL_BATCH_LINES.SERVICE_LINE_ID = dbo.SERVICE_LINES.SERVICE_LINE_ID ON 
                      dbo.ITEMS.ITEM_ID = dbo.SERVICE_LINES.ITEM_ID ON dbo.PAYROLL_BATCHES.INT_BATCH_ID = dbo.PAYROLL_BATCH_LINES.INT_BATCH_ID ON 
                      dbo.LOOKUPS.LOOKUP_ID = dbo.PAYROLL_BATCHES.PAYROLL_BATCH_STATUS_TYPE_ID ON 
                      dbo.RESOURCES.RESOURCE_ID = dbo.SERVICE_LINES.RESOURCE_ID ON dbo.USERS.USER_ID = dbo.RESOURCES.USER_ID




