CREATE VIEW dbo.PDA_TIME_V 
AS 
SELECT     dbo.SERVICE_LINE_STATUSES.CODE, dbo.SERVICE_LINES.CREATED_BY AS ims_user_id, dbo.SERVICE_LINES.ENTRY_METHOD, 

                      dbo.SERVICE_LINES.PALM_REP_ID AS rep_id 
FROM         dbo.SERVICE_LINES INNER JOIN 
                      dbo.SERVICE_LINE_STATUSES ON dbo.SERVICE_LINES.STATUS_ID = dbo.SERVICE_LINE_STATUSES.STATUS_ID 
WHERE     (dbo.SERVICE_LINES.ENTRY_METHOD = 'pda') AND (dbo.SERVICE_LINE_STATUSES.CODE = 'new') 


