CREATE VIEW dbo.PDA_RESOURCES_V
AS
SELECT     TOP 100 PERCENT dbo.RESOURCES.RESOURCE_ID, dbo.RESOURCES.NAME, dbo.RESOURCES.FOREMAN_FLAG AS sup_flag, dbo.USERS.LOGIN, 
                      dbo.USERS.PASSWORD, SUBSTRING(dbo.USERS.FIRST_NAME, 0, 3) + SUBSTRING(dbo.USERS.LAST_NAME, 0, 8) AS res_code, 
                      dbo.PDA_RESOURCE_SORT.row_number AS sort_order, dbo.USERS.EXT_EMPLOYEE_ID AS res_no, ISNULL(dbo.USERS.PIN, '') AS pin, 
                      dbo.USERS.ACTIVE_FLAG, PALM_USER.USER_ID AS ims_user_id, PALM_RESOURCE.ORGANIZATION_ID
FROM         dbo.USERS RIGHT OUTER JOIN
                      dbo.USERS PALM_USER INNER JOIN
                      dbo.RESOURCES INNER JOIN
                      dbo.PDA_RESOURCE_SORT ON dbo.RESOURCES.RESOURCE_ID = dbo.PDA_RESOURCE_SORT.resource_id INNER JOIN
                      dbo.RESOURCES PALM_RESOURCE ON dbo.RESOURCES.ORGANIZATION_ID = PALM_RESOURCE.ORGANIZATION_ID ON 
                      PALM_USER.USER_ID = PALM_RESOURCE.USER_ID ON dbo.USERS.USER_ID = dbo.RESOURCES.USER_ID
WHERE     (dbo.RESOURCES.ACTIVE_FLAG = 'Y') AND (dbo.USERS.ACTIVE_FLAG = 'Y' OR
                      dbo.USERS.ACTIVE_FLAG IS NULL)
ORDER BY PALM_USER.USER_ID

