CREATE VIEW dbo.PEP_POSTED_REQS_V
AS
SELECT     TOP 100 PERCENT dbo.JOBS_V.ORGANIZATION_ID, dbo.JOBS_V.JOB_NO, dbo.SERVICES.SERVICE_NO, dbo.JOBS_V.CUSTOMER_NAME, 
                      dbo.JOBS_V.JOB_NAME, dbo.SERVICES.DESCRIPTION, dbo.SERVICES.CUST_COL_1 AS location, SUM(dbo.BILLING_V.BILL_TOTAL) AS sum_bill_total, 
                      dbo.BILLING_V.INVOICE_ID, dbo.INVOICE_TOTALS_V.extended_price AS invoice_total
FROM         dbo.INVOICE_TOTALS_V RIGHT OUTER JOIN
                      dbo.JOBS_V LEFT OUTER JOIN
                      dbo.BILLING_V ON dbo.JOBS_V.JOB_ID = dbo.BILLING_V.BILL_JOB_ID LEFT OUTER JOIN
                      dbo.SERVICES ON dbo.BILLING_V.BILL_SERVICE_ID = dbo.SERVICES.SERVICE_ID ON 
                      dbo.INVOICE_TOTALS_V.INVOICE_ID = dbo.BILLING_V.INVOICE_ID
WHERE     (dbo.BILLING_V.SERVICE_LINE_DATE BETWEEN '4/25/2003' AND '5/4/2004')
GROUP BY dbo.JOBS_V.JOB_NO, dbo.JOBS_V.JOB_NAME, dbo.JOBS_V.CUSTOMER_NAME, dbo.BILLING_V.STATUS_ID, dbo.SERVICES.SERVICE_NO, 
                      dbo.SERVICES.DESCRIPTION, dbo.SERVICES.CUST_COL_1, dbo.INVOICE_TOTALS_V.extended_price, dbo.JOBS_V.JOB_ID, 
                      dbo.JOBS_V.ORGANIZATION_ID, dbo.SERVICES.CUST_COL_1, dbo.BILLING_V.INVOICE_ID
HAVING      (dbo.BILLING_V.STATUS_ID = 5) AND (dbo.JOBS_V.CUSTOMER_NAME LIKE 'medtronic%')
ORDER BY dbo.JOBS_V.JOB_NO, dbo.BILLING_V.INVOICE_ID

