CREATE VIEW dbo.PEP_RESOURCES_V
AS
SELECT     RESOURCE_ID, ORGANIZATION_ID, NAME, USER_ID, ATTACHED_FLAG, ACTIVE_FLAG, FOREMAN_FLAG
FROM         dbo.RESOURCES
WHERE     (ORGANIZATION_ID = 2) AND (ACTIVE_FLAG = 'y') AND (USER_ID IS NULL)

