CREATE VIEW dbo.Pep_USER_ROLES_V
AS
SELECT     TOP 100 PERCENT dbo.USERS.USER_ID, dbo.USERS.FIRST_NAME, dbo.USERS.LAST_NAME, dbo.USERS.LOGIN, dbo.USERS.PASSWORD, 
                      dbo.USERS.PIN, dbo.USERS.ACTIVE_FLAG, dbo.ROLES.NAME
FROM         dbo.USERS INNER JOIN
                      dbo.USER_ROLES ON dbo.USERS.USER_ID = dbo.USER_ROLES.USER_ID INNER JOIN
                      dbo.ROLES ON dbo.USER_ROLES.ROLE_ID = dbo.ROLES.ROLE_ID
WHERE     (dbo.USERS.ACTIVE_FLAG = 'y')
ORDER BY dbo.USERS.LAST_NAME

