CREATE VIEW dbo.PEP_POSTED_CUSTOM_LINES_V
AS
SELECT     TOP 100 PERCENT dbo.JOBS_V.ORGANIZATION_ID, dbo.JOBS_V.JOB_NO, dbo.INVOICES.INVOICE_ID, dbo.JOBS_V.CUSTOMER_NAME, 
                      dbo.JOBS_V.JOB_NAME, dbo.INVOICES.DESCRIPTION AS INVOICE_DESC, dbo.INVOICES.START_DATE, dbo.INVOICES.END_DATE, 
                      SUM(ISNULL(dbo.INVOICE_LINES.UNIT_PRICE, 0) * ISNULL(dbo.INVOICE_LINES.QTY, 0)) AS custom_line_total, 
                      dbo.INVOICE_TOTALS_V.extended_price AS invoice_total, dbo.INVOICE_TOTALS_V.extended_price - ISNULL(dbo.INVOICE_LINES.UNIT_PRICE, 0) 
                      * ISNULL(dbo.INVOICE_LINES.QTY, 0) AS req_total
FROM         dbo.INVOICE_TOTALS_V RIGHT OUTER JOIN
                      dbo.INVOICE_LINES RIGHT OUTER JOIN
                      dbo.INVOICES ON dbo.INVOICE_LINES.INVOICE_ID = dbo.INVOICES.INVOICE_ID LEFT OUTER JOIN
                      dbo.LOOKUPS ON dbo.INVOICE_LINES.INVOICE_LINE_TYPE_ID = dbo.LOOKUPS.LOOKUP_ID ON 
                      dbo.INVOICE_TOTALS_V.INVOICE_ID = dbo.INVOICES.INVOICE_ID RIGHT OUTER JOIN
                      dbo.JOBS_V ON dbo.INVOICES.JOB_ID = dbo.JOBS_V.JOB_ID
WHERE     (dbo.INVOICES.DATE_SENT BETWEEN CONVERT(DATETIME, '2003-04-25 00:00:00', 102) AND CONVERT(DATETIME, '2004-05-04 00:00:00', 102))
GROUP BY dbo.JOBS_V.JOB_NO, dbo.JOBS_V.JOB_NAME, dbo.JOBS_V.CUSTOMER_NAME, dbo.INVOICE_TOTALS_V.extended_price, dbo.JOBS_V.JOB_ID, 
                      dbo.JOBS_V.ORGANIZATION_ID, dbo.INVOICES.STATUS_ID, dbo.INVOICES.DESCRIPTION, dbo.INVOICES.START_DATE, dbo.INVOICES.END_DATE, 
                      dbo.LOOKUPS.CODE, dbo.INVOICES.INVOICE_ID, dbo.INVOICE_TOTALS_V.extended_price - ISNULL(dbo.INVOICE_LINES.UNIT_PRICE, 0) 
                      * ISNULL(dbo.INVOICE_LINES.QTY, 0)
HAVING      (dbo.JOBS_V.CUSTOMER_NAME LIKE 'medtronic%') AND (dbo.INVOICES.STATUS_ID = 4) AND (dbo.LOOKUPS.CODE = 'CUSTOM')
ORDER BY dbo.JOBS_V.JOB_NO, dbo.INVOICES.INVOICE_ID

