

CREATE VIEW dbo.PKT_SERVICE_LINES_V
AS
SELECT     dbo.SERVICE_LINES.TC_JOB_ID AS job_id, dbo.SERVICE_LINES.TC_SERVICE_ID AS service_id, dbo.SERVICE_LINES.SERVICE_LINE_ID, 
                      dbo.SERVICE_LINES.TC_SERVICE_LINE_NO AS service_line_no, dbo.SERVICE_LINE_STATUSES.CODE AS status_code, 
                      dbo.SERVICE_LINES.STATUS_ID, dbo.SERVICE_LINES.TC_QTY AS qty, dbo.SERVICE_LINES.RESOURCE_ID, 
                      dbo.RESOURCES.NAME AS resource_name, dbo.SERVICE_LINES.ITEM_ID, dbo.ITEMS.NAME AS item_name, 
                      dbo.SERVICE_LINES.SERVICE_LINE_DATE, dbo.SERVICE_LINES.TC_SERVICE_NO AS service_no, dbo.RESOURCES.USER_ID
FROM         dbo.SERVICE_LINES INNER JOIN
                      dbo.SERVICE_LINE_STATUSES ON dbo.SERVICE_LINES.STATUS_ID = dbo.SERVICE_LINE_STATUSES.STATUS_ID INNER JOIN
                      dbo.RESOURCES ON dbo.SERVICE_LINES.RESOURCE_ID = dbo.RESOURCES.RESOURCE_ID INNER JOIN
                      dbo.ITEMS ON dbo.SERVICE_LINES.ITEM_ID = dbo.ITEMS.ITEM_ID



