CREATE VIEW dbo.POOLED_HOURS_TOTALS_V
AS
SELECT     TOP 100 PERCENT sl.BILL_JOB_NO, sl.BILL_SERVICE_NO, sl.BILL_JOB_ID job_id, sl.BILL_SERVICE_ID service_id, sl.ITEM_ID, sl.ITEM_NAME, SUM(sl.BILL_QTY) 
                      AS total_qty, sl.BILL_RATE AS rate, sl.STATUS_ID AS service_line_status_id, sl.INVOICE_ID
FROM         dbo.SERVICE_LINES sl LEFT OUTER JOIN
                      dbo.POOLED_HOURS_CALC ON sl.BILL_SERVICE_ID = dbo.POOLED_HOURS_CALC.SERVICE_ID
GROUP BY sl.STATUS_ID, sl.BILL_JOB_ID, sl.BILL_SERVICE_ID, sl.BILL_JOB_NO, sl.BILL_SERVICE_NO, sl.BILL_RATE, sl.ITEM_ID, sl.INVOICE_ID, 
                      sl.ITEM_NAME
HAVING      (sl.STATUS_ID = 4) AND (sl.INVOICE_ID IS NULL)
ORDER BY sl.BILL_JOB_NO, sl.BILL_SERVICE_NO


