CREATE VIEW dbo.POOLED_HOURS_CALC_V
AS
SELECT     dbo.POOLED_HOURS_CALC.SERVICE_ID, dbo.POOLED_HOURS_CALC.ITEM_ID, dbo.POOLED_HOURS_CALC.RATE, 
                      dbo.POOLED_HOURS_CALC.QTY_POOLED, dbo.POOLED_HOURS_CALC.QTY_DIST, 
                      dbo.POOLED_HOURS_CALC.QTY_POOLED - dbo.POOLED_HOURS_CALC.QTY_DIST AS qty_left, dbo.ITEMS.NAME AS item_name, 
                      dbo.LOOKUPS.CODE AS item_type_code
FROM         dbo.POOLED_HOURS_CALC LEFT OUTER JOIN
                      dbo.ITEMS ON dbo.POOLED_HOURS_CALC.ITEM_ID = dbo.ITEMS.ITEM_ID LEFT OUTER JOIN
                      dbo.LOOKUPS ON dbo.ITEMS.ITEM_TYPE_ID = dbo.LOOKUPS.LOOKUP_ID

