CREATE VIEW dbo.PROJECT_NOTES_V
AS
SELECT     dbo.PROJECT_NOTES.PROJECT_NOTE_ID, dbo.PROJECT_NOTES.PROJECT_ID, dbo.PROJECT_NOTES.NOTE, dbo.PROJECT_NOTES.DATE_CREATED, 
                      dbo.PROJECT_NOTES.CREATED_BY, CREATED_BY.FIRST_NAME + ' ' + CREATED_BY.LAST_NAME AS created_by_name, 
                      dbo.PROJECT_NOTES.DATE_MODIFIED, dbo.PROJECT_NOTES.MODIFIED_BY, 
                      MODIFIED_BY.FIRST_NAME + ' ' + MODIFIED_BY.LAST_NAME AS modified_by_name
FROM         dbo.PROJECT_NOTES LEFT OUTER JOIN
                      dbo.USERS MODIFIED_BY ON dbo.PROJECT_NOTES.MODIFIED_BY = MODIFIED_BY.USER_ID LEFT OUTER JOIN
                      dbo.USERS CREATED_BY ON dbo.PROJECT_NOTES.CREATED_BY = CREATED_BY.USER_ID

