


CREATE  VIEW dbo.PROJECT_REQUESTS_V
AS
SELECT     dbo.PROJECTS_V.PROJECT_ID, dbo.PROJECTS_V.PROJECT_NO, dbo.REQUESTS_V.REQUEST_NO, dbo.REQUESTS_V.VERSION_NO, 
	dbo.REQUESTS_V.max_version_no, dbo.PROJECTS_V.PROJECT_TYPE_ID, dbo.PROJECTS_V.project_type_code, 
	dbo.PROJECTS_V.project_type_name, dbo.PROJECTS_V.PROJECT_STATUS_TYPE_ID, dbo.PROJECTS_V.project_status_type_code, 
	dbo.PROJECTS_V.project_status_type_name, dbo.PROJECTS_V.CUSTOMER_ID, dbo.PROJECTS_V.PARENT_CUSTOMER_ID, dbo.PROJECTS_V.ORGANIZATION_ID, 
	dbo.PROJECTS_V.EXT_DEALER_ID, dbo.PROJECTS_V.DEALER_NAME, dbo.PROJECTS_V.EXT_CUSTOMER_ID, dbo.PROJECTS_V.CUSTOMER_NAME, 
	dbo.PROJECTS_V.JOB_NAME, dbo.PROJECTS_V.DATE_CREATED, dbo.PROJECTS_V.CREATED_BY, dbo.PROJECTS_V.created_by_name, 
	dbo.REQUESTS_V.REQUEST_ID, dbo.REQUESTS_V.REQUEST_TYPE_ID, dbo.REQUESTS_V.request_type_code, 
	dbo.REQUESTS_V.request_type_name, dbo.REQUESTS_V.REQUEST_STATUS_TYPE_ID, dbo.REQUESTS_V.request_status_type_code, 
	dbo.REQUESTS_V.request_status_type_name, dbo.REQUESTS_V.CSC_WO_FIELD_FLAG,
	dbo.REQUESTS_V.est_start_date_varchar, dbo.REQUESTS_V.QUOTE_REQUEST_ID, 
	dbo.REQUESTS_V.IS_QUOTED, dbo.REQUESTS_V.A_D_DESIGNER_CONTACT_ID, dbo.REQUESTS_V.GEN_CONTRACTOR_CONTACT_ID, 
	dbo.REQUESTS_V.ELECTRICIAN_CONTACT_ID, dbo.REQUESTS_V.DATA_PHONE_CONTACT_ID, dbo.REQUESTS_V.CARPET_LAYER_CONTACT_ID, 
	dbo.REQUESTS_V.BLDG_MGR_CONTACT_ID, dbo.REQUESTS_V.SECURITY_CONTACT_ID, dbo.REQUESTS_V.MOVER_CONTACT_ID, 
	dbo.REQUESTS_V.OTHER_CONTACT_ID, dbo.REQUESTS_V.FURNITURE1_CONTACT_ID, dbo.REQUESTS_V.FURNITURE2_CONTACT_ID
FROM         dbo.PROJECTS_V LEFT OUTER JOIN
                      dbo.REQUESTS_V ON dbo.PROJECTS_V.PROJECT_ID = dbo.REQUESTS_V.PROJECT_ID

