CREATE VIEW dbo.PROJECT_INVOICES_V
AS
SELECT     dbo.PROJECTS_V.ORGANIZATION_ID, dbo.PROJECTS_V.PROJECT_ID, dbo.PROJECTS_V.PROJECT_NO, dbo.PROJECTS_V.project_type_code, 
                      dbo.PROJECTS_V.project_status_type_code, dbo.PROJECTS_V.CUSTOMER_ID, dbo.PROJECTS_V.PARENT_CUSTOMER_ID, 
                      dbo.PROJECTS_V.EXT_DEALER_ID, dbo.ORGANIZATIONS.EXT_DIRECT_DEALER_ID, dbo.ORGANIZATIONS.EXT_DCI_DEALER_ID, 
                      dbo.PROJECTS_V.DEALER_NAME, dbo.PROJECTS_V.CUSTOMER_NAME, dbo.INVOICE_TOTALS_V.INVOICE_ID, 
                      dbo.INVOICE_TOTALS_V.extended_price AS invoice_total, dbo.INVOICE_TOTALS_V.custom_total, dbo.INVOICES.PO_NO, dbo.INVOICES.DATE_SENT, 
                      dbo.INVOICE_STATUSES.CODE AS invoice_status_code
FROM         dbo.INVOICE_TOTALS_V INNER JOIN
                      dbo.PROJECTS_V INNER JOIN
                      dbo.JOBS ON dbo.PROJECTS_V.PROJECT_ID = dbo.JOBS.PROJECT_ID ON dbo.INVOICE_TOTALS_V.JOB_ID = dbo.JOBS.JOB_ID INNER JOIN
                      dbo.INVOICES ON dbo.INVOICE_TOTALS_V.INVOICE_ID = dbo.INVOICES.INVOICE_ID INNER JOIN
                      dbo.INVOICE_STATUSES ON dbo.INVOICES.STATUS_ID = dbo.INVOICE_STATUSES.STATUS_ID INNER JOIN
                      dbo.ORGANIZATIONS ON dbo.PROJECTS_V.ORGANIZATION_ID = dbo.ORGANIZATIONS.ORGANIZATION_ID

