CREATE VIEW dbo.QP3_RESOURCE_TYPES_V
AS
SELECT     TOP 100 PERCENT dbo.USERS.USER_ID, dbo.USER_ORGANIZATIONS.ORGANIZATION_ID, dbo.RESOURCES.ACTIVE_FLAG, dbo.USERS.FULL_NAME, 
                      dbo.USERS.EXT_EMPLOYEE_ID, dbo.RESOURCES.RESOURCE_TYPE_ID, dbo.USERS.LAST_NAME, dbo.USERS.LOGIN, dbo.USERS.PASSWORD, 
                      dbo.USERS.QP3, dbo.RESOURCES.ATTACHED_FLAG
FROM         dbo.USER_ORGANIZATIONS LEFT OUTER JOIN
                      dbo.USERS ON dbo.USER_ORGANIZATIONS.USER_ID = dbo.USERS.USER_ID RIGHT OUTER JOIN
                      dbo.RESOURCES ON dbo.USERS.USER_ID = dbo.RESOURCES.USER_ID
WHERE     (dbo.USERS.EXT_EMPLOYEE_ID IS NOT NULL) AND (dbo.USER_ORGANIZATIONS.ORGANIZATION_ID IS NOT NULL) AND 
                      (dbo.RESOURCES.ATTACHED_FLAG = 'y') AND (dbo.RESOURCES.ACTIVE_FLAG = 'Y')
ORDER BY dbo.USERS.LAST_NAME

