
CREATE VIEW dbo.QUICK_REQUESTS_V
AS
SELECT     dbo.REQUESTS.REQUEST_ID, dbo.REQUESTS.REQUEST_ID AS RECORD_ID, dbo.REQUESTS.REQUEST_NO AS RECORD_NO, 
                      dbo.REQUESTS.CUSTOMER_PO_NO, dbo.REQUESTS.DEALER_PO_NO, dbo.REQUESTS.DEALER_PROJECT_NO, dbo.REQUESTS.EST_START_DATE, 
                      dbo.REQUESTS.DESCRIPTION, dbo.REQUESTS.IS_QUOTED, dbo.REQUESTS.DATE_CREATED AS RECORD_CREATED, 
                      dbo.REQUESTS.DATE_MODIFIED AS RECORD_LAST_MODIFIED, dbo.PROJECTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, 
                      dbo.PROJECTS.JOB_NAME, CONVERT(varchar, dbo.PROJECTS.PROJECT_NO) + '-' + CONVERT(varchar, dbo.REQUESTS.REQUEST_NO) 
                      AS PROJECT_REQUEST_NO, dbo.CUSTOMERS.ORGANIZATION_ID, dbo.CUSTOMERS.CUSTOMER_ID, dbo.CUSTOMERS.PARENT_CUSTOMER_ID, 
                      dbo.CUSTOMERS.EXT_DEALER_ID, dbo.CUSTOMERS.CUSTOMER_NAME, dbo.CUSTOMERS.DEALER_NAME, 
                      request_status.CODE AS RECORD_STATUS_CODE, request_status.NAME AS RECORD_STATUS_NAME, 
                      request_status.SEQUENCE_NO AS RECORD_STATUS_SEQ_NO, request_type.CODE AS RECORD_TYPE_CODE, 
                      request_type.NAME AS RECORD_TYPE_NAME, request_type.SEQUENCE_NO AS RECORD_TYPE_SEQ_NO, dbo.REQUESTS.A_M_CONTACT_ID, 
                      dbo.REQUESTS.CUSTOMER_CONTACT_ID, dbo.REQUESTS.ALT_CUSTOMER_CONTACT_ID, dbo.REQUESTS.D_SALES_REP_CONTACT_ID, 
                      dbo.REQUESTS.D_SALES_SUP_CONTACT_ID, dbo.REQUESTS.D_PROJ_MGR_CONTACT_ID, dbo.REQUESTS.D_DESIGNER_CONTACT_ID, 
                      project_status.CODE AS PROJECT_STATUS_CODE, project_status.NAME AS PROJECT_STATUS_NAME
FROM         dbo.REQUESTS INNER JOIN
                      dbo.LOOKUPS request_status ON dbo.REQUESTS.REQUEST_STATUS_TYPE_ID = request_status.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS request_type ON dbo.REQUESTS.REQUEST_TYPE_ID = request_type.LOOKUP_ID INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.PROJECTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.LOOKUPS project_status ON dbo.PROJECTS.PROJECT_STATUS_TYPE_ID = project_status.LOOKUP_ID


