
CREATE VIEW dbo.QUOTE_CONDITION_XJOIN
AS
SELECT     dbo.QUOTES.QUOTE_ID, dbo.CONDITIONS.CONDITION_ID, dbo.CONDITIONS.NAME
FROM         dbo.CONDITIONS CROSS JOIN
                      dbo.QUOTES


