CREATE VIEW dbo.requests_query_for_Tim_VVV
AS
SELECT     dbo.REQUESTS.REQUEST_ID, dbo.REQUESTS.REQUEST_NO, dbo.REQUESTS.REQUEST_TYPE_ID, dbo.LOOKUPS.NAME, 
                      dbo.REQUESTS.D_PROJ_MGR_CONTACT_ID, dbo.REQUESTS.EST_START_DATE, dbo.REQUESTS.EST_START_TIME, 
                      dbo.REQUESTS.EST_END_DATE, dbo.REQUESTS.CUSTOMER_PO_NO, dbo.REQUESTS.A_M_SALES_CONTACT_ID, 
                      dbo.REQUESTS.WHO_CAN_APPROVE_NAME, dbo.REQUESTS.WHO_CAN_APPROVE_PHONE, dbo.REQUESTS.DOCK_AVAILABLE_TIME, 
                      dbo.REQUESTS.DOCK_HEIGHT, dbo.REQUESTS.STAIR_CARRY_FLIGHTS, dbo.REQUESTS.STAIR_CARRY_STAIRS, 
                      dbo.REQUESTS.SMALLEST_DOOR_ELEV_WIDTH, dbo.REQUESTS.LEVEL_TYPE_ID, dbo.CUSTOMERS.ORGANIZATION_ID
FROM         dbo.LOOKUPS INNER JOIN
                      dbo.REQUESTS ON dbo.LOOKUPS.LOOKUP_ID = dbo.REQUESTS.REQUEST_TYPE_ID INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.PROJECTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID

