CREATE VIEW dbo.REQUEST_INVOICES_V_ORIG
AS
SELECT     ISNULL(dbo.SERVICE_LINES.INVOICE_ID, dbo.SERVICE_LINES.POSTED_FROM_INVOICE_ID) AS invoice_id, SUM(dbo.SERVICE_LINES.BILL_TOTAL) 
                      AS sum_bill_total, dbo.PROJECTS.PROJECT_NO, dbo.REQUESTS.REQUEST_NO, dbo.REQUESTS.REQUEST_ID, 
                      dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID
FROM         dbo.REQUESTS INNER JOIN
                      dbo.SERVICE_LINES INNER JOIN
                      dbo.SERVICES ON dbo.SERVICE_LINES.BILL_SERVICE_ID = dbo.SERVICES.SERVICE_ID ON 
                      dbo.REQUESTS.REQUEST_ID = dbo.SERVICES.REQUEST_ID INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.REQUEST_VENDORS INNER JOIN
                      dbo.CUSTOMERS ON dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID = dbo.CUSTOMERS.A_M_FURNITURE1_CONTACT_ID ON 
                      dbo.REQUESTS.REQUEST_ID = dbo.REQUEST_VENDORS.REQUEST_ID AND 
                      dbo.REQUESTS.FURNITURE1_CONTACT_ID = dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID AND 
                      dbo.PROJECTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.ORGANIZATIONS ON dbo.CUSTOMERS.ORGANIZATION_ID = dbo.ORGANIZATIONS.ORGANIZATION_ID
GROUP BY ISNULL(dbo.SERVICE_LINES.INVOICE_ID, dbo.SERVICE_LINES.POSTED_FROM_INVOICE_ID), dbo.REQUESTS.REQUEST_ID, 
                      dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID, dbo.PROJECTS.PROJECT_NO, dbo.REQUESTS.REQUEST_NO

