CREATE VIEW dbo.RESOURCE_ESTIMATES_V
AS
SELECT     dbo.JOBS_V.ORGANIZATION_ID, dbo.RESOURCE_ESTIMATES.RESOURCE_EST_ID, dbo.RESOURCE_ESTIMATES.JOB_ID, dbo.JOBS_V.JOB_NO, 
                      dbo.JOBS_V.JOB_NAME, dbo.JOBS_V.JOB_TYPE_ID, dbo.JOBS_V.job_type_code AS Expr1, dbo.JOBS_V.job_type_name AS Expr2, 
                      dbo.SERVICES.SERVICE_ID, dbo.SERVICES.SERVICE_NO, dbo.RESOURCE_ESTIMATES.JOB_ITEM_RATE_ID, dbo.JOB_ITEM_RATES.ITEM_ID, 
                      dbo.ITEMS.NAME AS item_name, dbo.ITEMS.DESCRIPTION AS item_desc, dbo.ITEMS.ITEM_TYPE_ID, ITEM_TYPE.CODE AS item_type_code, 
                      ITEM_TYPE.NAME AS item_type_name, dbo.ITEMS.ITEM_STATUS_TYPE_ID, dbo.JOB_ITEM_RATES.RATE, 
                      dbo.RESOURCE_ESTIMATES.RESOURCE_TYPE_ID, dbo.RESOURCE_TYPES.CODE AS resource_type_code, 
                      dbo.RESOURCE_TYPES.NAME AS resource_type_name, dbo.RESOURCE_ESTIMATES.UNIT_QTY, dbo.RESOURCE_ESTIMATES.TIME_UOM_TYPE_ID, 
                      TIME_UOM_TYPE.CODE AS time_uom_type_code, TIME_UOM_TYPE.NAME AS time_uom_type_name, TIME_UOM_TYPE.ATTRIBUTE2 AS multiplier, 
                      dbo.RESOURCE_ESTIMATES.TIME_QTY, dbo.RESOURCE_ESTIMATES.TOTAL_HOURS, 
                      dbo.RESOURCE_ESTIMATES.UNIT_QTY * dbo.JOB_ITEM_RATES.RATE * dbo.RESOURCE_ESTIMATES.TIME_QTY * TIME_UOM_TYPE.ATTRIBUTE2 AS total_dollars,
                       dbo.RESOURCE_ESTIMATES.START_DATE, dbo.RESOURCE_ESTIMATES.DATE_CREATED, dbo.RESOURCE_ESTIMATES.CREATED_BY, 
                      USERS_1.FIRST_NAME + ' ' + USERS_1.LAST_NAME AS created_by_name, dbo.RESOURCE_ESTIMATES.DATE_MODIFIED, 
                      dbo.RESOURCE_ESTIMATES.MODIFIED_BY, USERS_2.FIRST_NAME + ' ' + USERS_2.LAST_NAME AS modified_by_name
FROM         dbo.LOOKUPS ITEM_TYPE RIGHT OUTER JOIN
                      dbo.ITEMS RIGHT OUTER JOIN
                      dbo.SERVICES RIGHT OUTER JOIN
                      dbo.JOB_ITEM_RATES RIGHT OUTER JOIN
                      dbo.RESOURCE_TYPES RIGHT OUTER JOIN
                      dbo.JOBS_V RIGHT OUTER JOIN
                      dbo.RESOURCE_ESTIMATES ON dbo.JOBS_V.JOB_ID = dbo.RESOURCE_ESTIMATES.JOB_ID ON 
                      dbo.RESOURCE_TYPES.RESOURCE_TYPE_ID = dbo.RESOURCE_ESTIMATES.RESOURCE_TYPE_ID ON 
                      dbo.JOB_ITEM_RATES.JOB_ITEM_RATE_ID = dbo.RESOURCE_ESTIMATES.JOB_ITEM_RATE_ID ON 
                      dbo.SERVICES.SERVICE_ID = dbo.RESOURCE_ESTIMATES.SERVICE_ID ON dbo.ITEMS.ITEM_ID = dbo.JOB_ITEM_RATES.ITEM_ID ON 
                      ITEM_TYPE.LOOKUP_ID = dbo.ITEMS.ITEM_TYPE_ID LEFT OUTER JOIN
                      dbo.USERS USERS_2 ON dbo.RESOURCE_ESTIMATES.MODIFIED_BY = USERS_2.USER_ID LEFT OUTER JOIN
                      dbo.USERS USERS_1 ON dbo.RESOURCE_ESTIMATES.CREATED_BY = USERS_1.USER_ID LEFT OUTER JOIN
                      dbo.LOOKUPS TIME_UOM_TYPE ON dbo.RESOURCE_ESTIMATES.TIME_UOM_TYPE_ID = TIME_UOM_TYPE.LOOKUP_ID
WHERE     (TIME_UOM_TYPE.ATTRIBUTE1 = 'time_hours')



