CREATE VIEW dbo.RESOURCES_V
AS
SELECT     dbo.RESOURCES.ORGANIZATION_ID, dbo.RESOURCES.RESOURCE_ID, dbo.RESOURCES.NAME, dbo.RESOURCES.NAME AS resource_name, 
                      dbo.RESOURCES.RES_CATEGORY_TYPE_ID, RES_CATEGORY_TYPES.CODE AS res_cat_type_code, 
                      RES_CATEGORY_TYPES.NAME AS res_cat_type_name, dbo.RESOURCES.RESOURCE_TYPE_ID, 
                      dbo.RESOURCE_TYPES.CODE AS resource_type_code, dbo.RESOURCE_TYPES.NAME AS resource_type_name, RESOURCE_USER.PIN, 
                      RESOURCE_USER.EXT_EMPLOYEE_ID, RESOURCE_USER.EMPLOYMENT_TYPE_ID, ISNULL(EMPLOYMENT_TYPES.CODE, 'None') 
                      AS employment_type_code, ISNULL(EMPLOYMENT_TYPES.NAME, 'None') AS employment_type_name, dbo.RESOURCES.USER_ID, 
                      RESOURCE_USER.FIRST_NAME + ' ' + RESOURCE_USER.LAST_NAME AS user_full_name, RESOURCE_USER.CONTACT_ID AS user_contact_id, 
                      dbo.CONTACTS.CONTACT_NAME AS user_contact_name, dbo.RESOURCES.ATTACHED_FLAG, dbo.RESOURCES.VENDOR_NAME, 
                      dbo.RESOURCES.EXT_VENDOR_ID, dbo.RESOURCE_TYPES.UNIQUE_FLAG, dbo.RESOURCES.ACTIVE_FLAG, dbo.RESOURCES.FOREMAN_FLAG, 
                      dbo.RESOURCES.NOTES, dbo.RESOURCES.DATE_CREATED, dbo.RESOURCES.CREATED_BY, 
                      CREATED_BY.FIRST_NAME + ' ' + CREATED_BY.LAST_NAME AS created_by_name, dbo.RESOURCES.DATE_MODIFIED, 
                      dbo.RESOURCES.MODIFIED_BY, MODIFIED_BY.FIRST_NAME + '
' + MODIFIED_BY.LAST_NAME AS modified_by_name
FROM         dbo.LOOKUPS EMPLOYMENT_TYPES RIGHT OUTER JOIN
                      dbo.CONTACTS RIGHT OUTER JOIN
                      dbo.USERS RESOURCE_USER ON dbo.CONTACTS.CONTACT_ID = RESOURCE_USER.CONTACT_ID RIGHT OUTER JOIN
                      dbo.RESOURCES LEFT OUTER JOIN
                      dbo.RESOURCE_TYPES ON dbo.RESOURCES.RESOURCE_TYPE_ID = dbo.RESOURCE_TYPES.RESOURCE_TYPE_ID LEFT OUTER JOIN
                      dbo.LOOKUPS RES_CATEGORY_TYPES ON dbo.RESOURCES.RES_CATEGORY_TYPE_ID = RES_CATEGORY_TYPES.LOOKUP_ID LEFT OUTER JOIN
                      dbo.USERS MODIFIED_BY ON dbo.RESOURCES.MODIFIED_BY = MODIFIED_BY.USER_ID LEFT OUTER JOIN
                      dbo.USERS CREATED_BY ON dbo.RESOURCES.CREATED_BY = CREATED_BY.USER_ID ON 
                      RESOURCE_USER.USER_ID = dbo.RESOURCES.USER_ID ON EMPLOYMENT_TYPES.LOOKUP_ID = RESOURCE_USER.EMPLOYMENT_TYPE_ID


