CREATE VIEW dbo.ROOT_CAUSES_V
AS
SELECT     dbo.LOOKUPS.LOOKUP_ID AS root_cause_id, dbo.LOOKUPS.NAME, dbo.LOOKUPS.ATTRIBUTE1 AS cause_number
FROM         dbo.LOOKUP_TYPES INNER JOIN
                      dbo.LOOKUPS ON dbo.LOOKUP_TYPES.LOOKUP_TYPE_ID = dbo.LOOKUPS.LOOKUP_TYPE_ID
WHERE     (dbo.LOOKUP_TYPES.CODE = 'root_cause_types') AND (dbo.LOOKUPS.ACTIVE_FLAG <> 'N') AND (dbo.LOOKUP_TYPES.ACTIVE_FLAG <> 'N')

