CREATE VIEW dbo.SCH_RESOURCE_DATES_V
AS
SELECT     TOP 100 PERCENT dbo.SCH_RESOURCES.SCH_RESOURCE_ID, dbo.SCH_RESOURCES.RESOURCE_ID, dbo.SCH_RESOURCES.JOB_ID, 
                      dbo.SCH_RESOURCES.SERVICE_ID, dbo.SCH_RESOURCES.RES_START_DATE, dbo.SCH_RESOURCES.RES_END_DATE, CAST(CONVERT(varchar(12), 
                      dbo.SCH_RESOURCES.RES_START_DATE + dbo.NUMBERS.number, 101) AS datetime) AS exploded_date
FROM         dbo.SCH_RESOURCES INNER JOIN
                      dbo.NUMBERS ON DATEDIFF(day, dbo.SCH_RESOURCES.RES_START_DATE, ISNULL(dbo.SCH_RESOURCES.RES_END_DATE, GETDATE())) 
                      >= dbo.NUMBERS.number
ORDER BY CAST(CONVERT(varchar(12), dbo.SCH_RESOURCES.RES_START_DATE + dbo.NUMBERS.number, 101) AS datetime) DESC

