CREATE VIEW dbo.SCH_REQUEST_VENDORS_V
AS
SELECT     dbo.SERVICES.SERVICE_ID, dbo.PROJECTS.PROJECT_ID, dbo.REQUEST_VENDORS.REQUEST_ID, dbo.REQUEST_VENDORS.REQUEST_VENDOR_ID, 
                      dbo.PROJECTS.PROJECT_NO, dbo.REQUESTS.REQUEST_NO, dbo.SERVICES.EST_START_DATE, dbo.SERVICES.EST_START_TIME, 
                      dbo.SERVICES.EST_END_DATE
FROM         dbo.SERVICES INNER JOIN
                      dbo.REQUESTS ON dbo.SERVICES.REQUEST_ID = dbo.REQUESTS.REQUEST_ID INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.PROJECTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.REQUEST_VENDORS ON dbo.REQUESTS.REQUEST_ID = dbo.REQUEST_VENDORS.REQUEST_ID AND 
                      dbo.REQUESTS.FURNITURE1_CONTACT_ID = dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID AND 
                      dbo.CUSTOMERS.A_M_FURNITURE1_CONTACT_ID = dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID

