CREATE VIEW dbo.SCH_JOBS_REPORT_V
AS
SELECT     dbo.PROJECTS_V.ORGANIZATION_ID, dbo.PROJECTS_V.PROJECT_ID, dbo.PROJECTS_V.PROJECT_NO, dbo.PROJECTS_V.JOB_NAME, 
                      dbo.PROJECTS_V.project_status_type_name, dbo.JOBS.JOB_STATUS_TYPE_ID, JOB_STATUS_TYPE.CODE AS job_status_type_code, 
                      JOB_STATUS_TYPE.NAME AS job_status_type_name, dbo.JOBS.JOB_NO, dbo.SERVICES.SERVICE_NO, dbo.REQUESTS.DEALER_PO_NO, 
                      dbo.PROJECTS_V.CUSTOMER_NAME, dbo.REQUESTS.DESCRIPTION, CONTACTS_1.CONTACT_NAME AS sales_rep_name, 
                      CONTACTS_2.CONTACT_NAME AS sales_sup_name, CONTACTS_3.CONTACT_NAME AS project_mgr_name, 
                      CONTACTS_4.CONTACT_NAME AS a_m_name, MIN(dbo.REQUESTS.EST_START_DATE) AS job_start_date, MAX(dbo.REQUESTS.EST_END_DATE) 
                      AS job_end_date
FROM         dbo.LOOKUPS JOB_STATUS_TYPE RIGHT OUTER JOIN
                      dbo.CONTACTS CONTACTS_1 RIGHT OUTER JOIN
                      dbo.CONTACTS CONTACTS_2 RIGHT OUTER JOIN
                      dbo.CONTACTS CONTACTS_3 RIGHT OUTER JOIN
                      dbo.CONTACTS CONTACTS_4 RIGHT OUTER JOIN
                      dbo.REQUESTS ON CONTACTS_4.CONTACT_ID = dbo.REQUESTS.A_M_CONTACT_ID ON 
                      CONTACTS_3.CONTACT_ID = dbo.REQUESTS.D_PROJ_MGR_CONTACT_ID ON 
                      CONTACTS_2.CONTACT_ID = dbo.REQUESTS.D_SALES_SUP_CONTACT_ID ON 
                      CONTACTS_1.CONTACT_ID = dbo.REQUESTS.D_SALES_REP_CONTACT_ID RIGHT OUTER JOIN
                      dbo.JOBS RIGHT OUTER JOIN
                      dbo.SERVICES ON dbo.JOBS.JOB_ID = dbo.SERVICES.JOB_ID ON dbo.REQUESTS.REQUEST_ID = dbo.SERVICES.REQUEST_ID ON 
                      JOB_STATUS_TYPE.LOOKUP_ID = dbo.JOBS.JOB_STATUS_TYPE_ID RIGHT OUTER JOIN
                      dbo.PROJECTS_V ON dbo.JOBS.PROJECT_ID = dbo.PROJECTS_V.PROJECT_ID
GROUP BY dbo.PROJECTS_V.PROJECT_ID, dbo.JOBS.JOB_STATUS_TYPE_ID, dbo.PROJECTS_V.PROJECT_NO, dbo.PROJECTS_V.CUSTOMER_NAME, 
                      dbo.PROJECTS_V.JOB_NAME, dbo.PROJECTS_V.project_status_type_name, JOB_STATUS_TYPE.CODE, JOB_STATUS_TYPE.NAME, 
                      dbo.PROJECTS_V.ORGANIZATION_ID, dbo.JOBS.JOB_NO, dbo.SERVICES.SERVICE_NO, dbo.REQUESTS.DEALER_PO_NO, 
                      dbo.REQUESTS.DESCRIPTION, CONTACTS_1.CONTACT_NAME, CONTACTS_2.CONTACT_NAME, CONTACTS_3.CONTACT_NAME, 
                      CONTACTS_4.CONTACT_NAME

