CREATE VIEW dbo.SERVICE_ACCOUNT_REPORT_TEMP
AS
SELECT     dbo.jobs_v.job_id, dbo.jobs_v.job_no, dbo.jobs_v.job_name, dbo.jobs_v.job_no_name, dbo.jobs_v.job_type_id, dbo.jobs_v.job_type_code, 
                      dbo.jobs_v.job_type_name, dbo.jobs_v.job_status_type_id, dbo.jobs_v.job_status_type_code, dbo.jobs_v.job_status_type_name, 
                      dbo.jobs_v.job_status_seq_no, dbo.jobs_v.customer_id, dbo.jobs_v.organization_id, dbo.jobs_v.dealer_name, dbo.jobs_v.ext_dealer_id, 
                      dbo.jobs_v.customer_name, dbo.jobs_v.ext_customer_id, dbo.INVOICES.INVOICE_ID, dbo.INVOICES.PO_NO, 
                      dbo.INVOICES.STATUS_ID AS invoice_status_id, dbo.INVOICE_STATUSES.CODE AS invoice_status_code, 
                      dbo.INVOICE_STATUSES.NAME AS invoice_status_name, dbo.INVOICES.DESCRIPTION AS Invoice_Desc, dbo.SERVICES.SERVICE_ID, 
                      dbo.SERVICES.SERVICE_NO, dbo.SERVICE_LINES.SERVICE_LINE_ID, dbo.SERVICES.DESCRIPTION, dbo.SERVICES.EST_START_DATE, 
                      dbo.SERVICES.SCH_START_DATE, dbo.SERVICES.PO_NO AS req_po_no, dbo.SERVICE_LINES.BILL_SERVICE_LINE_NO, 
                      dbo.SERVICE_LINES.SERVICE_LINE_DATE, dbo.SERVICE_LINES.STATUS_ID AS serv_line_status_id, dbo.SERVICE_LINES.TC_SERVICE_LINE_NO, 
                      dbo.SERVICE_LINES.TAXABLE_FLAG, dbo.SERVICE_LINES.bill_total, dbo.SERVICE_LINE_STATUSES.CODE AS serv_line_status_code, 
                      dbo.SERVICE_LINE_STATUSES.NAME AS serv_line_status_name, dbo.RESOURCES.RESOURCE_TYPE_ID, 
                      dbo.RESOURCE_TYPES_V.resource_type_code, dbo.RESOURCE_TYPES_V.resource_type_name, 
                      dbo.RESOURCES.RES_CATEGORY_TYPE_ID AS res_cat_type_id, res_cat_types.CODE AS res_cat_type_code, 
                      res_cat_types.NAME AS res_cat_type_name, dbo.SERVICE_LINES.ITEM_ID, dbo.ITEMS_V.NAME AS item_name, dbo.ITEMS_V.ITEM_TYPE_ID, 
                      dbo.ITEMS_V.item_type_name, dbo.ITEMS_V.item_type_code, dbo.ITEMS_V.BILLABLE_FLAG, dbo.SERVICE_LINES.EXT_PAY_CODE, 
                      dbo.SERVICE_LINES.BILLABLE_FLAG AS SL_BILLABLE_FLAG, dbo.SERVICE_LINES.BILL_HOURLY_RATE AS hourly_rate, 
                      dbo.SERVICE_LINES.BILL_EXP_RATE AS expense_rate, dbo.SERVICE_LINES.BILL_QTY, dbo.CUSTOM_CUST_COLUMNS_V.col1, 
                      dbo.CUSTOM_CUST_COLUMNS_V.col1_active_flag AS col1_enabled, dbo.SERVICES.CUST_COL_1, dbo.CUSTOM_CUST_COLUMNS_V.col2, 
                      dbo.CUSTOM_CUST_COLUMNS_V.col2_active_flag AS col2_enabled, dbo.SERVICES.CUST_COL_2, dbo.CUSTOM_CUST_COLUMNS_V.col3, 
                      dbo.CUSTOM_CUST_COLUMNS_V.col3_active_flag AS col3_enabled, dbo.SERVICES.CUST_COL_3, dbo.CUSTOM_CUST_COLUMNS_V.col4, 
                      dbo.CUSTOM_CUST_COLUMNS_V.col4_active_flag AS col4_enabled, dbo.SERVICES.CUST_COL_4, dbo.CUSTOM_CUST_COLUMNS_V.col5, 
                      dbo.CUSTOM_CUST_COLUMNS_V.col5_active_flag AS col5_enabled, dbo.SERVICES.CUST_COL_5, dbo.CUSTOM_CUST_COLUMNS_V.col6, 
                      dbo.CUSTOM_CUST_COLUMNS_V.col6_active_flag AS col6_enabled, dbo.SERVICES.CUST_COL_6, dbo.CUSTOM_CUST_COLUMNS_V.col7, 
                      dbo.CUSTOM_CUST_COLUMNS_V.col7_active_flag AS col7_enabled, dbo.SERVICES.CUST_COL_7, dbo.CUSTOM_CUST_COLUMNS_V.col8, 
                      dbo.CUSTOM_CUST_COLUMNS_V.col8_active_flag AS col8_enabled, dbo.SERVICES.CUST_COL_8, dbo.CUSTOM_CUST_COLUMNS_V.col9, 
                      dbo.CUSTOM_CUST_COLUMNS_V.col9_active_flag AS col9_enabled, dbo.SERVICES.CUST_COL_9, dbo.CUSTOM_CUST_COLUMNS_V.col10, 
                      dbo.CUSTOM_CUST_COLUMNS_V.col10_active_flag AS col10_enabled, dbo.SERVICES.CUST_COL_10, 
                      (CASE WHEN dbo.ITEMS_V.name NOT IN ('Keys', 'Keys-F', 'Keys-OH', 'Keys-S', 'Keys-W', 'baggies-s', 'baggies', 'baggies-w', 'baggies-f', 'boxes-s', 
                      'boxes', 'boxes-w', 'boxes-f', 'Equip Rental-S', 'Equip Rental', 'Equip Rental-W', 'Equip Rental-F
