CREATE VIEW dbo.SERVICE_LINE_TYPES_V
AS
SELECT     TOP 100 PERCENT dbo.LOOKUPS.LOOKUP_ID, dbo.LOOKUPS.CODE, dbo.LOOKUPS.NAME
FROM         dbo.LOOKUP_TYPES INNER JOIN
                      dbo.LOOKUPS ON dbo.LOOKUP_TYPES.LOOKUP_TYPE_ID = dbo.LOOKUPS.LOOKUP_TYPE_ID
WHERE     (dbo.LOOKUP_TYPES.CODE = 'service_line_type') AND (dbo.LOOKUPS.ACTIVE_FLAG <> 'N') AND (dbo.LOOKUP_TYPES.ACTIVE_FLAG <> 'N')
ORDER BY dbo.LOOKUPS.SEQUENCE_NO

