CREATE VIEW dbo.SERVICE_LINES_SCHD_V
AS
SELECT     dbo.SCH_RESOURCES_V.SCH_RESOURCE_ID, dbo.SCH_RESOURCE_DATES_V.exploded_date, dbo.SERVICE_LINES.SERVICE_LINE_ID
FROM         dbo.SCH_RESOURCES_V INNER JOIN
                      dbo.SCH_RESOURCE_DATES_V ON 
                      dbo.SCH_RESOURCES_V.SCH_RESOURCE_ID = dbo.SCH_RESOURCE_DATES_V.SCH_RESOURCE_ID LEFT OUTER JOIN
                      dbo.SERVICE_LINES ON dbo.SCH_RESOURCE_DATES_V.exploded_date = dbo.SERVICE_LINES.SERVICE_LINE_DATE AND 
                      dbo.SCH_RESOURCE_DATES_V.SERVICE_ID = dbo.SERVICE_LINES.TC_SERVICE_ID AND 
                      dbo.SCH_RESOURCE_DATES_V.RESOURCE_ID = dbo.SERVICE_LINES.RESOURCE_ID

