CREATE VIEW dbo.SURVEY_REQUEST_VENDORS_V
AS
SELECT     TOP 100 PERCENT dbo.REQUESTS.PROJECT_ID, dbo.REQUEST_VENDORS.REQUEST_ID, dbo.REQUEST_VENDORS.REQUEST_VENDOR_ID, 
                      dbo.REQUEST_VENDORS.COMPLETE_FLAG
FROM         dbo.CUSTOMERS INNER JOIN
                      dbo.CONTACTS ON dbo.CUSTOMERS.A_M_FURNITURE1_CONTACT_ID = dbo.CONTACTS.CONTACT_ID INNER JOIN
                      dbo.REQUEST_VENDORS ON dbo.CONTACTS.CONTACT_ID = dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID INNER JOIN
                      dbo.REQUESTS ON dbo.REQUEST_VENDORS.REQUEST_ID = dbo.REQUESTS.REQUEST_ID INNER JOIN
                      dbo.PROJECTS ON dbo.CUSTOMERS.CUSTOMER_ID = dbo.PROJECTS.CUSTOMER_ID AND 
                      dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.SURVEY_TEST_V ON dbo.PROJECTS.PROJECT_ID = dbo.SURVEY_TEST_V.PROJECT_ID
WHERE     (dbo.REQUEST_VENDORS.COMPLETE_FLAG = 'Y')
ORDER BY dbo.REQUESTS.PROJECT_ID, dbo.REQUEST_VENDORS.REQUEST_ID, dbo.REQUEST_VENDORS.REQUEST_VENDOR_ID

