CREATE VIEW dbo.SURVEY_TEST_V

AS

SELECT     dbo.REQUESTS.PROJECT_ID, ISNULL(dbo.CUSTOMERS.SURVEY_LAST_COUNT, 0) AS survey_last_count, 

                      ISNULL(dbo.CUSTOMERS.SURVEY_FREQUENCY, 0) AS survey_frequency, COUNT(dbo.REQUEST_VENDORS.COMPLETE_FLAG) AS sum_complete, 

                      dbo.CUSTOMERS.SURVEY_LOCATION

FROM         dbo.CUSTOMERS INNER JOIN

                      dbo.CONTACTS ON dbo.CUSTOMERS.A_M_FURNITURE1_CONTACT_ID = dbo.CONTACTS.CONTACT_ID INNER JOIN

                      dbo.REQUEST_VENDORS ON dbo.CONTACTS.CONTACT_ID = dbo.REQUEST_VENDORS.VENDOR_CONTACT_ID INNER JOIN

                      dbo.REQUESTS ON dbo.REQUEST_VENDORS.REQUEST_ID = dbo.REQUESTS.REQUEST_ID INNER JOIN

                      dbo.PROJECTS ON dbo.CUSTOMERS.CUSTOMER_ID = dbo.PROJECTS.CUSTOMER_ID AND 

                      dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID

GROUP BY dbo.REQUEST_VENDORS.COMPLETE_FLAG, ISNULL(dbo.CUSTOMERS.SURVEY_FREQUENCY, 0), ISNULL(dbo.CUSTOMERS.SURVEY_LAST_COUNT,

                       0), dbo.CUSTOMERS.SURVEY_LOCATION, dbo.REQUESTS.PROJECT_ID

HAVING      (dbo.REQUEST_VENDORS.COMPLETE_FLAG = 'Y')



