CREATE VIEW dbo.TABS_V2
AS
SELECT DISTINCT 
                      TOP 100 PERCENT dbo.TEMPLATES.TEMPLATE_NAME, dbo.TABS.NAME, dbo.TABS.SEQUENCE, dbo.TABS.TYPE_CODE, dbo.TABS.DEFAULT_TAB, 
                      dbo.TABS.TABLE_ID, dbo.USER_ROLES.USER_ID, dbo.TABS.TAB_LEVEL, dbo.FUNCTIONS.FUNCTION_ID, dbo.FUNCTIONS.NAME AS Expr1, 
                      dbo.TEMPLATES.TEMPLATE_ID, dbo.FUNCTIONS.FUNCTION_GROUP_ID, dbo.FUNCTION_GROUPS.CODE AS FUNCTION_TYPE_CODE
FROM         dbo.ROLES INNER JOIN
                      dbo.ROLE_FUNCTION_RIGHTS ON dbo.ROLES.ROLE_ID = dbo.ROLE_FUNCTION_RIGHTS.ROLE_ID INNER JOIN
                      dbo.FUNCTIONS ON dbo.ROLE_FUNCTION_RIGHTS.FUNCTION_ID = dbo.FUNCTIONS.FUNCTION_ID INNER JOIN
                      dbo.TABS INNER JOIN
                      dbo.TEMPLATES ON dbo.TABS.TEMPLATE_ID = dbo.TEMPLATES.TEMPLATE_ID ON 
                      dbo.FUNCTIONS.TEMPLATE_ID = dbo.TEMPLATES.TEMPLATE_ID INNER JOIN
                      dbo.USER_ROLES ON dbo.ROLES.ROLE_ID = dbo.USER_ROLES.ROLE_ID INNER JOIN
                      dbo.FUNCTION_GROUPS ON dbo.FUNCTIONS.FUNCTION_GROUP_ID = dbo.FUNCTION_GROUPS.FUNCTION_GROUP_ID
WHERE     (dbo.FUNCTION_GROUPS.CODE = 'TABS')
ORDER BY dbo.TABS.TAB_LEVEL, dbo.USER_ROLES.USER_ID, dbo.TABS.SEQUENCE

