CREATE VIEW dbo.Taxes_V
AS
SELECT     TOP 100 PERCENT AMBIM.dbo.IV00101.ITEMNMBR, AMBIM.dbo.IV00101.TAXOPTNS, AMBIM.dbo.RM00101.CUSTNMBR, 
                      AMBIM.dbo.RM00101.TAXSCHID, dbo.INVOICES.INVOICE_ID, dbo.INVOICE_LINES_V.ext_item_id, dbo.INVOICE_LINES_V.UNIT_PRICE, 
                      dbo.INVOICE_LINES_V.QTY, dbo.INVOICE_LINES_V.UNIT_PRICE * dbo.INVOICE_LINES_V.QTY AS Total_line, 
                      dbo.INVOICE_LINES_V.UNIT_PRICE * dbo.INVOICE_LINES_V.QTY * .07 AS line_tax, dbo.INVOICES.ORGANIZATION_ID
FROM         dbo.INVOICES INNER JOIN
                      AMBIM.dbo.RM00101 ON CAST(dbo.INVOICES.EXT_BILL_CUST_ID AS char(15)) = AMBIM.dbo.RM00101.CUSTNMBR INNER JOIN
                      AMBIM.dbo.IV00101 INNER JOIN
                      dbo.INVOICE_LINES_V ON AMBIM.dbo.IV00101.ITEMNMBR = CAST(dbo.INVOICE_LINES_V.ext_item_id AS char(31)) ON 
                      dbo.INVOICES.INVOICE_ID = dbo.INVOICE_LINES_V.INVOICE_ID
WHERE     (dbo.INVOICES.ORGANIZATION_ID = 2) AND (AMBIM.dbo.RM00101.TAXSCHID <> 'EXEMPT')
ORDER BY dbo.INVOICES.INVOICE_ID


