
CREATE VIEW dbo.TEMPLATE_LOCATIONS_1_V
AS
SELECT     dbo.TEMPLATE_LOCATIONS.LOCATION, TEMPLATES_1.TEMPLATE_NAME, TEMPLATES1.TEMPLATE_NAME AS TAB_NAME
FROM         dbo.TEMPLATES TEMPLATES1 INNER JOIN
                      dbo.TABS INNER JOIN
                      dbo.TEMPLATE_LOCATIONS ON dbo.TABS.TAB_ID = dbo.TEMPLATE_LOCATIONS.LEVEL_1_TAB INNER JOIN
                      dbo.TEMPLATES TEMPLATES_1 ON dbo.TEMPLATE_LOCATIONS.LEVEL_1_TEMPLATE = TEMPLATES_1.TEMPLATE_ID ON 
                      TEMPLATES1.TEMPLATE_ID = dbo.TABS.TEMPLATE_ID


