CREATE VIEW dbo.TEMPLATE_LOCATIONS_4_V
AS
SELECT     dbo.TEMPLATE_LOCATIONS.LOCATION, TEMPLATES_1.TEMPLATE_NAME, TEMPLATES1.TEMPLATE_NAME AS TAB_NAME, dbo.TABS.TYPE_CODE, 
                      dbo.TABS.TAB_LEVEL
FROM         dbo.TABS INNER JOIN
                      dbo.TEMPLATES TEMPLATES1 ON dbo.TABS.TEMPLATE_ID = TEMPLATES1.TEMPLATE_ID INNER JOIN
                      dbo.TEMPLATES TEMPLATES_1 INNER JOIN
                      dbo.TEMPLATE_LOCATIONS ON TEMPLATES_1.TEMPLATE_ID = dbo.TEMPLATE_LOCATIONS.LEVEL_3_TEMPLATE ON 
                      dbo.TABS.TAB_ID = dbo.TEMPLATE_LOCATIONS.LEVEL_3_TAB
WHERE     (dbo.TABS.TYPE_CODE = 'JOB_BILL')

