
CREATE VIEW dbo.TEMPLATE_LOCATIONS_2_V
AS
SELECT     dbo.TEMPLATE_LOCATIONS.LOCATION, TEMPLATES_1.TEMPLATE_NAME, TEMPLATES1.TEMPLATE_NAME AS TAB_NAME
FROM         dbo.TABS INNER JOIN
                      dbo.TEMPLATES TEMPLATES1 ON dbo.TABS.TEMPLATE_ID = TEMPLATES1.TEMPLATE_ID INNER JOIN
                      dbo.TEMPLATES TEMPLATES_1 INNER JOIN
                      dbo.TEMPLATE_LOCATIONS ON TEMPLATES_1.TEMPLATE_ID = dbo.TEMPLATE_LOCATIONS.LEVEL_2_TEMPLATE ON 
                      dbo.TABS.TAB_ID = dbo.TEMPLATE_LOCATIONS.LEVEL_2_TAB


