CREATE VIEW dbo.UNVERIFIED_HRS_V
AS
SELECT     dbo.TIME_CAPTURE_V.ORGANIZATION_ID, dbo.TIME_CAPTURE_V.TC_JOB_ID, dbo.TIME_CAPTURE_V.TC_SERVICE_ID, 
                      dbo.TIME_CAPTURE_V.SERVICE_LINE_ID, dbo.TIME_CAPTURE_V.TC_JOB_NO, dbo.TIME_CAPTURE_V.TC_SERVICE_NO, 
                      dbo.TIME_CAPTURE_V.TC_SERVICE_LINE_NO, dbo.JOBS_V.JOB_NAME, dbo.JOBS_V.FOREMAN_RESOURCE_ID, 
                      dbo.JOBS_V.foreman_resource_name, dbo.TIME_CAPTURE_V.SERVICE_LINE_DATE, dbo.TIME_CAPTURE_V.STATUS_ID, 
                      dbo.TIME_CAPTURE_V.status_name, dbo.TIME_CAPTURE_V.RESOURCE_ID, dbo.RESOURCES_V.USER_ID, dbo.RESOURCES_V.EXT_EMPLOYEE_ID, 
                      dbo.RESOURCES_V.user_full_name AS employee_name, dbo.TIME_CAPTURE_V.ITEM_NAME, dbo.TIME_CAPTURE_V.PAYROLL_QTY, 
                      dbo.TIME_CAPTURE_V.PAYROLL_TOTAL, dbo.TIME_CAPTURE_V.EXPENSE_QTY, dbo.TIME_CAPTURE_V.EXPENSE_RATE, 
                      dbo.TIME_CAPTURE_V.EXPENSE_TOTAL, dbo.TIME_CAPTURE_V.TC_TOTAL, dbo.TIME_CAPTURE_V.BILL_HOURLY_QTY, 
                      dbo.TIME_CAPTURE_V.BILL_HOURLY_RATE, dbo.TIME_CAPTURE_V.BILL_HOURLY_TOTAL, dbo.TIME_CAPTURE_V.BILL_EXP_QTY, 
                      dbo.TIME_CAPTURE_V.BILL_EXP_RATE, dbo.TIME_CAPTURE_V.BILL_EXP_TOTAL, dbo.TIME_CAPTURE_V.BILL_RATE, 
                      dbo.TIME_CAPTURE_V.BILL_TOTAL, dbo.TIME_CAPTURE_V.EXT_PAY_CODE
FROM         dbo.TIME_CAPTURE_V LEFT OUTER JOIN
                      dbo.RESOURCES_V ON dbo.TIME_CAPTURE_V.RESOURCE_ID = dbo.RESOURCES_V.RESOURCE_ID LEFT OUTER JOIN
                      dbo.JOBS_V ON dbo.TIME_CAPTURE_V.TC_JOB_ID = dbo.JOBS_V.JOB_ID
WHERE     (dbo.TIME_CAPTURE_V.STATUS_ID < 2)



