
CREATE VIEW dbo.USER_CUSTOMERS_V
AS
SELECT     dbo.USER_CUSTOMERS.user_id, dbo.CUSTOMERS.CUSTOMER_ID
FROM         dbo.CUSTOMERS INNER JOIN
                      dbo.USER_CUSTOMERS ON dbo.CUSTOMERS.PARENT_CUSTOMER_ID = dbo.USER_CUSTOMERS.customer_id
UNION
SELECT     dbo.USER_CUSTOMERS.user_id, dbo.USER_CUSTOMERS.customer_id
FROM         dbo.USER_CUSTOMERS


