CREATE VIEW dbo.USER_RESOURCES_V
AS
SELECT     dbo.USERS.USER_ID, CAST(dbo.USERS.EXT_EMPLOYEE_ID AS NUMERIC) AS emp_no, 
                      dbo.USERS.FIRST_NAME + ' ' + dbo.USERS.LAST_NAME AS employee_name, dbo.RESOURCES.ORGANIZATION_ID, dbo.RESOURCES.RESOURCE_ID, 
                      dbo.USERS.EMPLOYMENT_TYPE_ID, dbo.LOOKUPS.CODE, dbo.LOOKUPS.NAME, dbo.RESOURCES.ACTIVE_FLAG
FROM         dbo.USERS INNER JOIN
                      dbo.RESOURCES ON dbo.USERS.USER_ID = dbo.RESOURCES.USER_ID LEFT OUTER JOIN
                      dbo.LOOKUPS ON dbo.USERS.EMPLOYMENT_TYPE_ID = dbo.LOOKUPS.LOOKUP_ID


