CREATE VIEW dbo.VAR_JOB_EST_HOURS_V
AS
SELECT     dbo.JOBS.JOB_ID, SUM(cast(ISNULL(dbo.RESOURCE_ESTIMATES.TOTAL_HOURS,0.0) as decimal)) AS sum_estimated_hours
FROM         dbo.JOBS LEFT OUTER JOIN
                      dbo.RESOURCE_ESTIMATES ON dbo.JOBS.JOB_ID = dbo.RESOURCE_ESTIMATES.JOB_ID LEFT OUTER JOIN
                      dbo.ITEMS ITEMS_2 LEFT OUTER JOIN
                      dbo.LOOKUPS ITEM_TYPE ON ITEMS_2.ITEM_TYPE_ID = ITEM_TYPE.LOOKUP_ID RIGHT OUTER JOIN
                      dbo.JOB_ITEM_RATES ON ITEMS_2.ITEM_ID = dbo.JOB_ITEM_RATES.ITEM_ID ON 
                      dbo.RESOURCE_ESTIMATES.JOB_ITEM_RATE_ID = dbo.JOB_ITEM_RATES.JOB_ITEM_RATE_ID
GROUP BY dbo.JOBS.JOB_ID






