CREATE VIEW dbo.VERSIONS_MAX_NO_V
AS
SELECT     dbo.PROJECTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, dbo.REQUESTS.REQUEST_NO, MAX(dbo.REQUESTS.VERSION_NO) 
                      AS max_version_no
FROM         dbo.REQUESTS RIGHT OUTER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID
GROUP BY dbo.REQUESTS.REQUEST_NO, dbo.PROJECTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO

