INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Complete and accurate furniture specifications, and clear, detailed installation drawings are required one week before commencement of installation and reconfiguration work.' ,1, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('<?d:end_name?> is responsible for clearing any desktops. shelving, filing, pedestals or overhead contents prior to moving or reconfiguration services.' ,2, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Standard pricing is based on all work will be performed by non-union labor during normal business hours (7:00 a.m. - 4:30 p.m.), services performed after normal working hours (4:30 p.m. or later, weekends, and holidays) are shown as a labor up charge in the pricing and will be billed at the appropriate rate.' ,3, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('To complete the entire as outlined, we will require free and clear access to loading docks, elevators and job sites to move products and equipment over <?d:days?> consecutive, normal working days. Additional work trips will be billed at the approved rate.' ,4, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Additional charges will result if a "stair carry" is necessary.' ,5, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Adequate permits and scheduling for building access are the responsibility of <?d:company_name?> . It is the responsibility of <?d:company_name?> to schedule delivery into the building.' ,6, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Omni will assist <?d:company_name?> in determining the delivery schedule and what furniture items will arrive on what day and time. Additional charges will result to receive trucks early, late, or out of sequence.' ,7, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('<?d:company_name?> and or <?d:end_name?> will provide a representative at the time furniture product is received to verify shipment and condition. After that point the client is in control of care and custody of the delivered product, and are responsible for any loss, theft or damage incurred other than damage caused during installation of the product.' ,8, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Adequate area for staging by the installation area will be required, if not, there will be additional charges at hourly rates to "double handle" furniture.' ,9, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Only panel-to-panel connectors and duplex receptacles within the panel system will be installed by <?d:code?> employees unless otherwise specified. The connection between the furniture system and the base building electrical system is the customer’s responsibility.' ,10, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('All time, cost and resources for disconnecting and reconnecting phones, cabling and computer equipment are the customer’s responsibility. <?d:code?> will work with these vendors to complete the furniture installation to a predetermined plan and schedule.' ,11, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('To ensure a safe work environment the space will be free and clear for installation, adequately heated, ventilated, or air- conditioned, supplied with electricity and within close proximity to running water.' ,12, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Our estimate is based on receiving product in it’s standard shipping method from the manufacture. Additional charges will result if products received are not in this form.' ,13, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Re-inspections required due to missing product or layout issues are the responsibility of Customer and <?d:code?> assumes no financial responsibility.' ,14, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('The client is responsible for providing adequate trash receptacles for the disposal of furniture-related packaging materials generated by this project, unless trash removal has been included in our proposal.' ,15, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Our estimate includes an on-site Supervisor at all times during the project as outlined in the proposed schedule.' ,16, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('All additional work requests or changes to the original scope of work will be in writing and approved by an authorized customer representative before <?d:code?> will begin work. If changes are requested, <?d:code?> may complete the change with the assigned crew after normal working hours at the overtime rate if it is necessary in order to remain on schedule.' ,17, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('<?d:code?> will accommodate changes to the installation layout or design during the reconfiguration with the customer’s written approval. <?d:code?> will determine additional time and cost for these changes based on impact to the schedule.' ,18, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Follow up items will be addressed based on a priorities determined by the client and our Site Supervisor.' ,19, getDate() ,0)
GO
INSERT INTO [STANDARD_CONDITIONS] ([name] ,[sequence_no] ,[date_created] ,[created_by]) VALUES ('Our estimate specifies that project area will be left "broom-cleaned" at the completion of work unless otherwise specified. Furniture will be wiped down, tags removed and any glass cleaned one time upon the completion of installation' ,20, getDate() ,0)
GO

