DROP INDEX INVOICES.IX_I_ORGANIZATIONS
GO


CREATE INDEX [IX_S_ID_SERVICE_NO] ON [DBO].[SERVICES] ( [SERVICE_ID] ASC, [SERVICE_NO] ASC)
GO


CREATE INDEX [IX_CUSTOMERS2] ON [DBO].[CUSTOMERS] ( [CUSTOMER_ID] ASC, [ORGANIZATION_ID] ASC, [CUSTOMER_NAME] ASC, [CUSTOMER_TYPE_ID] ASC, [END_USER_PARENT_ID] ASC)
GO

 CREATE  INDEX [IX_L_CODE] ON [DBO].[LOOKUPS]([CODE]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [IX_L_LID_NAME] ON [DBO].[LOOKUPS]([LOOKUP_ID], [NAME]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [IX_L_LID_CODE] ON [DBO].[LOOKUPS]([LOOKUP_ID], [CODE]) ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [IX_L_LID_CODE_NAME] ON [DBO].[LOOKUPS]([LOOKUP_ID], [CODE], [NAME]) ON [PRIMARY]
GO




 CREATE  UNIQUE  INDEX [IX_CONTACTS_NAME1] ON [DBO].[CONTACTS]([CONTACT_ID], [CONTACT_NAME]) WITH  FILLFACTOR = 90 ON [PRIMARY]
GO


 CREATE  INDEX [IX_CUSTOMER_TYPE] ON [DBO].[CUSTOMERS]([CUSTOMER_TYPE_ID]) WITH  FILLFACTOR = 90 ON [PRIMARY]
GO

 CREATE  UNIQUE  INDEX [IX_CUSTOMER_TYPE_NAME] ON [DBO].[CUSTOMERS]([CUSTOMER_ID], [CUSTOMER_TYPE_ID], [CUSTOMER_NAME]) WITH  FILLFACTOR = 90 ON [PRIMARY]
GO



 CREATE  UNIQUE  INDEX [IX_JL_NAME] ON [DBO].[JOB_LOCATIONS]([JOB_LOCATION_ID], [JOB_LOCATION_NAME]) ON [PRIMARY]
GO



 CREATE  INDEX [IX_JLC_JOB_LOCATION] ON [DBO].[JOB_LOCATION_CONTACTS]([JOB_LOCATION_ID]) ON [PRIMARY]
GO




 CREATE  INDEX [IX_REQUESTS_JLC] ON [DBO].[REQUESTS]([JOB_LOCATION_CONTACT_ID]) ON [PRIMARY]
GO



 CREATE  INDEX [IX_SERVICES_JOB_LOCATION] ON [DBO].[SERVICES]([JOB_LOCATION_ID]) ON [PRIMARY]
GO


/*
 CREATE  INDEX [IX_SL_BILL] ON [DBO].[SERVICE_LINES]([BILL_SERVICE_ID], [BILL_JOB_ID], [INVOICE_ID]) ON [PRIMARY]
GO


 CREATE  INDEX [IX_SL_BILL_ITEM_TC_QTY] ON [DBO].[SERVICE_LINES]([BILL_SERVICE_ID], [ITEM_NAME], [TC_QTY]) ON [PRIMARY]
GO
*/



 CREATE  INDEX [JIR_EXT_RATE_ID] ON [DBO].[JOB_ITEM_RATES]([ITEM_ID], [EXT_RATE_ID]) ON [PRIMARY]
GO



CREATE STATISTICS [hind_172735868_12A_1A] ON [dbo].[INVOICES] ( [JOB_ID], [INVOICE_ID])
CREATE STATISTICS [hind_172735868_1A_12A] ON [dbo].[INVOICES] ( [INVOICE_ID], [JOB_ID])
CREATE STATISTICS [hind_232752282_2A_1A] ON [dbo].[SERVICES] ( [JOB_ID], [SERVICE_ID])
CREATE STATISTICS [hind_268580045_3A_1A] ON [dbo].[PROJECTS] ( [CUSTOMER_ID], [PROJECT_ID])
CREATE STATISTICS [hind_268580045_1A_3A_8A] ON [dbo].[PROJECTS] ( [PROJECT_ID], [CUSTOMER_ID], [CREATED_BY])
CREATE STATISTICS [hind_391164639_11A_21A] ON [dbo].[SERVICE_LINES] ( [STATUS_ID], [RESOURCE_ID])
CREATE STATISTICS [hind_391164639_21A_11A] ON [dbo].[SERVICE_LINES] ( [RESOURCE_ID], [STATUS_ID])
CREATE STATISTICS [hind_455321032_2A_3A] ON [dbo].[REQUEST_VENDORS] ( [REQUEST_ID], [VENDOR_CONTACT_ID])
CREATE STATISTICS [hind_474692989_1A_3A] ON [dbo].[USERS] ( [USER_ID], [CONTACT_ID])
CREATE STATISTICS [hind_474692989_1A_2A] ON [dbo].[USERS] ( [USER_ID], [EXT_EMPLOYEE_ID])
CREATE STATISTICS [hind_507305017_2A_3A_4A_5A_9A_1A_6A_11A] ON [dbo].[INVOICE_TRACKING] ( [INVOICE_ID], [INVOICE_TRACKING_TYPE_ID], [TO_CONTACT_ID], [FROM_USER_ID], [EMAIL_SENT_FLAG], [INVOICE_TRACKING_ID], [NOTES], [DATE_CREATED])
CREATE STATISTICS [hind_507305017_2A_1A_3A_4A_5A_6A_9A_11A] ON [dbo].[INVOICE_TRACKING] ( [INVOICE_ID], [INVOICE_TRACKING_ID], [INVOICE_TRACKING_TYPE_ID], [TO_CONTACT_ID], [FROM_USER_ID], [NOTES], [EMAIL_SENT_FLAG], [DATE_CREATED])
CREATE STATISTICS [hind_549733161_3A_1A] ON [dbo].[RESOURCES] ( [NAME], [RESOURCE_ID])
CREATE STATISTICS [hind_549733161_1A_3A] ON [dbo].[RESOURCES] ( [RESOURCE_ID], [NAME])
CREATE STATISTICS [hind_549733161_3A_6A] ON [dbo].[RESOURCES] ( [NAME], [USER_ID])
CREATE STATISTICS [hind_549733161_6A_3A] ON [dbo].[RESOURCES] ( [USER_ID], [NAME])
CREATE STATISTICS [hind_549733161_1A_6A_3A] ON [dbo].[RESOURCES] ( [RESOURCE_ID], [USER_ID], [NAME])
CREATE STATISTICS [hind_549733161_6A_1A_3A] ON [dbo].[RESOURCES] ( [USER_ID], [RESOURCE_ID], [NAME])
CREATE STATISTICS [hind_652685523_1A_4A] ON [dbo].[LOOKUPS] ( [LOOKUP_ID], [NAME])
CREATE STATISTICS [hind_652685523_1A_10A] ON [dbo].[LOOKUPS] ( [LOOKUP_ID], [ATTRIBUTE1])
CREATE STATISTICS [hind_652685523_1A_3A_4A] ON [dbo].[LOOKUPS] ( [LOOKUP_ID], [CODE], [NAME])
CREATE STATISTICS [hind_725121874_5A_7A] ON [dbo].[JOBS] ( [JOB_TYPE_ID], [CUSTOMER_ID])
CREATE STATISTICS [hind_725121874_5A_1A] ON [dbo].[JOBS] ( [JOB_TYPE_ID], [JOB_ID])
CREATE STATISTICS [hind_725121874_7A_1A] ON [dbo].[JOBS] ( [CUSTOMER_ID], [JOB_ID])
CREATE STATISTICS [hind_725121874_7A_5A] ON [dbo].[JOBS] ( [CUSTOMER_ID], [JOB_TYPE_ID])
CREATE STATISTICS [hind_725121874_1A_5A] ON [dbo].[JOBS] ( [JOB_ID], [JOB_TYPE_ID])
CREATE STATISTICS [hind_725121874_1A_7A] ON [dbo].[JOBS] ( [JOB_ID], [CUSTOMER_ID])
CREATE STATISTICS [hind_725121874_1A_3A_5A_6A_7A_12A_18A_4A_13A] ON [dbo].[JOBS] ( [JOB_ID], [JOB_NO], [JOB_TYPE_ID], [JOB_STATUS_TYPE_ID], [CUSTOMER_ID], [CREATED_BY], [end_user_id], [JOB_NAME], [DATE_CREATED])
CREATE STATISTICS [hind_725121874_1A_3A_4A_5A_6A_7A_12A_13A_18A] ON [dbo].[JOBS] ( [JOB_ID], [JOB_NO], [JOB_NAME], [JOB_TYPE_ID], [JOB_STATUS_TYPE_ID], [CUSTOMER_ID], [CREATED_BY], [DATE_CREATED], [end_user_id])
CREATE STATISTICS [hind_812230344_2A_5A] ON [dbo].[REQUESTS] ( [PROJECT_ID], [REQUEST_STATUS_TYPE_ID])
CREATE STATISTICS [hind_1255115662_1A_21A_2A] ON [dbo].[CUSTOMERS] ( [CUSTOMER_ID], [end_user_parent_id], [ORGANIZATION_ID])
CREATE STATISTICS [hind_1255115662_1A_2A_20A_21A_6A] ON [dbo].[CUSTOMERS] ( [CUSTOMER_ID], [ORGANIZATION_ID], [customer_type_id], [end_user_parent_id], [CUSTOMER_NAME])
CREATE STATISTICS [hind_1419152101_3A_2A] ON [dbo].[TRACKING] ( [SERVICE_ID], [JOB_ID])
CREATE STATISTICS [hind_1419152101_2A_1A_3A_4A_5A_6A_7A_11A_12A] ON [dbo].[TRACKING] ( [JOB_ID], [TRACKING_ID], [SERVICE_ID], [TRACKING_TYPE_ID], [TO_CONTACT_ID], [FROM_USER_ID], [NOTES], [EMAIL_SENT_FLAG], [DATE_CREATED])
CREATE STATISTICS [hind_1419152101_2A_3A_4A_5A_6A_11A_1A_7A_12A] ON [dbo].[TRACKING] ( [JOB_ID], [SERVICE_ID], [TRACKING_TYPE_ID], [TO_CONTACT_ID], [FROM_USER_ID], [EMAIL_SENT_FLAG], [TRACKING_ID], [NOTES], [DATE_CREATED])
CREATE STATISTICS [hind_2077510730_1A_11A] ON [dbo].[CONTACTS] ( [CONTACT_ID], [EMAIL])

