package com.dynamic.charm;

/**
 * These status codes can be regenerated by running dbscripts/generate_constants.sql
 */
public interface Constants
{
	public Integer SYSTEM_USER_ID = new Integer(1);

	public final static String SESSION_ATTR_USER = "user";
	public final static String SESSION_ATTR_USER_ID = "userId";
	public final static String SESSION_ATTR_ROLE_CODE = "roleCode";
	public final static String SESSION_ATTR_ORG_ID = "organizationId";
	public final static String SESSION_ATTR_ORG_NAME = "organizationName";

	public final static Character TRUE_CHARACTER = new Character('Y');
	public final static Character FALSE_CHARACTER = new Character('N');

		

}
