

DELETE FROM cities;

INSERT INTO cities (name, state) VALUES ('Ada', 'MN');
INSERT INTO cities (name, state) VALUES ('Adams', 'MN');
INSERT INTO cities (name, state) VALUES ('Adrian', 'MN');
INSERT INTO cities (name, state) VALUES ('Afton', 'MN');
INSERT INTO cities (name, state) VALUES ('Aitkin', 'MN');
INSERT INTO cities (name, state) VALUES ('Akeley', 'MN');
INSERT INTO cities (name, state) VALUES ('Albany', 'MN');
INSERT INTO cities (name, state) VALUES ('Albert Lea', 'MN');
INSERT INTO cities (name, state) VALUES ('Alberta', 'MN');
INSERT INTO cities (name, state) VALUES ('Albertville', 'MN');
INSERT INTO cities (name, state) VALUES ('Alden', 'MN');
INSERT INTO cities (name, state) VALUES ('Aldrich', 'MN');
INSERT INTO cities (name, state) VALUES ('Alexandria', 'MN');
INSERT INTO cities (name, state) VALUES ('Alpha', 'MN');
INSERT INTO cities (name, state) VALUES ('Altura', 'MN');
INSERT INTO cities (name, state) VALUES ('Alvarado', 'MN');
INSERT INTO cities (name, state) VALUES ('Amboy', 'MN');
INSERT INTO cities (name, state) VALUES ('Andover', 'MN');
INSERT INTO cities (name, state) VALUES ('Annandale', 'MN');
INSERT INTO cities (name, state) VALUES ('Anoka', 'MN');
INSERT INTO cities (name, state) VALUES ('Apple Valley', 'MN');
INSERT INTO cities (name, state) VALUES ('Appleton', 'MN');
INSERT INTO cities (name, state) VALUES ('Arco', 'MN');
INSERT INTO cities (name, state) VALUES ('Arden Hills', 'MN');
INSERT INTO cities (name, state) VALUES ('Argyle', 'MN');
INSERT INTO cities (name, state) VALUES ('Arlington', 'MN');
INSERT INTO cities (name, state) VALUES ('Ashby', 'MN');
INSERT INTO cities (name, state) VALUES ('Askov', 'MN');
INSERT INTO cities (name, state) VALUES ('Atwater', 'MN');
INSERT INTO cities (name, state) VALUES ('Audubon', 'MN');
INSERT INTO cities (name, state) VALUES ('Aurora', 'MN');
INSERT INTO cities (name, state) VALUES ('Austin', 'MN');
INSERT INTO cities (name, state) VALUES ('Avoca', 'MN');
INSERT INTO cities (name, state) VALUES ('Avon', 'MN');
INSERT INTO cities (name, state) VALUES ('Babbitt', 'MN');
INSERT INTO cities (name, state) VALUES ('Backus', 'MN');
INSERT INTO cities (name, state) VALUES ('Badger', 'MN');
INSERT INTO cities (name, state) VALUES ('Bagley', 'MN');
INSERT INTO cities (name, state) VALUES ('Balaton', 'MN');
INSERT INTO cities (name, state) VALUES ('Barnesville', 'MN');
INSERT INTO cities (name, state) VALUES ('Barnum', 'MN');
INSERT INTO cities (name, state) VALUES ('Barrett', 'MN');
INSERT INTO cities (name, state) VALUES ('Barry', 'MN');
INSERT INTO cities (name, state) VALUES ('Battle Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Baudette', 'MN');
INSERT INTO cities (name, state) VALUES ('Baxter', 'MN');
INSERT INTO cities (name, state) VALUES ('Bayport', 'MN');
INSERT INTO cities (name, state) VALUES ('Beardsley', 'MN');
INSERT INTO cities (name, state) VALUES ('Beaver Bay', 'MN');
INSERT INTO cities (name, state) VALUES ('Beaver Creek', 'MN');
INSERT INTO cities (name, state) VALUES ('Becker', 'MN');
INSERT INTO cities (name, state) VALUES ('Bejou', 'MN');
INSERT INTO cities (name, state) VALUES ('Belgrade', 'MN');
INSERT INTO cities (name, state) VALUES ('Belle Plaine', 'MN');
INSERT INTO cities (name, state) VALUES ('Bellechester', 'MN');
INSERT INTO cities (name, state) VALUES ('Bellingham', 'MN');
INSERT INTO cities (name, state) VALUES ('Beltrami', 'MN');
INSERT INTO cities (name, state) VALUES ('Belview', 'MN');
INSERT INTO cities (name, state) VALUES ('Bemidji', 'MN');
INSERT INTO cities (name, state) VALUES ('Bena', 'MN');
INSERT INTO cities (name, state) VALUES ('Benson', 'MN');
INSERT INTO cities (name, state) VALUES ('Bertha', 'MN');
INSERT INTO cities (name, state) VALUES ('Bethel', 'MN');
INSERT INTO cities (name, state) VALUES ('Big Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Big Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Bigelow', 'MN');
INSERT INTO cities (name, state) VALUES ('Bigfork', 'MN');
INSERT INTO cities (name, state) VALUES ('Bingham Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Birchwood Village', 'MN');
INSERT INTO cities (name, state) VALUES ('Bird Island', 'MN');
INSERT INTO cities (name, state) VALUES ('Biscay', 'MN');
INSERT INTO cities (name, state) VALUES ('Biwabik', 'MN');
INSERT INTO cities (name, state) VALUES ('Blackduck', 'MN');
INSERT INTO cities (name, state) VALUES ('Blaine', 'MN');
INSERT INTO cities (name, state) VALUES ('Blomkest', 'MN');
INSERT INTO cities (name, state) VALUES ('Blooming Prairie', 'MN');
INSERT INTO cities (name, state) VALUES ('Bloomington', 'MN');
INSERT INTO cities (name, state) VALUES ('Blue Earth', 'MN');
INSERT INTO cities (name, state) VALUES ('Bluffton', 'MN');
INSERT INTO cities (name, state) VALUES ('Bock', 'MN');
INSERT INTO cities (name, state) VALUES ('Borup', 'MN');
INSERT INTO cities (name, state) VALUES ('Bovey', 'MN');
INSERT INTO cities (name, state) VALUES ('Bowlus', 'MN');
INSERT INTO cities (name, state) VALUES ('Boy River', 'MN');
INSERT INTO cities (name, state) VALUES ('Boyd', 'MN');
INSERT INTO cities (name, state) VALUES ('Braham', 'MN');
INSERT INTO cities (name, state) VALUES ('Brainerd', 'MN');
INSERT INTO cities (name, state) VALUES ('Brandon', 'MN');
INSERT INTO cities (name, state) VALUES ('Breckenridge', 'MN');
INSERT INTO cities (name, state) VALUES ('Breezy Point', 'MN');
INSERT INTO cities (name, state) VALUES ('Brewster', 'MN');
INSERT INTO cities (name, state) VALUES ('Bricelyn', 'MN');
INSERT INTO cities (name, state) VALUES ('Brook Park', 'MN');
INSERT INTO cities (name, state) VALUES ('Brooklyn Center', 'MN');
INSERT INTO cities (name, state) VALUES ('Brooklyn Park', 'MN');
INSERT INTO cities (name, state) VALUES ('Brooks', 'MN');
INSERT INTO cities (name, state) VALUES ('Brookston', 'MN');
INSERT INTO cities (name, state) VALUES ('Brooten', 'MN');
INSERT INTO cities (name, state) VALUES ('Browerville', 'MN');
INSERT INTO cities (name, state) VALUES ('Browns Valley', 'MN');
INSERT INTO cities (name, state) VALUES ('Brownsdale', 'MN');
INSERT INTO cities (name, state) VALUES ('Brownsville', 'MN');
INSERT INTO cities (name, state) VALUES ('Brownton', 'MN');
INSERT INTO cities (name, state) VALUES ('Bruno', 'MN');
INSERT INTO cities (name, state) VALUES ('Buckman', 'MN');
INSERT INTO cities (name, state) VALUES ('Buffalo', 'MN');
INSERT INTO cities (name, state) VALUES ('Buffalo Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Buhl', 'MN');
INSERT INTO cities (name, state) VALUES ('Burnsville', 'MN');
INSERT INTO cities (name, state) VALUES ('Burtrum', 'MN');
INSERT INTO cities (name, state) VALUES ('Butterfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Byron', 'MN');
INSERT INTO cities (name, state) VALUES ('Caledonia', 'MN');
INSERT INTO cities (name, state) VALUES ('Callaway', 'MN');
INSERT INTO cities (name, state) VALUES ('Calumet', 'MN');
INSERT INTO cities (name, state) VALUES ('Cambridge', 'MN');
INSERT INTO cities (name, state) VALUES ('Campbell', 'MN');
INSERT INTO cities (name, state) VALUES ('Canby', 'MN');
INSERT INTO cities (name, state) VALUES ('Cannon Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Canton', 'MN');
INSERT INTO cities (name, state) VALUES ('Carlos', 'MN');
INSERT INTO cities (name, state) VALUES ('Carlton', 'MN');
INSERT INTO cities (name, state) VALUES ('Carver', 'MN');
INSERT INTO cities (name, state) VALUES ('Cass Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Cedar Mills', 'MN');
INSERT INTO cities (name, state) VALUES ('Center City', 'MN');
INSERT INTO cities (name, state) VALUES ('Centerville', 'MN');
INSERT INTO cities (name, state) VALUES ('Ceylon', 'MN');
INSERT INTO cities (name, state) VALUES ('Champlin', 'MN');
INSERT INTO cities (name, state) VALUES ('Chandler', 'MN');
INSERT INTO cities (name, state) VALUES ('Chanhassen', 'MN');
INSERT INTO cities (name, state) VALUES ('Chaska', 'MN');
INSERT INTO cities (name, state) VALUES ('Chatfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Chickamaw Beach', 'MN');
INSERT INTO cities (name, state) VALUES ('Chisago City', 'MN');
INSERT INTO cities (name, state) VALUES ('Chisholm', 'MN');
INSERT INTO cities (name, state) VALUES ('Chokio', 'MN');
INSERT INTO cities (name, state) VALUES ('Circle Pines', 'MN');
INSERT INTO cities (name, state) VALUES ('Clara City', 'MN');
INSERT INTO cities (name, state) VALUES ('Claremont', 'MN');
INSERT INTO cities (name, state) VALUES ('Clarissa', 'MN');
INSERT INTO cities (name, state) VALUES ('Clarkfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Clarks Grove', 'MN');
INSERT INTO cities (name, state) VALUES ('Clear Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Clearbrook', 'MN');
INSERT INTO cities (name, state) VALUES ('Clearwater', 'MN');
INSERT INTO cities (name, state) VALUES ('Clements', 'MN');
INSERT INTO cities (name, state) VALUES ('Cleveland', 'MN');
INSERT INTO cities (name, state) VALUES ('Climax', 'MN');
INSERT INTO cities (name, state) VALUES ('Clinton', 'MN');
INSERT INTO cities (name, state) VALUES ('Clitherall', 'MN');
INSERT INTO cities (name, state) VALUES ('Clontarf', 'MN');
INSERT INTO cities (name, state) VALUES ('Cloquet', 'MN');
INSERT INTO cities (name, state) VALUES ('Coates', 'MN');
INSERT INTO cities (name, state) VALUES ('Cobden', 'MN');
INSERT INTO cities (name, state) VALUES ('Cohasset', 'MN');
INSERT INTO cities (name, state) VALUES ('Cokato', 'MN');
INSERT INTO cities (name, state) VALUES ('Cold Spring', 'MN');
INSERT INTO cities (name, state) VALUES ('Coleraine', 'MN');
INSERT INTO cities (name, state) VALUES ('Cologne', 'MN');
INSERT INTO cities (name, state) VALUES ('Columbia Heights', 'MN');
INSERT INTO cities (name, state) VALUES ('Comfrey', 'MN');
INSERT INTO cities (name, state) VALUES ('Comstock', 'MN');
INSERT INTO cities (name, state) VALUES ('Conger', 'MN');
INSERT INTO cities (name, state) VALUES ('Cook', 'MN');
INSERT INTO cities (name, state) VALUES ('Coon Rapids', 'MN');
INSERT INTO cities (name, state) VALUES ('Corcoran', 'MN');
INSERT INTO cities (name, state) VALUES ('Correll', 'MN');
INSERT INTO cities (name, state) VALUES ('Cosmos', 'MN');
INSERT INTO cities (name, state) VALUES ('Cottage Grove', 'MN');
INSERT INTO cities (name, state) VALUES ('Cottonwood', 'MN');
INSERT INTO cities (name, state) VALUES ('Courtland', 'MN');
INSERT INTO cities (name, state) VALUES ('Cromwell', 'MN');
INSERT INTO cities (name, state) VALUES ('Crookston', 'MN');
INSERT INTO cities (name, state) VALUES ('Crosby', 'MN');
INSERT INTO cities (name, state) VALUES ('Crosslake', 'MN');
INSERT INTO cities (name, state) VALUES ('Crystal', 'MN');
INSERT INTO cities (name, state) VALUES ('Currie', 'MN');
INSERT INTO cities (name, state) VALUES ('Cuyuna', 'MN');
INSERT INTO cities (name, state) VALUES ('Cyrus', 'MN');
INSERT INTO cities (name, state) VALUES ('Dakota', 'MN');
INSERT INTO cities (name, state) VALUES ('Dalton', 'MN');
INSERT INTO cities (name, state) VALUES ('Danube', 'MN');
INSERT INTO cities (name, state) VALUES ('Danvers', 'MN');
INSERT INTO cities (name, state) VALUES ('Darfur', 'MN');
INSERT INTO cities (name, state) VALUES ('Darwin', 'MN');
INSERT INTO cities (name, state) VALUES ('Dassel', 'MN');
INSERT INTO cities (name, state) VALUES ('Dawson', 'MN');
INSERT INTO cities (name, state) VALUES ('Dayton', 'MN');
INSERT INTO cities (name, state) VALUES ('De Graff', 'MN');
INSERT INTO cities (name, state) VALUES ('Deephaven', 'MN');
INSERT INTO cities (name, state) VALUES ('Deer Creek', 'MN');
INSERT INTO cities (name, state) VALUES ('Deer River', 'MN');
INSERT INTO cities (name, state) VALUES ('Deerwood', 'MN');
INSERT INTO cities (name, state) VALUES ('Delano', 'MN');
INSERT INTO cities (name, state) VALUES ('Delavan', 'MN');
INSERT INTO cities (name, state) VALUES ('Delhi', 'MN');
INSERT INTO cities (name, state) VALUES ('Dellwood', 'MN');
INSERT INTO cities (name, state) VALUES ('Denham', 'MN');
INSERT INTO cities (name, state) VALUES ('Dennison', 'MN');
INSERT INTO cities (name, state) VALUES ('Dent', 'MN');
INSERT INTO cities (name, state) VALUES ('Detroit Lakes', 'MN');
INSERT INTO cities (name, state) VALUES ('Dexter', 'MN');
INSERT INTO cities (name, state) VALUES ('Dilworth', 'MN');
INSERT INTO cities (name, state) VALUES ('Dodge Center', 'MN');
INSERT INTO cities (name, state) VALUES ('Donaldson', 'MN');
INSERT INTO cities (name, state) VALUES ('Donnelly', 'MN');
INSERT INTO cities (name, state) VALUES ('Doran', 'MN');
INSERT INTO cities (name, state) VALUES ('Dover', 'MN');
INSERT INTO cities (name, state) VALUES ('Dovray', 'MN');
INSERT INTO cities (name, state) VALUES ('Duluth', 'MN');
INSERT INTO cities (name, state) VALUES ('Dumont', 'MN');
INSERT INTO cities (name, state) VALUES ('Dundas', 'MN');
INSERT INTO cities (name, state) VALUES ('Dundee', 'MN');
INSERT INTO cities (name, state) VALUES ('Dunnell', 'MN');
INSERT INTO cities (name, state) VALUES ('Eagan', 'MN');
INSERT INTO cities (name, state) VALUES ('Eagle Bend', 'MN');
INSERT INTO cities (name, state) VALUES ('Eagle Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('East Bethel', 'MN');
INSERT INTO cities (name, state) VALUES ('East Grand Forks', 'MN');
INSERT INTO cities (name, state) VALUES ('East Gull Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Easton', 'MN');
INSERT INTO cities (name, state) VALUES ('Echo', 'MN');
INSERT INTO cities (name, state) VALUES ('Eden Prairie', 'MN');
INSERT INTO cities (name, state) VALUES ('Eden Valley', 'MN');
INSERT INTO cities (name, state) VALUES ('Edgerton', 'MN');
INSERT INTO cities (name, state) VALUES ('Edina', 'MN');
INSERT INTO cities (name, state) VALUES ('Effie', 'MN');
INSERT INTO cities (name, state) VALUES ('Eitzen', 'MN');
INSERT INTO cities (name, state) VALUES ('Elba', 'MN');
INSERT INTO cities (name, state) VALUES ('Elbow Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Elgin', 'MN');
INSERT INTO cities (name, state) VALUES ('Elizabeth', 'MN');
INSERT INTO cities (name, state) VALUES ('Elk River', 'MN');
INSERT INTO cities (name, state) VALUES ('Elko', 'MN');
INSERT INTO cities (name, state) VALUES ('Elkton', 'MN');
INSERT INTO cities (name, state) VALUES ('Ellendale', 'MN');
INSERT INTO cities (name, state) VALUES ('Ellsworth', 'MN');
INSERT INTO cities (name, state) VALUES ('Elmdale', 'MN');
INSERT INTO cities (name, state) VALUES ('Elmore', 'MN');
INSERT INTO cities (name, state) VALUES ('Elrosa', 'MN');
INSERT INTO cities (name, state) VALUES ('Ely', 'MN');
INSERT INTO cities (name, state) VALUES ('Elysian', 'MN');
INSERT INTO cities (name, state) VALUES ('Emily', 'MN');
INSERT INTO cities (name, state) VALUES ('Emmons', 'MN');
INSERT INTO cities (name, state) VALUES ('Erhard', 'MN');
INSERT INTO cities (name, state) VALUES ('Erskine', 'MN');
INSERT INTO cities (name, state) VALUES ('Evan', 'MN');
INSERT INTO cities (name, state) VALUES ('Evansville', 'MN');
INSERT INTO cities (name, state) VALUES ('Eveleth', 'MN');
INSERT INTO cities (name, state) VALUES ('Excelsior', 'MN');
INSERT INTO cities (name, state) VALUES ('Eyota', 'MN');
INSERT INTO cities (name, state) VALUES ('Fairfax', 'MN');
INSERT INTO cities (name, state) VALUES ('Fairmont', 'MN');
INSERT INTO cities (name, state) VALUES ('Falcon Heights', 'MN');
INSERT INTO cities (name, state) VALUES ('Faribault', 'MN');
INSERT INTO cities (name, state) VALUES ('Farmington', 'MN');
INSERT INTO cities (name, state) VALUES ('Farwell', 'MN');
INSERT INTO cities (name, state) VALUES ('Federal Dam', 'MN');
INSERT INTO cities (name, state) VALUES ('Felton', 'MN');
INSERT INTO cities (name, state) VALUES ('Fergus Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Fertile', 'MN');
INSERT INTO cities (name, state) VALUES ('Fifty Lakes', 'MN');
INSERT INTO cities (name, state) VALUES ('Finlayson', 'MN');
INSERT INTO cities (name, state) VALUES ('Fisher', 'MN');
INSERT INTO cities (name, state) VALUES ('Flensburg', 'MN');
INSERT INTO cities (name, state) VALUES ('Floodwood', 'MN');
INSERT INTO cities (name, state) VALUES ('Florence', 'MN');
INSERT INTO cities (name, state) VALUES ('Foley', 'MN');
INSERT INTO cities (name, state) VALUES ('Forada', 'MN');
INSERT INTO cities (name, state) VALUES ('Forest Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Foreston', 'MN');
INSERT INTO cities (name, state) VALUES ('Fort Ripley', 'MN');
INSERT INTO cities (name, state) VALUES ('Fosston', 'MN');
INSERT INTO cities (name, state) VALUES ('Fountain', 'MN');
INSERT INTO cities (name, state) VALUES ('Foxhome', 'MN');
INSERT INTO cities (name, state) VALUES ('Franklin', 'MN');
INSERT INTO cities (name, state) VALUES ('Frazee', 'MN');
INSERT INTO cities (name, state) VALUES ('Freeborn', 'MN');
INSERT INTO cities (name, state) VALUES ('Freeport', 'MN');
INSERT INTO cities (name, state) VALUES ('Fridley', 'MN');
INSERT INTO cities (name, state) VALUES ('Frost', 'MN');
INSERT INTO cities (name, state) VALUES ('Fulda', 'MN');
INSERT INTO cities (name, state) VALUES ('Funkley', 'MN');
INSERT INTO cities (name, state) VALUES ('Garfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Garrison', 'MN');
INSERT INTO cities (name, state) VALUES ('Garvin', 'MN');
INSERT INTO cities (name, state) VALUES ('Gary', 'MN');
INSERT INTO cities (name, state) VALUES ('Gaylord', 'MN');
INSERT INTO cities (name, state) VALUES ('Gem Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Geneva', 'MN');
INSERT INTO cities (name, state) VALUES ('Genola', 'MN');
INSERT INTO cities (name, state) VALUES ('Georgetown', 'MN');
INSERT INTO cities (name, state) VALUES ('Ghent', 'MN');
INSERT INTO cities (name, state) VALUES ('Gibbon', 'MN');
INSERT INTO cities (name, state) VALUES ('Gilbert', 'MN');
INSERT INTO cities (name, state) VALUES ('Gilman', 'MN');
INSERT INTO cities (name, state) VALUES ('Glencoe', 'MN');
INSERT INTO cities (name, state) VALUES ('Glenville', 'MN');
INSERT INTO cities (name, state) VALUES ('Glenwood', 'MN');
INSERT INTO cities (name, state) VALUES ('Glyndon', 'MN');
INSERT INTO cities (name, state) VALUES ('Golden Valley', 'MN');
INSERT INTO cities (name, state) VALUES ('Gonvick', 'MN');
INSERT INTO cities (name, state) VALUES ('Good Thunder', 'MN');
INSERT INTO cities (name, state) VALUES ('Goodhue', 'MN');
INSERT INTO cities (name, state) VALUES ('Goodridge', 'MN');
INSERT INTO cities (name, state) VALUES ('Goodview', 'MN');
INSERT INTO cities (name, state) VALUES ('Graceville', 'MN');
INSERT INTO cities (name, state) VALUES ('Granada', 'MN');
INSERT INTO cities (name, state) VALUES ('Grand Marais', 'MN');
INSERT INTO cities (name, state) VALUES ('Grand Meadow', 'MN');
INSERT INTO cities (name, state) VALUES ('Grand Rapids', 'MN');
INSERT INTO cities (name, state) VALUES ('Granite Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Grant', 'MN');
INSERT INTO cities (name, state) VALUES ('Grasston', 'MN');
INSERT INTO cities (name, state) VALUES ('Green Isle', 'MN');
INSERT INTO cities (name, state) VALUES ('Greenbush', 'MN');
INSERT INTO cities (name, state) VALUES ('Greenfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Greenwald', 'MN');
INSERT INTO cities (name, state) VALUES ('Greenwood', 'MN');
INSERT INTO cities (name, state) VALUES ('Grey Eagle', 'MN');
INSERT INTO cities (name, state) VALUES ('Grove City', 'MN');
INSERT INTO cities (name, state) VALUES ('Grygla', 'MN');
INSERT INTO cities (name, state) VALUES ('Gully', 'MN');
INSERT INTO cities (name, state) VALUES ('Hackensack', 'MN');
INSERT INTO cities (name, state) VALUES ('Hadley', 'MN');
INSERT INTO cities (name, state) VALUES ('Hallock', 'MN');
INSERT INTO cities (name, state) VALUES ('Halma', 'MN');
INSERT INTO cities (name, state) VALUES ('Halstad', 'MN');
INSERT INTO cities (name, state) VALUES ('Ham Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Hamburg', 'MN');
INSERT INTO cities (name, state) VALUES ('Hammond', 'MN');
INSERT INTO cities (name, state) VALUES ('Hampton', 'MN');
INSERT INTO cities (name, state) VALUES ('Hancock', 'MN');
INSERT INTO cities (name, state) VALUES ('Hanley Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Hanover', 'MN');
INSERT INTO cities (name, state) VALUES ('Hanska', 'MN');
INSERT INTO cities (name, state) VALUES ('Harding', 'MN');
INSERT INTO cities (name, state) VALUES ('Hardwick', 'MN');
INSERT INTO cities (name, state) VALUES ('Harmony', 'MN');
INSERT INTO cities (name, state) VALUES ('Harris', 'MN');
INSERT INTO cities (name, state) VALUES ('Hartland', 'MN');
INSERT INTO cities (name, state) VALUES ('Hastings', 'MN');
INSERT INTO cities (name, state) VALUES ('Hatfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Hawley', 'MN');
INSERT INTO cities (name, state) VALUES ('Hayfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Hayward', 'MN');
INSERT INTO cities (name, state) VALUES ('Hazel Run', 'MN');
INSERT INTO cities (name, state) VALUES ('Hector', 'MN');
INSERT INTO cities (name, state) VALUES ('Heidelberg', 'MN');
INSERT INTO cities (name, state) VALUES ('Henderson', 'MN');
INSERT INTO cities (name, state) VALUES ('Hendricks', 'MN');
INSERT INTO cities (name, state) VALUES ('Hendrum', 'MN');
INSERT INTO cities (name, state) VALUES ('Henning', 'MN');
INSERT INTO cities (name, state) VALUES ('Henriette', 'MN');
INSERT INTO cities (name, state) VALUES ('Herman', 'MN');
INSERT INTO cities (name, state) VALUES ('Hermantown', 'MN');
INSERT INTO cities (name, state) VALUES ('Heron Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Hewitt', 'MN');
INSERT INTO cities (name, state) VALUES ('Hibbing', 'MN');
INSERT INTO cities (name, state) VALUES ('Hill City', 'MN');
INSERT INTO cities (name, state) VALUES ('Hillman', 'MN');
INSERT INTO cities (name, state) VALUES ('Hills', 'MN');
INSERT INTO cities (name, state) VALUES ('Hilltop', 'MN');
INSERT INTO cities (name, state) VALUES ('Hinckley', 'MN');
INSERT INTO cities (name, state) VALUES ('Hitterdal', 'MN');
INSERT INTO cities (name, state) VALUES ('Hoffman', 'MN');
INSERT INTO cities (name, state) VALUES ('Hokah', 'MN');
INSERT INTO cities (name, state) VALUES ('Holdingford', 'MN');
INSERT INTO cities (name, state) VALUES ('Holland', 'MN');
INSERT INTO cities (name, state) VALUES ('Hollandale', 'MN');
INSERT INTO cities (name, state) VALUES ('Holloway', 'MN');
INSERT INTO cities (name, state) VALUES ('Holt', 'MN');
INSERT INTO cities (name, state) VALUES ('Hopkins', 'MN');
INSERT INTO cities (name, state) VALUES ('Houston', 'MN');
INSERT INTO cities (name, state) VALUES ('Howard Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Hoyt Lakes', 'MN');
INSERT INTO cities (name, state) VALUES ('Hugo', 'MN');
INSERT INTO cities (name, state) VALUES ('Humboldt', 'MN');
INSERT INTO cities (name, state) VALUES ('Hutchinson', 'MN');
INSERT INTO cities (name, state) VALUES ('Ihlen', 'MN');
INSERT INTO cities (name, state) VALUES ('Independence', 'MN');
INSERT INTO cities (name, state) VALUES ('International Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Inver Grove Heights', 'MN');
INSERT INTO cities (name, state) VALUES ('Iona', 'MN');
INSERT INTO cities (name, state) VALUES ('Iron Junction', 'MN');
INSERT INTO cities (name, state) VALUES ('Ironton', 'MN');
INSERT INTO cities (name, state) VALUES ('Isanti', 'MN');
INSERT INTO cities (name, state) VALUES ('Isle', 'MN');
INSERT INTO cities (name, state) VALUES ('Ivanhoe', 'MN');
INSERT INTO cities (name, state) VALUES ('Jackson', 'MN');
INSERT INTO cities (name, state) VALUES ('Janesville', 'MN');
INSERT INTO cities (name, state) VALUES ('Jasper', 'MN');
INSERT INTO cities (name, state) VALUES ('Jeffers', 'MN');
INSERT INTO cities (name, state) VALUES ('Jenkins', 'MN');
INSERT INTO cities (name, state) VALUES ('Johnson', 'MN');
INSERT INTO cities (name, state) VALUES ('Jordan', 'MN');
INSERT INTO cities (name, state) VALUES ('Kandiyohi', 'MN');
INSERT INTO cities (name, state) VALUES ('Karlstad', 'MN');
INSERT INTO cities (name, state) VALUES ('Kasota', 'MN');
INSERT INTO cities (name, state) VALUES ('Kasson', 'MN');
INSERT INTO cities (name, state) VALUES ('Keewatin', 'MN');
INSERT INTO cities (name, state) VALUES ('Kelliher', 'MN');
INSERT INTO cities (name, state) VALUES ('Kellogg', 'MN');
INSERT INTO cities (name, state) VALUES ('Kennedy', 'MN');
INSERT INTO cities (name, state) VALUES ('Kenneth', 'MN');
INSERT INTO cities (name, state) VALUES ('Kensington', 'MN');
INSERT INTO cities (name, state) VALUES ('Kent', 'MN');
INSERT INTO cities (name, state) VALUES ('Kenyon', 'MN');
INSERT INTO cities (name, state) VALUES ('Kerkhoven', 'MN');
INSERT INTO cities (name, state) VALUES ('Kerrick', 'MN');
INSERT INTO cities (name, state) VALUES ('Kettle River', 'MN');
INSERT INTO cities (name, state) VALUES ('Kiester', 'MN');
INSERT INTO cities (name, state) VALUES ('Kilkenny', 'MN');
INSERT INTO cities (name, state) VALUES ('Kimball', 'MN');
INSERT INTO cities (name, state) VALUES ('Kinbrae', 'MN');
INSERT INTO cities (name, state) VALUES ('Kingston', 'MN');
INSERT INTO cities (name, state) VALUES ('Kinney', 'MN');
INSERT INTO cities (name, state) VALUES ('La Crescent', 'MN');
INSERT INTO cities (name, state) VALUES ('La Prairie', 'MN');
INSERT INTO cities (name, state) VALUES ('La Salle', 'MN');
INSERT INTO cities (name, state) VALUES ('Lafayette', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake Benton', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake Bronson', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake City', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake Crystal', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake Elmo', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake Henry', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake Lillian', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake Park', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake Shore', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake St. Croix Beach', 'MN');
INSERT INTO cities (name, state) VALUES ('Lake Wilson', 'MN');
INSERT INTO cities (name, state) VALUES ('Lakefield', 'MN');
INSERT INTO cities (name, state) VALUES ('Lakeland', 'MN');
INSERT INTO cities (name, state) VALUES ('Lakeland Shores', 'MN');
INSERT INTO cities (name, state) VALUES ('Lakeville', 'MN');
INSERT INTO cities (name, state) VALUES ('Lamberton', 'MN');
INSERT INTO cities (name, state) VALUES ('Lancaster', 'MN');
INSERT INTO cities (name, state) VALUES ('Landfall', 'MN');
INSERT INTO cities (name, state) VALUES ('Lanesboro', 'MN');
INSERT INTO cities (name, state) VALUES ('Laporte', 'MN');
INSERT INTO cities (name, state) VALUES ('Lastrup', 'MN');
INSERT INTO cities (name, state) VALUES ('Lauderdale', 'MN');
INSERT INTO cities (name, state) VALUES ('Le Center', 'MN');
INSERT INTO cities (name, state) VALUES ('Le Roy', 'MN');
INSERT INTO cities (name, state) VALUES ('Le Sueur', 'MN');
INSERT INTO cities (name, state) VALUES ('Lengby', 'MN');
INSERT INTO cities (name, state) VALUES ('Leonard', 'MN');
INSERT INTO cities (name, state) VALUES ('Leonidas', 'MN');
INSERT INTO cities (name, state) VALUES ('Lester Prairie', 'MN');
INSERT INTO cities (name, state) VALUES ('Lewiston', 'MN');
INSERT INTO cities (name, state) VALUES ('Lewisville', 'MN');
INSERT INTO cities (name, state) VALUES ('Lexington', 'MN');
INSERT INTO cities (name, state) VALUES ('Lilydale', 'MN');
INSERT INTO cities (name, state) VALUES ('Lindstrom', 'MN');
INSERT INTO cities (name, state) VALUES ('Lino Lakes', 'MN');
INSERT INTO cities (name, state) VALUES ('Lismore', 'MN');
INSERT INTO cities (name, state) VALUES ('Litchfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Little Canada', 'MN');
INSERT INTO cities (name, state) VALUES ('Little Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Littlefork', 'MN');
INSERT INTO cities (name, state) VALUES ('Long Beach', 'MN');
INSERT INTO cities (name, state) VALUES ('Long Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Long Prairie', 'MN');
INSERT INTO cities (name, state) VALUES ('Longville', 'MN');
INSERT INTO cities (name, state) VALUES ('Lonsdale', 'MN');
INSERT INTO cities (name, state) VALUES ('Loretto', 'MN');
INSERT INTO cities (name, state) VALUES ('Louisburg', 'MN');
INSERT INTO cities (name, state) VALUES ('Lowry', 'MN');
INSERT INTO cities (name, state) VALUES ('Lucan', 'MN');
INSERT INTO cities (name, state) VALUES ('Luverne', 'MN');
INSERT INTO cities (name, state) VALUES ('Lyle', 'MN');
INSERT INTO cities (name, state) VALUES ('Lynd', 'MN');
INSERT INTO cities (name, state) VALUES ('Mabel', 'MN');
INSERT INTO cities (name, state) VALUES ('Madelia', 'MN');
INSERT INTO cities (name, state) VALUES ('Madison', 'MN');
INSERT INTO cities (name, state) VALUES ('Madison Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Magnolia', 'MN');
INSERT INTO cities (name, state) VALUES ('Mahnomen', 'MN');
INSERT INTO cities (name, state) VALUES ('Mahtomedi', 'MN');
INSERT INTO cities (name, state) VALUES ('Manchester', 'MN');
INSERT INTO cities (name, state) VALUES ('Manhattan Beach', 'MN');
INSERT INTO cities (name, state) VALUES ('Mankato', 'MN');
INSERT INTO cities (name, state) VALUES ('Mantorville', 'MN');
INSERT INTO cities (name, state) VALUES ('Maple Grove', 'MN');
INSERT INTO cities (name, state) VALUES ('Maple Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Maple Plain', 'MN');
INSERT INTO cities (name, state) VALUES ('Mapleton', 'MN');
INSERT INTO cities (name, state) VALUES ('Mapleview', 'MN');
INSERT INTO cities (name, state) VALUES ('Maplewood', 'MN');
INSERT INTO cities (name, state) VALUES ('Marble', 'MN');
INSERT INTO cities (name, state) VALUES ('Marietta', 'MN');
INSERT INTO cities (name, state) VALUES ('Marine on St. Croix', 'MN');
INSERT INTO cities (name, state) VALUES ('Marshall', 'MN');
INSERT INTO cities (name, state) VALUES ('Mayer', 'MN');
INSERT INTO cities (name, state) VALUES ('Maynard', 'MN');
INSERT INTO cities (name, state) VALUES ('Mazeppa', 'MN');
INSERT INTO cities (name, state) VALUES ('McGrath', 'MN');
INSERT INTO cities (name, state) VALUES ('McGregor', 'MN');
INSERT INTO cities (name, state) VALUES ('McIntosh', 'MN');
INSERT INTO cities (name, state) VALUES ('McKinley', 'MN');
INSERT INTO cities (name, state) VALUES ('Meadowlands', 'MN');
INSERT INTO cities (name, state) VALUES ('Medford', 'MN');
INSERT INTO cities (name, state) VALUES ('Medicine Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Medina', 'MN');
INSERT INTO cities (name, state) VALUES ('Meire Grove', 'MN');
INSERT INTO cities (name, state) VALUES ('Melrose', 'MN');
INSERT INTO cities (name, state) VALUES ('Menahga', 'MN');
INSERT INTO cities (name, state) VALUES ('Mendota', 'MN');
INSERT INTO cities (name, state) VALUES ('Mendota Heights', 'MN');
INSERT INTO cities (name, state) VALUES ('Mentor', 'MN');
INSERT INTO cities (name, state) VALUES ('Middle River', 'MN');
INSERT INTO cities (name, state) VALUES ('Miesville', 'MN');
INSERT INTO cities (name, state) VALUES ('Milaca', 'MN');
INSERT INTO cities (name, state) VALUES ('Milan', 'MN');
INSERT INTO cities (name, state) VALUES ('Millerville', 'MN');
INSERT INTO cities (name, state) VALUES ('Millville', 'MN');
INSERT INTO cities (name, state) VALUES ('Milroy', 'MN');
INSERT INTO cities (name, state) VALUES ('Miltona', 'MN');
INSERT INTO cities (name, state) VALUES ('Minneapolis', 'MN');
INSERT INTO cities (name, state) VALUES ('Minneiska', 'MN');
INSERT INTO cities (name, state) VALUES ('Minneota', 'MN');
INSERT INTO cities (name, state) VALUES ('Minnesota City', 'MN');
INSERT INTO cities (name, state) VALUES ('Minnesota Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Minnetonka', 'MN');
INSERT INTO cities (name, state) VALUES ('Minnetonka Beach', 'MN');
INSERT INTO cities (name, state) VALUES ('Minnetrista', 'MN');
INSERT INTO cities (name, state) VALUES ('Mizpah', 'MN');
INSERT INTO cities (name, state) VALUES ('Montevideo', 'MN');
INSERT INTO cities (name, state) VALUES ('Montgomery', 'MN');
INSERT INTO cities (name, state) VALUES ('Monticello', 'MN');
INSERT INTO cities (name, state) VALUES ('Montrose', 'MN');
INSERT INTO cities (name, state) VALUES ('Moorhead', 'MN');
INSERT INTO cities (name, state) VALUES ('Moose Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Mora', 'MN');
INSERT INTO cities (name, state) VALUES ('Morgan', 'MN');
INSERT INTO cities (name, state) VALUES ('Morris', 'MN');
INSERT INTO cities (name, state) VALUES ('Morristown', 'MN');
INSERT INTO cities (name, state) VALUES ('Morton', 'MN');
INSERT INTO cities (name, state) VALUES ('Motley', 'MN');
INSERT INTO cities (name, state) VALUES ('Mound', 'MN');
INSERT INTO cities (name, state) VALUES ('Mounds View', 'MN');
INSERT INTO cities (name, state) VALUES ('Mountain Iron', 'MN');
INSERT INTO cities (name, state) VALUES ('Mountain Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Murdock', 'MN');
INSERT INTO cities (name, state) VALUES ('Myrtle', 'MN');
INSERT INTO cities (name, state) VALUES ('Nashua', 'MN');
INSERT INTO cities (name, state) VALUES ('Nashwauk', 'MN');
INSERT INTO cities (name, state) VALUES ('Nassau', 'MN');
INSERT INTO cities (name, state) VALUES ('Nelson', 'MN');
INSERT INTO cities (name, state) VALUES ('Nerstrand', 'MN');
INSERT INTO cities (name, state) VALUES ('Nevis', 'MN');
INSERT INTO cities (name, state) VALUES ('New Auburn', 'MN');
INSERT INTO cities (name, state) VALUES ('New Brighton', 'MN');
INSERT INTO cities (name, state) VALUES ('New Germany', 'MN');
INSERT INTO cities (name, state) VALUES ('New Hope', 'MN');
INSERT INTO cities (name, state) VALUES ('New London', 'MN');
INSERT INTO cities (name, state) VALUES ('New Market', 'MN');
INSERT INTO cities (name, state) VALUES ('New Munich', 'MN');
INSERT INTO cities (name, state) VALUES ('New Prague', 'MN');
INSERT INTO cities (name, state) VALUES ('New Richland', 'MN');
INSERT INTO cities (name, state) VALUES ('New Trier', 'MN');
INSERT INTO cities (name, state) VALUES ('New Ulm', 'MN');
INSERT INTO cities (name, state) VALUES ('New York Mills', 'MN');
INSERT INTO cities (name, state) VALUES ('Newfolden', 'MN');
INSERT INTO cities (name, state) VALUES ('Newport', 'MN');
INSERT INTO cities (name, state) VALUES ('Nicollet', 'MN');
INSERT INTO cities (name, state) VALUES ('Nielsville', 'MN');
INSERT INTO cities (name, state) VALUES ('Nimrod', 'MN');
INSERT INTO cities (name, state) VALUES ('Nisswa', 'MN');
INSERT INTO cities (name, state) VALUES ('Norcross', 'MN');
INSERT INTO cities (name, state) VALUES ('North Branch', 'MN');
INSERT INTO cities (name, state) VALUES ('North Mankato', 'MN');
INSERT INTO cities (name, state) VALUES ('North Oaks', 'MN');
INSERT INTO cities (name, state) VALUES ('North St. Paul', 'MN');
INSERT INTO cities (name, state) VALUES ('Northfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Northome', 'MN');
INSERT INTO cities (name, state) VALUES ('Northrop', 'MN');
INSERT INTO cities (name, state) VALUES ('Norwood Young America', 'MN');
INSERT INTO cities (name, state) VALUES ('Oak Grove', 'MN');
INSERT INTO cities (name, state) VALUES ('Oak Park Heights', 'MN');
INSERT INTO cities (name, state) VALUES ('Oakdale', 'MN');
INSERT INTO cities (name, state) VALUES ('Odessa', 'MN');
INSERT INTO cities (name, state) VALUES ('Odin', 'MN');
INSERT INTO cities (name, state) VALUES ('Ogema', 'MN');
INSERT INTO cities (name, state) VALUES ('Ogilvie', 'MN');
INSERT INTO cities (name, state) VALUES ('Okabena', 'MN');
INSERT INTO cities (name, state) VALUES ('Oklee', 'MN');
INSERT INTO cities (name, state) VALUES ('Olivia', 'MN');
INSERT INTO cities (name, state) VALUES ('Onamia', 'MN');
INSERT INTO cities (name, state) VALUES ('Ormsby', 'MN');
INSERT INTO cities (name, state) VALUES ('Orono', 'MN');
INSERT INTO cities (name, state) VALUES ('Oronoco', 'MN');
INSERT INTO cities (name, state) VALUES ('Orr', 'MN');
INSERT INTO cities (name, state) VALUES ('Ortonville', 'MN');
INSERT INTO cities (name, state) VALUES ('Osakis', 'MN');
INSERT INTO cities (name, state) VALUES ('Oslo', 'MN');
INSERT INTO cities (name, state) VALUES ('Osseo', 'MN');
INSERT INTO cities (name, state) VALUES ('Ostrander', 'MN');
INSERT INTO cities (name, state) VALUES ('Otsego', 'MN');
INSERT INTO cities (name, state) VALUES ('Ottertail', 'MN');
INSERT INTO cities (name, state) VALUES ('Owatonna', 'MN');
INSERT INTO cities (name, state) VALUES ('Palisade', 'MN');
INSERT INTO cities (name, state) VALUES ('Park Rapids', 'MN');
INSERT INTO cities (name, state) VALUES ('Parkers Prairie', 'MN');
INSERT INTO cities (name, state) VALUES ('Paynesville', 'MN');
INSERT INTO cities (name, state) VALUES ('Pease', 'MN');
INSERT INTO cities (name, state) VALUES ('Pelican Rapids', 'MN');
INSERT INTO cities (name, state) VALUES ('Pemberton', 'MN');
INSERT INTO cities (name, state) VALUES ('Pennock', 'MN');
INSERT INTO cities (name, state) VALUES ('Pequot Lakes', 'MN');
INSERT INTO cities (name, state) VALUES ('Perham', 'MN');
INSERT INTO cities (name, state) VALUES ('Perley', 'MN');
INSERT INTO cities (name, state) VALUES ('Peterson', 'MN');
INSERT INTO cities (name, state) VALUES ('Pierz', 'MN');
INSERT INTO cities (name, state) VALUES ('Pillager', 'MN');
INSERT INTO cities (name, state) VALUES ('Pine City', 'MN');
INSERT INTO cities (name, state) VALUES ('Pine Island', 'MN');
INSERT INTO cities (name, state) VALUES ('Pine River', 'MN');
INSERT INTO cities (name, state) VALUES ('Pine Springs', 'MN');
INSERT INTO cities (name, state) VALUES ('Pipestone', 'MN');
INSERT INTO cities (name, state) VALUES ('Plainview', 'MN');
INSERT INTO cities (name, state) VALUES ('Plato', 'MN');
INSERT INTO cities (name, state) VALUES ('Pleasant Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Plummer', 'MN');
INSERT INTO cities (name, state) VALUES ('Plymouth', 'MN');
INSERT INTO cities (name, state) VALUES ('Porter', 'MN');
INSERT INTO cities (name, state) VALUES ('Preston', 'MN');
INSERT INTO cities (name, state) VALUES ('Princeton', 'MN');
INSERT INTO cities (name, state) VALUES ('Prinsburg', 'MN');
INSERT INTO cities (name, state) VALUES ('Prior Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Proctor', 'MN');
INSERT INTO cities (name, state) VALUES ('Quamba', 'MN');
INSERT INTO cities (name, state) VALUES ('Racine', 'MN');
INSERT INTO cities (name, state) VALUES ('Ramsey', 'MN');
INSERT INTO cities (name, state) VALUES ('Randall', 'MN');
INSERT INTO cities (name, state) VALUES ('Randolph', 'MN');
INSERT INTO cities (name, state) VALUES ('Ranier', 'MN');
INSERT INTO cities (name, state) VALUES ('Raymond', 'MN');
INSERT INTO cities (name, state) VALUES ('Red Lake Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Red Wing', 'MN');
INSERT INTO cities (name, state) VALUES ('Redwood Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Regal', 'MN');
INSERT INTO cities (name, state) VALUES ('Remer', 'MN');
INSERT INTO cities (name, state) VALUES ('Renville', 'MN');
INSERT INTO cities (name, state) VALUES ('Revere', 'MN');
INSERT INTO cities (name, state) VALUES ('Rice', 'MN');
INSERT INTO cities (name, state) VALUES ('Richfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Richmond', 'MN');
INSERT INTO cities (name, state) VALUES ('Richville', 'MN');
INSERT INTO cities (name, state) VALUES ('Riverton', 'MN');
INSERT INTO cities (name, state) VALUES ('Robbinsdale', 'MN');
INSERT INTO cities (name, state) VALUES ('Rochester', 'MN');
INSERT INTO cities (name, state) VALUES ('Rock Creek', 'MN');
INSERT INTO cities (name, state) VALUES ('Rockford', 'MN');
INSERT INTO cities (name, state) VALUES ('Rockville', 'MN');
INSERT INTO cities (name, state) VALUES ('Rogers', 'MN');
INSERT INTO cities (name, state) VALUES ('Rollingstone', 'MN');
INSERT INTO cities (name, state) VALUES ('Ronneby', 'MN');
INSERT INTO cities (name, state) VALUES ('Roosevelt', 'MN');
INSERT INTO cities (name, state) VALUES ('Roscoe', 'MN');
INSERT INTO cities (name, state) VALUES ('Rose Creek', 'MN');
INSERT INTO cities (name, state) VALUES ('Roseau', 'MN');
INSERT INTO cities (name, state) VALUES ('Rosemount', 'MN');
INSERT INTO cities (name, state) VALUES ('Roseville', 'MN');
INSERT INTO cities (name, state) VALUES ('Rothsay', 'MN');
INSERT INTO cities (name, state) VALUES ('Round Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Royalton', 'MN');
INSERT INTO cities (name, state) VALUES ('Rush City', 'MN');
INSERT INTO cities (name, state) VALUES ('Rushford', 'MN');
INSERT INTO cities (name, state) VALUES ('Rushford Village', 'MN');
INSERT INTO cities (name, state) VALUES ('Rushmore', 'MN');
INSERT INTO cities (name, state) VALUES ('Russell', 'MN');
INSERT INTO cities (name, state) VALUES ('Ruthton', 'MN');
INSERT INTO cities (name, state) VALUES ('Rutledge', 'MN');
INSERT INTO cities (name, state) VALUES ('Sabin', 'MN');
INSERT INTO cities (name, state) VALUES ('Sacred Heart', 'MN');
INSERT INTO cities (name, state) VALUES ('Sanborn', 'MN');
INSERT INTO cities (name, state) VALUES ('Sandstone', 'MN');
INSERT INTO cities (name, state) VALUES ('Sargeant', 'MN');
INSERT INTO cities (name, state) VALUES ('Sartell', 'MN');
INSERT INTO cities (name, state) VALUES ('Sauk Centre', 'MN');
INSERT INTO cities (name, state) VALUES ('Sauk Rapids', 'MN');
INSERT INTO cities (name, state) VALUES ('Savage', 'MN');
INSERT INTO cities (name, state) VALUES ('Scanlon', 'MN');
INSERT INTO cities (name, state) VALUES ('Seaforth', 'MN');
INSERT INTO cities (name, state) VALUES ('Sebeka', 'MN');
INSERT INTO cities (name, state) VALUES ('Sedan', 'MN');
INSERT INTO cities (name, state) VALUES ('Shafer', 'MN');
INSERT INTO cities (name, state) VALUES ('Shakopee', 'MN');
INSERT INTO cities (name, state) VALUES ('Shelly', 'MN');
INSERT INTO cities (name, state) VALUES ('Sherburn', 'MN');
INSERT INTO cities (name, state) VALUES ('Shevlin', 'MN');
INSERT INTO cities (name, state) VALUES ('Shoreview', 'MN');
INSERT INTO cities (name, state) VALUES ('Shorewood', 'MN');
INSERT INTO cities (name, state) VALUES ('Silver Bay', 'MN');
INSERT INTO cities (name, state) VALUES ('Silver Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Skyline', 'MN');
INSERT INTO cities (name, state) VALUES ('Slayton', 'MN');
INSERT INTO cities (name, state) VALUES ('Sleepy Eye', 'MN');
INSERT INTO cities (name, state) VALUES ('Sobieski', 'MN');
INSERT INTO cities (name, state) VALUES ('Solway', 'MN');
INSERT INTO cities (name, state) VALUES ('South Haven', 'MN');
INSERT INTO cities (name, state) VALUES ('South St. Paul', 'MN');
INSERT INTO cities (name, state) VALUES ('Spicer', 'MN');
INSERT INTO cities (name, state) VALUES ('Spring Grove', 'MN');
INSERT INTO cities (name, state) VALUES ('Spring Hill', 'MN');
INSERT INTO cities (name, state) VALUES ('Spring Lake Park', 'MN');
INSERT INTO cities (name, state) VALUES ('Spring Park', 'MN');
INSERT INTO cities (name, state) VALUES ('Spring Valley', 'MN');
INSERT INTO cities (name, state) VALUES ('Springfield', 'MN');
INSERT INTO cities (name, state) VALUES ('Squaw Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Anthony', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Anthony', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Augusta', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Bonifacius', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Charles', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Clair', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Cloud', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Francis', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Hilaire', 'MN');
INSERT INTO cities (name, state) VALUES ('St. James', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Joseph', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Leo', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Louis Park', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Martin', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Marys Point', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Michael', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Paul', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Paul Park', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Peter', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Rosa', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Stephen', 'MN');
INSERT INTO cities (name, state) VALUES ('St. Vincent', 'MN');
INSERT INTO cities (name, state) VALUES ('Stacy', 'MN');
INSERT INTO cities (name, state) VALUES ('Staples', 'MN');
INSERT INTO cities (name, state) VALUES ('Starbuck', 'MN');
INSERT INTO cities (name, state) VALUES ('Steen', 'MN');
INSERT INTO cities (name, state) VALUES ('Stephen', 'MN');
INSERT INTO cities (name, state) VALUES ('Stewart', 'MN');
INSERT INTO cities (name, state) VALUES ('Stewartville', 'MN');
INSERT INTO cities (name, state) VALUES ('Stillwater', 'MN');
INSERT INTO cities (name, state) VALUES ('Stockton', 'MN');
INSERT INTO cities (name, state) VALUES ('Storden', 'MN');
INSERT INTO cities (name, state) VALUES ('Strandquist', 'MN');
INSERT INTO cities (name, state) VALUES ('Strathcona', 'MN');
INSERT INTO cities (name, state) VALUES ('Sturgeon Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Sunburg', 'MN');
INSERT INTO cities (name, state) VALUES ('Sunfish Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Swanville', 'MN');
INSERT INTO cities (name, state) VALUES ('Taconite', 'MN');
INSERT INTO cities (name, state) VALUES ('Tamarack', 'MN');
INSERT INTO cities (name, state) VALUES ('Taopi', 'MN');
INSERT INTO cities (name, state) VALUES ('Taunton', 'MN');
INSERT INTO cities (name, state) VALUES ('Taylors Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Tenney', 'MN');
INSERT INTO cities (name, state) VALUES ('Tenstrike', 'MN');
INSERT INTO cities (name, state) VALUES ('Thief River Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Thomson', 'MN');
INSERT INTO cities (name, state) VALUES ('Tintah', 'MN');
INSERT INTO cities (name, state) VALUES ('Tonka Bay', 'MN');
INSERT INTO cities (name, state) VALUES ('Tower', 'MN');
INSERT INTO cities (name, state) VALUES ('Tracy', 'MN');
INSERT INTO cities (name, state) VALUES ('Trail', 'MN');
INSERT INTO cities (name, state) VALUES ('Trimont', 'MN');
INSERT INTO cities (name, state) VALUES ('Trommald', 'MN');
INSERT INTO cities (name, state) VALUES ('Trosky', 'MN');
INSERT INTO cities (name, state) VALUES ('Truman', 'MN');
INSERT INTO cities (name, state) VALUES ('Turtle River', 'MN');
INSERT INTO cities (name, state) VALUES ('Twin Lakes', 'MN');
INSERT INTO cities (name, state) VALUES ('Twin Valley', 'MN');
INSERT INTO cities (name, state) VALUES ('Two Harbors', 'MN');
INSERT INTO cities (name, state) VALUES ('Tyler', 'MN');
INSERT INTO cities (name, state) VALUES ('Ulen', 'MN');
INSERT INTO cities (name, state) VALUES ('Underwood', 'MN');
INSERT INTO cities (name, state) VALUES ('Upsala', 'MN');
INSERT INTO cities (name, state) VALUES ('Urbank', 'MN');
INSERT INTO cities (name, state) VALUES ('Utica', 'MN');
INSERT INTO cities (name, state) VALUES ('Vadnais Heights', 'MN');
INSERT INTO cities (name, state) VALUES ('Vergas', 'MN');
INSERT INTO cities (name, state) VALUES ('Vermillion', 'MN');
INSERT INTO cities (name, state) VALUES ('Verndale', 'MN');
INSERT INTO cities (name, state) VALUES ('Vernon Center', 'MN');
INSERT INTO cities (name, state) VALUES ('Vesta', 'MN');
INSERT INTO cities (name, state) VALUES ('Victoria', 'MN');
INSERT INTO cities (name, state) VALUES ('Viking', 'MN');
INSERT INTO cities (name, state) VALUES ('Villard', 'MN');
INSERT INTO cities (name, state) VALUES ('Vining', 'MN');
INSERT INTO cities (name, state) VALUES ('Virginia', 'MN');
INSERT INTO cities (name, state) VALUES ('Wabasha', 'MN');
INSERT INTO cities (name, state) VALUES ('Wabasso', 'MN');
INSERT INTO cities (name, state) VALUES ('Waconia', 'MN');
INSERT INTO cities (name, state) VALUES ('Wadena', 'MN');
INSERT INTO cities (name, state) VALUES ('Wahkon', 'MN');
INSERT INTO cities (name, state) VALUES ('Waite Park', 'MN');
INSERT INTO cities (name, state) VALUES ('Waldorf', 'MN');
INSERT INTO cities (name, state) VALUES ('Walker', 'MN');
INSERT INTO cities (name, state) VALUES ('Walnut Grove', 'MN');
INSERT INTO cities (name, state) VALUES ('Walters', 'MN');
INSERT INTO cities (name, state) VALUES ('Waltham', 'MN');
INSERT INTO cities (name, state) VALUES ('Wanamingo', 'MN');
INSERT INTO cities (name, state) VALUES ('Wanda', 'MN');
INSERT INTO cities (name, state) VALUES ('Warba', 'MN');
INSERT INTO cities (name, state) VALUES ('Warren', 'MN');
INSERT INTO cities (name, state) VALUES ('Warroad', 'MN');
INSERT INTO cities (name, state) VALUES ('Waseca', 'MN');
INSERT INTO cities (name, state) VALUES ('Watertown', 'MN');
INSERT INTO cities (name, state) VALUES ('Waterville', 'MN');
INSERT INTO cities (name, state) VALUES ('Watkins', 'MN');
INSERT INTO cities (name, state) VALUES ('Watson', 'MN');
INSERT INTO cities (name, state) VALUES ('Waubun', 'MN');
INSERT INTO cities (name, state) VALUES ('Waverly', 'MN');
INSERT INTO cities (name, state) VALUES ('Wayzata', 'MN');
INSERT INTO cities (name, state) VALUES ('Welcome', 'MN');
INSERT INTO cities (name, state) VALUES ('Wells', 'MN');
INSERT INTO cities (name, state) VALUES ('Wendell', 'MN');
INSERT INTO cities (name, state) VALUES ('West Concord', 'MN');
INSERT INTO cities (name, state) VALUES ('West St. Paul', 'MN');
INSERT INTO cities (name, state) VALUES ('West Union', 'MN');
INSERT INTO cities (name, state) VALUES ('Westbrook', 'MN');
INSERT INTO cities (name, state) VALUES ('Westport', 'MN');
INSERT INTO cities (name, state) VALUES ('Whalan', 'MN');
INSERT INTO cities (name, state) VALUES ('Wheaton', 'MN');
INSERT INTO cities (name, state) VALUES ('White Bear Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Wilder', 'MN');
INSERT INTO cities (name, state) VALUES ('Willernie', 'MN');
INSERT INTO cities (name, state) VALUES ('Williams', 'MN');
INSERT INTO cities (name, state) VALUES ('Willmar', 'MN');
INSERT INTO cities (name, state) VALUES ('Willow River', 'MN');
INSERT INTO cities (name, state) VALUES ('Wilmont', 'MN');
INSERT INTO cities (name, state) VALUES ('Wilton', 'MN');
INSERT INTO cities (name, state) VALUES ('Windom', 'MN');
INSERT INTO cities (name, state) VALUES ('Winger', 'MN');
INSERT INTO cities (name, state) VALUES ('Winnebago', 'MN');
INSERT INTO cities (name, state) VALUES ('Winona', 'MN');
INSERT INTO cities (name, state) VALUES ('Winsted', 'MN');
INSERT INTO cities (name, state) VALUES ('Winthrop', 'MN');
INSERT INTO cities (name, state) VALUES ('Winton', 'MN');
INSERT INTO cities (name, state) VALUES ('Wolf Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Wolverton', 'MN');
INSERT INTO cities (name, state) VALUES ('Wood Lake', 'MN');
INSERT INTO cities (name, state) VALUES ('Woodbury', 'MN');
INSERT INTO cities (name, state) VALUES ('Woodland', 'MN');
INSERT INTO cities (name, state) VALUES ('Woodstock', 'MN');
INSERT INTO cities (name, state) VALUES ('Worthington', 'MN');
INSERT INTO cities (name, state) VALUES ('Wrenshall', 'MN');
INSERT INTO cities (name, state) VALUES ('Wright', 'MN');
INSERT INTO cities (name, state) VALUES ('Wykoff', 'MN');
INSERT INTO cities (name, state) VALUES ('Wyoming', 'MN');
INSERT INTO cities (name, state) VALUES ('Zemple', 'MN');
INSERT INTO cities (name, state) VALUES ('Zimmerman', 'MN');
INSERT INTO cities (name, state) VALUES ('Zumbro Falls', 'MN');
INSERT INTO cities (name, state) VALUES ('Zumbrota', 'MN');

COMMIT;

SHUTDOWN COMPACT;



