package com.dynamic.charm.examples.orm;
// Generated Nov 27, 2006 11:54:35 AM by Hibernate Tools 3.2.0.beta8



/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {

    // Fields    

     private int cityId;
     private String cityName;
     private String stateCode;

     // Constructors

    /** default constructor */
    public City() {
    }

	/** minimal constructor */
    public City(int cityId, String cityName) {
        this.cityId = cityId;
        this.cityName = cityName;
    }
    /** full constructor */
    public City(int cityId, String cityName, String stateCode) {
       this.cityId = cityId;
       this.cityName = cityName;
       this.stateCode = stateCode;
    }
   
    // Property accessors
    public int getCityId() {
        return this.cityId;
    }
    
    public void setCityId(int cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }




}


