package com.dynamic.charm.examples.orm;
// Generated Nov 27, 2006 11:54:35 AM by Hibernate Tools 3.2.0.beta8



/**
 * State generated by hbm2java
 */
public class State  implements java.io.Serializable {

    // Fields    

     private int stateId;
     private String stateCode;
     private String stateName;

     // Constructors

    /** default constructor */
    public State() {
    }

    /** full constructor */
    public State(int stateId, String stateCode, String stateName) {
       this.stateId = stateId;
       this.stateCode = stateCode;
       this.stateName = stateName;
    }
   
    // Property accessors
    public int getStateId() {
        return this.stateId;
    }
    
    public void setStateId(int stateId) {
        this.stateId = stateId;
    }
    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }




}


