/* $Id: billing_v.sql 1655 2009-08-05 21:24:48Z bvonhaden $ */

ALTER VIEW [dbo].[billing_v]
AS
SELECT sl.organization_id, 
       sl.service_line_id, 
       CAST(sl.bill_job_id AS VARCHAR) + '-' + CAST(sl.item_id AS VARCHAR) + '-' + CAST(sl.status_id AS VARCHAR) AS job_item_status_id, 
       CAST(sl.bill_service_id AS VARCHAR) + '-' + CAST(sl.item_id AS VARCHAR) + '-' + CAST(sl.status_id AS VARCHAR) AS service_item_status_id, 
       CAST(sl.bill_service_id AS VARCHAR) + '-' + CAST(sl.status_id AS VARCHAR) AS bill_service_status_id,
       sl.bill_job_no, 
       sl.bill_service_no, 
       sl.bill_service_line_no, 
       j_v.job_status_type_name, 
       sl.service_line_date, 
       sl.service_line_date_VARCHAR, 
       sl.service_line_week, 
       sl.service_line_week_VARCHAR, 
       sl.status_id, 
       sls.name AS status_name, 
       sl.exported_flag, 
       sl.billed_flag, 
       sl.posted_flag, 
       sl.pooled_flag, 
       sl.internal_req_flag,
       sl.bill_job_id, 
       sl.bill_service_id,
       sl.ph_service_id,
       sl.resource_id, 
       sl.resource_name,
       sl.item_id,
       sl.item_name,
       sl.item_type_code, 
       sl.invoice_id,
       i.description AS invoice_description, 
       sl.posted_from_invoice_id, 
       ist.status_id AS invoice_status_id,
       ist.name AS invoice_status_name, 
       sl.billable_flag, 
       s.taxable_flag AS service_taxable_flag,
       sl.taxable_flag, 
       sl.ext_pay_code,
       sl.tc_qty,
       sl.payroll_qty,
       sl.bill_qty, 
       sl.bill_rate, 
       sl.bill_total, 
       sl.bill_exp_qty, 
       sl.bill_exp_rate, 
       sl.bill_exp_total,
       sl.bill_hourly_qty,
       sl.bill_hourly_rate, 
       sl.bill_hourly_total,
       s.quote_total,
       s.quote_id,
       j_v.job_name, 
       j_v.billing_user_name,
       j_v.dealer_name,
       j_v.ext_dealer_id,
       j_v.customer_name, 
       j_v.ext_customer_id,
       j_v.billing_user_id,
       j_v.foreman_resource_name AS supervisor_name, 
       j_v.foreman_user_id AS sup_user_id,
       s.billing_type_id,
       billing_types.code AS billing_type_code, 
       billing_types.name AS billing_type_name,
       s.po_no,
       s.cust_col_1,
       s.cust_col_2, 
       s.cust_col_3,
       s.cust_col_4,
       s.cust_col_5,
       s.cust_col_6, 
       s.cust_col_7, 
       s.cust_col_8,
       s.cust_col_9,
       s.cust_col_10, 
       s.est_start_date, 
       s.est_end_date,
       sl.palm_rep_id, 
       s.description AS service_description, 
       CAST(j_v.job_no AS VARCHAR) + ' - ' + ISNULL(j_v.job_name, '') AS job_no_name2, 
       CAST(s.service_no AS VARCHAR) + ' - ' + ISNULL(s.description, '') AS service_no_description2, 
       sl.entered_date, 
       sl.entered_by, 
       sl.entry_method, 
       sl.override_date, 
       sl.override_by, 
       sl.override_reason, 
       sl.verified_date, 
       sl.verified_by, 
       sl.date_created, 
       sl.created_by, 
       sl.date_modified, 
       sl.modified_by, 
       ISNULL(sl.invoice_post_date, i.date_sent) AS invoiced_date, 
       sl.invoice_post_date,
       ISNULL(q.quote_total, 0) quoted_total,
       p.is_new
  FROM dbo.service_lines sl LEFT OUTER JOIN 
       dbo.services s ON sl.bill_service_id = s.service_id LEFT OUTER JOIN
       dbo.jobs_v j_v ON sl.bill_job_id = j_v.job_id LEFT OUTER JOIN
       dbo.invoices i ON sl.invoice_id = i.invoice_id LEFT OUTER JOIN
       dbo.invoice_statuses ist ON i.status_id = ist.status_id LEFT OUTER JOIN
       dbo.lookups billing_types on s.billing_type_id = billing_types.lookup_id LEFT OUTER JOIN
       dbo.service_line_statuses sls ON sl.status_id = sls.status_id LEFT OUTER JOIN
       dbo.quotes q ON s.quote_id = q.quote_id LEFT OUTER JOIN
       dbo.projects p ON j_v.project_id = p.project_id
 WHERE sl.status_id > 3
   AND sl.internal_req_flag = 'N'
