
CREATE TABLE dbo.USER_JOB_TYPES
([USER_JOB_TYPE_ID] [numeric](18, 0) IDENTITY (1, 1) NOT NULL
,[USER_ID] [numeric](18, 0) NOT NULL
,[LOOKUP_ID] [numeric](18, 0) NOT NULL
,[CREATED_BY] [numeric](18, 0) NOT NULL
,[DATE_CREATED] [datetime] DEFAULT getdate() NOT NULL
,CONSTRAINT [PK_USER_JOB_TYPES] PRIMARY KEY  CLUSTERED 
	(
		[USER_JOB_TYPE_ID]
	)  ON [PRIMARY] ,
	CONSTRAINT [FK_USER_JOB_TYPES_USERS] FOREIGN KEY 
	(
		[USER_ID]
	) REFERENCES [USERS] (
		[USER_ID]
	),
	CONSTRAINT [FK_USER_JOB_TYPES_LOOKUPS] FOREIGN KEY 
	(
		[LOOKUP_ID]
	) REFERENCES [LOOKUPS] (
		[LOOKUP_ID]
	),
	CONSTRAINT [UK_USER_JOB_TYPES] UNIQUE
	(
		[USER_ID], [LOOKUP_ID]
	)
)
go

INSERT INTO user_job_types (user_id, lookup_id, created_by, date_created)
(SELECT u.user_id, jt.lookup_id, 0, CURRENT_TIMESTAMP
FROM users u, job_types_v jt
WHERE jt.lookup_code = 'project')
go

INSERT INTO user_job_types (user_id, lookup_id, created_by, date_created)
(SELECT u.user_id, jt.lookup_id, 0, CURRENT_TIMESTAMP
FROM users u, job_types_v jt
WHERE u.user_id IN (SELECT ur.user_id 
from user_roles ur, role_function_rights rfr, functions f
where ur.role_id = rfr.role_id
AND rfr.function_id = f.function_id
AND f.code = 'enet/proj/project_numbering')
AND jt.lookup_code <> 'project')
go


ALTER TABLE [dbo].JOBS
ADD SPREADSHEET_BILLING_FLAG varchar(1) DEFAULT 'N' NOT NULL
go

ALTER TABLE [dbo].[JOBS] ADD CONSTRAINT [SPREADSHEET_BILLING_YN] CHECK ([SPREADSHEET_BILLING_FLAG] = 'Y' or [SPREADSHEET_BILLING_FLAG] = 'N')
go

UPDATE JOBS
SET SPREADSHEET_BILLING_FLAG = 'Y'
WHERE job_type_id = (SELECT lookup_id FROM job_types_v WHERE lookup_code = 'service_account')
go


INSERT INTO lookups
(code, name, active_flag, updatable_flag, sequence_no, lookup_type_id, created_by, date_created)
(SELECT 'service_provider_sales', 'Service Provider Sales', 'Y', 'Y', 1, lt.lookup_type_id, 0, CURRENT_TIMESTAMP
FROM lookup_types lt
WHERE lt.code = 'contact_type')
go


ALTER TABLE requests
ADD A_M_SALES_CONTACT_ID numeric(18,0)
go

ALTER TABLE requests
ADD CONSTRAINT [FK_REQUESTS_A_M_SALES_CONTACT_ID] FOREIGN KEY 
	(
		[A_M_SALES_CONTACT_ID]
	) REFERENCES [CONTACTS] (
		[CONTACT_ID]
	)
go

drop view dbo.VERSIONS_COPY_V
go
CREATE VIEW dbo.VERSIONS_COPY_V    
AS    
SELECT    PROJECT_ID, REQUEST_NO, REQUEST_TYPE_ID, REQUEST_STATUS_TYPE_ID, IS_SENT, IS_QUOTED, QUOTE_REQUEST_ID,     
                      DEALER_CUST_ID, CUSTOMER_PO_NO, DEALER_PO_NO, DEALER_PO_LINE_NO, DEALER_PROJECT_NO, DESIGN_PROJECT_NO,     
                      PROJECT_VOLUME, ACCOUNT_TYPE_ID, QUOTE_TYPE_ID, QUOTE_NEEDED_BY, JOB_LOCATION_ID, CUSTOMER_CONTACT_ID,     
                      ALT_CUSTOMER_CONTACT_ID, D_SALES_REP_CONTACT_ID, D_SALES_SUP_CONTACT_ID, D_PROJ_MGR_CONTACT_ID,     
                      D_DESIGNER_CONTACT_ID, A_M_CONTACT_ID, A_M_INSTALL_SUP_CONTACT_ID, A_D_DESIGNER_CONTACT_ID, GEN_CONTRACTOR_CONTACT_ID,     
                      ELECTRICIAN_CONTACT_ID, DATA_PHONE_CONTACT_ID, CARPET_LAYER_CONTACT_ID, BLDG_MGR_CONTACT_ID, SECURITY_CONTACT_ID,     
                      MOVER_CONTACT_ID, OTHER_CONTACT_ID, PRI_FURN_TYPE_ID, PRI_FURN_LINE_TYPE_ID, SEC_FURN_TYPE_ID, SEC_FURN_LINE_TYPE_ID,     
                      CASE_FURN_TYPE_ID, CASE_FURN_LINE_TYPE_ID, WOOD_PRODUCT_TYPE_ID, DELIVERY_TYPE_ID, WAREHOUSE_LOC, FURN_PLAN_TYPE_ID,     
                      PLAN_LOCATION, FURN_SPEC_TYPE_ID, WORKSTATION_TYPICAL_TYPE_ID, POWER_TYPE, PUNCHLIST_ITEM_TYPE_ID, PUNCHLIST_LINE,     
                      WALL_MOUNT_TYPE_ID, INIT_PROJ_TEAM_MTG_DATE, DESIGN_PRESENTATION_DATE, DESIGN_COMPLETION_DATE, SPEC_CHECK_CMPL_DATE,     
                      DEALER_ORDER_PLACED_DATE, INT_PRE_INSTALL_MTG_DATE, EXT_PRE_INSTALL_MTG_DATE, DEALER_INSTALL_PLAN_DATE, MFG_SHIP_DATE,     
                      PROD_DEL_TO_WH_DATE, TRUCK_ARRIVAL_TIME, CONSTRUCT_COMPLETE_DATE, ELECTRICAL_COMPLETE_DATE, CABLE_COMPLETE_DATE,     
                      CARPET_COMPLETE_DATE, SITE_VISIT_REQ_TYPE_ID, SITE_VISIT_DATE, PRODUCT_DEL_TO_SITE_DATE, SCHEDULE_TYPE_ID, EST_START_DATE,     
                      EST_START_TIME, EST_END_DATE, MOVE_IN_DATE, PUNCHLIST_COMPLETE_DATE, COORD_PHONE_DATA_TYPE_ID,     
                      COORD_WALL_COVR_TYPE_ID, COORD_FLOOR_COVR_TYPE_ID, COORD_ELECTRICAL_TYPE_ID, COORD_MOVER_TYPE_ID, ACTIVITY_TYPE_ID1,     
                      QTY1, ACTIVITY_CAT_TYPE_ID1, ACTIVITY_TYPE_ID2, QTY2, ACTIVITY_CAT_TYPE_ID2, ACTIVITY_TYPE_ID3, QTY3, ACTIVITY_CAT_TYPE_ID3,     
                      ACTIVITY_TYPE_ID4, QTY4, ACTIVITY_CAT_TYPE_ID4, ACTIVITY_TYPE_ID5, QTY5, ACTIVITY_CAT_TYPE_ID5, ACTIVITY_TYPE_ID6, QTY6,     
                      ACTIVITY_CAT_TYPE_ID6, ACTIVITY_TYPE_ID7, QTY7, ACTIVITY_CAT_TYPE_ID7, ACTIVITY_TYPE_ID8, QTY8, ACTIVITY_CAT_TYPE_ID8,     
                      ACTIVITY_TYPE_ID9, QTY9, ACTIVITY_CAT_TYPE_ID9, ACTIVITY_TYPE_ID10, QTY10, ACTIVITY_CAT_TYPE_ID10, DESCRIPTION,     
                      APPROVAL_REQ_TYPE_ID, WHO_CAN_APPROVE_NAME, WHO_CAN_APPROVE_PHONE, REGULAR_HOURS_TYPE_ID, EVENING_HOURS_TYPE_ID,     
                      WEEKEND_HOURS_TYPE_ID, UNION_LABOR_REQ_TYPE_ID, COST_TO_CUST_TYPE_ID, COST_TO_VEND_TYPE_ID, COST_TO_JOB_TYPE_ID,     
                      WAREHOUSE_FEE_TYPE_ID, TAXABLE_FLAG, DURATION_TIME_UOM_TYPE_ID, DURATION_QTY, PHASED_INSTALL_TYPE_ID,     
                      LOADING_DOCK_TYPE_ID, DOCK_AVAILABLE_TIME, DOCK_RESERV_REQ_TYPE_ID, SEMI_ACCESS_TYPE_ID, DOCK_HEIGHT,     
                      ELEVATOR_AVAIL_TYPE_ID, ELEVATOR_AVAIL_TIME, ELEVATOR_RESERV_REQ_TYPE_ID, STAIR_CARRY_TYPE_ID, STAIR_CARRY_FLIGHTS,     
                      STAIR_CARRY_STAIRS, SMALLEST_DOOR_ELEV_WIDTH, FLOOR_PROTECTION_TYPE_ID, WALL_PROTECTION_TYPE_ID,     
                      DOORWAY_PROT_TYPE_ID, WALKBOARD_TYPE_ID, STAGING_AREA_TYPE_ID, DUMPSTER_TYPE_ID, NEW_SITE_TYPE_ID,     
                      OCCUPIED_SITE_TYPE_ID, OTHER_CONDITIONS, DATE_CREATED, CREATED_BY, DATE_MODIFIED, MODIFIED_BY, VERSION_NO,     
                      P_CARD_NUMBER, FURNITURE1_CONTACT_ID, FURNITURE2_CONTACT_ID, APPROVER_CONTACT_ID, PHONE_CONTACT_ID,     
                      FLOOR_NUMBER_TYPE_ID, PRIORITY_TYPE_ID, LEVEL_TYPE_ID, FURN_REQ_TYPE_ID, CUST_CONTACT_MOD_DATE, JOB_LOCATION_MOD_DATE,     
                      CUST_COL_1, CUST_COL_2, CUST_COL_3, CUST_COL_4, CUST_COL_5, CUST_COL_6, CUST_COL_7, CUST_COL_8, CUST_COL_9, CUST_COL_10,     
                      IS_COPY, IS_SURVEYED, FURNITURE_TYPE, FURNITURE_QTY, PROD_DISP_FLAG, PROD_DISP_ID, A_M_SALES_CONTACT_ID    
FROM         dbo.REQUESTS    
go

  