ALTER TABLE dbo.requests
ADD [CSC_WO_FIELD_FLAG] [varchar] (1) NOT NULL DEFAULT ('N')
go

ALTER TABLE dbo.requests
ADD CONSTRAINT [CSC_WO_FIELD_YN] CHECK ([CSC_WO_FIELD_FLAG] = 'Y' or [CSC_WO_FIELD_FLAG] = 'N')
go



ALTER  VIEW dbo.REQUESTS_V
AS
SELECT     dbo.REQUESTS.REQUEST_ID, dbo.REQUESTS.REQUEST_NO, dbo.REQUESTS.VERSION_NO, dbo.VERSIONS_MAX_NO_V.max_version_no, 
                      dbo.REQUESTS.REQUEST_TYPE_ID, REQUEST_TYPE.CODE AS request_type_code, REQUEST_TYPE.NAME AS request_type_name, 
                      dbo.REQUESTS.REQUEST_STATUS_TYPE_ID, REQUEST_STATUS_TYPE.CODE AS request_status_type_code, 
                      REQUEST_STATUS_TYPE.NAME AS request_status_type_name, dbo.REQUESTS.PROJECT_ID, dbo.SERVICES.SERVICE_ID, 
                      dbo.SERVICES.SERV_STATUS_TYPE_ID, SERV_STATUS_TYPE.CODE AS serv_status_type_code, 
                      SERV_STATUS_TYPE.NAME AS serv_status_type_name, dbo.REQUESTS.DEALER_CUST_ID, dbo.REQUESTS.CUSTOMER_PO_NO, 
                      dbo.REQUESTS.DEALER_PO_NO, dbo.REQUESTS.DEALER_PO_LINE_NO, dbo.REQUESTS.DEALER_PROJECT_NO, 
                      dbo.REQUESTS.DESIGN_PROJECT_NO, dbo.REQUESTS.PROJECT_VOLUME, dbo.REQUESTS.ACCOUNT_TYPE_ID, 
                      ACCOUNT_TYPE.CODE AS account_type_code, ACCOUNT_TYPE.NAME AS account_type_name, dbo.REQUESTS.QUOTE_TYPE_ID, 
                      QUOTE_TYPE.CODE AS quote_type_code, QUOTE_TYPE.NAME AS quote_type_name, dbo.REQUESTS.QUOTE_NEEDED_BY, 
                      dbo.REQUESTS.JOB_LOCATION_ID, dbo.REQUESTS.CUSTOMER_CONTACT_ID, dbo.REQUESTS.ALT_CUSTOMER_CONTACT_ID, 
                      dbo.REQUESTS.D_SALES_REP_CONTACT_ID, dbo.REQUESTS.D_SALES_SUP_CONTACT_ID, dbo.REQUESTS.D_PROJ_MGR_CONTACT_ID, 
                      dbo.REQUESTS.D_DESIGNER_CONTACT_ID, dbo.REQUESTS.A_M_CONTACT_ID, dbo.REQUESTS.A_M_INSTALL_SUP_CONTACT_ID, 
                      dbo.REQUESTS.FURNITURE1_CONTACT_ID, dbo.REQUESTS.FURNITURE2_CONTACT_ID, dbo.REQUESTS.A_D_DESIGNER_CONTACT_ID, 
                      dbo.REQUESTS.GEN_CONTRACTOR_CONTACT_ID, dbo.REQUESTS.ELECTRICIAN_CONTACT_ID, dbo.REQUESTS.DATA_PHONE_CONTACT_ID, 
                      dbo.REQUESTS.PHONE_CONTACT_ID, dbo.REQUESTS.CARPET_LAYER_CONTACT_ID, dbo.REQUESTS.BLDG_MGR_CONTACT_ID, 
                      dbo.REQUESTS.SECURITY_CONTACT_ID, dbo.REQUESTS.MOVER_CONTACT_ID, dbo.REQUESTS.OTHER_CONTACT_ID, 
                      dbo.REQUESTS.PRI_FURN_TYPE_ID, PRI_FURN_TYPE.CODE AS pri_furn_type_code, PRI_FURN_TYPE.NAME AS pri_furn_type_name, 
                      dbo.REQUESTS.PRI_FURN_LINE_TYPE_ID, dbo.REQUESTS.CSC_WO_FIELD_FLAG,
                      PRI_FURN_LINE_TYPE.CODE AS pri_furn_line_type_code, 
                      PRI_FURN_LINE_TYPE.NAME AS pri_furn_line_type_name, dbo.REQUESTS.SEC_FURN_TYPE_ID, SEC_FURN_TYPE.CODE AS sec_furn_type_code, 
                      SEC_FURN_TYPE.NAME AS sec_furn_type_name, dbo.REQUESTS.SEC_FURN_LINE_TYPE_ID, 
                      SEC_FURN_LINE_TYPE.CODE AS sec_furn_line_type_code, SEC_FURN_LINE_TYPE.NAME AS sec_furn_line_type_name, 
                      dbo.REQUESTS.CASE_FURN_TYPE_ID, CASE_FURN_TYPE.CODE AS case_furn_type_code, CASE_FURN_TYPE.NAME AS case_furn_type_name, 
                      dbo.REQUESTS.CASE_FURN_LINE_TYPE_ID, CASE_FURN_LINE_TYPE.CODE AS case_furn_line_type_code, 
                      CASE_FURN_LINE_TYPE.NAME AS case_furn_line_type_name, dbo.REQUESTS.WOOD_PRODUCT_TYPE_ID, 
                      WOOD_PRODUCT_TYPE.CODE AS wood_product_type_code, WOOD_PRODUCT_TYPE.NAME AS wood_product_type_name, 
                      dbo.REQUESTS.DELIVERY_TYPE_ID, DELIVERY_TYPE.CODE AS delivery_type_code, DELIVERY_TYPE.NAME AS delivery_type_name, 
                      dbo.REQUESTS.WAREHOUSE_LOC, dbo.REQUESTS.FURN_PLAN_TYPE_ID, FURN_PLAN_TYPE.CODE AS furn_plan_type_code, 
                      FURN_PLAN_TYPE.NAME AS furn_plan_type_name, dbo.REQUESTS.PLAN_LOCATION, dbo.REQUESTS.FURN_SPEC_TYPE_ID, 
                      FURN_SPEC_TYPE.CODE AS furn_spec_type_code, FURN_SPEC_TYPE.NAME AS furn_spec_type_name, 
                      dbo.REQUESTS.WORKSTATION_TYPICAL_TYPE_ID, WORKSTATION_TYPICAL_TYPE.CODE AS workstation_typical_type_code, 
                      WORKSTATION_TYPICAL_TYPE.NAME AS workstation_typical_type_name, dbo.REQUESTS.POWER_TYPE, 
                      dbo.REQUESTS.PUNCHLIST_ITEM_TYPE_ID, PUNCHLIST_ITEM_TYPE.CODE AS punchlist_item_type_code, 
                      PUNCHLIST_ITEM_TYPE.NAME AS punchlist_item_type_name, dbo.REQUESTS.PUNCHLIST_LINE, dbo.REQUESTS.WALL_MOUNT_TYPE_ID, 
                      WALL_MOUNT_TYPE.CODE AS wall_mount_type_code, WALL_MOUNT_TYPE.NAME AS wall_mount_type_name, 
                      dbo.REQUESTS.INIT_PROJ_TEAM_MTG_DATE, dbo.REQUESTS.DESIGN_PRESENTATION_DATE, dbo.REQUESTS.DESIGN_COMPLETION_DATE, 
                      dbo.REQUESTS.SPEC_CHECK_CMPL_DATE, dbo.REQUESTS.DEALER_ORDER_PLACED_DATE, dbo.REQUESTS.INT_PRE_INSTALL_MTG_DATE, 
                      dbo.REQUESTS.EXT_PRE_INSTALL_MTG_DATE, dbo.REQUESTS.DEALER_INSTALL_PLAN_DATE, dbo.REQUESTS.MFG_SHIP_DATE, 
                      dbo.REQUESTS.PROD_DEL_TO_WH_DATE, dbo.REQUESTS.TRUCK_ARRIVAL_TIME, dbo.REQUESTS.CONSTRUCT_COMPLETE_DATE, 
                      dbo.REQUESTS.ELECTRICAL_COMPLETE_DATE, dbo.REQUESTS.CABLE_COMPLETE_DATE, dbo.REQUESTS.CARPET_COMPLETE_DATE, 
                      dbo.REQUESTS.SITE_VISIT_REQ_TYPE_ID, SITE_VISIT_REQ_TYPE.CODE AS site_visit_req_type_code, 
                      SITE_VISIT_REQ_TYPE.NAME AS site_visit_req_type_name, dbo.REQUESTS.SITE_VISIT_DATE, dbo.REQUESTS.PRODUCT_DEL_TO_SITE_DATE, 
                      dbo.REQUESTS.SCHEDULE_TYPE_ID, SCHEDULE_TYPE.CODE AS schedule_type_code, SCHEDULE_TYPE.NAME AS schedule_type_name, 
                      dbo.REQUESTS.EST_START_DATE, CONVERT(varchar(12), dbo.REQUESTS.EST_START_DATE, 101) AS est_start_date_varchar, 
                      dbo.REQUESTS.EST_START_TIME, dbo.REQUESTS.EST_END_DATE, dbo.REQUESTS.MOVE_IN_DATE, 
                      dbo.REQUESTS.PUNCHLIST_COMPLETE_DATE, dbo.REQUESTS.COORD_PHONE_DATA_TYPE_ID, dbo.REQUESTS.COORD_WALL_COVR_TYPE_ID, 
                      dbo.REQUESTS.COORD_FLOOR_COVR_TYPE_ID, dbo.REQUESTS.COORD_ELECTRICAL_TYPE_ID, dbo.REQUESTS.COORD_MOVER_TYPE_ID, 
                      dbo.REQUESTS.ACTIVITY_TYPE_ID1, dbo.REQUESTS.QTY1, dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID1, dbo.REQUESTS.ACTIVITY_TYPE_ID2, 
                      dbo.REQUESTS.QTY2, dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID2, dbo.REQUESTS.ACTIVITY_TYPE_ID3, dbo.REQUESTS.QTY3, 
                      dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID3, dbo.REQUESTS.ACTIVITY_TYPE_ID4, dbo.REQUESTS.QTY4, dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID4, 
                      dbo.REQUESTS.ACTIVITY_TYPE_ID5, dbo.REQUESTS.QTY5, dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID5, dbo.REQUESTS.ACTIVITY_TYPE_ID6, 
                      dbo.REQUESTS.QTY6, dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID6, dbo.REQUESTS.ACTIVITY_TYPE_ID7, dbo.REQUESTS.QTY7, 
                      dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID7, dbo.REQUESTS.ACTIVITY_TYPE_ID8, dbo.REQUESTS.QTY8, dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID8, 
                      dbo.REQUESTS.ACTIVITY_TYPE_ID9, dbo.REQUESTS.QTY9, dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID9, dbo.REQUESTS.ACTIVITY_TYPE_ID10, 
                      dbo.REQUESTS.QTY10, dbo.REQUESTS.ACTIVITY_CAT_TYPE_ID10, dbo.REQUESTS.DESCRIPTION, dbo.REQUESTS.APPROVAL_REQ_TYPE_ID, 
                      APPROVAL_REQ_TYPE.CODE AS approval_req_type_code, APPROVAL_REQ_TYPE.NAME AS approval_req_type_name, 
                      dbo.REQUESTS.WHO_CAN_APPROVE_NAME, dbo.REQUESTS.WHO_CAN_APPROVE_PHONE, dbo.REQUESTS.REGULAR_HOURS_TYPE_ID, 
                      dbo.REQUESTS.EVENING_HOURS_TYPE_ID, dbo.REQUESTS.WEEKEND_HOURS_TYPE_ID, dbo.REQUESTS.UNION_LABOR_REQ_TYPE_ID, 
                      dbo.REQUESTS.COST_TO_CUST_TYPE_ID, dbo.REQUESTS.COST_TO_VEND_TYPE_ID, dbo.REQUESTS.COST_TO_JOB_TYPE_ID, 
                      dbo.REQUESTS.WAREHOUSE_FEE_TYPE_ID, dbo.REQUESTS.DURATION_TIME_UOM_TYPE_ID, dbo.REQUESTS.DURATION_QTY, 
                      dbo.REQUESTS.PHASED_INSTALL_TYPE_ID, dbo.REQUESTS.LOADING_DOCK_TYPE_ID, dbo.REQUESTS.DOCK_AVAILABLE_TIME, 
                      dbo.REQUESTS.DOCK_RESERV_REQ_TYPE_ID, dbo.REQUESTS.SEMI_ACCESS_TYPE_ID, dbo.REQUESTS.DOCK_HEIGHT, 
                      dbo.REQUESTS.ELEVATOR_AVAIL_TYPE_ID, dbo.REQUESTS.ELEVATOR_AVAIL_TIME, dbo.REQUESTS.ELEVATOR_RESERV_REQ_TYPE_ID, 
                      dbo.REQUESTS.STAIR_CARRY_TYPE_ID, dbo.REQUESTS.STAIR_CARRY_FLIGHTS, dbo.REQUESTS.STAIR_CARRY_STAIRS, 
                      dbo.REQUESTS.SMALLEST_DOOR_ELEV_WIDTH, dbo.REQUESTS.FLOOR_PROTECTION_TYPE_ID, dbo.REQUESTS.WALL_PROTECTION_TYPE_ID, 
                      dbo.REQUESTS.DOORWAY_PROT_TYPE_ID, dbo.REQUESTS.WALKBOARD_TYPE_ID, dbo.REQUESTS.STAGING_AREA_TYPE_ID, 
                      dbo.REQUESTS.DUMPSTER_TYPE_ID, dbo.REQUESTS.NEW_SITE_TYPE_ID, dbo.REQUESTS.OCCUPIED_SITE_TYPE_ID, 
                      dbo.REQUESTS.OTHER_CONDITIONS, dbo.REQUESTS.DATE_CREATED, dbo.REQUESTS.CREATED_BY, dbo.REQUESTS.DATE_MODIFIED, 
                      dbo.REQUESTS.MODIFIED_BY, dbo.PROJECTS_V.PROJECT_NO, CONVERT(varchar, dbo.PROJECTS_V.PROJECT_NO) + '-' + CONVERT(varchar, 
                      dbo.REQUESTS.REQUEST_NO) AS project_request_no, dbo.PROJECTS_V.CUSTOMER_ID, CUSTOMERS_1.PARENT_CUSTOMER_ID, 
                      CUSTOMERS_1.ORGANIZATION_ID, CUSTOMERS_1.EXT_DEALER_ID, CUSTOMERS_1.DEALER_NAME, CUSTOMERS_1.EXT_CUSTOMER_ID, 
                      CUSTOMERS_1.CUSTOMER_NAME, dbo.PROJECTS_V.JOB_NAME, dbo.REQUESTS.IS_SENT, dbo.REQUESTS.IS_QUOTED, 
                      dbo.REQUESTS.QUOTE_REQUEST_ID, dbo.REQUESTS.REQUEST_NO AS record_seq_no, 
                      USERS_1.FIRST_NAME + ' ' + USERS_1.LAST_NAME AS created_by_name, 
                      USERS_2.FIRST_NAME + ' ' + USERS_2.LAST_NAME AS modified_by_name, A_M_CONTACT.CONTACT_NAME AS a_m_contact_name, 
                      dbo.PROJECTS_V.PROJECT_STATUS_TYPE_ID, dbo.PROJECTS_V.project_status_type_code, dbo.PROJECTS_V.project_status_type_name, 
                      CONVERT(varchar(12), dbo.REQUESTS.DATE_CREATED, 101) AS date_created_varchar
FROM         dbo.LOOKUPS SITE_VISIT_REQ_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS QUOTE_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS SEC_FURN_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS PRI_FURN_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS REQUEST_STATUS_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS FURN_PLAN_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS ACCOUNT_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS WORKSTATION_TYPICAL_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS PUNCHLIST_ITEM_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS CASE_FURN_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS FURN_SPEC_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS CASE_FURN_LINE_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS WOOD_PRODUCT_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS SCHEDULE_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS APPROVAL_REQ_TYPE RIGHT OUTER JOIN
                      dbo.LOOKUPS SERV_STATUS_TYPE RIGHT OUTER JOIN
                      dbo.SERVICES RIGHT OUTER JOIN
                      dbo.USERS USERS_1 RIGHT OUTER JOIN
                      dbo.USERS USERS_2 RIGHT OUTER JOIN
                      dbo.VERSIONS_MAX_NO_V RIGHT OUTER JOIN
                      dbo.REQUESTS ON dbo.VERSIONS_MAX_NO_V.PROJECT_ID = dbo.REQUESTS.PROJECT_ID AND 
                      dbo.VERSIONS_MAX_NO_V.REQUEST_NO = dbo.REQUESTS.REQUEST_NO ON USERS_2.USER_ID = dbo.REQUESTS.MODIFIED_BY ON 
                      USERS_1.USER_ID = dbo.REQUESTS.CREATED_BY ON dbo.SERVICES.REQUEST_ID = dbo.REQUESTS.REQUEST_ID ON 
                      SERV_STATUS_TYPE.LOOKUP_ID = dbo.SERVICES.SERV_STATUS_TYPE_ID ON 
                      APPROVAL_REQ_TYPE.LOOKUP_ID = dbo.REQUESTS.APPROVAL_REQ_TYPE_ID ON 
                      SCHEDULE_TYPE.LOOKUP_ID = dbo.REQUESTS.SCHEDULE_TYPE_ID ON 
                      WOOD_PRODUCT_TYPE.LOOKUP_ID = dbo.REQUESTS.WOOD_PRODUCT_TYPE_ID ON 
                      CASE_FURN_LINE_TYPE.LOOKUP_ID = dbo.REQUESTS.CASE_FURN_LINE_TYPE_ID ON 
                      FURN_SPEC_TYPE.LOOKUP_ID = dbo.REQUESTS.FURN_SPEC_TYPE_ID ON 
                      CASE_FURN_TYPE.LOOKUP_ID = dbo.REQUESTS.CASE_FURN_TYPE_ID ON 
                      PUNCHLIST_ITEM_TYPE.LOOKUP_ID = dbo.REQUESTS.PUNCHLIST_ITEM_TYPE_ID ON 
                      WORKSTATION_TYPICAL_TYPE.LOOKUP_ID = dbo.REQUESTS.WORKSTATION_TYPICAL_TYPE_ID ON 
                      ACCOUNT_TYPE.LOOKUP_ID = dbo.REQUESTS.ACCOUNT_TYPE_ID ON FURN_PLAN_TYPE.LOOKUP_ID = dbo.REQUESTS.FURN_PLAN_TYPE_ID ON 
                      REQUEST_STATUS_TYPE.LOOKUP_ID = dbo.REQUESTS.REQUEST_STATUS_TYPE_ID ON 
                      PRI_FURN_TYPE.LOOKUP_ID = dbo.REQUESTS.PRI_FURN_TYPE_ID LEFT OUTER JOIN
                      dbo.LOOKUPS SEC_FURN_LINE_TYPE ON dbo.REQUESTS.SEC_FURN_LINE_TYPE_ID = SEC_FURN_LINE_TYPE.LOOKUP_ID LEFT OUTER JOIN
                      dbo.LOOKUPS REQUEST_TYPE ON dbo.REQUESTS.REQUEST_TYPE_ID = REQUEST_TYPE.LOOKUP_ID LEFT OUTER JOIN
                      dbo.LOOKUPS PRI_FURN_LINE_TYPE ON dbo.REQUESTS.PRI_FURN_LINE_TYPE_ID = PRI_FURN_LINE_TYPE.LOOKUP_ID ON 
                      SEC_FURN_TYPE.LOOKUP_ID = dbo.REQUESTS.SEC_FURN_TYPE_ID LEFT OUTER JOIN
                      dbo.LOOKUPS WALL_MOUNT_TYPE ON dbo.REQUESTS.WALL_MOUNT_TYPE_ID = WALL_MOUNT_TYPE.LOOKUP_ID ON 
                      QUOTE_TYPE.LOOKUP_ID = dbo.REQUESTS.QUOTE_TYPE_ID ON 
                      SITE_VISIT_REQ_TYPE.LOOKUP_ID = dbo.REQUESTS.SITE_VISIT_REQ_TYPE_ID LEFT OUTER JOIN
                      dbo.LOOKUPS DELIVERY_TYPE ON dbo.REQUESTS.DELIVERY_TYPE_ID = DELIVERY_TYPE.LOOKUP_ID LEFT OUTER JOIN
                      dbo.JOB_LOCATIONS ON dbo.REQUESTS.JOB_LOCATION_ID = dbo.JOB_LOCATIONS.JOB_LOCATION_ID LEFT OUTER JOIN
                      dbo.CUSTOMERS CUSTOMERS_1 RIGHT OUTER JOIN
                      dbo.PROJECTS_V ON CUSTOMERS_1.CUSTOMER_ID = dbo.PROJECTS_V.CUSTOMER_ID ON 
                      dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS_V.PROJECT_ID LEFT OUTER JOIN
                      dbo.CONTACTS A_M_CONTACT ON dbo.REQUESTS.A_M_CONTACT_ID = A_M_CONTACT.CONTACT_ID
GO



ALTER  VIEW dbo.PROJECT_REQUESTS_V
AS
SELECT     dbo.PROJECTS_V.PROJECT_ID, dbo.PROJECTS_V.PROJECT_NO, dbo.REQUESTS_V.REQUEST_NO, dbo.REQUESTS_V.VERSION_NO, 
	dbo.REQUESTS_V.max_version_no, dbo.PROJECTS_V.PROJECT_TYPE_ID, dbo.PROJECTS_V.project_type_code, 
	dbo.PROJECTS_V.project_type_name, dbo.PROJECTS_V.PROJECT_STATUS_TYPE_ID, dbo.PROJECTS_V.project_status_type_code, 
	dbo.PROJECTS_V.project_status_type_name, dbo.PROJECTS_V.CUSTOMER_ID, dbo.PROJECTS_V.PARENT_CUSTOMER_ID, dbo.PROJECTS_V.ORGANIZATION_ID, 
	dbo.PROJECTS_V.EXT_DEALER_ID, dbo.PROJECTS_V.DEALER_NAME, dbo.PROJECTS_V.EXT_CUSTOMER_ID, dbo.PROJECTS_V.CUSTOMER_NAME, 
	dbo.PROJECTS_V.JOB_NAME, dbo.PROJECTS_V.DATE_CREATED, dbo.PROJECTS_V.CREATED_BY, dbo.PROJECTS_V.created_by_name, 
	dbo.REQUESTS_V.REQUEST_ID, dbo.REQUESTS_V.REQUEST_TYPE_ID, dbo.REQUESTS_V.request_type_code, 
	dbo.REQUESTS_V.request_type_name, dbo.REQUESTS_V.REQUEST_STATUS_TYPE_ID, dbo.REQUESTS_V.request_status_type_code, 
	dbo.REQUESTS_V.request_status_type_name, dbo.REQUESTS_V.CSC_WO_FIELD_FLAG,
	dbo.REQUESTS_V.est_start_date_varchar, dbo.REQUESTS_V.QUOTE_REQUEST_ID, 
	dbo.REQUESTS_V.IS_QUOTED, dbo.REQUESTS_V.A_D_DESIGNER_CONTACT_ID, dbo.REQUESTS_V.GEN_CONTRACTOR_CONTACT_ID, 
	dbo.REQUESTS_V.ELECTRICIAN_CONTACT_ID, dbo.REQUESTS_V.DATA_PHONE_CONTACT_ID, dbo.REQUESTS_V.CARPET_LAYER_CONTACT_ID, 
	dbo.REQUESTS_V.BLDG_MGR_CONTACT_ID, dbo.REQUESTS_V.SECURITY_CONTACT_ID, dbo.REQUESTS_V.MOVER_CONTACT_ID, 
	dbo.REQUESTS_V.OTHER_CONTACT_ID, dbo.REQUESTS_V.FURNITURE1_CONTACT_ID, dbo.REQUESTS_V.FURNITURE2_CONTACT_ID
FROM         dbo.PROJECTS_V LEFT OUTER JOIN
                      dbo.REQUESTS_V ON dbo.PROJECTS_V.PROJECT_ID = dbo.REQUESTS_V.PROJECT_ID
GO

UPDATE requests
SET csc_wo_field_flag = 'Y'
WHERE request_id in (SELECT request_id FROM project_requests_v WHERE project_type_code = 'service_account')
go
