if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[QUICK_PROJECT_V]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[QUICK_PROJECT_V]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[QUICK_QUOTES_V]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[QUICK_QUOTES_V]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[QUICK_QUOTE_REQUESTS_V]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[QUICK_QUOTE_REQUESTS_V]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[QUICK_REQUESTS_V]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[QUICK_REQUESTS_V]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[QUICK_REQUEST_VENDORS_HELPER_V]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[QUICK_REQUEST_VENDORS_HELPER_V]
GO

if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[QUICK_REQUEST_VENDORS_V]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[QUICK_REQUEST_VENDORS_V]
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO



SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.QUICK_REQUESTS_V
AS
SELECT     dbo.REQUESTS.REQUEST_ID, dbo.REQUESTS.REQUEST_ID AS RECORD_ID, dbo.REQUESTS.REQUEST_NO AS RECORD_NO, 
                      dbo.REQUESTS.CUSTOMER_PO_NO, dbo.REQUESTS.DEALER_PO_NO, dbo.REQUESTS.DEALER_PROJECT_NO, dbo.REQUESTS.EST_START_DATE, 
                      dbo.REQUESTS.DESCRIPTION, dbo.REQUESTS.IS_QUOTED, dbo.REQUESTS.DATE_CREATED AS RECORD_CREATED, 
                      dbo.REQUESTS.DATE_MODIFIED AS RECORD_LAST_MODIFIED, dbo.PROJECTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, 
                      dbo.PROJECTS.JOB_NAME, CONVERT(varchar, dbo.PROJECTS.PROJECT_NO) + '-' + CONVERT(varchar, dbo.REQUESTS.REQUEST_NO) 
                      AS PROJECT_REQUEST_NO, dbo.CUSTOMERS.ORGANIZATION_ID, dbo.CUSTOMERS.CUSTOMER_ID, dbo.CUSTOMERS.PARENT_CUSTOMER_ID, 
                      dbo.CUSTOMERS.EXT_DEALER_ID, dbo.CUSTOMERS.CUSTOMER_NAME, dbo.CUSTOMERS.DEALER_NAME, 
                      request_status.CODE AS RECORD_STATUS_CODE, request_status.NAME AS RECORD_STATUS_NAME, 
                      request_status.SEQUENCE_NO AS RECORD_STATUS_SEQ_NO, request_type.CODE AS RECORD_TYPE_CODE, 
                      request_type.NAME AS RECORD_TYPE_NAME, request_type.SEQUENCE_NO AS RECORD_TYPE_SEQ_NO, dbo.REQUESTS.A_M_CONTACT_ID, 
                      dbo.REQUESTS.CUSTOMER_CONTACT_ID, dbo.REQUESTS.ALT_CUSTOMER_CONTACT_ID, dbo.REQUESTS.D_SALES_REP_CONTACT_ID, 
                      dbo.REQUESTS.D_SALES_SUP_CONTACT_ID, dbo.REQUESTS.D_PROJ_MGR_CONTACT_ID, dbo.REQUESTS.D_DESIGNER_CONTACT_ID, 
                      project_status.CODE AS PROJECT_STATUS_CODE, project_status.NAME AS PROJECT_STATUS_NAME
FROM         dbo.REQUESTS INNER JOIN
                      dbo.LOOKUPS request_status ON dbo.REQUESTS.REQUEST_STATUS_TYPE_ID = request_status.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS request_type ON dbo.REQUESTS.REQUEST_TYPE_ID = request_type.LOOKUP_ID INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.PROJECTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.LOOKUPS project_status ON dbo.PROJECTS.PROJECT_STATUS_TYPE_ID = project_status.LOOKUP_ID

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO


CREATE VIEW dbo.QUICK_PROJECT_V
AS
SELECT     dbo.PROJECTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, dbo.PROJECTS.JOB_NAME, dbo.CUSTOMERS.ORGANIZATION_ID, 
                      dbo.CUSTOMERS.CUSTOMER_ID, dbo.CUSTOMERS.PARENT_CUSTOMER_ID, dbo.CUSTOMERS.EXT_DEALER_ID, 
                      dbo.CUSTOMERS.CUSTOMER_NAME, dbo.CUSTOMERS.DEALER_NAME, PROJECT_STATUS.CODE AS PROJECT_STATUS_CODE, 
                      PROJECT_STATUS.NAME AS PROJECT_STATUS_NAME, dbo.PROJECTS.DATE_CREATED, dbo.PROJECTS.CREATED_BY
FROM         dbo.CUSTOMERS INNER JOIN
                      dbo.PROJECTS ON dbo.CUSTOMERS.CUSTOMER_ID = dbo.PROJECTS.CUSTOMER_ID INNER JOIN
                      dbo.LOOKUPS project_status ON dbo.PROJECTS.PROJECT_STATUS_TYPE_ID = project_status.LOOKUP_ID


GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.QUICK_QUOTES_V
AS
SELECT     dbo.REQUESTS.REQUEST_ID, dbo.REQUESTS.REQUEST_ID AS RECORD_ID, dbo.REQUESTS.REQUEST_NO AS RECORD_NO, 
                      dbo.REQUESTS.CUSTOMER_PO_NO, dbo.REQUESTS.DEALER_PO_NO, dbo.REQUESTS.DEALER_PROJECT_NO, dbo.REQUESTS.EST_START_DATE, 
                      dbo.REQUESTS.DESCRIPTION, dbo.REQUESTS.IS_QUOTED, dbo.REQUESTS.DATE_CREATED AS RECORD_CREATED, 
                      dbo.REQUESTS.DATE_MODIFIED AS RECORD_LAST_MODIFIED, dbo.PROJECTS.PROJECT_ID, dbo.PROJECTS.PROJECT_NO, 
                      dbo.PROJECTS.JOB_NAME, CONVERT(varchar, dbo.PROJECTS.PROJECT_NO) + '-' + CONVERT(varchar, dbo.REQUESTS.REQUEST_NO) 
                      AS QUOTE_REQUEST_NO, dbo.CUSTOMERS.ORGANIZATION_ID, dbo.CUSTOMERS.CUSTOMER_ID, dbo.CUSTOMERS.PARENT_CUSTOMER_ID, 
                      dbo.CUSTOMERS.EXT_DEALER_ID, dbo.CUSTOMERS.CUSTOMER_NAME, dbo.CUSTOMERS.DEALER_NAME, 
                      request_status.CODE AS RECORD_STATUS_CODE, request_status.NAME AS RECORD_STATUS_NAME, request_type.CODE AS RECORD_TYPE_CODE, 
                      request_type.NAME AS RECORD_TYPE_NAME, request_type.SEQUENCE_NO AS RECORD_TYPE_SEQ_NO, dbo.REQUESTS.A_M_CONTACT_ID, 
                      dbo.REQUESTS.CUSTOMER_CONTACT_ID, dbo.REQUESTS.ALT_CUSTOMER_CONTACT_ID, dbo.REQUESTS.D_SALES_REP_CONTACT_ID, 
                      dbo.REQUESTS.D_SALES_SUP_CONTACT_ID, dbo.REQUESTS.D_PROJ_MGR_CONTACT_ID, dbo.REQUESTS.D_DESIGNER_CONTACT_ID, 
                      quoted_by.FIRST_NAME + '  ' + quoted_by.LAST_NAME AS QUOTED_BY_NAME, dbo.QUOTES.QUOTE_ID, dbo.QUOTES.QUOTE_TOTAL, 
                      dbo.QUOTES.DATE_QUOTED, quote_type.CODE AS QUOTE_TYPE_CODE, quote_type.NAME AS QUOTE_TYPE_NAME
FROM         dbo.REQUESTS INNER JOIN
                      dbo.PROJECTS ON dbo.REQUESTS.PROJECT_ID = dbo.PROJECTS.PROJECT_ID INNER JOIN
                      dbo.CUSTOMERS ON dbo.PROJECTS.CUSTOMER_ID = dbo.CUSTOMERS.CUSTOMER_ID INNER JOIN
                      dbo.QUOTES ON dbo.REQUESTS.REQUEST_ID = dbo.QUOTES.REQUEST_ID INNER JOIN
                      dbo.USERS quoted_by ON dbo.QUOTES.QUOTED_BY_USER_ID = quoted_by.USER_ID INNER JOIN
                      dbo.LOOKUPS quote_type ON dbo.QUOTES.QUOTE_TYPE_ID = quote_type.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS request_type ON dbo.QUOTES.REQUEST_TYPE_ID = request_type.LOOKUP_ID INNER JOIN
                      dbo.LOOKUPS request_status ON dbo.QUOTES.QUOTE_STATUS_TYPE_ID = request_status.LOOKUP_ID

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


create   VIEW dbo.QUICK_QUOTE_REQUESTS_V 
as
SELECT     dbo.quick_requests_v.*, dbo.CONTACTS.CONTACT_NAME AS A_M_CONTACT_NAME, CASE WHEN EXISTS
                          (SELECT     r.request_id
                            FROM          requests r
                            WHERE      quote_request_id = quick_requests_v.request_id) THEN 'Y' ELSE 'N' END AS HAS_SERVICE_REQUEST
FROM         dbo.quick_requests_v LEFT OUTER JOIN
                      dbo.CONTACTS ON dbo.quick_requests_v.A_M_CONTACT_ID = dbo.CONTACTS.CONTACT_ID


GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO


SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO


CREATE VIEW dbo.QUICK_REQUEST_VENDORS_HELPER_V as
SELECT     REQUEST_ID, COUNT(REQUEST_VENDOR_ID) AS VENDOR_COUNT, MIN(SCH_START_DATE) AS MIN_SCH_START_DATE, MIN(ACT_START_DATE) 
                      AS MIN_ACT_START_DATE, MAX(SCH_START_DATE) AS MAX_SCH_START_DATE, MAX(ACT_END_DATE) AS MAX_ACT_END_DATE, 
                      ISNULL(COUNT(CASE WHEN COMPLETE_FLAG = 'y' THEN 1 ELSE 0 END),0) AS VENDOR_COMPLETE_COUNT, 
                      ISNULL(COUNT(CASE WHEN invoiced_FLAG = 'y' THEN 1 ELSE 0 END),0) AS VENDOR_INVOICED_COUNT
FROM         dbo.REQUEST_VENDORS
GROUP BY REQUEST_ID


GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

CREATE VIEW dbo.QUICK_REQUEST_VENDORS_V
AS
SELECT     helper.MIN_SCH_START_DATE, helper.MIN_ACT_START_DATE, helper.MAX_SCH_START_DATE, helper.MAX_ACT_END_DATE, 
                      ISNULL(helper.VENDOR_COUNT, 0) AS VENDOR_COUNT, ISNULL(helper.VENDOR_COMPLETE_COUNT, 0) AS VENDOR_COMPLETE_COUNT, 
                      ISNULL(helper.VENDOR_INVOICED_COUNT, 0) AS VENDOR_INVOICED_COUNT, dbo.QUICK_REQUESTS_V.REQUEST_ID, 
                      dbo.QUICK_REQUESTS_V.RECORD_ID, dbo.QUICK_REQUESTS_V.RECORD_NO, dbo.QUICK_REQUESTS_V.CUSTOMER_PO_NO, 
                      dbo.QUICK_REQUESTS_V.DEALER_PO_NO, dbo.QUICK_REQUESTS_V.DEALER_PROJECT_NO, dbo.QUICK_REQUESTS_V.EST_START_DATE, 
                      dbo.QUICK_REQUESTS_V.DESCRIPTION, dbo.QUICK_REQUESTS_V.IS_QUOTED, dbo.QUICK_REQUESTS_V.RECORD_CREATED, 
                      dbo.QUICK_REQUESTS_V.RECORD_LAST_MODIFIED, dbo.QUICK_REQUESTS_V.PROJECT_ID, dbo.QUICK_REQUESTS_V.PROJECT_NO, 
                      dbo.QUICK_REQUESTS_V.JOB_NAME, dbo.QUICK_REQUESTS_V.PROJECT_REQUEST_NO, dbo.QUICK_REQUESTS_V.D_DESIGNER_CONTACT_ID, 
                      dbo.QUICK_REQUESTS_V.D_PROJ_MGR_CONTACT_ID, dbo.QUICK_REQUESTS_V.D_SALES_SUP_CONTACT_ID, 
                      dbo.QUICK_REQUESTS_V.D_SALES_REP_CONTACT_ID, dbo.QUICK_REQUESTS_V.ALT_CUSTOMER_CONTACT_ID, 
                      dbo.QUICK_REQUESTS_V.CUSTOMER_CONTACT_ID, dbo.QUICK_REQUESTS_V.A_M_CONTACT_ID, 
                      dbo.QUICK_REQUESTS_V.RECORD_TYPE_SEQ_NO, dbo.QUICK_REQUESTS_V.RECORD_TYPE_NAME, 
                      dbo.QUICK_REQUESTS_V.RECORD_TYPE_CODE, dbo.QUICK_REQUESTS_V.RECORD_STATUS_NAME, dbo.QUICK_REQUESTS_V.ORGANIZATION_ID, 
                      dbo.QUICK_REQUESTS_V.CUSTOMER_ID, dbo.QUICK_REQUESTS_V.PARENT_CUSTOMER_ID, dbo.QUICK_REQUESTS_V.EXT_DEALER_ID, 
                      dbo.QUICK_REQUESTS_V.CUSTOMER_NAME, dbo.QUICK_REQUESTS_V.DEALER_NAME, dbo.QUICK_REQUESTS_V.RECORD_STATUS_CODE, 
                      dbo.QUICK_REQUESTS_V.RECORD_STATUS_SEQ_NO, dbo.QUICK_REQUESTS_V.PROJECT_STATUS_CODE, 
                      dbo.QUICK_REQUESTS_V.PROJECT_STATUS_NAME
FROM         dbo.QUICK_REQUESTS_V LEFT OUTER JOIN
                      dbo.QUICK_REQUEST_VENDORS_HELPER_V helper ON dbo.QUICK_REQUESTS_V.REQUEST_ID = helper.REQUEST_ID

GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

