/****** Object:  View [dbo].[CUSTOMERS_V]    Script Date: 01/27/2009 11:17:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[CUSTOMERS_V]
AS
SELECT     dbo.CUSTOMERS.CUSTOMER_ID, dbo.CUSTOMERS.ORGANIZATION_ID, dbo.CUSTOMERS.PARENT_CUSTOMER_ID, 
                      parent_customers.CUSTOMER_NAME AS parent_customer_name, dbo.CUSTOMERS.EXT_DEALER_ID, dbo.CUSTOMERS.DEALER_NAME, 
                      dbo.CUSTOMERS.EXT_CUSTOMER_ID, dbo.CUSTOMERS.CUSTOMER_NAME, dbo.CUSTOMERS.SURVEY_LOCATION, 
                      dbo.CUSTOMERS.SURVEY_FREQUENCY, dbo.CUSTOMERS.SURVEY_LAST_COUNT, dbo.CUSTOMERS.REFUSAL_EMAIL_INFO, 
                      dbo.CUSTOMERS.A_M_FURNITURE1_CONTACT_ID, dbo.CUSTOMERS.ACTIVE_FLAG, dbo.CUSTOMERS.DATE_CREATED, 
                      dbo.CUSTOMERS.CREATED_BY, dbo.CUSTOMERS.DATE_MODIFIED, dbo.CUSTOMERS.MODIFIED_BY
FROM         dbo.CUSTOMERS LEFT OUTER JOIN
                      dbo.CUSTOMERS AS parent_customers ON dbo.CUSTOMERS.PARENT_CUSTOMER_ID = parent_customers.CUSTOMER_ID

GO
