package com.dynamic.charm.ajax.objects;
// Generated Jan 24, 2006 4:34:13 PM by Hibernate Tools 3.1.0 beta1JBIDERC2



/**
 * City generated by hbm2java
 */

public class City  implements java.io.Serializable {


    // Fields    

     private Integer cityId;
     private String name;
     private String state;


    // Constructors

    /** default constructor */
    public City() {
    }

	/** minimal constructor */
    public City(Integer cityId, String name) {
        this.cityId = cityId;
        this.name = name;
    }
    
    /** full constructor */
    public City(Integer cityId, String name, String state) {
        this.cityId = cityId;
        this.name = name;
        this.state = state;
    }
    

   
    // Property accessors

    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
   








}
